# Generated by Django 6.0.2 on 2026-02-13 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiscal_year', models.CharField(max_length=4)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_allocated', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_consumed', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_reserved', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.account')),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='budget.budgetallocation')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.function')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.fund')),
                ('geo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.geo')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.program')),
            ],
        ),
    ]
