# Generated by Django 6.0.2 on 2026-02-13 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_fix'),
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetallocation',
            name='period_type',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Annual', 'Annual')], default='Annual', max_length=20),
        ),
        migrations.CreateModel(
            name='BudgetVariance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(help_text='Month 1-12 or Quarter 1-4')),
                ('period_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ytd_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('period_actual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ytd_actual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('period_variance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ytd_variance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.account')),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.budgetallocation')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.function')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.fund')),
                ('geo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.geo')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.program')),
            ],
            options={
                'unique_together': {('allocation', 'period', 'fund', 'function', 'program', 'geo', 'account')},
            },
        ),
    ]
