# Generated by Django 4.2.28 on 2026-03-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_budgetline_positive_budget_allocated_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.CheckConstraint(check=models.Q(('amount_allocated__gte', 0)), name='positive_budget_allocated'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.CheckConstraint(check=models.Q(('amount_consumed__gte', 0)), name='positive_budget_consumed'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.CheckConstraint(check=models.Q(('amount_reserved__gte', 0)), name='positive_budget_reserved'),
        ),
    ]
