# Generated by Django 4.2.28 on 2026-03-17 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_budgetperiod_allow_adjustments_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0004_budgetline_positive_budget_allocated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('budget_type', models.CharField(choices=[('PUBLIC_SECTOR', 'Public Sector (MDA-based)'), ('PRIVATE_SECTOR', 'Private Sector (CostCenter-based)'), ('HYBRID', 'Hybrid (MDA + CostCenter)')], default='PUBLIC_SECTOR', max_length=20)),
                ('fiscal_year', models.CharField(db_index=True, max_length=4)),
                ('period_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUAL', 'Annual')], default='ANNUAL', max_length=20)),
                ('period_number', models.IntegerField(default=1, help_text='1-12 for monthly, 1-4 for quarterly, 1 for annual')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('original_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('revised_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('supplemental_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('control_level', models.CharField(choices=[('NONE', 'No Control'), ('WARNING', 'Warning Only'), ('HARD_STOP', 'Hard Stop')], default='HARD_STOP', max_length=10)),
                ('enable_encumbrance', models.BooleanField(default=True)),
                ('allow_over_expenditure', models.BooleanField(default=False)),
                ('over_expenditure_limit_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unified_budgets', to='accounting.account')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets_approved', to=settings.AUTH_USER_MODEL)),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unified_budgets', to='accounting.costcenter')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unified_budgets', to='accounting.function')),
                ('fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unified_budgets', to='accounting.fund')),
                ('geo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unified_budgets', to='accounting.geo')),
                ('mda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unified_budgets', to='accounting.mda')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unified_budgets', to='accounting.program')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'unified_budget',
                'ordering': ['-fiscal_year', 'period_type', 'period_number', 'budget_code'],
                'permissions': [('approve_unifiedbudget', 'Can approve unified budgets'), ('close_unifiedbudget', 'Can close unified budgets')],
            },
        ),
        migrations.CreateModel(
            name='UnifiedBudgetAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amendment_number', models.CharField(max_length=50, unique=True)),
                ('amendment_type', models.CharField(choices=[('SUPPLEMENTAL', 'Supplemental Budget'), ('REDUCTION', 'Budget Reduction'), ('TRANSFER_IN', 'Transfer In (Virement)'), ('TRANSFER_OUT', 'Transfer Out (Virement)'), ('REVISION', 'Budget Revision')], max_length=20)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('new_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('change_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('reason', models.TextField()),
                ('justification', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_amendments_approved', to=settings.AUTH_USER_MODEL)),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='budget.unifiedbudget')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('from_budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='budget.unifiedbudget')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_amendments_requested', to=settings.AUTH_USER_MODEL)),
                ('to_budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='budget.unifiedbudget')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'unified_budget_amendment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnifiedBudgetEncumbrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_type', models.CharField(choices=[('PR', 'Purchase Requisition'), ('PO', 'Purchase Order'), ('CONTRACT', 'Contract'), ('WORK_ORDER', 'Work Order'), ('GENERAL', 'General Commitment')], max_length=20)),
                ('reference_id', models.IntegerField()),
                ('reference_number', models.CharField(blank=True, default='', max_length=50)),
                ('encumbrance_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('liquidated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active (Committed)'), ('PARTIALLY_LIQUIDATED', 'Partially Liquidated'), ('FULLY_LIQUIDATED', 'Fully Liquidated'), ('CANCELLED', 'Cancelled'), ('REVERSED', 'Reversed')], default='DRAFT', max_length=25)),
                ('description', models.TextField(blank=True, default='')),
                ('is_aggregate', models.BooleanField(default=False)),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encumbrances', to='budget.unifiedbudget')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encumbrances_created', to=settings.AUTH_USER_MODEL)),
                ('parent_encumbrance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='budget.unifiedbudgetencumbrance')),
            ],
            options={
                'db_table': 'unified_budget_encumbrance',
                'ordering': ['-encumbrance_date'],
            },
        ),
        migrations.CreateModel(
            name='UnifiedBudgetVariance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(max_length=4)),
                ('period_type', models.CharField(max_length=20)),
                ('period_number', models.IntegerField()),
                ('variance_type', models.CharField(choices=[('PERIOD', 'Period (Monthly/Quarterly)'), ('YEAR_TO_DATE', 'Year to Date'), ('FORECAST', 'Forecast')], default='PERIOD', max_length=20)),
                ('period_budget', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('ytd_budget', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('period_actual', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('ytd_actual', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('period_variance', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('ytd_variance', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('period_variance_percent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ytd_variance_percent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('encumbered_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('committed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variances', to='budget.unifiedbudget')),
            ],
            options={
                'db_table': 'unified_budget_variance',
                'ordering': ['-fiscal_year', '-period_number'],
                'unique_together': {('budget', 'fiscal_year', 'period_type', 'period_number', 'variance_type')},
            },
        ),
        migrations.RemoveField(
            model_name='budgetline',
            name='account',
        ),
        migrations.RemoveField(
            model_name='budgetline',
            name='allocation',
        ),
        migrations.RemoveField(
            model_name='budgetline',
            name='function',
        ),
        migrations.RemoveField(
            model_name='budgetline',
            name='fund',
        ),
        migrations.RemoveField(
            model_name='budgetline',
            name='geo',
        ),
        migrations.RemoveField(
            model_name='budgetline',
            name='program',
        ),
        migrations.AlterUniqueTogether(
            name='budgetvariance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='budgetvariance',
            name='account',
        ),
        migrations.RemoveField(
            model_name='budgetvariance',
            name='allocation',
        ),
        migrations.RemoveField(
            model_name='budgetvariance',
            name='function',
        ),
        migrations.RemoveField(
            model_name='budgetvariance',
            name='fund',
        ),
        migrations.RemoveField(
            model_name='budgetvariance',
            name='geo',
        ),
        migrations.RemoveField(
            model_name='budgetvariance',
            name='program',
        ),
        migrations.DeleteModel(
            name='BudgetAllocation',
        ),
        migrations.DeleteModel(
            name='BudgetLine',
        ),
        migrations.DeleteModel(
            name='BudgetVariance',
        ),
        migrations.AddIndex(
            model_name='unifiedbudgetencumbrance',
            index=models.Index(fields=['reference_type', 'reference_id'], name='unified_bud_referen_e89447_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedbudgetencumbrance',
            index=models.Index(fields=['status', 'encumbrance_date'], name='unified_bud_status_a52bb3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unifiedbudgetencumbrance',
            unique_together={('budget', 'reference_type', 'reference_id')},
        ),
        migrations.AddIndex(
            model_name='unifiedbudget',
            index=models.Index(fields=['fiscal_year', 'period_type', 'status'], name='unified_bud_fiscal__7b1edd_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedbudget',
            index=models.Index(fields=['mda', 'fiscal_year'], name='unified_bud_mda_id_9aa1dc_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedbudget',
            index=models.Index(fields=['cost_center', 'fiscal_year'], name='unified_bud_cost_ce_c03d13_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedbudget',
            index=models.Index(fields=['account', 'fiscal_year'], name='unified_bud_account_156dba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unifiedbudget',
            unique_together={('fiscal_year', 'period_type', 'period_number', 'mda', 'cost_center', 'fund', 'function', 'program', 'geo', 'account')},
        ),
    ]
