# Generated by Django 4.2.28 on 2026-04-09 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0055_ncoa_segments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0005_unifiedbudget_unifiedbudgetamendment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appropriation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_approved', models.DecimalField(decimal_places=2, max_digits=20)),
                ('appropriation_type', models.CharField(choices=[('ORIGINAL', 'Original Appropriation'), ('SUPPLEMENTARY', 'Supplementary Appropriation'), ('VIREMENT', 'Virement (Transfer)')], default='ORIGINAL', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted to Legislature'), ('APPROVED', 'Approved by Legislature'), ('ENACTED', 'Enacted into Law'), ('ACTIVE', 'Active / Current'), ('CLOSED', 'Closed')], default='DRAFT', max_length=15)),
                ('law_reference', models.CharField(blank=True, default='', help_text='Appropriation Act citation', max_length=100)),
                ('enactment_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('notes', models.TextField(blank=True, default='')),
                ('administrative', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appropriations', to='accounting.administrativesegment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('economic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appropriations', to='accounting.economicsegment')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appropriations', to='accounting.fiscalyear')),
                ('functional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appropriations', to='accounting.functionalsegment')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appropriations', to='accounting.fundsegment')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appropriations', to='accounting.programmesegment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appropriation',
                'verbose_name_plural': 'Appropriations',
                'ordering': ['fiscal_year', 'administrative', 'economic'],
            },
        ),
        migrations.CreateModel(
            name='Warrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quarter', models.IntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')])),
                ('amount_released', models.DecimalField(decimal_places=2, max_digits=20)),
                ('release_date', models.DateField()),
                ('authority_reference', models.CharField(help_text='AGF warrant letter/reference number', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Release'), ('RELEASED', 'Released'), ('SUSPENDED', 'Suspended'), ('EXHAUSTED', 'Exhausted')], default='PENDING', max_length=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('appropriation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warrants', to='budget.appropriation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warrants_issued', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Warrant (Cash Release)',
                'verbose_name_plural': 'Warrants (Cash Releases)',
                'ordering': ['appropriation', 'quarter'],
                'unique_together': {('appropriation', 'quarter')},
            },
        ),
        migrations.AddIndex(
            model_name='appropriation',
            index=models.Index(fields=['fiscal_year', 'status'], name='budget_appr_fiscal__34aa94_idx'),
        ),
        migrations.AddIndex(
            model_name='appropriation',
            index=models.Index(fields=['administrative', 'economic', 'fiscal_year'], name='budget_appr_adminis_4b73b7_idx'),
        ),
    ]
