# Generated by Django 4.2.28 on 2026-04-11 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0058_administrativesegment_legacy_mda_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0006_ncoa_segments'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimated_amount', models.DecimalField(decimal_places=2, help_text='Budgeted/estimated revenue target for the fiscal year', max_digits=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='DRAFT', max_length=10)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('notes', models.TextField(blank=True, default='')),
                ('administrative', models.ForeignKey(help_text='MDA responsible for collecting this revenue', on_delete=django.db.models.deletion.PROTECT, related_name='revenue_budgets', to='accounting.administrativesegment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('economic', models.ForeignKey(help_text='NCoA Revenue account (must be type 1 = Revenue)', on_delete=django.db.models.deletion.PROTECT, related_name='revenue_budgets', to='accounting.economicsegment')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_budgets', to='accounting.fiscalyear')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_budgets', to='accounting.fundsegment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Revenue Budget',
                'verbose_name_plural': 'Revenue Budgets',
                'ordering': ['fiscal_year', 'administrative', 'economic'],
                'indexes': [models.Index(fields=['fiscal_year', 'status'], name='budget_reve_fiscal__723893_idx'), models.Index(fields=['administrative', 'economic', 'fiscal_year'], name='budget_reve_adminis_864c4a_idx')],
            },
        ),
    ]
