# Generated by Django 4.2.28 on 2026-04-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_revenuebudget'),
    ]

    operations = [
        migrations.AddField(
            model_name='appropriation',
            name='monthly_spread',
            field=models.JSONField(blank=True, default=None, help_text='Monthly budget allocation {1: Jan, 2: Feb, ...12: Dec}. Null = equal monthly spread.', null=True),
        ),
        migrations.AddField(
            model_name='revenuebudget',
            name='monthly_spread',
            field=models.JSONField(blank=True, default=None, help_text='Monthly revenue targets {1: Jan, 2: Feb, ...12: Dec}. Null = equal monthly spread.', null=True),
        ),
    ]
