# Generated by Django 4.2.28 on 2026-04-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_appropriation_monthly_spread_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrant',
            name='attachment',
            field=models.FileField(blank=True, help_text='Scanned AIE letter from Budget Office (PDF/image)', null=True, upload_to='warrants/aie_letters/%Y/'),
        ),
    ]
