# Generated by Django 4.2.28 on 2026-04-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_warrant_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appropriation',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original (as-enacted) appropriation; immutable after activation.', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='appropriation',
            name='variance_explanation',
            field=models.TextField(blank=True, default='', help_text='IPSAS 24 variance narrative (for the final FS notes).'),
        ),
    ]
