# Generated by Django 4.2.28 on 2026-04-17 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0078_accountingsettings_defined_benefit_obligation_code_and_more'),
        ('budget', '0010_appropriation_original_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appropriation',
            name='geographic',
            field=models.ForeignKey(blank=True, help_text='Optional geographic dimension (LGA / zone) for statistical and dimensional reporting. Not required for legal enactment.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appropriations', to='accounting.geographicsegment'),
        ),
    ]
