# Generated by Django 4.2.28 on 2026-04-18 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0013_appropriation_unique_per_tuple'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppropriationVirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_number', models.CharField(db_index=True, help_text='Auto-generated VIR-YYYY-####', max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('reason', models.TextField(help_text='Business justification — required for audit.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('APPLIED', 'Applied'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=15)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('from_balance_before', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('from_balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('to_balance_before', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('to_balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virements_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('from_appropriation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='virements_out', to='budget.appropriation')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virements_submitted', to=settings.AUTH_USER_MODEL)),
                ('to_appropriation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='virements_in', to='budget.appropriation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appropriation Virement',
                'verbose_name_plural': 'Appropriation Virements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='budget_appr_status_52fcd9_idx'), models.Index(fields=['from_appropriation', 'status'], name='budget_appr_from_ap_31b7b2_idx'), models.Index(fields=['to_appropriation', 'status'], name='budget_appr_to_appr_c7794a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='appropriationvirement',
            constraint=models.CheckConstraint(check=models.Q(('from_appropriation', models.F('to_appropriation')), _negated=True), name='virement_source_target_distinct'),
        ),
        migrations.AddConstraint(
            model_name='appropriationvirement',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='virement_amount_positive'),
        ),
    ]
