# Generated by Django 5.2.14 on 2026-05-07 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0014_appropriationvirement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantPrintoutSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_name', models.CharField(default='Delta State', help_text='Used in the printout title block (e.g. "Delta State Government").', max_length=100)),
                ('ministry_of_finance_name', models.CharField(default='Ministry of Finance', help_text='Issuing ministry shown on the warrant header.', max_length=200)),
                ('office_address', models.TextField(blank=True, default='', help_text='Office address printed under the letterhead.')),
                ('letterhead_logo', models.ImageField(blank=True, help_text='State coat of arms or ministry logo (PNG/JPG, ~200px tall).', null=True, upload_to='warrants/printout_settings/logos/')),
                ('governor_name', models.CharField(default='', help_text='Full name of the Executive Governor (printed under signature).', max_length=200)),
                ('governor_title', models.CharField(default='Executive Governor of Delta State', help_text='Title shown under the signature block.', max_length=200)),
                ('governor_signature', models.ImageField(blank=True, help_text='Scanned signature image (PNG with transparent background ideal).', null=True, upload_to='warrants/printout_settings/signatures/')),
                ('finance_commissioner_name', models.CharField(default='', help_text='Full name of the Commissioner for Finance.', max_length=200)),
                ('finance_commissioner_title', models.CharField(default='Honourable Commissioner for Finance, Delta State', max_length=200)),
                ('finance_commissioner_signature', models.ImageField(blank=True, null=True, upload_to='warrants/printout_settings/signatures/')),
                ('accountant_general_name', models.CharField(default='', help_text='Full name of the Accountant-General of Delta State.', max_length=200)),
                ('accountant_general_title', models.CharField(default='Accountant-General of Delta State', max_length=200)),
                ('accountant_general_signature', models.ImageField(blank=True, null=True, upload_to='warrants/printout_settings/signatures/')),
                ('footer_notes', models.TextField(blank=True, default='', help_text='Optional footer text (e.g. distribution list, archive ref).')),
                ('reference_pdf_template', models.FileField(blank=True, help_text='Optional sample PDF showing the agreed warrant layout. Stored as a design reference; never injected into actual printouts (each warrant has unique data).', null=True, upload_to='warrants/printout_settings/reference_templates/')),
            ],
            options={
                'verbose_name': 'Warrant Printout Settings',
                'verbose_name_plural': 'Warrant Printout Settings',
            },
        ),
        # Drift detection in this codebase generates a stray
        # RemoveConstraint('uniq_active_appropriation_per_dimension_tuple')
        # for the Appropriation model whenever ``makemigrations`` runs —
        # it's an unrelated leftover from earlier work. Removed here so
        # this migration stays scoped to the warrant-printout feature.
        migrations.AddField(
            model_name='warrantprintoutsettings',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warrantprintoutsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
