# Generated by Django 5.2.14 on 2026-05-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0016_warrant_date_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrant',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Release'), ('RELEASED', 'Released'), ('SUSPENDED', 'Suspended'), ('EXHAUSTED', 'Exhausted'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15),
        ),
    ]
