# Generated by Django 5.2.14 on 2026-09-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0017_alter_warrant_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="appropriation",
            name="budget_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Your own reference for the budget line this row belongs to (e.g. 'BL-2026-0142'). Optional and free text: the NCoA segment combination is what identifies the line structurally, so this is for tracking against an external budget document, not a key. Deliberately not unique — several rows may roll up to one budget line.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="revenuebudget",
            name="budget_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Your own reference for the budget line this row belongs to (e.g. 'BL-2026-0142'). Optional and free text: the NCoA segment combination is what identifies the line structurally, so this is for tracking against an external budget document, not a key. Deliberately not unique — several rows may roll up to one budget line.",
                max_length=50,
            ),
        ),
    ]
