import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import apiClient from '../../../api/client';

// ============================================================================
// PAYLOAD INTERFACES
// ============================================================================

export interface PurchaseRequestLinePayload {
    item_description: string;
    quantity: number;
    estimated_unit_price: number;
    account: number;
    asset?: number | null;
    item?: number | null;
    product_type?: number | null;
    product_category?: number | null;
}

export interface PurchaseRequestPayload {
    request_number: string;
    description: string;
    requested_by?: number;
    priority?: string;
    status?: string;
    mda?: number;
    fund: number;
    function: number;
    program: number;
    geo: number;
    cost_center?: number | null;
    lines: PurchaseRequestLinePayload[];
}

export interface ConvertPRtoPOPayload {
    id: number;
    vendor_id: number;
    order_date: string;
    expected_delivery_date?: string;
}

export interface PurchaseOrderLinePayload {
    item_description: string;
    quantity: number;
    unit_price: number;
    account: number;
    item?: number;
    product_type?: number;
    product_category?: number;
    asset?: number;
}

export interface PurchaseOrderPayload {
    po_number: string;
    vendor: number;
    purchase_request?: number;
    order_date: string;
    expected_delivery_date?: string;
    delivery_address?: string;
    delivery_contact?: string;
    payment_terms?: string;
    tax_rate?: number;
    tax_amount?: number;
    notes?: string;
    terms_and_conditions?: string;
    status?: string;
    mda?: number;
    fund: number;
    function: number;
    program: number;
    geo: number;
    lines: PurchaseOrderLinePayload[];
}

export interface GoodsReceivedNoteLinePayload {
    po_line: number;
    quantity_received: number;
}

export interface GoodsReceivedNotePayload {
    grn_number?: string;   // auto-generated by backend; do not send from client
    purchase_order: number;
    received_date: string;
    received_by: string;
    /**
     * MDA receiving the goods. Public-sector accountability requires this to
     * match `purchase_order.mda` — the backend enforces equality in
     * GoodsReceivedNote.clean(). Optional on the wire because the model's
     * save() hook auto-populates from the PO when omitted.
     */
    mda?: number | null;
    /**
     * Receiving warehouse. Auto-resolved from `mda` by the backend
     * (`inventory.services.get_default_warehouse_for_mda`); the GRN UI no
     * longer asks the user to pick one. Kept here as `read-only` from the
     * client's perspective — list/detail responses still surface it.
     */
    warehouse?: number;
    notes?: string;
    lines: GoodsReceivedNoteLinePayload[];
}

export interface InvoiceMatchingPayload {
    purchase_order?: number;
    goods_received_note?: number;
    invoice_reference: string;
    invoice_date: string;
    invoice_amount: number;
    invoice_tax_amount?: number;
    invoice_subtotal?: number;
    variance_amount?: number;
    variance_percentage?: number;
    variance_reason?: string;
    notes?: string;
}

export interface MatchInvoicePayload {
    id: number;
    variance_reason?: string;
}

export interface RejectMatchingPayload {
    id: number;
    reason?: string;
}

export interface PurchaseReturnLinePayload {
    /** FK to the originating PO line — enables server-side qty validation vs GRN */
    po_line?: number | null;
    /** Inventory item FK — optional when po_line is set (backend derives from it) */
    item?: number | null;
    /** Human-readable description preserved for display */
    item_description?: string;
    quantity: number;
    unit_price: number;
    /** Per-line reason (optional; header reason covers the whole return) */
    reason?: string;
}

export interface PurchaseReturnPayload {
    purchase_order: number;
    goods_received_note?: number | null;
    return_date: string;
    reason: string;
    notes?: string;
    lines: PurchaseReturnLinePayload[];
}

const STALE_TIME = 5 * 60 * 1000;

// ============================================================================
// VENDOR TRANSACTION HISTORY
// ============================================================================

export const useVendorTransactionHistory = (vendorId: number | null) => {
    return useQuery({
        queryKey: ['vendor-history', vendorId],
        queryFn: async () => {
            const [invoices, payments, returns] = await Promise.all([
                apiClient.get('/accounting/vendor-invoices/', { params: { vendor: vendorId, page_size: 9999 } }),
                apiClient.get('/accounting/payments/', { params: { vendor: vendorId, page_size: 9999 } }),
                apiClient.get('/procurement/purchase-returns/', { params: { vendor: vendorId, page_size: 9999 } }),
            ]);
            return {
                invoices: invoices.data.results || invoices.data || [],
                payments: payments.data.results || payments.data || [],
                returns: returns.data.results || returns.data || [],
            };
        },
        enabled: !!vendorId,
        staleTime: STALE_TIME,
    });
};

// ============================================================================
// VENDORS
// ============================================================================

export const useVendors = (filters: Record<string, any> = {}) => {
    return useQuery({
        queryKey: ['vendors', filters],
        queryFn: async () => {
            const { data } = await apiClient.get('/procurement/vendors/', { params: filters });
            // Return full paginated response when page param is present, otherwise just results for backward compat
            if (filters.page) return data;
            return data.results || data;
        },
        staleTime: STALE_TIME,
    });
};

export const useCreateVendor = () => {
    const queryClient = useQueryClient();
    return useMutation({
        mutationFn: async (payload: { name: string; code: string; category: number; tax_id?: string; address?: string; email?: string; phone?: string; is_active?: boolean }) => {
            const { data } = await apiClient.post('/procurement/vendors/', payload);
            return data;
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['vendors'] });
        },
    });
};

export const useVendorPerformance = (vendorId: number) => {
    return useQuery({
        queryKey: ['vendor-performance', vendorId],
        queryFn: async () => {
            const { data } = await apiClient.get(`/procurement/vendors/${vendorId}/performance/`);
            return data;
        },
        staleTime: STALE_TIME,
        enabled: !!vendorId,
    });
};

export const useVendorPerformanceReport = () => {
    return useQuery({
        queryKey: ['vendor-performance-report'],
        queryFn: async () => {
            const { data } = await apiClient.get('/procurement/vendors/performance_report/');
            return data;
        },
        staleTime: STALE_TIME,
    });
};

// ============================================================================
// PURCHASE REQUISITIONS
// ============================================================================

export const usePurchaseRequests = (filters = {}) => {
    return useQuery({
        queryKey: ['purchase-requests', filters],
        queryFn: async () => {
            const { data } = await apiClient.get('/procurement/requests/', { params: filters });
            return data;
        },
        staleTime: STALE_TIME,
    });
};

/** Fetch a single Purchase Request by id (used when converting to PO). */
export const usePurchaseRequest = (id: number | null) => {
    return useQuery({
        queryKey: ['purchase-request', id],
        queryFn: async () => {
            const { data } = await apiClient.get(`/procurement/requests/${id}/`);
            return data;
        },
        enabled: !!id,
        staleTime: STALE_TIME,
    });
};

export const useCreatePR = () => {
    const queryClient = useQueryClient();
    return useMutation({
        mutationFn: async (prData: PurchaseRequestPayload) => {
            const { data } = await apiClient.post('/procurement/requests/', prData);
            return data;
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['purchase-requests'] });
        },
    });
};

export const useApprovePR = () => {
    const queryClient = useQueryClient();
    return useMutation({
        mutationFn: async (id: number) => {
            const { data } = await apiClient.post(`/procurement/requests/${id}/approve/`);
            return data;
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['purchase-requests'] });
        },
    });
};

export const useRejectPR = () => {
    const queryClient = useQueryClient();
    return useMutation({
        mutationFn: async (id: number) => {
            const { data } = await apiClient.post(`/procurement/requests/${id}/reject/`);
            return data;
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['purchase-requests'] });
        },
    });
};

export const useConvertPRtoPO = () => {
    const queryClient = useQueryClient();
    return useMutation({
        mutationFn: async ({ id, vendor_id, order_date, expected_delivery_date }: ConvertPRtoPOPayload) => {
            const { data } = await apiClient.post(`/procurement/requests/${id}/convert_to_po/`, {
                vendor_id,
                order_date,
                expected_delivery_date,
            });
            return data;
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['purchase-requests'] });
            queryClient.invalidateQueries({ queryKey: ['purchase-orders'] });
        },
    });
};

// ============================================================================
// PURCHASE ORDERS
// ============================================================================

export const usePurchaseOrders = (filters = {}) => {
    return useQuery({
        queryKey: ['purchase-orders', filters],
        queryFn: async () => {
            const { data } = await apiClient.get('/procurement/orders/', { params: filters });
            return data;
        },
        staleTime: STALE_TIME,
    });
};

export const usePurchaseOrder = (id: number | null) => {
    return useQuery({
        queryKey: ['purchase-order', id],
        queryFn: async () => {
            const { data } = await apiClient.get(`/procurement/orders/${id}/`);
            return data;
        },
        staleTime: STALE_TIME,
        enabled: !!id,
    });
};

export const useCreatePO = () => {
    const queryClient = useQueryClient();
    return useMutation({
        mutationFn: async (poData: PurchaseOrderPayload) => {
            const { data } = await apiClient.post('/procurement/orders/', poData);
            return data;
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['purchase-orders'] });
        },
    });
};

export const usePostPO = () => {
    const queryClient = useQueryClient();
    return useMutation({
        mutationFn: async (id: number) => {
            const { data } = await apiClient.post(`/procurement/orders/${id}/post_order/`);
            return data;
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['purchase-orders'] });
            queryClient.invalidateQueries({ queryKey: ['journals'] });
            queryClient.invalidateQueries({ queryKey: ['budget-summary'] });
            queryClient.invalidateQueries({ queryKey: ['budget-utilization'] });
            queryClient.invalidateQueries({ queryKey: ['budget-alerts'] });
            queryClient.invalidateQueries({ queryKey: ['budget-encumbrances'] });
            // PO posting records DR Inventory / CR AP and increments vendor.balance
            queryClient.invalidateQueries({ queryKey: ['vendors'] });
            queryClient.invalidateQueries({ queryKey: ['vendor-ledger'] });
        },
    });
};

export const useSubmitPOForApproval = () => {
    const queryClient = useQueryClient();
    return useMutation({
        mutationFn: async (id: number) => {
            const { data } = await apiClient.post(`/procurement/orders/${id}/submit_for_approval/`);
            return data;
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['purchase-orders'] });
        },
    });
};

/** Approve a Pending PO directly from the list (Pending → Approved). */
export const useApprovePO = () => {
    const queryClient = useQueryClient();
    return useMutation({
        mutationFn: async (id: number) => {
            const { data } = await apiClient.post(`/procurement/orders/${id}/approve/`);
            return data;
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['purchase-orders'] });
            queryClient.invalidateQueries({ queryKey: ['purchase-order'] });
            queryClient.invalidateQueries({ queryKey: ['budget-summary'] });
            queryClient.invalidateQueries({ queryKey: ['budget-utilization'] });
        },
    });
};

/** Reject a Pending PO (Pending → Rejected). */
export const useRejectPO = () => {
    const queryClient = useQueryClient();
    return useMutation({
        mutationFn: async (id: number) => {
            const { data } = await apiClient.post(`/procurement/orders/${id}/reject/`);
            return data;
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['purchase-orders'] });
            queryClient.invalidateQueries({ queryKey: ['purchase-order'] });
        },
    });
};

export const useClosePO = () => {
    const queryClient = useQueryClient();
    return useMutation({
        mutationFn: async (id: number) => {
            const { data } = await apiClient.post(`/procurement/orders/${id}/close_order/`);
            return data;
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['purchase-orders'] });
        },
    });
};

// ============================================================================
// GOODS RECEIVED NOTES
// ============================================================================

export const useGRNs = (filters = {}) => {
    return useQuery({
        queryKey: ['grns', filters],
        queryFn: async () => {
            const { data } = await apiClient.get('/procurement/grns/', { params: filters });
            return data;
        },
        staleTime: STALE_TIME,
    });
};

export const useGRN = (id: number | null) => {
    return useQuery({
        queryKey: ['grn', id],
        queryFn: async () => {
            const { data } = await apiClient.get(`/procurement/grns/${id}/`);
            return data;
        },
        staleTime: STALE_TIME,
        enabled: !!id,
    });
};

export const useCreateGRN = () => {
    const queryClient = useQueryClient();
    return useMutation({
        mutationFn: async (grnData: GoodsReceivedNotePayload) => {
            const { data } = await apiClient.post('/procurement/grns/', grnData);
            return data;
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['grns'] });
            queryClient.invalidateQueries({ queryKey: ['purchase-orders'] });
        },
    });
};

export const usePostGRN = () => {
    const queryClient = useQueryClient();
    return useMutation({
        mutationFn: async (id: number) => {
            const { data } = await apiClient.post(`/procurement/grns/${id}/post_grn/`);
            return data;
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['grns'] });
            queryClient.invalidateQueries({ queryKey: ['purchase-orders'] });
            // Cross-module: GRN posting creates stock movements and updates inventory
            queryClient.invalidateQueries({ queryKey: ['items'] });
            queryClient.invalidateQueries({ queryKey: ['stock-movements'] });
            queryClient.invalidateQueries({ queryKey: ['inventory-stocks'] });
            queryClient.invalidateQueries({ queryKey: ['inventory-stock'] }); // prefix match
            queryClient.invalidateQueries({ queryKey: ['inventory-valuation'] });
            // GRN posting also posts AP journal and affects budget utilization
            queryClient.invalidateQueries({ queryKey: ['journals'] });
            queryClient.invalidateQueries({ queryKey: ['budget-summary'] });
            queryClient.invalidateQueries({ queryKey: ['budget-utilization'] });
            queryClient.invalidateQueries({ queryKey: ['budget-alerts'] });
            queryClient.invalidateQueries({ queryKey: ['budget-encumbrances'] });
            // When PO is not yet Posted, GRN posting increments vendor.balance
            queryClient.invalidateQueries({ queryKey: ['vendors'] });
            queryClient.invalidateQueries({ queryKey: ['vendor-ledger'] });
        },
    });
};

export const useCancelGRN = () => {
    const queryClient = useQueryClient();
    return useMutation({
        mutationFn: async (id: number) => {
            const { data } = await apiClient.post(`/procurement/grns/${id}/cancel_grn/`);
            return data;
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['grns'] });
            queryClient.invalidateQueries({ queryKey: ['purchase-orders'] });
            queryClient.invalidateQueries({ queryKey: ['items'] });
            queryClient.invalidateQueries({ queryKey: ['stock-movements'] });
            queryClient.invalidateQueries({ queryKey: ['inventory-stocks'] });
            queryClient.invalidateQueries({ queryKey: ['inventory-stock'] }); // prefix match
            queryClient.invalidateQueries({ queryKey: ['inventory-valuation'] });
            queryClient.invalidateQueries({ queryKey: ['journals'] });
        },
    });
};

export const useBulkCancelGRN = () => {
    const queryClient = useQueryClient();
    return useMutation({
        mutationFn: async (ids: number[]) => {
            const { data } = await apiClient.post('/procurement/grns/bulk_cancel/', { ids });
            return data;
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['grns'] });
            queryClient.invalidateQueries({ queryKey: ['purchase-orders'] });
            queryClient.invalidateQueries({ queryKey: ['items'] });
            queryClient.invalidateQueries({ queryKey: ['stock-movements'] });
            queryClient.invalidateQueries({ queryKey: ['inventory-stocks'] });
            queryClient.invalidateQueries({ queryKey: ['inventory-stock'] }); // prefix match
            queryClient.invalidateQueries({ queryKey: ['inventory-valuation'] });
            queryClient.invalidateQueries({ queryKey: ['journals'] });
        },
    });
};

// ============================================================================
// 3-WAY MATCHING
// ============================================================================

export const useInvoiceMatchings = (filters = {}) => {
    return useQuery({
        queryKey: ['invoice-matchings', filters],
        queryFn: async () => {
            const { data } = await apiClient.get('/procurement/invoice-matching/', { params: filters });
            return data;
        },
        staleTime: STALE_TIME,
    });
};

export const useCreateMatching = () => {
    const queryClient = useQueryClient();
    return useMutation({
        mutationFn: async (matchingData: InvoiceMatchingPayload) => {
            const { data } = await apiClient.post('/procurement/invoice-matching/', matchingData);
            return data;
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['invoice-matchings'] });
        },
    });
};

export const useMatchInvoice = () => {
    const queryClient = useQueryClient();
    return useMutation({
        mutationFn: async ({ id, variance_reason }: MatchInvoicePayload) => {
            const { data } = await apiClient.post(`/procurement/invoice-matching/${id}/match/`, {
                variance_reason,
            });
            return data;
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['invoice-matchings'] });
        },
    });
};

export const useRejectMatching = () => {
    const queryClient = useQueryClient();
    return useMutation({
        mutationFn: async ({ id, reason }: RejectMatchingPayload) => {
            const { data } = await apiClient.post(`/procurement/invoice-matching/${id}/reject/`, {
                reason,
            });
            return data;
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['invoice-matchings'] });
        },
    });
};

/** Fetch a single InvoiceMatching by ID for the detail/view page. */
export const useInvoiceMatching = (id: number | null) => {
    return useQuery({
        queryKey: ['invoice-matching', id],
        queryFn: async () => {
            const { data } = await apiClient.get(`/procurement/invoice-matching/${id}/`);
            return data;
        },
        staleTime: STALE_TIME,
        enabled: !!id,
    });
};

/**
 * Submit a Matched verification for finance approval. Routes via the
 * centralized workflow engine — small invoices can auto-approve.
 */
export const useSubmitMatchingForApproval = () => {
    const queryClient = useQueryClient();
    return useMutation({
        mutationFn: async (id: number) => {
            const { data } = await apiClient.post(
                `/procurement/invoice-matching/${id}/submit_for_approval/`,
            );
            return data;
        },
        onSuccess: (_data, id) => {
            queryClient.invalidateQueries({ queryKey: ['invoice-matchings'] });
            queryClient.invalidateQueries({ queryKey: ['invoice-matching', id] });
            queryClient.invalidateQueries({ queryKey: ['approvals'] });
        },
    });
};

/**
 * SAP MIRO-style single-call verification + posting.
 *
 * Submits the invoice header (PO + GRN + amounts + reference + tax) and,
 * in one atomic backend transaction:
 *   1. Creates the InvoiceMatching record
 *   2. Calculates the 3-way match
 *   3. Creates/updates the linked VendorInvoice with the verified amounts
 *   4. Posts the GL journal (DR GR/IR / CR AP)
 *   5. Closes the budget commitment (INVOICED → CLOSED)
 *
 * Two backend gates require the client to acknowledge:
 *  - `partial_receipt: true`  → show "goods only partially received" modal
 *  - `requires_variance_reason: true` → variance > 5%, prompt for reason
 *
 * Both can be retried by adding `acknowledge_partial: true` and/or
 * `variance_reason: "..."` to the next call.
 */
export interface VerifyAndPostPayload {
    purchase_order: number;
    goods_received_note?: number | null;
    invoice_reference: string;
    invoice_date: string;
    invoice_amount: number;
    invoice_subtotal?: number;
    invoice_tax_amount?: number;
    notes?: string;
    variance_reason?: string;
    acknowledge_partial?: boolean;
    down_payment_amount?: number;
    /**
     * SAP MIRO Account Assignment override. The backend defaults to
     * `purchase_order.mda` when omitted; supply this only when the
     * verifier needs to redirect the spend to a different MDA than the
     * PO's owning MDA (rare but supported).
     */
    mda?: number | null;
}
export const useVerifyAndPost = () => {
    const queryClient = useQueryClient();
    return useMutation({
        mutationFn: async (payload: VerifyAndPostPayload) => {
            const { data } = await apiClient.post(
                '/procurement/invoice-matching/verify_and_post/',
                payload,
            );
            return data;
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['invoice-matchings'] });
            queryClient.invalidateQueries({ queryKey: ['vendor-invoices'] });
            queryClient.invalidateQueries({ queryKey: ['journals'] });
            queryClient.invalidateQueries({ queryKey: ['vendors'] });
            queryClient.invalidateQueries({ queryKey: ['vendor-ledger'] });
            queryClient.invalidateQueries({ queryKey: ['budget-summary'] });
            queryClient.invalidateQueries({ queryKey: ['budget-utilization'] });
            queryClient.invalidateQueries({ queryKey: ['budget-encumbrances'] });
            queryClient.invalidateQueries({ queryKey: ['budget-execution-report'] });
        },
    });
};

/**
 * SAP MIRO "Simulate" — preview the GL journal without writing anything.
 *
 * Returns the proposed DR/CR lines, totals, and the calculated 3-way
 * match result so the verifier can sanity-check the GL hit before
 * committing. No InvoiceMatching, VendorInvoice, or journal records
 * are created.
 */
export interface SimulatePayload {
    purchase_order: number;
    goods_received_note?: number | null;
    invoice_reference?: string;
    invoice_amount: number;
    invoice_subtotal?: number;
    invoice_tax_amount?: number;
}
export interface SimulatedJournalLine {
    account_code: string;
    account_name: string;
    account_type: string;
    debit: string;
    credit: string;
    memo: string;
}
export interface SimulationResult {
    simulated: true;
    match_type: string;
    status: string;
    variance_amount: string;
    variance_percentage: string;
    partial_receipt: boolean;
    po_total: string;
    grn_total: string;
    invoice_amount: string;
    invoice_subtotal: string;
    invoice_tax: string;
    proposed_lines: SimulatedJournalLine[];
    total_debit: string;
    total_credit: string;
    balanced: boolean;
    accounts_used: { gr_ir_clearing: string | null; accounts_payable: string | null };
}
export const useSimulateInvoice = () => {
    return useMutation({
        mutationFn: async (payload: SimulatePayload) => {
            const { data } = await apiClient.post<SimulationResult>(
                '/procurement/invoice-matching/simulate/',
                payload,
            );
            return data;
        },
        // Read-only — no cache invalidation needed.
    });
};

/**
 * Post the verified invoice to the GL — IPSAS three-way close.
 * Locates/creates the linked VendorInvoice, copies the verified
 * amounts onto it, posts the journal (DR GR/IR / CR AP), and flips
 * the budget commitment INVOICED → CLOSED.
 */
export const usePostMatching = () => {
    const queryClient = useQueryClient();
    return useMutation({
        mutationFn: async (id: number) => {
            const { data } = await apiClient.post(
                `/procurement/invoice-matching/${id}/post_to_gl/`,
            );
            return data;
        },
        onSuccess: (_data, id) => {
            queryClient.invalidateQueries({ queryKey: ['invoice-matchings'] });
            queryClient.invalidateQueries({ queryKey: ['invoice-matching', id] });
            // Cross-module invalidation: VI posting affects journals, AP, budget.
            queryClient.invalidateQueries({ queryKey: ['vendor-invoices'] });
            queryClient.invalidateQueries({ queryKey: ['journals'] });
            queryClient.invalidateQueries({ queryKey: ['vendors'] });
            queryClient.invalidateQueries({ queryKey: ['vendor-ledger'] });
            queryClient.invalidateQueries({ queryKey: ['budget-summary'] });
            queryClient.invalidateQueries({ queryKey: ['budget-utilization'] });
            queryClient.invalidateQueries({ queryKey: ['budget-encumbrances'] });
            queryClient.invalidateQueries({ queryKey: ['budget-execution-report'] });
        },
    });
};

// ============================================================================
// PURCHASE RETURNS
// ============================================================================

/** Fetch a single GRN by ID — used when the form pre-loads lines from a specific GRN */
export const useGRNsForPO = (poId: number | null | undefined) => {
    return useQuery({
        queryKey: ['grns', { purchase_order: poId }],
        queryFn: async () => {
            const { data } = await apiClient.get('/procurement/grns/', {
                params: { purchase_order: poId, page_size: 100 },
            });
            return (data.results || data) as any[];
        },
        enabled: !!poId,
        staleTime: STALE_TIME,
    });
};

export const usePurchaseReturns = (filters = {}) => {
    return useQuery({
        queryKey: ['purchase-returns', filters],
        queryFn: async () => {
            const { data } = await apiClient.get('/procurement/purchase-returns/', { params: filters });
            return data;
        },
        staleTime: STALE_TIME,
    });
};

export const usePurchaseReturn = (id: number | null | undefined) => {
    return useQuery({
        queryKey: ['purchase-return', id],
        queryFn: async () => {
            const { data } = await apiClient.get(`/procurement/purchase-returns/${id}/`);
            return data;
        },
        staleTime: STALE_TIME,
        enabled: !!id,
    });
};

export const useCreatePurchaseReturn = () => {
    const queryClient = useQueryClient();
    return useMutation({
        mutationFn: async (payload: PurchaseReturnPayload) => {
            const { data } = await apiClient.post('/procurement/purchase-returns/', payload);
            return data;
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['purchase-returns'] });
        },
    });
};

/** Transition a Draft return to Pending for manager review */
export const useSubmitPurchaseReturn = () => {
    const queryClient = useQueryClient();
    return useMutation({
        mutationFn: async (id: number) => {
            const { data } = await apiClient.post(`/procurement/purchase-returns/${id}/submit_for_approval/`);
            return data;
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['purchase-returns'] });
            queryClient.invalidateQueries({ queryKey: ['purchase-return'] });
        },
    });
};

export const useApprovePurchaseReturn = () => {
    const queryClient = useQueryClient();
    return useMutation({
        mutationFn: async (id: number) => {
            const { data } = await apiClient.post(`/procurement/purchase-returns/${id}/approve/`);
            return data;
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['purchase-returns'] });
        },
    });
};

export const useCompletePurchaseReturn = () => {
    const queryClient = useQueryClient();
    return useMutation({
        mutationFn: async ({ id, warehouse_id }: { id: number; warehouse_id?: number }) => {
            const { data } = await apiClient.post(`/procurement/purchase-returns/${id}/complete/`, {
                warehouse_id,
            });
            return data;
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['purchase-returns'] });
            queryClient.invalidateQueries({ queryKey: ['purchase-return'] });
            // Cross-module: purchase return creates stock OUT movements and GL entries
            queryClient.invalidateQueries({ queryKey: ['items'] });
            queryClient.invalidateQueries({ queryKey: ['stock-movements'] });
            queryClient.invalidateQueries({ queryKey: ['inventory-stocks'] });
            queryClient.invalidateQueries({ queryKey: ['inventory-stock'] }); // prefix match
            queryClient.invalidateQueries({ queryKey: ['inventory-valuation'] });
            queryClient.invalidateQueries({ queryKey: ['journals'] });
            // Credit note auto-created on complete
            queryClient.invalidateQueries({ queryKey: ['vendor-credit-notes'] });
            // Purchase return reduces vendor balance (AP is reduced via credit note)
            queryClient.invalidateQueries({ queryKey: ['vendors'] });
            queryClient.invalidateQueries({ queryKey: ['vendor-ledger'] });
        },
    });
};

export const useCancelPurchaseReturn = () => {
    const queryClient = useQueryClient();
    return useMutation({
        mutationFn: async (id: number) => {
            const { data } = await apiClient.post(`/procurement/purchase-returns/${id}/cancel/`);
            return data;
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['purchase-returns'] });
        },
    });
};

// ============================================================================
// VENDOR CATEGORY HOOKS
// ============================================================================

export const useVendorCategories = (filters: Record<string, any> = {}) => {
    return useQuery({
        queryKey: ['vendor-categories', filters],
        queryFn: async () => {
            const { data } = await apiClient.get('/procurement/vendor-categories/', { params: filters });
            return data.results || data;
        },
        staleTime: STALE_TIME,
    });
};

export const useCreateVendorCategory = () => {
    const queryClient = useQueryClient();
    return useMutation({
        mutationFn: async (payload: { name: string; code: string; description?: string; reconciliation_account: number; is_active?: boolean }) => {
            const { data } = await apiClient.post('/procurement/vendor-categories/', payload);
            return data;
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['vendor-categories'] });
        },
    });
};

export const useUpdateVendorCategory = () => {
    const queryClient = useQueryClient();
    return useMutation({
        mutationFn: async ({ id, ...payload }: { id: number; name?: string; code?: string; description?: string; reconciliation_account?: number; is_active?: boolean }) => {
            const { data } = await apiClient.patch(`/procurement/vendor-categories/${id}/`, payload);
            return data;
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['vendor-categories'] });
        },
    });
};

export const useDeleteVendorCategory = () => {
    const queryClient = useQueryClient();
    return useMutation({
        mutationFn: async (id: number) => {
            await apiClient.delete(`/procurement/vendor-categories/${id}/`);
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['vendor-categories'] });
        },
    });
};

// ============================================================================
// BANK ACCOUNTS (for Down Payment payment method selection)
// ============================================================================

export const useBankAccounts = (filters?: { account_type?: string }) => {
    return useQuery({
        queryKey: ['bank-accounts', filters],
        queryFn: async () => {
            const { data } = await apiClient.get('/accounting/bank-accounts/', { params: filters });
            return data;
        },
        staleTime: STALE_TIME,
    });
};

// ============================================================================
// DOWN PAYMENT REQUESTS
// ============================================================================

export const useDownPaymentRequests = (filters?: { status?: string; purchase_order?: number }) => {
    return useQuery({
        queryKey: ['down-payment-requests', filters],
        queryFn: async () => {
            const params = new URLSearchParams();
            if (filters?.status) params.set('status', filters.status);
            if (filters?.purchase_order) params.set('purchase_order', String(filters.purchase_order));
            const { data } = await apiClient.get(`/procurement/down-payment-requests/?${params}`);
            return data;
        },
        staleTime: STALE_TIME,
    });
};

export const useApproveDownPayment = () => {
    const queryClient = useQueryClient();
    return useMutation({
        mutationFn: async (id: number) => {
            const { data } = await apiClient.post(`/procurement/down-payment-requests/${id}/approve/`);
            return data;
        },
        onSuccess: () => queryClient.invalidateQueries({ queryKey: ['down-payment-requests'] }),
    });
};

export const useRejectDownPayment = () => {
    const queryClient = useQueryClient();
    return useMutation({
        mutationFn: async ({ id, reason }: { id: number; reason: string }) => {
            const { data } = await apiClient.post(`/procurement/down-payment-requests/${id}/reject/`, { reason });
            return data;
        },
        onSuccess: () => queryClient.invalidateQueries({ queryKey: ['down-payment-requests'] }),
    });
};

export const useProcessDownPayment = () => {
    const queryClient = useQueryClient();
    return useMutation({
        mutationFn: async (id: number) => {
            const { data } = await apiClient.post(`/procurement/down-payment-requests/${id}/process/`);
            return data;
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['down-payment-requests'] });
            queryClient.invalidateQueries({ queryKey: ['payments'] });
        },
    });
};

/**
 * Fetch the processed DownPaymentRequest for a specific PO (if any).
 * Returns null when no processed DPR exists.
 * Used by the invoice verification form to show the "Apply Down Payment" section.
 */
export const useDownPaymentForPO = (poId: number | null | undefined) => {
    return useQuery({
        queryKey: ['down-payment-for-po', poId],
        queryFn: async () => {
            const { data } = await apiClient.get(
                `/procurement/down-payment-requests/?purchase_order=${poId}&status=Processed&page_size=1`,
            );
            const results = data?.results ?? data;
            return Array.isArray(results) && results.length > 0 ? results[0] : null;
        },
        enabled: !!poId,
        staleTime: STALE_TIME,
    });
};

/**
 * Apply (or adjust) a down payment deduction against an InvoiceMatching record.
 * POST /procurement/invoice-matching/{id}/apply_down_payment/
 * Body: { amount?: number }  — omit to apply the full available advance balance.
 */
export const useApplyDownPayment = () => {
    const queryClient = useQueryClient();
    return useMutation({
        mutationFn: async ({ matchingId, amount }: { matchingId: number; amount?: number }) => {
            const body: Record<string, any> = {};
            if (amount !== undefined) body.amount = amount;
            const { data } = await apiClient.post(
                `/procurement/invoice-matching/${matchingId}/apply_down_payment/`,
                body,
            );
            return data;
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['invoice-matchings'] });
            queryClient.invalidateQueries({ queryKey: ['down-payment-requests'] });
            queryClient.invalidateQueries({ queryKey: ['down-payment-for-po'] });
        },
    });
};
