import type { ModuleConfig } from '../_base/types';

export const moduleConfig: ModuleConfig = {
  key: 'legal',
  label: 'Legal, Risk & Case Tracking',
  icon: '\u2696\uFE0F',
  description: 'Litigation cases, hearing diaries, case costs, risk register and provisions.',
  basePath: '/legal',
  entities: [
    {
      key: 'legalCase',
      plural: 'cases',
      label: 'Legal Case',
      searchField: 'case_number',
      statusField: 'stage',
      idField: 'id',
      columns: [
        { name: 'case_number', label: 'Case Number', type: 'text' },
        { name: 'title', label: 'Title', type: 'text' },
        { name: 'stage', label: 'Stage', type: 'select', options: { intake: 'Intake', pleadings: 'Pleadings', hearing: 'Hearing', judgement: 'Judgement', appeal: 'Appeal', closed: 'Closed' } },
        { name: 'court', label: 'Court', type: 'text', secondary: true },
        { name: 'next_hearing_date', label: 'Next Hearing', type: 'date' },
      ],
      fields: [
        { name: 'case_number', label: 'Case Number', type: 'text', required: true },
        { name: 'title', label: 'Title', type: 'text', required: true },
        { name: 'court', label: 'Court', type: 'text' },
        { name: 'claimant', label: 'Claimant', type: 'text', secondary: true },
        { name: 'defendant', label: 'Defendant', type: 'text', secondary: true },
        { name: 'stage', label: 'Stage', type: 'select', required: true, options: { intake: 'Intake', pleadings: 'Pleadings', hearing: 'Hearing', judgement: 'Judgement', appeal: 'Appeal', closed: 'Closed' } },
        { name: 'next_hearing_date', label: 'Next Hearing Date', type: 'date' },
        { name: 'assigned_counsel', label: 'Assigned Counsel', type: 'text', secondary: true },
        { name: 'summary', label: 'Summary', type: 'longtext', secondary: true },
      ],
    },
    {
      key: 'hearingDiary',
      plural: 'hearings',
      label: 'Hearing Diary',
      searchField: 'outcome',
      idField: 'id',
      columns: [
        { name: 'hearing_date', label: 'Hearing Date', type: 'date' },
        { name: 'case', label: 'Case', type: 'integer', reference: { module: 'legal', entity: 'legalCase' } },
        { name: 'outcome', label: 'Outcome', type: 'longtext', secondary: true },
        { name: 'next_hearing_date', label: 'Next Hearing', type: 'date', secondary: true },
      ],
      fields: [
        { name: 'case', label: 'Case', type: 'integer', required: true, reference: { module: 'legal', entity: 'legalCase' } },
        { name: 'hearing_date', label: 'Hearing Date', type: 'date', required: true },
        { name: 'outcome', label: 'Outcome', type: 'longtext', secondary: true },
        { name: 'next_hearing_date', label: 'Next Hearing Date', type: 'date' },
      ],
    },
    {
      key: 'caseCost',
      plural: 'costs',
      label: 'Case Cost',
      searchField: 'description',
      idField: 'id',
      columns: [
        { name: 'cost_date', label: 'Date', type: 'date' },
        { name: 'case', label: 'Case', type: 'integer', reference: { module: 'legal', entity: 'legalCase' } },
        { name: 'amount', label: 'Amount', type: 'decimal', numeric: true },
        { name: 'cost_type', label: 'Type', type: 'text' },
        { name: 'is_award', label: 'Award?', type: 'boolean' },
      ],
      fields: [
        { name: 'case', label: 'Case', type: 'integer', required: true, reference: { module: 'legal', entity: 'legalCase' } },
        { name: 'cost_date', label: 'Cost Date', type: 'date', required: true },
        { name: 'description', label: 'Description', type: 'text', secondary: true },
        { name: 'amount', label: 'Amount', type: 'decimal', numeric: true, required: true },
        { name: 'cost_type', label: 'Cost Type', type: 'text' },
        { name: 'is_award', label: 'Judgement Award', type: 'boolean' },
      ],
    },
    {
      key: 'riskRegister',
      plural: 'risks',
      label: 'Risk Register',
      searchField: 'title',
      idField: 'id',
      columns: [
        { name: 'title', label: 'Title', type: 'text' },
        { name: 'category', label: 'Category', type: 'select', options: { legal: 'Legal', financial: 'Financial', operational: 'Operational', compliance: 'Compliance', reputational: 'Reputational' } },
        { name: 'likelihood', label: 'Likelihood', type: 'select', options: { rare: 'Rare', unlikely: 'Unlikely', possible: 'Possible', likely: 'Likely', almost_certain: 'Almost Certain' } },
        { name: 'impact', label: 'Impact', type: 'select', options: { negligible: 'Negligible', minor: 'Minor', moderate: 'Moderate', major: 'Major', severe: 'Severe' } },
        { name: 'is_active', label: 'Active', type: 'boolean' },
      ],
      fields: [
        { name: 'title', label: 'Title', type: 'text', required: true },
        { name: 'category', label: 'Category', type: 'select', required: true, options: { legal: 'Legal', financial: 'Financial', operational: 'Operational', compliance: 'Compliance', reputational: 'Reputational' } },
        { name: 'likelihood', label: 'Likelihood', type: 'select', required: true, options: { rare: 'Rare', unlikely: 'Unlikely', possible: 'Possible', likely: 'Likely', almost_certain: 'Almost Certain' } },
        { name: 'impact', label: 'Impact', type: 'select', required: true, options: { negligible: 'Negligible', minor: 'Minor', moderate: 'Moderate', major: 'Major', severe: 'Severe' } },
        { name: 'mitigation', label: 'Mitigation', type: 'longtext', secondary: true },
        { name: 'mitigation_owner', label: 'Mitigation Owner', type: 'text', secondary: true },
        { name: 'is_active', label: 'Active', type: 'boolean' },
        { name: 'case', label: 'Related Case', type: 'integer', reference: { module: 'legal', entity: 'legalCase' } },
      ],
    },
    {
      key: 'litigationProvisionLink',
      plural: 'provision-links',
      label: 'Provision Link',
      searchField: 'provision',
      idField: 'id',
      columns: [
        { name: 'case', label: 'Case', type: 'integer', reference: { module: 'legal', entity: 'legalCase' } },
        { name: 'provision', label: 'Provision', type: 'integer' },
        { name: 'amount', label: 'Amount', type: 'decimal', numeric: true },
        { name: 'contingent_liability', label: 'Contingent Liability', type: 'integer', secondary: true },
        { name: 'linked_at', label: 'Linked At', type: 'datetime', secondary: true },
      ],
      fields: [
        { name: 'case', label: 'Case', type: 'integer', required: true, reference: { module: 'legal', entity: 'legalCase' } },
        { name: 'provision', label: 'Provision', type: 'integer', required: true },
        { name: 'contingent_liability', label: 'Contingent Liability', type: 'integer' },
        { name: 'amount', label: 'Amount', type: 'decimal', numeric: true, required: true },
        { name: 'linked_by', label: 'Linked By', type: 'integer', readOnly: true, hideInForm: true },
        { name: 'linked_at', label: 'Linked At', type: 'datetime', readOnly: true, hideInForm: true },
      ],
    },
  ],
};
