import type { ModuleConfig } from '../_base/types';

export const moduleConfig: ModuleConfig = {
  key: 'staff_advances',
  label: 'Staff Advances, Imprest & Travel',
  icon: '✈️',
  description: 'Staff advances, imprest accounts, retirements, per diem tables, travel requests and travel advances.',
  basePath: '/staff-advances',
  entities: [
    {
      key: 'staffAdvance',
      plural: 'staff-advances',
      label: 'Staff Advances',
      searchField: 'reference',
      statusField: 'status',
      idField: 'id',
      columns: [
        { name: 'reference', label: 'Reference', type: 'text' },
        { name: 'employee_name', label: 'Employee', type: 'text' },
        { name: 'amount', label: 'Amount', type: 'decimal', numeric: true },
        { name: 'advance_date', label: 'Advance Date', type: 'date' },
        { name: 'status', label: 'Status', type: 'select', options: { OUTSTANDING: 'Outstanding', PARTIAL: 'Partially Recovered', CLEARED: 'Fully Cleared' } },
      ],
      fields: [
        { name: 'id', label: 'ID', type: 'integer', readOnly: true, hideInForm: true },
        { name: 'employee', label: 'Employee', type: 'integer', required: true, reference: { module: 'hrm', entity: 'employee' } },
        { name: 'employee_name', label: 'Employee Name', type: 'text', readOnly: true, hideInForm: true },
        { name: 'recon_account', label: 'Recon Account', type: 'integer', required: true, reference: { module: 'accounting', entity: 'account' } },
        { name: 'purpose', label: 'Purpose', type: 'select', options: { travel: 'Travel', estacode: 'Estacode / Per-diem', imprest: 'Imprest', welfare: 'Welfare', other: 'Other' } },
        { name: 'amount', label: 'Amount', type: 'decimal', numeric: true, required: true },
        { name: 'advance_date', label: 'Advance Date', type: 'date' },
        { name: 'recovery_start', label: 'Recovery Start', type: 'date', secondary: true },
        { name: 'status', label: 'Status', type: 'select', options: { OUTSTANDING: 'Outstanding', PARTIAL: 'Partially Recovered', CLEARED: 'Fully Cleared' } },
        { name: 'recovered_amount', label: 'Recovered Amount', type: 'decimal', numeric: true, readOnly: true, hideInForm: true },
        { name: 'outstanding', label: 'Outstanding', type: 'decimal', numeric: true, readOnly: true, hideInForm: true },
        { name: 'journal', label: 'Journal', type: 'integer', readOnly: true, hideInForm: true },
        { name: 'reference', label: 'Reference', type: 'text', secondary: true },
        { name: 'notes', label: 'Notes', type: 'longtext', secondary: true },
        { name: 'created_at', label: 'Created At', type: 'datetime', readOnly: true, hideInForm: true },
        { name: 'updated_at', label: 'Updated At', type: 'datetime', readOnly: true, hideInForm: true },
      ],
    },
    {
      key: 'imprestAccount',
      plural: 'imprest-accounts',
      label: 'Imprest Accounts',
      searchField: 'reference',
      statusField: 'status',
      idField: 'id',
      columns: [
        { name: 'reference', label: 'Reference', type: 'text' },
        { name: 'employee', label: 'Employee', type: 'integer' },
        { name: 'issued_amount', label: 'Issued Amount', type: 'decimal', numeric: true },
        { name: 'issue_date', label: 'Issue Date', type: 'date' },
        { name: 'status', label: 'Status', type: 'select', options: { OPEN: 'Open', FROZEN: 'Frozen — retirement outstanding', CLOSED: 'Closed' } },
      ],
      fields: [
        { name: 'id', label: 'ID', type: 'integer', readOnly: true, hideInForm: true },
        { name: 'employee', label: 'Employee', type: 'integer', required: true, reference: { module: 'hrm', entity: 'employee' } },
        { name: 'reference', label: 'Reference', type: 'text', secondary: true },
        { name: 'issued_amount', label: 'Issued Amount', type: 'decimal', numeric: true },
        { name: 'retired_amount', label: 'Retired Amount', type: 'decimal', numeric: true, readOnly: true, hideInForm: true },
        { name: 'replenished_amount', label: 'Replenished Amount', type: 'decimal', numeric: true, readOnly: true, hideInForm: true },
        { name: 'issue_date', label: 'Issue Date', type: 'date' },
        { name: 'retirement_due_date', label: 'Retirement Due Date', type: 'date', secondary: true },
        { name: 'status', label: 'Status', type: 'select', options: { OPEN: 'Open', FROZEN: 'Frozen — retirement outstanding', CLOSED: 'Closed' } },
        { name: 'outstanding_retirement', label: 'Outstanding Retirement', type: 'decimal', numeric: true, readOnly: true, hideInForm: true },
        { name: 'created_at', label: 'Created At', type: 'datetime', readOnly: true, hideInForm: true },
        { name: 'updated_at', label: 'Updated At', type: 'datetime', readOnly: true, hideInForm: true },
      ],
    },
    {
      key: 'imprestRetirement',
      plural: 'imprest-retirements',
      label: 'Imprest Retirements',
      searchField: 'imprest',
      idField: 'id',
      columns: [
        { name: 'imprest', label: 'Imprest', type: 'integer' },
        { name: 'retirement_date', label: 'Retirement Date', type: 'date' },
        { name: 'amount', label: 'Amount', type: 'decimal', numeric: true },
        { name: 'approved_by', label: 'Approved By', type: 'integer', secondary: true },
      ],
      fields: [
        { name: 'id', label: 'ID', type: 'integer', readOnly: true, hideInForm: true },
        { name: 'imprest', label: 'Imprest', type: 'integer', required: true, reference: { module: 'staff_advances', entity: 'imprestAccount' } },
        { name: 'retirement_date', label: 'Retirement Date', type: 'date' },
        { name: 'amount', label: 'Amount', type: 'decimal', numeric: true, required: true },
        { name: 'supporting_docs', label: 'Supporting Docs', type: 'longtext', secondary: true },
        { name: 'approved_by', label: 'Approved By', type: 'integer', readOnly: true, hideInForm: true },
        { name: 'approved_at', label: 'Approved At', type: 'datetime', readOnly: true, hideInForm: true },
        { name: 'journal', label: 'Journal', type: 'integer', readOnly: true, hideInForm: true },
      ],
    },
    {
      key: 'perDiemTable',
      plural: 'per-diem',
      label: 'Per Diem Table',
      searchField: 'destination',
      idField: 'id',
      columns: [
        { name: 'grade', label: 'Grade', type: 'select', options: { Entry: 'Entry Level', Mid: 'Mid Level', Senior: 'Senior Level', Manager: 'Manager', Director: 'Director', Executive: 'Executive' } },
        { name: 'destination', label: 'Destination', type: 'text' },
        { name: 'daily_rate', label: 'Daily Rate', type: 'decimal', numeric: true },
        { name: 'effective_date', label: 'Effective Date', type: 'date' },
        { name: 'is_active', label: 'Active', type: 'boolean', secondary: true },
      ],
      fields: [
        { name: 'id', label: 'ID', type: 'integer', readOnly: true, hideInForm: true },
        { name: 'grade', label: 'Grade', type: 'select', required: true, options: { Entry: 'Entry Level', Mid: 'Mid Level', Senior: 'Senior Level', Manager: 'Manager', Director: 'Director', Executive: 'Executive' } },
        { name: 'destination', label: 'Destination', type: 'text', secondary: true },
        { name: 'daily_rate', label: 'Daily Rate', type: 'decimal', numeric: true, required: true },
        { name: 'effective_date', label: 'Effective Date', type: 'date' },
        { name: 'is_active', label: 'Active', type: 'boolean', secondary: true },
      ],
    },
    {
      key: 'travelRequest',
      plural: 'travel-requests',
      label: 'Travel Requests',
      searchField: 'destination',
      statusField: 'status',
      idField: 'id',
      columns: [
        { name: 'destination', label: 'Destination', type: 'text' },
        { name: 'employee_name', label: 'Employee', type: 'text' },
        { name: 'start_date', label: 'Start Date', type: 'date' },
        { name: 'estimated_cost', label: 'Estimated Cost', type: 'decimal', numeric: true },
        { name: 'status', label: 'Status', type: 'select', options: { draft: 'Draft', submitted: 'Submitted', approved: 'Approved', advanced: 'Advanced', retired: 'Retired', rejected: 'Rejected' } },
      ],
      fields: [
        { name: 'id', label: 'ID', type: 'integer', readOnly: true, hideInForm: true },
        { name: 'employee', label: 'Employee', type: 'integer', required: true, reference: { module: 'hrm', entity: 'employee' } },
        { name: 'employee_name', label: 'Employee Name', type: 'text', readOnly: true, hideInForm: true },
        { name: 'destination', label: 'Destination', type: 'text', required: true, placeholder: 'Travel destination' },
        { name: 'purpose', label: 'Purpose', type: 'longtext', secondary: true },
        { name: 'start_date', label: 'Start Date', type: 'date' },
        { name: 'end_date', label: 'End Date', type: 'date' },
        { name: 'days', label: 'Days', type: 'integer', numeric: true, secondary: true },
        { name: 'estimated_cost', label: 'Estimated Cost', type: 'decimal', numeric: true },
        { name: 'status', label: 'Status', type: 'select', options: { draft: 'Draft', submitted: 'Submitted', approved: 'Approved', advanced: 'Advanced', retired: 'Retired', rejected: 'Rejected' } },
        { name: 'created_at', label: 'Created At', type: 'datetime', readOnly: true, hideInForm: true },
        { name: 'updated_at', label: 'Updated At', type: 'datetime', readOnly: true, hideInForm: true },
      ],
    },
    {
      key: 'travelAdvance',
      plural: 'travel-advances',
      label: 'Travel Advances',
      searchField: 'travel_request',
      idField: 'id',
      columns: [
        { name: 'travel_request', label: 'Travel Request', type: 'integer' },
        { name: 'amount', label: 'Amount', type: 'decimal', numeric: true },
        { name: 'advance_date', label: 'Advance Date', type: 'date' },
        { name: 'staff_advance', label: 'Staff Advance', type: 'integer', secondary: true },
      ],
      fields: [
        { name: 'id', label: 'ID', type: 'integer', readOnly: true, hideInForm: true },
        { name: 'travel_request', label: 'Travel Request', type: 'integer', required: true, reference: { module: 'staff_advances', entity: 'travelRequest' } },
        { name: 'staff_advance', label: 'Staff Advance', type: 'integer', reference: { module: 'staff_advances', entity: 'staffAdvance' }, secondary: true },
        { name: 'amount', label: 'Amount', type: 'decimal', numeric: true, required: true },
        { name: 'advance_date', label: 'Advance Date', type: 'date' },
      ],
    },
    {
      key: 'travelRetirement',
      plural: 'travel-retirements',
      label: 'Travel Retirements',
      searchField: 'travel_advance',
      idField: 'id',
      columns: [
        { name: 'travel_advance', label: 'Travel Advance', type: 'integer' },
        { name: 'retired_date', label: 'Retired Date', type: 'date' },
        { name: 'amount', label: 'Amount', type: 'decimal', numeric: true },
        { name: 'balance_returned', label: 'Balance Returned', type: 'decimal', numeric: true, secondary: true },
      ],
      fields: [
        { name: 'id', label: 'ID', type: 'integer', readOnly: true, hideInForm: true },
        { name: 'travel_advance', label: 'Travel Advance', type: 'integer', required: true, reference: { module: 'staff_advances', entity: 'travelAdvance' } },
        { name: 'retired_date', label: 'Retired Date', type: 'date' },
        { name: 'amount', label: 'Amount', type: 'decimal', numeric: true, required: true },
        { name: 'balance_returned', label: 'Balance Returned', type: 'decimal', numeric: true, secondary: true },
        { name: 'documents', label: 'Documents', type: 'longtext', secondary: true },
      ],
    },
  ],
};
