# Generated by Django 5.2.14 on 2026-06-11 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('schema_name', models.CharField(db_index=True, max_length=63)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='queued', max_length=12)),
                ('triggered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('artifact_path', models.CharField(blank=True, max_length=512)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('kek_fingerprint', models.CharField(blank=True, max_length=32)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('error_class', models.CharField(blank=True, max_length=120)),
                ('triggered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['schema_name', '-triggered_at'], name='snapshots_s_schema__840b2d_idx'), models.Index(fields=['status', '-triggered_at'], name='snapshots_s_status_9138ac_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('schema_name__regex', '^[a-z][a-z0-9_]{0,62}$')), name='snapshotjob_schema_name_valid')],
            },
        ),
    ]
