# Generated by Django 5.2.14 on 2026-06-12 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snapshotjob',
            options={'ordering': ['-triggered_at', '-id']},
        ),
        migrations.AlterField(
            model_name='snapshotjob',
            name='artifact_path',
            field=models.CharField(blank=True, help_text='Path relative to SNAPSHOTS_BACKUP_DIR.', max_length=512),
        ),
        migrations.AlterField(
            model_name='snapshotjob',
            name='kek_fingerprint',
            field=models.CharField(blank=True, help_text='Identifier of the KEK used to encrypt the artifact (e.g., "kek-v1").', max_length=32),
        ),
        migrations.AlterField(
            model_name='snapshotjob',
            name='manifest',
            field=models.JSONField(blank=True, default=dict, help_text='Mirror of the manifest.json embedded in the artifact.'),
        ),
        migrations.AlterField(
            model_name='snapshotjob',
            name='schema_name',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='snapshotjob',
            name='sha256',
            field=models.CharField(blank=True, help_text='SHA-256 of the on-disk encrypted artifact bytes.', max_length=64),
        ),
        migrations.AlterField(
            model_name='snapshotjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('expired', 'Expired')], default='queued', max_length=12),
        ),
    ]
