# Generated by Django 4.2.28 on 2026-03-17 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('POST', 'Posted to GL'), ('UNPOST', 'Unposted from GL'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('CANCEL', 'Cancelled'), ('VOID', 'Voided'), ('CLOSE', 'Closed'), ('OPEN', 'Opened'), ('LOCK', 'Locked'), ('UNLOCK', 'Unlocked'), ('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('VIEW', 'Viewed'), ('EXPORT', 'Exported'), ('IMPORT', 'Imported')], db_index=True, max_length=20)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('object_repr', models.CharField(blank=True, default='', max_length=500)),
                ('object_key', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('previous_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('old_status', models.CharField(blank=True, default='', max_length=50)),
                ('new_status', models.CharField(blank=True, default='', max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=3)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('tenant', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('session_id', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('reference', models.CharField(blank=True, default='', max_length=200)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'core_audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='core_audit__timesta_9f170b_idx'), models.Index(fields=['user', '-timestamp'], name='core_audit__user_id_1daed5_idx'), models.Index(fields=['content_type', 'object_id', '-timestamp'], name='core_audit__content_5f78f5_idx'), models.Index(fields=['tenant', '-timestamp'], name='core_audit__tenant_d0df50_idx'), models.Index(fields=['action', '-timestamp'], name='core_audit__action_a453b1_idx'), models.Index(fields=['object_key', '-timestamp'], name='core_audit__object__e45fff_idx')],
            },
        ),
    ]
