# Generated by Django 4.2.28 on 2026-03-26 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auth_security_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='loginattempt',
            new_name='core_logina_usernam_de1067_idx',
            old_name='core_logina_usernam_idx',
        ),
        migrations.RenameIndex(
            model_name='loginattempt',
            new_name='core_logina_ip_addr_230faa_idx',
            old_name='core_logina_ip_addr_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordhistory',
            new_name='core_passwo_user_id_c19029_idx',
            old_name='core_passwo_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='usersession',
            new_name='core_userse_user_id_3fb840_idx',
            old_name='core_userses_user_id_idx',
        ),
    ]
