# Generated by Django 4.2.28 on 2026-04-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tenantsetupprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='module',
            field=models.CharField(choices=[('accounting', 'General Ledger & Accounting'), ('budget', 'Budget & Appropriation'), ('treasury', 'Treasury & TSA'), ('procurement', 'Procurement & Due Process'), ('inventory', 'Stores & Inventory'), ('hrm', 'Human Resources & Payroll'), ('revenue', 'Revenue Collection (IGR)'), ('assets', 'Fixed Asset Management'), ('workflow', 'Workflow & Approvals'), ('reporting', 'Financial Reporting'), ('audit', 'Internal Audit & Compliance'), ('admin', 'System Administration')], max_length=20),
        ),
    ]
