# Generated by Django 4.2.28 on 2026-04-10 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0058_administrativesegment_legacy_mda_and_more'),
        ('core', '0006_alter_role_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('short_name', models.CharField(blank=True, default='', max_length=50)),
                ('org_role', models.CharField(choices=[('MDA', 'Standard MDA'), ('BUDGET_AUTHORITY', 'Budget Authority (Min. of Budget)'), ('FINANCE_AUTHORITY', 'Finance Authority (AG Office)'), ('AUDIT_AUTHORITY', 'Audit Authority (Auditor General)')], default='MDA', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('description', models.TextField(blank=True, default='')),
                # S5-01 — db_constraint=False on both cross-schema FKs.
                # ``core`` lives in SHARED_APPS so this migration runs against
                # the ``public`` schema, but ``accounting.administrativesegment``
                # and ``accounting.mda`` live only in tenant schemas. A physical
                # FK REFERENCES cannot exist across schemas in Postgres, so we
                # keep these as ORM-level logical FKs (queryset joins +
                # ``_id`` columns still work) and skip the impossible physical
                # constraint. Mirrored at ``core.models.Organization``.
                ('administrative_segment', models.OneToOneField(blank=True, db_constraint=False, help_text='NCoA Administrative Segment this org represents', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization', to='accounting.administrativesegment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('legacy_mda', models.OneToOneField(blank=True, db_constraint=False, help_text='Bridge to legacy MDA dimension model', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization', to='accounting.mda')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization (MDA)',
                'verbose_name_plural': 'Organizations (MDAs)',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='UserOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_org_role', models.CharField(choices=[('admin', 'Organization Admin'), ('manager', 'Manager'), ('officer', 'Officer'), ('viewer', 'Read-Only Viewer')], default='officer', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Auto-select this org on login')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='core.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['organization__code'],
                'unique_together': {('user', 'organization')},
            },
        ),
    ]
