# Generated by Django 4.2.28 on 2026-04-11 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_organization_userorganization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('BUDGET', 'Budget & Appropriation'), ('WARRANT', 'Warrant / AIE'), ('PAYMENT', 'Payment Voucher'), ('PROCUREMENT', 'Procurement'), ('REVENUE', 'Revenue'), ('PERIOD', 'Period / Fiscal Year'), ('APPROVAL', 'Approval Required'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, default='', max_length=300)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('related_model', models.CharField(blank=True, default='', max_length=50)),
                ('related_id', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='core_notifi_user_id_f286cd_idx')],
            },
        ),
    ]
