# Generated by Django 4.2.28 on 2026-04-17 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0071_accountingsettings_accumulated_fund_account_code'),
        ('core', '0008_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='administrative_segment',
            field=models.OneToOneField(blank=True, db_constraint=False, help_text='NCoA Administrative Segment this org represents', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization', to='accounting.administrativesegment'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='legacy_mda',
            field=models.OneToOneField(blank=True, db_constraint=False, help_text='Bridge to legacy MDA dimension model', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization', to='accounting.mda'),
        ),
    ]
