# Generated by Django 4.2.28 on 2026-05-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_roleassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='mfa_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
