# Generated by Django 5.2.14 on 2026-05-08 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_usersession_mfa_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Long-form explanation shown in the role editor.'),
        ),
        migrations.AddField(
            model_name='role',
            name='is_system',
            field=models.BooleanField(default=False, help_text='System-seeded role (e.g. accountant_general, budget_officer). System roles can be edited by admins but not deleted — tenants always have a path back to a known-good baseline.'),
        ),
        migrations.CreateModel(
            name='PermissionDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=120, unique=True)),
                ('module', models.CharField(choices=[('accounting', 'General Ledger & Accounting'), ('budget', 'Budget & Appropriation'), ('treasury', 'Treasury & TSA'), ('procurement', 'Procurement & Due Process'), ('contracts', 'Contracts & IPC'), ('inventory', 'Stores & Inventory'), ('hrm', 'Human Resources & Payroll'), ('revenue', 'Revenue Collection (IGR)'), ('assets', 'Fixed Asset Management'), ('workflow', 'Workflow & Approvals'), ('reporting', 'Financial Reporting'), ('audit', 'Internal Audit & Compliance'), ('admin', 'System Administration'), ('rbac', 'Roles & Permissions')], db_index=True, help_text='Module the permission belongs to.', max_length=30)),
                ('resource', models.CharField(db_index=True, help_text='Resource within the module — e.g. "po", "ipc", "warrant".', max_length=60)),
                ('action', models.CharField(db_index=True, help_text='Verb — e.g. "view", "create", "submit", "approve", "post", "release", "reverse", "pay", "configure".', max_length=40)),
                ('label', models.CharField(help_text='Human-readable label shown in the role editor.', max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Long-form explanation displayed on hover / in details panel.')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', help_text='Surfaces in the UI so admins see which permissions carry audit weight (high/critical permissions get a coloured badge).', max_length=10)),
                ('sort_order', models.PositiveIntegerField(default=100, help_text='Display ordering inside the (module, resource) group.')),
                ('is_system', models.BooleanField(default=True, help_text='System permissions are seeded and cannot be deleted by tenants. Custom (is_system=False) permissions can be created by tenant admins for tenant-specific resources.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['module', 'resource', 'sort_order', 'action'],
                'indexes': [models.Index(fields=['module', 'resource'], name='core_permis_module_534b24_idx')],
                'constraints': [models.UniqueConstraint(fields=('module', 'resource', 'action'), name='uniq_perm_module_resource_action')],
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Granular permissions held by this role. The legacy ``can_view`` / ``can_add`` / ``can_change`` / ``can_delete`` / ``can_approve`` / ``can_post`` flags are kept for backward compatibility with existing permission-string consumers, but new code reads from this M2M.', related_name='roles', to='core.permissiondefinition'),
        ),
        migrations.CreateModel(
            name='SoDRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=120, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('scope', models.CharField(choices=[('hold', 'Cannot Hold Both Permissions'), ('same_document', 'Cannot Exercise Both on Same Document')], default='same_document', max_length=20)),
                ('severity', models.CharField(choices=[('block', 'Block (hard reject)'), ('warn', 'Warn (log, allow, banner)')], default='block', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_system', models.BooleanField(default=False, help_text='System rules are seeded by ``seed_permission_catalog`` and cannot be deleted (only deactivated). Tenant admins can add their own non-system rules freely.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sod_rules_as_a', to='core.permissiondefinition')),
                ('permission_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sod_rules_as_b', to='core.permissiondefinition')),
            ],
            options={
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(fields=('permission_a', 'permission_b', 'scope'), name='uniq_sod_rule_pair_scope')],
            },
        ),
    ]
