import type { ModuleConfig } from '../_base/types';

export const moduleConfig: ModuleConfig = {
  key: 'integrations',
  label: 'Integration Gateway',
  icon: 'ðŸ”Œ',
  description: 'Integration endpoints, runs and message logs for external connectors.',
  basePath: '/integrations',
  entities: [
    {
      key: 'integrationEndpoint',
      plural: 'endpoints',
      label: 'Integration Endpoints',
      searchField: 'name',
      idField: 'id',
      columns: [
        { name: 'name', label: 'Name', type: 'text', required: true },
        {
          name: 'connector_type',
          label: 'Connector Type',
          type: 'select',
          options: {
            remita: 'Remita',
            nibss: 'NIBSS / Bank',
            gifmis: 'GIFMIS',
            ippis: 'IPPIS',
            bvn_tin: 'BVN / TIN Verification',
          },
        },
        {
          name: 'environment',
          label: 'Environment',
          type: 'select',
          options: { sandbox: 'Sandbox', production: 'Production' },
        },
        { name: 'base_url', label: 'Base URL', type: 'text' },
        { name: 'is_enabled', label: 'Enabled', type: 'boolean' },
      ],
      fields: [
        { name: 'name', label: 'Name', type: 'text', required: true, placeholder: 'e.g. Remita Production' },
        {
          name: 'connector_type',
          label: 'Connector Type',
          type: 'select',
          required: true,
          options: {
            remita: 'Remita',
            nibss: 'NIBSS / Bank',
            gifmis: 'GIFMIS',
            ippis: 'IPPIS',
            bvn_tin: 'BVN / TIN Verification',
          },
        },
        {
          name: 'environment',
          label: 'Environment',
          type: 'select',
          required: true,
          options: { sandbox: 'Sandbox', production: 'Production' },
        },
        { name: 'base_url', label: 'Base URL', type: 'text', placeholder: 'https://api.example.com' },
        { name: 'credentials_ref', label: 'Credentials Reference', type: 'text' },
        { name: 'is_enabled', label: 'Enabled', type: 'boolean' },
        { name: 'config', label: 'Config', type: 'longtext' },
        { name: 'timeout_seconds', label: 'Timeout (seconds)', type: 'integer', numeric: true },
        { name: 'retry_limit', label: 'Retry Limit', type: 'integer', numeric: true },
        { name: 'last_success_at', label: 'Last Success At', type: 'datetime', hideInForm: true, readOnly: true, secondary: true },
        { name: 'last_error', label: 'Last Error', type: 'longtext', hideInForm: true, readOnly: true, secondary: true },
        { name: 'sources', label: 'Source Modules', type: 'object', hideInForm: true, readOnly: true },
        { name: 'created_at', label: 'Created At', type: 'datetime', hideInForm: true, readOnly: true, secondary: true },
        { name: 'updated_at', label: 'Updated At', type: 'datetime', hideInForm: true, readOnly: true, secondary: true },
      ],
    },
    {
      key: 'integrationRun',
      plural: 'runs',
      label: 'Integration Runs',
      searchField: 'trigger',
      idField: 'id',
      statusField: 'status',
      columns: [
        {
          name: 'endpoint',
          label: 'Endpoint',
          type: 'integer',
          required: true,
          reference: { module: 'integrations', entity: 'integrationEndpoint' },
        },
        { name: 'status', label: 'Status', type: 'select', options: { pending: 'Pending', running: 'Running', success: 'Success', partial: 'Partial', failed: 'Failed' } },
        { name: 'started_at', label: 'Started At', type: 'datetime' },
        { name: 'messages_sent', label: 'Sent', type: 'integer', numeric: true },
        { name: 'messages_failed', label: 'Failed', type: 'integer', numeric: true },
      ],
      fields: [
        {
          name: 'endpoint',
          label: 'Endpoint',
          type: 'integer',
          required: true,
          reference: { module: 'integrations', entity: 'integrationEndpoint' },
        },
        { name: 'endpoint_name', label: 'Endpoint Name', type: 'text', hideInForm: true, readOnly: true },
        { name: 'started_at', label: 'Started At', type: 'datetime', hideInForm: true, readOnly: true },
        { name: 'finished_at', label: 'Finished At', type: 'datetime', hideInForm: true, readOnly: true },
        {
          name: 'status',
          label: 'Status',
          type: 'select',
          options: { pending: 'Pending', running: 'Running', success: 'Success', partial: 'Partial', failed: 'Failed' },
        },
        { name: 'messages_sent', label: 'Messages Sent', type: 'integer', numeric: true },
        { name: 'messages_received', label: 'Messages Received', type: 'integer', numeric: true },
        { name: 'messages_failed', label: 'Messages Failed', type: 'integer', numeric: true },
        { name: 'payload_hash', label: 'Payload Hash', type: 'text', secondary: true },
        { name: 'trigger', label: 'Trigger', type: 'text' },
        { name: 'operator_note', label: 'Operator Note', type: 'longtext' },
      ],
    },
    {
      key: 'integrationMessage',
      plural: 'messages',
      label: 'Integration Messages',
      searchField: 'message_key',
      idField: 'id',
      statusField: 'status',
      columns: [
        {
          name: 'run',
          label: 'Run',
          type: 'integer',
          required: true,
          reference: { module: 'integrations', entity: 'integrationRun' },
        },
        { name: 'message_key', label: 'Message Key', type: 'text' },
        {
          name: 'direction',
          label: 'Direction',
          type: 'select',
          options: { out: 'Outbound', in: 'Inbound' },
        },
        { name: 'status', label: 'Status', type: 'select', options: { sent: 'Sent', received: 'Received', replayed: 'Replayed (idempotent)', failed: 'Failed', skipped: 'Skipped (duplicate message_key)' } },
        { name: 'sent_at', label: 'Sent At', type: 'datetime' },
      ],
      fields: [
        {
          name: 'run',
          label: 'Run',
          type: 'integer',
          required: true,
          reference: { module: 'integrations', entity: 'integrationRun' },
        },
        {
          name: 'direction',
          label: 'Direction',
          type: 'select',
          required: true,
          options: { out: 'Outbound', in: 'Inbound' },
        },
        { name: 'message_key', label: 'Message Key', type: 'text', placeholder: 'Idempotency key' },
        { name: 'payload_hash', label: 'Payload Hash', type: 'text', secondary: true },
        {
          name: 'status',
          label: 'Status',
          type: 'select',
          options: { sent: 'Sent', received: 'Received', replayed: 'Replayed (idempotent)', failed: 'Failed', skipped: 'Skipped (duplicate message_key)' },
        },
        { name: 'retry_count', label: 'Retry Count', type: 'integer', numeric: true },
        { name: 'failure_reason', label: 'Failure Reason', type: 'longtext', secondary: true },
        { name: 'source_model', label: 'Source Model', type: 'text', secondary: true },
        { name: 'source_id', label: 'Source ID', type: 'integer', numeric: true },
        { name: 'sent_at', label: 'Sent At', type: 'datetime', hideInForm: true, readOnly: true },
      ],
    },
  ],
};

