import type { ModuleConfig } from '../_base/types';

export const moduleConfig: ModuleConfig = {
  key: 'budget_prep',
  label: 'Budget Preparation (MTEF/MTSS)',
  icon: '🏛️',
  description: 'Call circulars, MTEF projections, MDA ceilings, budget submissions and review comments.',
  basePath: '/budget-prep',
  entities: [
    {
      key: 'callCircular',
      plural: 'call-circulars',
      label: 'Call Circulars',
      searchField: 'fiscal_year',
      idField: 'id',
      statusField: 'is_active',
      columns: [
        { name: 'fiscal_year', label: 'Fiscal Year', type: 'integer', numeric: true },
        { name: 'issue_date', label: 'Issue Date', type: 'date' },
        { name: 'submission_deadline', label: 'Submission Deadline', type: 'date' },
        { name: 'is_active', label: 'Active', type: 'boolean' },
        { name: 'document', label: 'Document', type: 'text', secondary: true },
      ],
      fields: [
        { name: 'fiscal_year', label: 'Fiscal Year', type: 'integer', numeric: true, required: true },
        { name: 'issue_date', label: 'Issue Date', type: 'date', required: true },
        { name: 'submission_deadline', label: 'Submission Deadline', type: 'date' },
        { name: 'guidelines', label: 'Guidelines', type: 'longtext' },
        { name: 'is_active', label: 'Active', type: 'boolean' },
        { name: 'document', label: 'Document', type: 'text' },
      ],
    },
    {
      key: 'mtefProjection',
      plural: 'mtef-projections',
      label: 'MTEF Projections',
      searchField: 'fiscal_year',
      idField: 'id',
      columns: [
        { name: 'fiscal_year', label: 'Fiscal Year', type: 'integer', numeric: true },
        { name: 'inflation_assumption', label: 'Inflation', type: 'decimal', numeric: true },
        { name: 'aggregate_revenue', label: 'Aggregate Revenue', type: 'decimal', numeric: true },
        { name: 'aggregate_expenditure', label: 'Aggregate Expenditure', type: 'decimal', numeric: true },
        { name: 'fiscal_balance', label: 'Fiscal Balance', type: 'decimal', numeric: true },
      ],
      fields: [
        { name: 'fiscal_year', label: 'Fiscal Year', type: 'integer', numeric: true, required: true },
        { name: 'inflation_assumption', label: 'Inflation Assumption', type: 'decimal', numeric: true },
        { name: 'exchange_rate_assumption', label: 'Exchange Rate Assumption', type: 'decimal', numeric: true },
        { name: 'oil_price_assumption', label: 'Oil Price Assumption', type: 'decimal', numeric: true },
        { name: 'aggregate_revenue', label: 'Aggregate Revenue', type: 'decimal', numeric: true },
        { name: 'aggregate_expenditure', label: 'Aggregate Expenditure', type: 'decimal', numeric: true },
        { name: 'fiscal_balance', label: 'Fiscal Balance', type: 'decimal', numeric: true },
      ],
    },
    {
      key: 'mdaCeiling',
      plural: 'mda-ceilings',
      label: 'MDA Ceilings',
      searchField: 'mda_name',
      idField: 'id',
      columns: [
        { name: 'mda_name', label: 'MDA', type: 'text' },
        { name: 'fiscal_year', label: 'Fiscal Year', type: 'integer', numeric: true },
        { name: 'personnel_ceiling', label: 'Personnel', type: 'decimal', numeric: true },
        { name: 'overhead_ceiling', label: 'Overhead', type: 'decimal', numeric: true },
        { name: 'total_ceiling', label: 'Total Ceiling', type: 'decimal', numeric: true },
      ],
      fields: [
        { name: 'fiscal_year', label: 'Fiscal Year', type: 'integer', numeric: true, required: true },
        { name: 'mda_name', label: 'MDA Name', type: 'text', required: true },
        { name: 'personnel_ceiling', label: 'Personnel Ceiling', type: 'decimal', numeric: true },
        { name: 'overhead_ceiling', label: 'Overhead Ceiling', type: 'decimal', numeric: true },
        { name: 'capital_ceiling', label: 'Capital Ceiling', type: 'decimal', numeric: true },
        { name: 'total_ceiling', label: 'Total Ceiling', type: 'decimal', numeric: true, readOnly: true, hideInForm: true },
      ],
    },
    {
      key: 'budgetSubmission',
      plural: 'submissions',
      label: 'Budget Submissions',
      searchField: 'mda_name',
      idField: 'id',
      statusField: 'stage',
      columns: [
        { name: 'mda_name', label: 'MDA', type: 'text' },
        { name: 'fiscal_year', label: 'Fiscal Year', type: 'integer', numeric: true },
        { name: 'stage', label: 'Stage', type: 'select', options: { draft: 'Draft', submitted: 'Submitted to Budget Office', in_review: 'Under Review', revised: 'Revision Requested', incorporated: 'Incorporated / Adopted', rejected: 'Rejected' } },
        { name: 'total_capital', label: 'Total Capital', type: 'decimal', numeric: true },
        { name: 'lines', label: 'Lines', type: 'object', readOnly: true, secondary: true },
      ],
      fields: [
        { name: 'fiscal_year', label: 'Fiscal Year', type: 'integer', numeric: true, required: true },
        { name: 'mda_name', label: 'MDA Name', type: 'text', required: true },
        { name: 'circular', label: 'Call Circular', type: 'integer', reference: { module: 'budget_prep', entity: 'callCircular' } },
        { name: 'stage', label: 'Stage', type: 'select', options: { draft: 'Draft', submitted: 'Submitted to Budget Office', in_review: 'Under Review', revised: 'Revision Requested', incorporated: 'Incorporated / Adopted', rejected: 'Rejected' } },
        { name: 'submitted_at', label: 'Submitted At', type: 'datetime', readOnly: true, hideInForm: true },
        { name: 'total_personnel', label: 'Total Personnel', type: 'decimal', numeric: true, secondary: true },
        { name: 'total_overhead', label: 'Total Overhead', type: 'decimal', numeric: true, secondary: true },
        { name: 'total_capital', label: 'Total Capital', type: 'decimal', numeric: true },
        { name: 'notes', label: 'Notes', type: 'longtext' },
        { name: 'lines', label: 'Lines', type: 'object', readOnly: true, hideInForm: true },
        { name: 'created_at', label: 'Created At', type: 'datetime', readOnly: true, hideInForm: true, secondary: true },
        { name: 'updated_at', label: 'Updated At', type: 'datetime', readOnly: true, hideInForm: true, secondary: true },
      ],
    },
    {
      key: 'submissionLine',
      plural: 'submission-lines',
      label: 'Submission Lines',
      searchField: 'description',
      idField: 'id',
      columns: [
        { name: 'submission', label: 'Submission', type: 'integer', reference: { module: 'budget_prep', entity: 'budgetSubmission' } },
        { name: 'line_type', label: 'Line Type', type: 'select', options: { personnel: 'Personnel', overhead: 'Overhead', capital: 'Capital' } },
        { name: 'description', label: 'Description', type: 'text' },
        { name: 'proposed_amount', label: 'Proposed Amount', type: 'decimal', numeric: true },
        { name: 'ceiling_reference', label: 'Ceiling', type: 'integer', reference: { module: 'budget_prep', entity: 'mdaCeiling' } },
      ],
      fields: [
        { name: 'submission', label: 'Submission', type: 'integer', required: true, reference: { module: 'budget_prep', entity: 'budgetSubmission' } },
        { name: 'line_type', label: 'Line Type', type: 'select', required: true, options: { personnel: 'Personnel', overhead: 'Overhead', capital: 'Capital' } },
        { name: 'administrative', label: 'Administrative Segment', type: 'integer', reference: { module: 'accounting', entity: 'administrativeSegment' } },
        { name: 'economic', label: 'Economic Segment', type: 'integer', reference: { module: 'accounting', entity: 'economicSegment' } },
        { name: 'functional', label: 'Functional Segment', type: 'integer', reference: { module: 'accounting', entity: 'functionalSegment' } },
        { name: 'description', label: 'Description', type: 'text' },
        { name: 'proposed_amount', label: 'Proposed Amount', type: 'decimal', numeric: true },
        { name: 'ceiling_reference', label: 'Ceiling Reference', type: 'integer', reference: { module: 'budget_prep', entity: 'mdaCeiling' } },
      ],
    },
    {
      key: 'reviewComment',
      plural: 'review-comments',
      label: 'Review Comments',
      searchField: 'comment',
      idField: 'id',
      statusField: 'action_required',
      columns: [
        { name: 'submission', label: 'Submission', type: 'integer', reference: { module: 'budget_prep', entity: 'budgetSubmission' } },
        { name: 'comment', label: 'Comment', type: 'longtext' },
        { name: 'action_required', label: 'Action Required', type: 'boolean' },
        { name: 'commented_by', label: 'Commented By', type: 'text' },
        { name: 'commented_at', label: 'Commented At', type: 'datetime' },
      ],
      fields: [
        { name: 'submission', label: 'Submission', type: 'integer', required: true, reference: { module: 'budget_prep', entity: 'budgetSubmission' } },
        { name: 'comment', label: 'Comment', type: 'longtext' },
        { name: 'action_required', label: 'Action Required', type: 'boolean' },
        { name: 'commented_by', label: 'Commented By', type: 'text' },
        { name: 'commented_at', label: 'Commented At', type: 'datetime', readOnly: true, hideInForm: true },
      ],
    },
  ],
};
