# Generated by Django 4.2.28 on 2026-04-21 19:41

import contracts.models.audit
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procurement', '0045_invoicematching_wht_exempt_and_more'),
        ('accounting', '0085_paymentvoucherdeduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_number', models.CharField(db_index=True, help_text='Auto-generated on activation, e.g. DSG/WORKS/2026/001', max_length=30, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('reference', models.CharField(blank=True, default='', help_text='Internal reference / file number', max_length=100)),
                ('contract_type', models.CharField(choices=[('WORKS', 'Works (Civil / Construction)'), ('GOODS', 'Goods / Supply'), ('CONSULTANCY', 'Consultancy Services'), ('NON_CONSULTANCY', 'Non-Consultancy Services')], max_length=20)),
                ('procurement_method', models.CharField(choices=[('OPEN_TENDER', 'Open Competitive Tender'), ('RESTRICTED', 'Restricted Tender'), ('SELECTIVE', 'Selective Tender'), ('DIRECT_LABOUR', 'Direct Labour'), ('DIRECT_AWARD', 'Direct Award (Emergency)')], default='OPEN_TENDER', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVATED', 'Activated'), ('IN_PROGRESS', 'In Progress'), ('PRACTICAL_COMPLETION', 'Practical Completion'), ('DEFECTS_LIABILITY', 'Defects Liability Period'), ('FINAL_COMPLETION', 'Final Completion'), ('CLOSED', 'Closed')], db_index=True, default='DRAFT', max_length=30)),
                ('original_sum', models.DecimalField(decimal_places=2, help_text='Original contract sum in NGN', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('mobilization_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Mobilization advance as % of original sum (0–30%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('30'))])),
                ('retention_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Retention deduction as % of each certified payment (0–20%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('20'))])),
                ('bpp_no_objection_ref', models.CharField(blank=True, default='', help_text='BPP Certificate of No Objection reference number', max_length=100)),
                ('due_process_certificate', models.CharField(blank=True, default='', help_text='State Due Process Bureau certificate number', max_length=100)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('commencement_date', models.DateField(blank=True, null=True)),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('defects_liability_period_days', models.PositiveIntegerField(default=365, help_text='Duration of defects liability period in days after practical completion')),
                ('notes', models.TextField(blank=True, default='')),
                ('appropriation', models.ForeignKey(blank=True, help_text='Budget appropriation line; validated on each IPC payment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='accounting.budgetencumbrance')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(help_text='Primary fiscal year — used for IPSAS accrual boundary', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='accounting.fiscalyear')),
                ('mda', models.ForeignKey(help_text='Implementing / procuring MDA', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='accounting.administrativesegment')),
                ('ncoa_code', models.ForeignKey(help_text='Expenditure charge account (NCoA 52-digit code)', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='accounting.ncoacode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(help_text='Contractor / supplier', on_delete=django.db.models.deletion.PROTECT, related_name='gov_contracts', to='procurement.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractBalance',
            fields=[
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='balance', serialize=False, to='contracts.contract')),
                ('contract_ceiling', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Snapshot of ceiling at last update (original + approved variations)', max_digits=20)),
                ('cumulative_gross_certified', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total gross value certified across all approved IPCs', max_digits=20)),
                ('pending_voucher_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='IPC approved but PV not yet raised (committed, not yet paid)', max_digits=20)),
                ('cumulative_gross_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total net payments actually disbursed to contractor', max_digits=20)),
                ('mobilization_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('mobilization_recovered', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('retention_held', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('retention_released', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('version', models.BigIntegerField(default=0, help_text='Incremented on every write; DB trigger rejects non-increasing version')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RetentionRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('release_type', models.CharField(choices=[('PRACTICAL_COMPLETION', 'Practical Completion (50% of retention)'), ('FINAL_COMPLETION', 'Final Completion (remaining 50%)')], max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to be released (computed by RetentionService)', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_retention_releases', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_releases', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('payment_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retention_releases', to='accounting.paymentvouchergov')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['contract', 'release_type'],
            },
        ),
        migrations.CreateModel(
            name='MobilizationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Mobilization advance disbursed (mobilization_rate × original_sum)', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Disbursement'), ('PAID', 'Paid'), ('PARTIALLY_RECOVERED', 'Partially Recovered'), ('FULLY_RECOVERED', 'Fully Recovered')], default='PENDING', max_length=25)),
                ('notes', models.TextField(blank=True, default='')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobilization_payment', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('payment_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mobilization_payments', to='accounting.paymentvouchergov')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MilestoneSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milestone_number', models.PositiveSmallIntegerField(help_text='Ordering number within the contract')),
                ('description', models.CharField(max_length=300)),
                ('scheduled_value', models.DecimalField(decimal_places=2, help_text='Scheduled payment value for this milestone', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('percentage_weight', models.DecimalField(decimal_places=3, help_text='% of contract sum attributable to this milestone', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('target_date', models.DateField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('WAIVED', 'Waived')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['contract', 'milestone_number'],
            },
        ),
        migrations.CreateModel(
            name='MeasurementBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mb_number', models.CharField(db_index=True, help_text='Auto-generated, e.g. MB/DSG/WORKS/2026/001/001', max_length=30)),
                ('measurement_date', models.DateField()),
                ('items', models.JSONField(default=list, help_text='List of measurement line items. Each item: {description, unit, quantity, rate, amount}. All numeric values stored as strings to preserve precision.')),
                ('total_measured_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all item amounts — recomputed on save', max_digits=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_measurement_books', to=settings.AUTH_USER_MODEL)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_measurement_books', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_books', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('measured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measured_measurement_books', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['contract', 'measurement_date'],
            },
        ),
        migrations.CreateModel(
            name='InterimPaymentCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ipc_number', models.CharField(db_index=True, help_text='Auto-generated, e.g. IPC/DSG/WORKS/2026/001/003', max_length=30)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('cumulative_work_done_to_date', models.DecimalField(decimal_places=2, help_text="Engineer's cumulative assessment of work completed to date", max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('previous_certified', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cumulative gross certified at previous IPC (auto-filled on submit)', max_digits=20)),
                ('this_certificate_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gross value for this period = cumulative_work_done - previous_certified', max_digits=20)),
                ('mobilization_recovery_this_cert', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Mobilization advance recovery deduction for this IPC', max_digits=20)),
                ('retention_deduction_this_cert', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Retention deduction for this IPC', max_digits=20)),
                ('ld_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Liquidated Damages deduction', max_digits=20)),
                ('variation_claims', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Variation amount included in this certificate', max_digits=20)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT (7.5 %) applied at payment posting', max_digits=20)),
                ('wht_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='WHT applied at payment posting (rate varies by contract type)', max_digits=20)),
                ('net_payable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net amount payable to contractor (computed, never user-editable)', max_digits=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Certification'), ('CERTIFIER_REVIEWED', 'Certifier Reviewed'), ('APPROVED', 'Approved (Payment Due)'), ('VOUCHER_RAISED', 'Payment Voucher Raised'), ('PAID', 'Paid'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=25)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('integrity_hash', models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 of (contract_id, period_from, period_to, cumulative_work_done_to_date). Prevents duplicate IPC for same period+amount.', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('accrual_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ipc_accruals', to='accounting.journalheader')),
                ('certifying_engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certified_ipcs', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipcs', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('measurement_book', models.ForeignKey(blank=True, help_text='Source measurement book (three-way match control)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ipcs', to='contracts.measurementbook')),
                ('payment_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ipcs', to='accounting.paymentvouchergov')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['contract', 'period_from'],
            },
        ),
        migrations.CreateModel(
            name='ContractVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variation_number', models.PositiveSmallIntegerField(help_text='Sequential within the contract, auto-assigned by IPCService')),
                ('variation_type', models.CharField(choices=[('ADDITION', 'Addition (extra work / scope)'), ('OMISSION', 'Omission (scope reduction)'), ('SUBSTITUTION', 'Substitution (replace item)'), ('EXTENSION_OF_TIME', 'Extension of Time (no cost)')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Review'), ('REVIEWED', 'Technical Review Complete'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=20)),
                ('approval_tier', models.CharField(choices=[('LOCAL', 'Local (MDA level, ≤ 15%)'), ('BOARD', 'Board / Executive Council (15–25%)'), ('BPP_REQUIRED', 'BPP Approval Required (> 25%)')], default='LOCAL', help_text='Computed automatically — do not set manually', max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('justification', models.TextField(help_text='Technical / engineering justification for the variation')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net financial impact (positive=addition, negative=omission, 0=EOT only)', max_digits=20)),
                ('time_extension_days', models.IntegerField(default=0, help_text='Additional calendar days granted (0 if no time extension)')),
                ('bpp_approval_ref', models.CharField(blank=True, default='', help_text='BPP No-Objection certificate reference for BPP_REQUIRED tier', max_length=100)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_variations', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['contract', 'variation_number'],
            },
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('CONTRACT', 'Signed Contract'), ('VARIATION_ORDER', 'Variation Order'), ('IPC_DOCUMENT', 'Interim Payment Certificate'), ('MEASUREMENT_BOOK', 'Measurement Book'), ('COMPLETION_CERT', 'Completion Certificate'), ('PERFORMANCE_BOND', 'Performance Bond / Guarantee'), ('INSURANCE', 'Insurance Certificate'), ('BPP_CERTIFICATE', 'BPP No-Objection Certificate'), ('OTHER', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(help_text='Uploaded document (PDF, DOCX, XLSX, image)', upload_to=contracts.models.audit.contract_document_path)),
                ('description', models.TextField(blank=True, default='')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_contract_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('IPC', 'Interim Payment Certificate'), ('VARIATION', 'Contract Variation'), ('COMPLETION', 'Completion Certificate'), ('MOB', 'Mobilization Payment'), ('RETENTION', 'Retention Release'), ('CONTRACT', 'Contract')], max_length=20)),
                ('object_id', models.BigIntegerField(help_text='PK of the related IPC / Variation / Completion cert / etc.')),
                ('step_number', models.PositiveSmallIntegerField(help_text="Sequential step number within this object's workflow")),
                ('role_required', models.CharField(help_text="Permission / role required to take this action, e.g. 'contracts.approve_ipc'", max_length=100)),
                ('action', models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('REQUEST_INFO', 'Request Additional Information'), ('ESCALATE', 'Escalate to Higher Authority'), ('CERTIFY', 'Certify (Engineer)'), ('VERIFY', 'Verify (Quantity Surveyor)')], max_length=20)),
                ('action_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taken_approval_steps', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_approval_steps', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='contracts.contract')),
            ],
            options={
                'ordering': ['contract', 'action_at'],
            },
        ),
        migrations.CreateModel(
            name='CompletionCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_type', models.CharField(choices=[('PRACTICAL', 'Practical Completion Certificate'), ('DEFECTS_LIABILITY', 'Defects Liability Certificate'), ('FINAL', 'Final Completion Certificate')], max_length=20)),
                ('issued_date', models.DateField()),
                ('effective_date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('certified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_completion_certificates', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_certificates', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['contract', 'certificate_type'],
            },
        ),
        migrations.AddConstraint(
            model_name='retentionrelease',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='contracts_retention_release_amount_non_negative'),
        ),
        migrations.AlterUniqueTogether(
            name='retentionrelease',
            unique_together={('contract', 'release_type')},
        ),
        migrations.AddConstraint(
            model_name='mobilizationpayment',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='contracts_mob_payment_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='milestoneschedule',
            constraint=models.CheckConstraint(check=models.Q(('scheduled_value__gt', 0)), name='contracts_milestone_value_positive'),
        ),
        migrations.AddConstraint(
            model_name='milestoneschedule',
            constraint=models.CheckConstraint(check=models.Q(('percentage_weight__gte', 0), ('percentage_weight__lte', 100)), name='contracts_milestone_weight_0_to_100'),
        ),
        migrations.AlterUniqueTogether(
            name='milestoneschedule',
            unique_together={('contract', 'milestone_number')},
        ),
        migrations.AlterUniqueTogether(
            name='measurementbook',
            unique_together={('contract', 'mb_number')},
        ),
        migrations.AddIndex(
            model_name='interimpaymentcertificate',
            index=models.Index(fields=['status', 'contract'], name='contracts_i_status_cfdb47_idx'),
        ),
        migrations.AddIndex(
            model_name='interimpaymentcertificate',
            index=models.Index(fields=['integrity_hash'], name='contracts_i_integri_beb0c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='interimpaymentcertificate',
            constraint=models.CheckConstraint(check=models.Q(('cumulative_work_done_to_date__gte', 0)), name='contracts_ipc_cumulative_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='interimpaymentcertificate',
            constraint=models.CheckConstraint(check=models.Q(('this_certificate_gross__gte', 0)), name='contracts_ipc_certificate_gross_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='interimpaymentcertificate',
            constraint=models.CheckConstraint(check=models.Q(('net_payable__gte', 0)), name='contracts_ipc_net_payable_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='interimpaymentcertificate',
            constraint=models.CheckConstraint(check=models.Q(('mobilization_recovery_this_cert__gte', 0)), name='contracts_ipc_mob_recovery_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='interimpaymentcertificate',
            constraint=models.CheckConstraint(check=models.Q(('retention_deduction_this_cert__gte', 0)), name='contracts_ipc_retention_deduction_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='interimpaymentcertificate',
            constraint=models.CheckConstraint(check=models.Q(('ld_deduction__gte', 0)), name='contracts_ipc_ld_deduction_non_negative'),
        ),
        migrations.AlterUniqueTogether(
            name='interimpaymentcertificate',
            unique_together={('contract', 'ipc_number')},
        ),
        migrations.AddConstraint(
            model_name='contractvariation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('variation_type', 'EXTENSION_OF_TIME'), _negated=True), ('amount', Decimal('0.00')), _connector='OR'), name='contracts_variation_eot_amount_zero'),
        ),
        migrations.AddConstraint(
            model_name='contractvariation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('variation_type', 'OMISSION'), _negated=True), ('amount__lte', Decimal('0.00')), _connector='OR'), name='contracts_variation_omission_non_positive'),
        ),
        migrations.AddConstraint(
            model_name='contractvariation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('variation_type', 'ADDITION'), _negated=True), ('amount__gte', Decimal('0.00')), _connector='OR'), name='contracts_variation_addition_non_negative'),
        ),
        migrations.AlterUniqueTogether(
            name='contractvariation',
            unique_together={('contract', 'variation_number')},
        ),
        migrations.AddConstraint(
            model_name='contractbalance',
            constraint=models.CheckConstraint(check=models.Q(('cumulative_gross_certified__gte', 0)), name='contracts_balance_certified_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='contractbalance',
            constraint=models.CheckConstraint(check=models.Q(('cumulative_gross_paid__gte', 0)), name='contracts_balance_paid_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='contractbalance',
            constraint=models.CheckConstraint(check=models.Q(('cumulative_gross_paid__lte', models.F('cumulative_gross_certified'))), name='contracts_balance_paid_lte_certified'),
        ),
        migrations.AddConstraint(
            model_name='contractbalance',
            constraint=models.CheckConstraint(check=models.Q(('mobilization_recovered__lte', models.F('mobilization_paid'))), name='contracts_balance_mob_recovered_lte_paid'),
        ),
        migrations.AddConstraint(
            model_name='contractbalance',
            constraint=models.CheckConstraint(check=models.Q(('retention_released__lte', models.F('retention_held'))), name='contracts_balance_retention_released_lte_held'),
        ),
        migrations.AddConstraint(
            model_name='contractbalance',
            constraint=models.CheckConstraint(check=models.Q(('contract_ceiling__gt', 0)), name='contracts_balance_ceiling_positive'),
        ),
        migrations.AddIndex(
            model_name='contractapprovalstep',
            index=models.Index(fields=['object_type', 'object_id'], name='contracts_c_object__c8bf65_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status', 'mda'], name='contracts_c_status_4443ba_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['fiscal_year', 'status'], name='contracts_c_fiscal__000209_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['vendor', 'status'], name='contracts_c_vendor__067611_idx'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(check=models.Q(('original_sum__gt', 0)), name='contracts_contract_original_sum_positive'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(check=models.Q(('mobilization_rate__gte', 0), ('mobilization_rate__lte', 30)), name='contracts_contract_mobilization_rate_0_to_30'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(check=models.Q(('retention_rate__gte', 0), ('retention_rate__lte', 20)), name='contracts_contract_retention_rate_0_to_20'),
        ),
        migrations.AlterUniqueTogether(
            name='completioncertificate',
            unique_together={('contract', 'certificate_type')},
        ),
    ]
