# Generated by Django 4.2.28 on 2026-04-23 19:32

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0045_invoicematching_wht_exempt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0002_contract_balance_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorStatusVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField(help_text='Calendar year in which the fee was deducted.')),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('40000.00'), help_text='Fee amount at the time of recording (historical snapshot).', max_digits=20)),
                ('recorded_on', models.DateField(help_text='Date the deduction was applied on a payment voucher.')),
                ('payment_voucher_id', models.BigIntegerField(blank=True, help_text="FK-shaped reference to accounting.PaymentVoucherGov. Kept as a loose BigInteger to avoid a cross-app migration cycle; the accounting app's PV is in the same tenant schema.", null=True)),
                ('circular_reference', models.CharField(default='AG/CIR/54/C/Vol.10/1/134', help_text='Source circular reference.', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_verifications', to='procurement.vendor')),
            ],
            options={
                'ordering': ['-year', 'vendor_id'],
                'indexes': [models.Index(fields=['year'], name='contracts_v_year_8ca07b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='vendorstatusverification',
            constraint=models.UniqueConstraint(fields=('vendor', 'year'), name='contracts_vendorsv_unique_per_vendor_year'),
        ),
        migrations.AddConstraint(
            model_name='vendorstatusverification',
            constraint=models.CheckConstraint(check=models.Q(('fee_amount__gte', 0)), name='contracts_vendorsv_fee_non_negative'),
        ),
    ]
