# Generated by Django 4.2.28 on 2026-04-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_ipc_posting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interimpaymentcertificate',
            name='integrity_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 of (contract_id, posting_date, cumulative_work_done_to_date). Prevents duplicate IPC for same posting-date+amount.', max_length=64),
        ),
    ]
