# Generated by Django 4.2.28 on 2026-05-03 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0096_backfill_grir_clearing_account'),
        ('contracts', '0005_alter_interimpaymentcertificate_integrity_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='interimpaymentcertificate',
            name='milestone',
            field=models.OneToOneField(blank=True, help_text='Source milestone for milestone-driven IPCs. Each milestone yields at most one IPC.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ipc', to='contracts.milestoneschedule'),
        ),
        migrations.AddField(
            model_name='interimpaymentcertificate',
            name='tax_code',
            field=models.ForeignKey(blank=True, help_text="VAT / input-tax code applied to this IPC's gross.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipcs', to='accounting.taxcode'),
        ),
        migrations.AddField(
            model_name='interimpaymentcertificate',
            name='wht_exempt',
            field=models.BooleanField(default=False, help_text="Override vendor's WHT default — exempts this IPC from WHT at payment."),
        ),
        migrations.AddField(
            model_name='interimpaymentcertificate',
            name='withholding_tax',
            field=models.ForeignKey(blank=True, help_text='WHT code applied at payment time (Nigerian PFM cash-basis).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipcs', to='accounting.withholdingtax'),
        ),
    ]
