# Generated by Django 4.2.28 on 2026-05-05 06:54

from decimal import Decimal
from django.db import migrations, models


def backfill_last_submitted(apps, schema_editor):
    """For every existing ContractBalance, seed
    ``last_cumulative_submitted`` from the highest
    ``cumulative_work_done_to_date`` of any IPC on that contract.

    Without this backfill the field starts at 0 for existing
    contracts; the first post-migration submission on any contract
    that already has IPCs would fail the monotonicity check.

    Note: the ContractBalance row carries a Postgres BEFORE UPDATE
    trigger (migration 0002) requiring ``version`` to strictly
    increase on every write. We use ``F('version') + 1`` here so
    the trigger accepts the backfill update.
    """
    ContractBalance = apps.get_model('contracts', 'ContractBalance')
    InterimPaymentCertificate = apps.get_model('contracts', 'InterimPaymentCertificate')
    from django.db.models import Max, F
    qs = (
        InterimPaymentCertificate.objects
        .values('contract_id')
        .annotate(top=Max('cumulative_work_done_to_date'))
    )
    for row in qs:
        ContractBalance.objects.filter(pk=row['contract_id']).update(
            last_cumulative_submitted=row['top'] or Decimal('0'),
            version=F('version') + 1,
        )


def noop_reverse(apps, schema_editor):
    """No reverse — backfill data is recoverable from IPC table."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_ipc_milestone_and_tax_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractbalance',
            name='last_cumulative_submitted',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                help_text=(
                    "Highest cumulative_work_done_to_date submitted on any IPC. "
                    "Anchors the monotonicity check — IPC submit refuses values "
                    "<= this. Bumped under SELECT FOR UPDATE so concurrent "
                    "submissions can't double-certify the same work."
                ),
                max_digits=20,
            ),
        ),
        migrations.RunPython(backfill_last_submitted, noop_reverse),
    ]
