# Generated by Django 4.2.28 on 2026-05-05 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0099_add_retention_release_accrual_journal'),
        ('contracts', '0007_contractbalance_last_cumulative_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='retentionrelease',
            name='accrual_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retention_release_accruals', to='accounting.journalheader'),
        ),
    ]
