# Generated by Django 5.2.14 on 2026-05-07
#
# Adds the ContractYearPlan model + a data migration that backfills
# one year-plan row per existing contract. Single-year contracts —
# every Contract that exists at the time of this migration — are
# treated as one-year plans whose ``planned_amount`` equals the
# contract's ``original_sum``. The activation flow continues to behave
# identically for these legacy rows; only contracts created AFTER this
# migration may opt into multi-row year plans.

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_year_plans(apps, schema_editor):
    """Create one ContractYearPlan per existing Contract.

    Uses ``apps.get_model`` so the migration is replayable on any
    historical state. Idempotent — skips contracts that already have
    a year_plan (e.g. on re-run after rollback).

    Sequence is set to 1; planned_amount mirrors original_sum so the
    activation invariant ``sum(year_plans.planned) == original_sum``
    holds for legacy rows without operator action.
    """
    Contract = apps.get_model("contracts", "Contract")
    ContractYearPlan = apps.get_model("contracts", "ContractYearPlan")

    for contract in Contract.objects.all():
        # Skip if a plan already exists (idempotency).
        if ContractYearPlan.objects.filter(contract=contract).exists():
            continue

        # Inherit appropriation from the contract if one is set; otherwise
        # leave null and let the operator assign it later.
        appropriation = getattr(contract, "appropriation", None)

        ContractYearPlan.objects.create(
            contract=contract,
            fiscal_year=contract.fiscal_year,
            appropriation=appropriation,
            planned_amount=contract.original_sum,
            carried_forward_from_prior_year=Decimal("0.00"),
            sequence=1,
        )


def unbackfill_year_plans(apps, schema_editor):
    """Reverse the backfill — only deletes the auto-generated rows.

    Heuristic: a row is "auto-generated" if ``sequence == 1`` AND the
    contract has exactly one year plan. Anything else is operator-
    edited multi-year work that the reverse must not touch.
    """
    ContractYearPlan = apps.get_model("contracts", "ContractYearPlan")

    # Find every contract with exactly one plan, sequence=1.
    from django.db.models import Count
    auto_contract_ids = (
        ContractYearPlan.objects
        .values("contract")
        .annotate(plan_count=Count("id"))
        .filter(plan_count=1)
        .values_list("contract", flat=True)
    )
    ContractYearPlan.objects.filter(
        contract_id__in=list(auto_contract_ids), sequence=1,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0100_treasuryaccount_uniq_main_tsa_per_mda_active"),
        # Depend on the latest stable budget migration that added the
        # appropriation totals + virement support — NOT the auto-detected
        # drift migration which was unrelated to this feature.
        ("budget", "0014_appropriationvirement_and_more"),
        ("contracts", "0008_add_retention_release_accrual_journal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractYearPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "planned_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Planned IPC spend for this fiscal year (NGN, > 0)",
                        max_digits=20,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "carried_forward_from_prior_year",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text=(
                            "Unspent commitment carried over from the prior year's plan "
                            "(when tenant policy is carry-over, not lapse). Disclosed in "
                            "the IPSAS 24 variance narrative as 'prior-year spillover' "
                            "so it doesn't distort current-year variance."
                        ),
                        max_digits=20,
                    ),
                ),
                (
                    "sequence",
                    models.PositiveSmallIntegerField(
                        help_text="1, 2, 3 … chronological order of fiscal years for this contract",
                    ),
                ),
                (
                    "appropriation",
                    models.ForeignKey(
                        blank=True,
                        help_text=(
                            "Budget appropriation that authorises this year's planned spend. "
                            "Required at contract activation for the primary year; subsequent "
                            "years may have it assigned later (typically when that year's "
                            "Appropriation Act is enacted)."
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contract_year_plans",
                        to="budget.appropriation",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="year_plans",
                        to="contracts.contract",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        help_text="Fiscal year this slice covers; gates IPC posting in that year",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contract_year_plans",
                        to="accounting.fiscalyear",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract Year Plan",
                "verbose_name_plural": "Contract Year Plans",
                "ordering": ["contract", "sequence"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("planned_amount__gt", Decimal("0.00"))),
                        name="contract_year_plan_planned_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("sequence__gte", 1)),
                        name="contract_year_plan_sequence_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("carried_forward_from_prior_year__gte", Decimal("0.00"))),
                        name="contract_year_plan_carryforward_non_negative",
                    ),
                ],
                "unique_together": {("contract", "fiscal_year")},
            },
        ),
        # Backfill: every existing Contract gets a single-year plan so
        # legacy single-year flows continue to work unchanged.
        migrations.RunPython(backfill_year_plans, reverse_code=unbackfill_year_plans),
    ]
