"""
Repoint ``Contract.appropriation`` FK from ``accounting.BudgetEncumbrance``
(legacy procurement encumbrance ledger) to ``budget.Appropriation``
(IPSAS appropriation register).

Audit fix #2 — the FK was pointing at the wrong model: the legacy
``BudgetEncumbrance`` is a per-line procurement-side encumbrance row,
not the appropriation register that drives IPSAS execution reports.
The help-text claimed it was "validated on each IPC payment" but no
validation against this FK existed anywhere in the codebase. Production
audit confirmed 0 of 4 contracts across all tenants had it set, so this
migration is a pure schema repoint with no data migration risk.

Multi-year contracts use ``ContractYearPlan.appropriation`` (already
correctly pointing at ``budget.Appropriation``) — that's the canonical
modern path. The repointed ``Contract.appropriation`` exists for legacy
single-year flows where a year_plan would be redundant, and it's now
genuinely validated by ``IPCService._enforce_appropriation_gate``.
"""
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Pin to 0016 (the warrant date-range refactor); the spurious
        # 0017 generated by ``makemigrations`` here was the documented
        # drift migration (``RemoveConstraint`` of
        # ``uniq_active_appropriation_per_dimension_tuple``) that we
        # explicitly do NOT want — it would silently drop a real
        # uniqueness invariant on Appropriation.
        ('budget', '0016_warrant_date_range'),
        ('contracts', '0009_add_contract_year_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='appropriation',
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    'Budget appropriation line for single-year contracts. '
                    'Validated by IPCService._enforce_appropriation_gate at '
                    'each IPC approval. Multi-year contracts use ContractYearPlan.'
                ),
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='contracts',
                to='budget.appropriation',
            ),
        ),
    ]
