# Generated by Django 5.2.14 on 2026-05-24 19:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_repoint_appropriation_fk_to_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='retention_cap_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Maximum cumulative retention as % of original_sum. Once balance.retention_held reaches this cap no further deduction is taken on subsequent IPCs (standard FIDIC / Nigerian PPP practice — typically 5–10% of contract sum).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('20'))]),
        ),
    ]
