# Generated by Django 5.2.14 on 2026-09-08 23:53

from django.db import migrations, models

# Catches the model up with the APPROVED/CANCELLED states the
# mobilization governance work added to MobilizationPaymentStatus. The
# migration was never generated, so `makemigrations --check` — a hard
# gate in CI — failed on every branch.
#
# Metadata only: choices are validated in Python, not by the database,
# and the sole CheckConstraint on this model is on `amount`, not
# `status`, so this alters no SQL and touches no rows. max_length stays
# 25, which still clears the longest value (PARTIALLY_RECOVERED, 19).


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0011_contract_retention_cap_percent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mobilizationpayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Approval"),
                    ("APPROVED", "Approved for Payment"),
                    ("CANCELLED", "Cancelled"),
                    ("PAID", "Paid"),
                    ("PARTIALLY_RECOVERED", "Partially Recovered"),
                    ("FULLY_RECOVERED", "Fully Recovered"),
                ],
                default="PENDING",
                max_length=25,
            ),
        ),
    ]
