# Generated by Django 5.2.14 on 2026-09-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0011_contract_retention_cap_percent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mobilizationpayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Approval"),
                    ("APPROVED", "Approved for Payment"),
                    ("CANCELLED", "Cancelled"),
                    ("PAID", "Paid"),
                    ("PARTIALLY_RECOVERED", "Partially Recovered"),
                    ("FULLY_RECOVERED", "Fully Recovered"),
                ],
                default="PENDING",
                max_length=25,
            ),
        ),
    ]
