# Generated by Django 5.2.14 on 2026-09-16 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0012_alter_mobilizationpayment_status"),
        ("contracts", "0012_contract_duplicate_ack"),
    ]

    operations = []
