# Generated by Django 5.2.14 on 2026-09-23 00:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0131_vendorinvoice_retention_withheld"),
        ("budget", "0022_revenuebudget_budget_code"),
        ("contracts", "0013_merge_20260916_1552"),
    ]

    operations = [
        migrations.AlterField(
            model_name="milestoneschedule",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("INVOICED", "Invoiced"),
                    ("WAIVED", "Waived"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MilestoneInvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        help_text="Expense GL account debited for this line.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.account",
                    ),
                ),
                (
                    "appropriation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Budget appropriation this spend draws against (optional).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="milestone_lines",
                        to="budget.appropriation",
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="contracts.milestoneschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["milestone", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="contracts_milestoneline_amount_positive",
                    )
                ],
            },
        ),
    ]
