# Generated by Django 6.0.2 on 2026-03-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0002_subscriptionplan_tenantmodule_tenantsubscription_usertenantrole_tenantpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertenantrole',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Django Groups assigned to this user for this tenant', related_name='tenant_roles', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='usertenantrole',
            name='role',
            field=models.CharField(choices=[('admin', 'Tenant Admin'), ('senior_manager', 'Senior Manager'), ('manager', 'Mid-Level Manager'), ('user', 'Standard User'), ('viewer', 'Read-Only Viewer')], default='user', max_length=20),
        ),
    ]
