# Generated by Django 4.2.28 on 2026-03-12 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_usertenantrole_groups_alter_usertenantrole_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('module', models.CharField(choices=[('accounting', 'Accounting'), ('sales', 'Sales'), ('procurement', 'Procurement'), ('inventory', 'Inventory'), ('hrm', 'Human Resources'), ('budget', 'Budget'), ('production', 'Production'), ('quality', 'Quality'), ('service', 'Service'), ('technical', 'Technical'), ('admin', 'Administration')], max_length=20)),
                ('role_type', models.CharField(choices=[('manager', 'Manager'), ('officer', 'Officer')], max_length=20)),
                ('can_view', models.BooleanField(default=True)),
                ('can_add', models.BooleanField(default=False)),
                ('can_change', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_approve', models.BooleanField(default=False)),
                ('can_post', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default role for new users in this module')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='tenants.client')),
            ],
            options={
                'ordering': ['module', 'role_type', 'name'],
                'unique_together': {('tenant', 'code')},
            },
        ),
    ]
