# Generated by Django 4.2.28 on 2026-03-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertenantrole',
            name='preferred_language',
            field=models.CharField(blank=True, default='', help_text='User preferred language for this tenant (e.g., en, fr, es)', max_length=10),
        ),
        migrations.AddField(
            model_name='usertenantrole',
            name='timezone',
            field=models.CharField(blank=True, default='', help_text='User timezone for this tenant', max_length=50),
        ),
    ]
