# Generated by Django 4.2.28 on 2026-04-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_add_branding_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(help_text='Must match a key from AVAILABLE_MODULES (e.g. "accounting")', max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('tagline', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, default='AppstoreOutlined', help_text='Ant Design icon name for the frontend', max_length=50)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('features', models.JSONField(blank=True, default=list, help_text='List of feature strings shown on the pricing card')),
                ('highlights', models.JSONField(blank=True, default=list, help_text='Key benefits shown on the detail page')),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False, help_text='Show a "Popular" badge')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
