# Generated by Django 4.2.28 on 2026-04-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_client_business_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='government_tier',
            field=models.CharField(blank=True, choices=[('STATE', 'State Government'), ('LGA', 'Local Government Area')], default='', help_text='STATE = State Government, LGA = Local Government Area', max_length=5),
        ),
        migrations.AddField(
            model_name='client',
            name='lga_code',
            field=models.CharField(blank=True, default='', help_text='NBS LGA code within the state (only for LGA-tier tenants)', max_length=2),
        ),
        migrations.AddField(
            model_name='client',
            name='lga_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='state_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='state_nbs_code',
            field=models.CharField(blank=True, default='', help_text='NBS 2-digit state code (e.g., 24 for Kwara, 28 for Lagos)', max_length=2),
        ),
        migrations.AlterField(
            model_name='role',
            name='module',
            field=models.CharField(choices=[('accounting', 'General Ledger & Accounting'), ('budget', 'Budget & Appropriation'), ('treasury', 'Treasury & TSA'), ('procurement', 'Procurement & Due Process'), ('inventory', 'Stores & Inventory'), ('hrm', 'Human Resources & Payroll'), ('revenue', 'Revenue Collection (IGR)'), ('workflow', 'Workflow & Approvals'), ('reporting', 'Financial Reporting'), ('audit', 'Audit & Compliance'), ('admin', 'System Administration')], max_length=20),
        ),
    ]
