# Generated by Django 4.2.28 on 2026-04-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_client_government_tier_client_lga_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mda_isolation_mode',
            field=models.CharField(choices=[('UNIFIED', 'Unified — all users see all MDAs'), ('SEPARATED', 'Separated — each MDA operates as a branch')], default='UNIFIED', help_text='UNIFIED = no data filtering; SEPARATED = per-MDA data isolation', max_length=10),
        ),
    ]
