# Generated by Django 4.2.28 on 2026-04-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_client_mda_isolation_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='enforce_warrant',
            field=models.BooleanField(default=False, help_text='True = warrant must be released before payment (strict). False = only appropriation + balance checked (relaxed).'),
        ),
    ]
