# Generated by Django 4.2.28 on 2026-04-24 14:47

from django.db import migrations, models


def mark_existing_tenants_active(apps, schema_editor):
    """Backfill: every pre-existing tenant already has a migrated schema,
    so their provisioning_status must be 'active' — not the 'pending'
    default. Without this, the whole tenant list would show "Queued"
    chips after the migration and the frontend would never stop polling.
    """
    Client = apps.get_model('tenants', 'Client')
    Client.objects.exclude(schema_name='public').update(provisioning_status='active')


def noop_reverse(apps, schema_editor):
    """Reverse is a no-op — dropping the column drops the data with it."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_client_enforce_warrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='provisioning_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='provisioning_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='client',
            name='provisioning_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='provisioning_status',
            field=models.CharField(choices=[('pending', 'Pending — queued for schema creation'), ('provisioning', 'Provisioning — migrations running'), ('active', 'Active — ready for use'), ('failed', 'Failed — see provisioning_error')], default='pending', help_text='Async schema-creation state. Frontend polls this.', max_length=20),
        ),
        migrations.RunPython(mark_existing_tenants_active, noop_reverse),
    ]
