# Generated by Django 5.2.14 on 2026-09-02 22:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0112_journal_balance_guard_case_insensitive"),
        ("budget", "0017_alter_warrant_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fiscal_year", models.IntegerField(db_index=True)),
                ("month", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("annual", "Annual"),
                            ("quarterly", "Quarterly"),
                            ("monthly", "Monthly"),
                        ],
                        default="annual",
                        max_length=20,
                    ),
                ),
                ("mda_name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "planned_inflow",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "planned_outflow",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fund",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.fund",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["fiscal_year", "month"],
            },
        ),
        migrations.CreateModel(
            name="CashForecastLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("commitment", "Open Procurement Commitment"),
                            ("contract", "Contract Year Plan"),
                            ("payroll", "Payroll Obligation"),
                            ("debt", "Debt Service"),
                            ("revenue", "Revenue Seasonality"),
                            ("manual", "Manual Entry"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "flow",
                    models.CharField(
                        choices=[("inflow", "Inflow"), ("outflow", "Outflow")],
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("due_date", models.DateField(default=django.utils.timezone.now)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "source_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Reference to the originating record (PO / contract / run id).",
                        max_length=100,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cash_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="cash_planning.cashplan",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date"],
            },
        ),
        migrations.CreateModel(
            name="CashPlanVariance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fiscal_year", models.IntegerField(db_index=True)),
                ("month", models.PositiveIntegerField(blank=True, null=True)),
                ("mda_name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "planned_inflow",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "actual_inflow",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "planned_outflow",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "actual_outflow",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["fiscal_year", "month"],
            },
        ),
        migrations.CreateModel(
            name="WarrantRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("mda_name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "proposed_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("accepted", "Accepted"),
                            ("converted", "Converted to Warrant"),
                            ("rejected", "Rejected"),
                        ],
                        default="proposed",
                        max_length=20,
                    ),
                ),
                ("rationale", models.TextField(blank=True, default="")),
                (
                    "appropriation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="budget.appropriation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fund",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.fund",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warrant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when the recommendation is converted to a Warrant.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="budget.warrant",
                    ),
                ),
            ],
            options={
                "ordering": ["recommendation_date"],
            },
        ),
        migrations.CreateModel(
            name="CashPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position_date", models.DateField(db_index=True)),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "projected_inflow",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "projected_outflow",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "closing_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "warning_floor",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Configurable floor below which the position flags a warning.",
                        max_digits=18,
                    ),
                ),
                ("is_below_floor", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["position_date"],
                "indexes": [
                    models.Index(
                        fields=["position_date"], name="cash_planni_positio_c22623_idx"
                    )
                ],
            },
        ),
    ]
