# Generated by Django 6.0.2 on 2026-03-01 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0002_employee_salary_structure_trainingprogram_department'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_cards', to='hrm.employee'),
        ),
    ]
