# Generated by Django 6.0.2 on 2026-03-01 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_jobcard_operator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionorder',
            options={'permissions': [('approve_productionorder', 'Can approve production orders')]},
        ),
    ]
