# Generated by Django 4.2.28 on 2026-03-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_productionorder_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterials',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='item_code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='item_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='item_type',
            field=models.CharField(choices=[('Finished', 'Finished Product'), ('Semi-Finished', 'Semi-Finished Product'), ('Raw Material', 'Raw Material')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Done', 'Done')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='materialissue',
            name='issue_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='materialreceipt',
            name='receipt_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='order_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Done', 'Done'), ('Cancelled', 'Cancelled')], db_index=True, default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='workcenter',
            name='code',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='workcenter',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['production_order', 'status'], name='production__product_82a3cd_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['work_center', 'status'], name='production__work_ce_ba384a_idx'),
        ),
        migrations.AddIndex(
            model_name='materialissue',
            index=models.Index(fields=['production_order', 'issue_date'], name='production__product_6268aa_idx'),
        ),
        migrations.AddIndex(
            model_name='materialreceipt',
            index=models.Index(fields=['production_order', 'receipt_date'], name='production__product_29c9bc_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['status', 'start_date'], name='production__status_1005ce_idx'),
        ),
    ]
