# Generated by Django 4.2.28 on 2026-03-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_alter_billofmaterials_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Done', 'Done'), ('Cancelled', 'Cancelled')], db_index=True, default='Draft', max_length=20),
        ),
    ]
