# Generated by Django 6.0.2 on 2026-03-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_add_on_hold_status_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterials',
            name='requires_quality_inspection',
            field=models.BooleanField(default=False),
        ),
    ]
