# Generated by Django 6.0.2 on 2026-04-05 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0052_add_journal_source_soft_delete'),
        ('production', '0006_add_requires_quality_inspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='finished_goods_account',
            field=models.ForeignKey(blank=True, help_text="Override Finished Goods account. Falls back to DEFAULT_GL_ACCOUNTS['FINISHED_GOODS'].", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders_as_finished_goods', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='wip_account',
            field=models.ForeignKey(blank=True, help_text="Override WIP Inventory account. Falls back to DEFAULT_GL_ACCOUNTS['WIP_INVENTORY'].", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders_as_wip', to='accounting.account'),
        ),
    ]
