# Generated by Django 6.0.2 on 2026-04-05 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_alter_inventorysettings_id'),
        ('production', '0007_add_gl_account_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterials',
            name='inventory_item',
            field=models.ForeignKey(blank=True, help_text='Link to inventory Item for price lookups and stock integration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_set', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Done', 'Done'), ('Cancelled', 'Cancelled')], db_index=True, default='Draft', max_length=20),
        ),
    ]
