import type { ModuleConfig } from '../_base/types';

export const moduleConfig: ModuleConfig = {
  key: 'cash_planning',
  label: 'Cash Planning & Forecasting',
  icon: '💹',
  description: 'Cash plans, forecast lines, cash positions, warrant recommendations and cash plan variances.',
  basePath: '/cash-planning',
  entities: [
    {
      key: 'cashPlan',
      plural: 'plans',
      label: 'Cash Plans',
      searchField: 'mda_name',
      idField: 'id',
      columns: [
        { name: 'fiscal_year', label: 'Fiscal Year', type: 'integer', numeric: true },
        { name: 'month', label: 'Month', type: 'integer', numeric: true },
        {
          name: 'plan_type',
          label: 'Plan Type',
          type: 'select',
          options: { annual: 'Annual', quarterly: 'Quarterly', monthly: 'Monthly' },
        },
        { name: 'mda_name', label: 'MDA', type: 'text' },
        { name: 'planned_inflow', label: 'Planned Inflow', type: 'decimal', numeric: true },
        { name: 'planned_outflow', label: 'Planned Outflow', type: 'decimal', numeric: true },
      ],
      fields: [
        { name: 'fiscal_year', label: 'Fiscal Year', type: 'integer', numeric: true, required: true },
        { name: 'month', label: 'Month', type: 'integer', numeric: true, secondary: true },
        {
          name: 'plan_type',
          label: 'Plan Type',
          type: 'select',
          required: true,
          options: { annual: 'Annual', quarterly: 'Quarterly', monthly: 'Monthly' },
        },
        {
          name: 'fund',
          label: 'Fund',
          type: 'integer',
          secondary: true,
          reference: { module: 'accounting', entity: 'fund' },
        },
        { name: 'mda_name', label: 'MDA Name', type: 'text' },
        { name: 'planned_inflow', label: 'Planned Inflow', type: 'decimal', numeric: true },
        { name: 'planned_outflow', label: 'Planned Outflow', type: 'decimal', numeric: true },
        { name: 'net_planned', label: 'Net Planned', type: 'decimal', numeric: true, hideInForm: true, readOnly: true, secondary: true },
        { name: 'notes', label: 'Notes', type: 'longtext', secondary: true },
        { name: 'lines', label: 'Lines', type: 'object', hideInForm: true, readOnly: true, secondary: true },
        { name: 'created_at', label: 'Created At', type: 'datetime', hideInForm: true, readOnly: true, secondary: true },
        { name: 'updated_at', label: 'Updated At', type: 'datetime', hideInForm: true, readOnly: true, secondary: true },
      ],
    },
    {
      key: 'cashForecastLine',
      plural: 'lines',
      label: 'Cash Forecast Lines',
      searchField: 'description',
      idField: 'id',
      columns: [
        { name: 'cash_plan', label: 'Cash Plan', type: 'integer', reference: { module: 'cash_planning', entity: 'cashPlan' } },
        {
          name: 'source',
          label: 'Source',
          type: 'select',
          options: {
            commitment: 'Open Procurement Commitment',
            contract: 'Contract Year Plan',
            payroll: 'Payroll Obligation',
            debt: 'Debt Service',
            revenue: 'Revenue Seasonality',
            manual: 'Manual Entry',
          },
        },
        { name: 'flow', label: 'Flow', type: 'select', options: { inflow: 'Inflow', outflow: 'Outflow' } },
        { name: 'amount', label: 'Amount', type: 'decimal', numeric: true },
        { name: 'due_date', label: 'Due Date', type: 'date' },
      ],
      fields: [
        {
          name: 'cash_plan',
          label: 'Cash Plan',
          type: 'integer',
          required: true,
          reference: { module: 'cash_planning', entity: 'cashPlan' },
        },
        {
          name: 'source',
          label: 'Source',
          type: 'select',
          options: {
            commitment: 'Open Procurement Commitment',
            contract: 'Contract Year Plan',
            payroll: 'Payroll Obligation',
            debt: 'Debt Service',
            revenue: 'Revenue Seasonality',
            manual: 'Manual Entry',
          },
        },
        { name: 'flow', label: 'Flow', type: 'select', required: true, options: { inflow: 'Inflow', outflow: 'Outflow' } },
        { name: 'amount', label: 'Amount', type: 'decimal', numeric: true },
        { name: 'due_date', label: 'Due Date', type: 'date' },
        { name: 'description', label: 'Description', type: 'longtext', secondary: true },
        { name: 'source_ref', label: 'Source Reference', type: 'text', secondary: true },
      ],
    },
    {
      key: 'cashPosition',
      plural: 'positions',
      label: 'Cash Positions',
      searchField: 'position_date',
      idField: 'id',
      columns: [
        { name: 'position_date', label: 'Position Date', type: 'date' },
        { name: 'opening_balance', label: 'Opening Balance', type: 'decimal', numeric: true },
        { name: 'projected_inflow', label: 'Projected Inflow', type: 'decimal', numeric: true },
        { name: 'projected_outflow', label: 'Projected Outflow', type: 'decimal', numeric: true },
        { name: 'closing_balance', label: 'Closing Balance', type: 'decimal', numeric: true },
      ],
      fields: [
        { name: 'position_date', label: 'Position Date', type: 'date', required: true },
        { name: 'opening_balance', label: 'Opening Balance', type: 'decimal', numeric: true },
        { name: 'projected_inflow', label: 'Projected Inflow', type: 'decimal', numeric: true },
        { name: 'projected_outflow', label: 'Projected Outflow', type: 'decimal', numeric: true },
        { name: 'closing_balance', label: 'Closing Balance', type: 'decimal', numeric: true, secondary: true },
        { name: 'warning_floor', label: 'Warning Floor', type: 'decimal', numeric: true, secondary: true },
        { name: 'is_below_floor', label: 'Below Floor', type: 'boolean', secondary: true },
        { name: 'notes', label: 'Notes', type: 'longtext', secondary: true },
      ],
    },
    {
      key: 'warrantRecommendation',
      plural: 'recommendations',
      label: 'Warrant Recommendations',
      searchField: 'mda_name',
      idField: 'id',
      statusField: 'status',
      columns: [
        { name: 'recommendation_date', label: 'Recommendation Date', type: 'date' },
        { name: 'mda_name', label: 'MDA', type: 'text' },
        { name: 'proposed_amount', label: 'Proposed Amount', type: 'decimal', numeric: true },
        {
          name: 'status',
          label: 'Status',
          type: 'select',
          options: { proposed: 'Proposed', accepted: 'Accepted', converted: 'Converted to Warrant', rejected: 'Rejected' },
        },
        { name: 'fund', label: 'Fund', type: 'integer', reference: { module: 'accounting', entity: 'fund' } },
      ],
      fields: [
        { name: 'recommendation_date', label: 'Recommendation Date', type: 'date', required: true },
        { name: 'mda_name', label: 'MDA Name', type: 'text' },
        {
          name: 'appropriation',
          label: 'Appropriation',
          type: 'integer',
          secondary: true,
          reference: { module: 'budget', entity: 'appropriation' },
        },
        {
          name: 'fund',
          label: 'Fund',
          type: 'integer',
          secondary: true,
          reference: { module: 'accounting', entity: 'fund' },
        },
        { name: 'proposed_amount', label: 'Proposed Amount', type: 'decimal', numeric: true },
        {
          name: 'status',
          label: 'Status',
          type: 'select',
          options: { proposed: 'Proposed', accepted: 'Accepted', converted: 'Converted to Warrant', rejected: 'Rejected' },
        },
        { name: 'rationale', label: 'Rationale', type: 'longtext', secondary: true },
        {
          name: 'warrant',
          label: 'Warrant',
          type: 'integer',
          secondary: true,
          reference: { module: 'budget', entity: 'warrant' },
        },
        { name: 'created_at', label: 'Created At', type: 'datetime', hideInForm: true, readOnly: true, secondary: true },
        { name: 'updated_at', label: 'Updated At', type: 'datetime', hideInForm: true, readOnly: true, secondary: true },
      ],
    },
    {
      key: 'cashPlanVariance',
      plural: 'variances',
      label: 'Cash Plan Variances',
      searchField: 'mda_name',
      idField: 'id',
      columns: [
        { name: 'fiscal_year', label: 'Fiscal Year', type: 'integer', numeric: true },
        { name: 'month', label: 'Month', type: 'integer', numeric: true },
        { name: 'mda_name', label: 'MDA', type: 'text' },
        { name: 'planned_inflow', label: 'Planned Inflow', type: 'decimal', numeric: true },
        { name: 'actual_inflow', label: 'Actual Inflow', type: 'decimal', numeric: true },
        { name: 'planned_outflow', label: 'Planned Outflow', type: 'decimal', numeric: true },
      ],
      fields: [
        { name: 'fiscal_year', label: 'Fiscal Year', type: 'integer', numeric: true, required: true },
        { name: 'month', label: 'Month', type: 'integer', numeric: true, secondary: true },
        { name: 'mda_name', label: 'MDA Name', type: 'text' },
        { name: 'planned_inflow', label: 'Planned Inflow', type: 'decimal', numeric: true },
        { name: 'actual_inflow', label: 'Actual Inflow', type: 'decimal', numeric: true },
        { name: 'planned_outflow', label: 'Planned Outflow', type: 'decimal', numeric: true },
        { name: 'actual_outflow', label: 'Actual Outflow', type: 'decimal', numeric: true },
      ],
    },
  ],
};
