import type { ModuleConfig } from '../_base/types';

export const moduleConfig: ModuleConfig = {
  key: 'fleet',
  label: 'Fleet Management',
  icon: '🚌',
  description: 'Vehicle, fuel, mileage and maintenance registers for the government fleet.',
  basePath: '/fleet',
  entities: [
    {
      key: 'vehicle',
      plural: 'vehicles',
      label: 'Vehicles',
      searchField: 'registration_number',
      statusField: 'status',
      idField: 'id',
      columns: [
        { name: 'registration_number', label: 'Registration No.', type: 'text',  },
        { name: 'make', label: 'Make', type: 'text',  },
        { name: 'model', label: 'Model', type: 'text' },
        { name: 'year', label: 'Year', type: 'integer', numeric: true },
        { name: 'status', label: 'Status', type: 'select', options: { active: 'Active', assigned: 'Assigned', maintenance: 'Under Maintenance', offroad: 'Off Road', disposed: 'Disposed' } },
      ],
      fields: [
        { name: 'id', label: 'ID', type: 'integer', readOnly: true, hideInForm: true },
        { name: 'fixed_asset', label: 'Fixed Asset', type: 'integer', required: true, placeholder: 'Fixed Asset ID' },
        { name: 'registration_number', label: 'Registration No.', type: 'text', required: true, placeholder: 'e.g. AB 123 CD' },
        { name: 'chassis_number', label: 'Chassis No.', type: 'text', placeholder: 'Chassis number' },
        { name: 'make', label: 'Make', type: 'text', placeholder: 'e.g. Toyota' },
        { name: 'model', label: 'Model', type: 'text', placeholder: 'e.g. Hilux' },
        { name: 'year', label: 'Year', type: 'integer', numeric: true },
        { name: 'fuel_type', label: 'Fuel Type', type: 'text', placeholder: 'e.g. Petrol' },
        { name: 'status', label: 'Status', type: 'select', options: { active: 'Active', assigned: 'Assigned', maintenance: 'Under Maintenance', offroad: 'Off Road', disposed: 'Disposed' } },
        { name: 'licence_expiry', label: 'Licence Expiry', type: 'date' },
        { name: 'insurance_expiry', label: 'Insurance Expiry', type: 'date' },
        { name: 'roadworthiness_expiry', label: 'Roadworthiness Expiry', type: 'date', secondary: true },
        { name: 'is_expiring', label: 'Is Expiring', type: 'boolean', readOnly: true, hideInForm: true },
      ],
    },
    {
      key: 'vehicleAssignment',
      plural: 'assignments',
      label: 'Vehicle Assignments',
      searchField: 'assigned_to',
      idField: 'id',
      columns: [
        { name: 'vehicle', label: 'Vehicle', type: 'integer',  },
        { name: 'assigned_to', label: 'Assigned To', type: 'text',  },
        { name: 'department', label: 'Department', type: 'text' },
        { name: 'assigned_from', label: 'From', type: 'date' },
        { name: 'assigned_to_date', label: 'To', type: 'date', secondary: true },
      ],
      fields: [
        { name: 'id', label: 'ID', type: 'integer', readOnly: true, hideInForm: true },
        { name: 'vehicle', label: 'Vehicle', type: 'integer', required: true, reference: { module: 'fleet', entity: 'vehicle' } },
        { name: 'assigned_to', label: 'Assigned To', type: 'text', required: true, placeholder: 'Assignee name' },
        { name: 'department', label: 'Department', type: 'text', placeholder: 'Department name' },
        { name: 'assigned_from', label: 'Assigned From', type: 'date' },
        { name: 'assigned_to_date', label: 'Assigned To Date', type: 'date', secondary: true },
        { name: 'notes', label: 'Notes', type: 'longtext', secondary: true },
      ],
    },
    {
      key: 'fuelLog',
      plural: 'fuel-logs',
      label: 'Fuel Logs',
      searchField: 'vendor',
      idField: 'id',
      columns: [
        { name: 'log_date', label: 'Date', type: 'date',  },
        { name: 'vehicle', label: 'Vehicle', type: 'integer',  },
        { name: 'litres', label: 'Litres', type: 'decimal', numeric: true },
        { name: 'cost', label: 'Cost', type: 'decimal', numeric: true },
        { name: 'vendor', label: 'Vendor', type: 'text', secondary: true },
      ],
      fields: [
        { name: 'id', label: 'ID', type: 'integer', readOnly: true, hideInForm: true },
        { name: 'vehicle', label: 'Vehicle', type: 'integer', required: true, reference: { module: 'fleet', entity: 'vehicle' } },
        { name: 'log_date', label: 'Log Date', type: 'date' },
        { name: 'litres', label: 'Litres', type: 'decimal', numeric: true },
        { name: 'cost', label: 'Cost', type: 'decimal', numeric: true },
        { name: 'odometer_reading', label: 'Odometer Reading', type: 'integer', numeric: true, secondary: true },
        { name: 'vendor', label: 'Vendor', type: 'text', secondary: true, placeholder: 'Fuel vendor name' },
      ],
    },
    {
      key: 'mileageLog',
      plural: 'mileage-logs',
      label: 'Mileage Logs',
      searchField: 'driver',
      idField: 'id',
      columns: [
        { name: 'log_date', label: 'Date', type: 'date',  },
        { name: 'vehicle', label: 'Vehicle', type: 'integer',  },
        { name: 'driver', label: 'Driver', type: 'text' },
        { name: 'odometer_reading', label: 'Odometer', type: 'integer', numeric: true },
        { name: 'trip_purpose', label: 'Trip Purpose', type: 'longtext', secondary: true },
      ],
      fields: [
        { name: 'id', label: 'ID', type: 'integer', readOnly: true, hideInForm: true },
        { name: 'vehicle', label: 'Vehicle', type: 'integer', required: true, reference: { module: 'fleet', entity: 'vehicle' } },
        { name: 'log_date', label: 'Log Date', type: 'date' },
        { name: 'odometer_reading', label: 'Odometer Reading', type: 'integer', numeric: true },
        { name: 'trip_purpose', label: 'Trip Purpose', type: 'longtext', secondary: true },
        { name: 'driver', label: 'Driver', type: 'text', secondary: true, placeholder: 'Driver name' },
      ],
    },
    {
      key: 'maintenanceRecord',
      plural: 'maintenance',
      label: 'Maintenance Records',
      searchField: 'service_type',
      idField: 'id',
      columns: [
        { name: 'service_date', label: 'Service Date', type: 'date',  },
        { name: 'vehicle', label: 'Vehicle', type: 'integer',  },
        { name: 'service_type', label: 'Service Type', type: 'text' },
        { name: 'cost', label: 'Cost', type: 'decimal', numeric: true },
        { name: 'service_provider', label: 'Provider', type: 'text', secondary: true },
      ],
      fields: [
        { name: 'id', label: 'ID', type: 'integer', readOnly: true, hideInForm: true },
        { name: 'vehicle', label: 'Vehicle', type: 'integer', required: true, reference: { module: 'fleet', entity: 'vehicle' } },
        { name: 'service_date', label: 'Service Date', type: 'date' },
        { name: 'next_due_date', label: 'Next Due Date', type: 'date', secondary: true },
        { name: 'service_type', label: 'Service Type', type: 'text', placeholder: 'e.g. Oil Change' },
        { name: 'description', label: 'Description', type: 'longtext', secondary: true },
        { name: 'cost', label: 'Cost', type: 'decimal', numeric: true },
        { name: 'service_provider', label: 'Service Provider', type: 'text', secondary: true, placeholder: 'Workshop or provider name' },
      ],
    },
  ],
};
