# Generated by Django 6.0.2 on 2026-03-01 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0001_product_type_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hrm.salarystructure'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_programs', to='hrm.department'),
        ),
    ]
