# Generated by Django 6.0.2 on 2026-03-01 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0002_employee_salary_structure_trainingprogram_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'permissions': [('approve_leaverequest', 'Can approve leave requests')]},
        ),
        migrations.AlterModelOptions(
            name='payrollrun',
            options={'permissions': [('process_payrollrun', 'Can process payroll runs'), ('approve_payrollrun', 'Can approve payroll runs')]},
        ),
    ]
