# Generated by Django 4.2.28 on 2026-03-26 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrm', '0003_alter_leaverequest_options_alter_payrollrun_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('tax_year', models.PositiveIntegerField(unique=True)),
                ('basic_exemption', models.DecimalField(decimal_places=2, default=0, help_text='Annual income exemption', max_digits=12)),
                ('standard_deduction', models.DecimalField(decimal_places=2, default=0, help_text='Standard deduction amount', max_digits=12)),
                ('social_security_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('social_security_cap', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pension_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pension_cap', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaxBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('min_income', models.DecimalField(decimal_places=2, help_text='Minimum income for this bracket', max_digits=12)),
                ('max_income', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum income (null = no limit)', max_digits=12, null=True)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Tax rate as percentage (e.g., 25.00 for 25%)', max_digits=5)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0, help_text='Fixed amount to add to calculated tax', max_digits=12)),
                ('effective_date', models.DateField(help_text='Date this bracket becomes effective')),
                ('end_date', models.DateField(blank=True, help_text='Date this bracket expires', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['min_income'],
            },
        ),
    ]
