# Generated by Django 4.2.28 on 2026-03-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0004_add_tax_brackets'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='health_insurance_number',
            field=models.CharField(blank=True, help_text='NHIS / Health Insurance Number', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='national_id_number',
            field=models.CharField(blank=True, help_text='National ID Card Number', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_number',
            field=models.CharField(blank=True, help_text='Passport Number', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='pension_number',
            field=models.CharField(blank=True, help_text='Pension Membership Number', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='social_security_number',
            field=models.CharField(blank=True, help_text='SSN / Social Security Number', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='tax_identification_number',
            field=models.CharField(blank=True, help_text='Tax ID / TIN', max_length=50),
        ),
    ]
