# Generated by Django 4.2.28 on 2026-03-26 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0038_baddebtwriteoff_financialratio_and_more'),
        ('hrm', '0005_add_statutory_id_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='accounting.costcenter'),
        ),
    ]
