# Generated by Django 4.2.28 on 2026-03-26 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0038_baddebtwriteoff_financialratio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrm', '0006_add_cost_center_to_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatutoryDeductionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('deduction_type', models.CharField(choices=[('NHIS', 'National Health Insurance'), ('GETFL', 'GETFL/Trade Union'), ('Tier1', 'Tier 1 Pension'), ('Tier2', 'Tier 2 Pension'), ('Income_Tax', 'Income Tax'), ('Other', 'Other')], max_length=20)),
                ('rate', models.DecimalField(decimal_places=4, default=0, help_text='Percentage rate (e.g., 0.025 for 2.5%)', max_digits=6)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0, help_text='Fixed amount to deduct (used instead of rate if set)', max_digits=12)),
                ('employer_rate', models.DecimalField(decimal_places=4, default=0, help_text='Employer contribution rate', max_digits=6)),
                ('employer_fixed', models.DecimalField(decimal_places=2, default=0, help_text='Employer fixed contribution', max_digits=12)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('applies_to_employment_types', models.JSONField(blank=True, default=list, help_text="List of employment types this applies to (e.g., ['Permanent', 'Contract'])")),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum deduction amount', max_digits=12)),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum deduction amount (cap)', max_digits=12, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('gl_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='statutory_deduction_templates', to='accounting.account')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['deduction_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StatutoryDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employer_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_employer_contribution', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('payroll_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statutory_deductions', to='hrm.payrollline')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deductions', to='hrm.statutorydeductiontemplate')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('payroll_line', 'template')},
            },
        ),
    ]
