# Generated by Django 6.0.2 on 2026-03-30 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0038_baddebtwriteoff_financialratio_and_more'),
        ('hrm', '0007_add_statutory_deduction_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrun',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs', to='accounting.journalheader'),
        ),
    ]
