# Generated by Django 6.0.2 on 2026-04-05 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0052_add_journal_source_soft_delete'),
        ('hrm', '0008_payrollrun_journal_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrun',
            name='payroll_expense_account',
            field=models.ForeignKey(blank=True, help_text="Override GL account for Salary/Wage Expense. Falls back to DEFAULT_GL_ACCOUNTS['SALARY_EXPENSE'].", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs_as_expense', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='payroll_liability_account',
            field=models.ForeignKey(blank=True, help_text="Override GL account for Net Pay Liability. Falls back to DEFAULT_GL_ACCOUNTS['PAYROLL_LIABILITY'].", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs_as_liability', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='pension_account',
            field=models.ForeignKey(blank=True, help_text="Override GL account for Pension Payable. Falls back to DEFAULT_GL_ACCOUNTS['PENSION_PAYABLE'].", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs_as_pension', to='accounting.account'),
        ),
    ]
