# Generated by Django 4.2.28 on 2026-04-09 21:41

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0056_ncoa_segments'),
        ('hrm', '0009_add_gl_account_overrides'),
    ]

    operations = [
        migrations.CreateModel(
            name='NigeriaTaxBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_bound', models.DecimalField(decimal_places=2, max_digits=15)),
                ('upper_bound', models.DecimalField(blank=True, decimal_places=2, help_text='Null = unlimited (highest bracket)', max_digits=15, null=True)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Tax rate as percentage', max_digits=5)),
                ('effective_date', models.DateField()),
                ('is_current', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Nigeria PAYE Tax Bracket',
                'verbose_name_plural': 'Nigeria PAYE Tax Brackets',
                'ordering': ['lower_bound'],
            },
        ),
        migrations.CreateModel(
            name='PensionConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Employer contribution rate (minimum 10%)', max_digits=5)),
                ('employee_rate', models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text='Employee contribution rate (minimum 8%)', max_digits=5)),
                ('qualifying_components', models.JSONField(default=list, help_text='Salary components for pension base, e.g. ["basic", "housing", "transport"]')),
                ('remittance_deadline_days', models.IntegerField(default=7, help_text='Days after payroll to remit to PFA (7 working days per PRA 2014)')),
                ('effective_date', models.DateField()),
                ('is_current', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pension Configuration',
                'verbose_name_plural': 'Pension Configurations',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='PensionFundAdministrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pfa_code', models.CharField(help_text='PENCOM registration code', max_length=10, unique=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_account', models.CharField(max_length=20)),
                ('sort_code', models.CharField(blank=True, default='', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pension Fund Administrator (PFA)',
                'verbose_name_plural': 'Pension Fund Administrators (PFAs)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeePensionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsa_pin', models.CharField(help_text='Retirement Savings Account PIN (from PENCOM)', max_length=20, unique=True)),
                ('enrollment_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pension_profile', to='hrm.employee')),
                ('pfa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='hrm.pensionfundadministrator')),
            ],
            options={
                'verbose_name': 'Employee Pension Profile',
                'verbose_name_plural': 'Employee Pension Profiles',
            },
        ),
        migrations.CreateModel(
            name='PensionRemittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_count', models.IntegerField()),
                ('employer_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('employee_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('remittance_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INITIATED', 'Remittance Initiated'), ('REMITTED', 'Remitted'), ('FAILED', 'Failed')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pension_remittances', to='accounting.paymentvouchergov')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pension_remittances', to='hrm.payrollrun')),
                ('pfa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remittances', to='hrm.pensionfundadministrator')),
            ],
            options={
                'verbose_name': 'Pension Remittance',
                'verbose_name_plural': 'Pension Remittances',
                'ordering': ['-created_at'],
                'unique_together': {('payroll_run', 'pfa')},
            },
        ),
    ]
