# Generated by Django 4.2.28 on 2026-04-24 11:23

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrm', '0011_employeedocument_verificationcycle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accrual_per_month', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Days earned per completed month of service.', max_digits=5)),
                ('max_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Hard cap on accrued balance (0 = uncapped).', max_digits=6)),
                ('carry_forward_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Days carried into next year at reset.', max_digits=5)),
                ('min_service_months', models.PositiveIntegerField(default=0, help_text='Employee must have N completed months before accrual starts.')),
                ('requires_hr_approval', models.BooleanField(default=True, help_text='If True, request must pass HR after line-manager approval.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='hrm.leavetype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Leave policies',
            },
        ),
        migrations.CreateModel(
            name='LeaveApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_order', models.PositiveSmallIntegerField()),
                ('role', models.CharField(choices=[('Line_Manager', 'Line Manager'), ('HR', 'HR'), ('Head_of_Department', 'Head of Department')], max_length=30)),
                ('decision', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Skipped', 'Skipped')], default='Pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('approver', models.ForeignKey(blank=True, help_text='User who actioned this step (filled on decision).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_approval_steps', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Specific user expected to approve (optional routing hint).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leave_steps', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='hrm.leaverequest')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['leave_request_id', 'step_order'],
                'indexes': [models.Index(fields=['decision'], name='hrm_leaveap_decisio_daecbe_idx'), models.Index(fields=['assigned_to', 'decision'], name='hrm_leaveap_assigne_633e95_idx')],
                'unique_together': {('leave_request', 'step_order')},
            },
        ),
        migrations.CreateModel(
            name='LeaveAccrualEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('days_credited', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_accruals', to='hrm.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accrual_entries', to='hrm.leavetype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', 'employee_id'],
                'indexes': [models.Index(fields=['employee', 'leave_type', 'year'], name='hrm_leaveac_employe_ed8f0e_idx'), models.Index(fields=['year', 'month'], name='hrm_leaveac_year_fe94f3_idx')],
                'unique_together': {('employee', 'leave_type', 'year', 'month')},
            },
        ),
    ]
