# Generated by Django 4.2.28 on 2026-04-24 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrm', '0012_leavepolicy_leaveapprovalstep_leaveaccrualentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='e.g. GL01, GL08, CONPSS14.', max_length=10)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('rank_order', models.PositiveSmallIntegerField(help_text='Sort key; higher = more senior.')),
                ('max_steps', models.PositiveSmallIntegerField(default=15)),
                ('annual_increment_months', models.PositiveSmallIntegerField(default=12, help_text='Months between automatic step increments (typically 12).')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scale_id', 'rank_order'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_number', models.PositiveSmallIntegerField()),
                ('annual_basic', models.DecimalField(decimal_places=2, help_text='Annual basic pay in NGN.', max_digits=14)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='hrm.salarygrade')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['grade_id', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='SalaryScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.CharField(choices=[('CONPSS', 'Consolidated Public Service Salary Structure'), ('CONTISS', 'Consolidated Tertiary Institutions Salary Structure'), ('CONPCASS', 'Consolidated Prof. & Chief Academics Salary Structure'), ('CONMESS', 'Consolidated Medical Salary Structure'), ('CONRAISS', 'Consolidated Research & Allied Institutions'), ('CUSTOM', 'Custom / MDA-specific scale')], max_length=20)),
                ('name', models.CharField(help_text='Human-friendly label e.g. "CONPSS 2024 Review".', max_length=100)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['family', '-effective_from'],
            },
        ),
        migrations.AddField(
            model_name='salarygrade',
            name='scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='hrm.salaryscale'),
        ),
        migrations.AddField(
            model_name='salarygrade',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EmployeeGradePlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_from', models.DateField()),
                ('reason', models.CharField(choices=[('Appointment', 'Appointment'), ('Step_Increment', 'Annual Step Increment'), ('Promotion', 'Promotion'), ('Reinstatement', 'Reinstatement'), ('Correction', 'Correction')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_placements', to='hrm.employee')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='hrm.salarystep')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_from', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='salarystep',
            index=models.Index(fields=['grade', 'step_number'], name='hrm_salarys_grade_i_7d76a1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salarystep',
            unique_together={('grade', 'step_number')},
        ),
        migrations.AddIndex(
            model_name='salaryscale',
            index=models.Index(fields=['family', 'is_active'], name='hrm_salarys_family_a7c638_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryscale',
            index=models.Index(fields=['effective_from', 'effective_to'], name='hrm_salarys_effecti_f4e7cc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salaryscale',
            unique_together={('family', 'effective_from')},
        ),
        migrations.AddIndex(
            model_name='salarygrade',
            index=models.Index(fields=['scale', 'rank_order'], name='hrm_salaryg_scale_i_f4f5e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salarygrade',
            unique_together={('scale', 'code')},
        ),
        migrations.AddIndex(
            model_name='employeegradeplacement',
            index=models.Index(fields=['employee', '-effective_from'], name='hrm_employe_employe_5812ce_idx'),
        ),
        migrations.AddIndex(
            model_name='employeegradeplacement',
            index=models.Index(fields=['step'], name='hrm_employe_step_id_cc8a51_idx'),
        ),
    ]
