# Generated by Django 4.2.28 on 2026-04-24 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrm', '0013_salarygrade_salarystep_salaryscale_salarygrade_scale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetirementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger', models.CharField(choices=[('Age_60', 'Statutory age (60)'), ('Service_35', 'Statutory service (35 years)'), ('Voluntary', 'Voluntary early retirement'), ('Medical', 'Medical retirement'), ('Mandatory', 'Mandatory / compulsory')], max_length=20)),
                ('retirement_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Settled', 'Settled'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('final_settlement_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('gratuity_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retirements_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retirement', to='hrm.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-retirement_date'],
                'indexes': [models.Index(fields=['status', 'retirement_date'], name='hrm_retirem_status_d89630_idx'), models.Index(fields=['trigger'], name='hrm_retirem_trigger_f09d99_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_date', models.DateField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Implemented', 'Implemented'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('implemented_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='hrm.employee')),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='hrm.department')),
                ('from_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='hrm.position')),
                ('to_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='hrm.department')),
                ('to_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='hrm.position')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_date', '-id'],
                'indexes': [models.Index(fields=['employee', '-effective_date'], name='hrm_employe_employe_88515d_idx'), models.Index(fields=['status'], name='hrm_employe_status_8dcfbe_idx')],
            },
        ),
    ]
