# Generated by Django 4.2.28 on 2026-04-24 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrm', '0014_retirementrecord_employeetransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('device_type', models.CharField(choices=[('fingerprint', 'Fingerprint'), ('face', 'Facial Recognition'), ('rfid', 'RFID / Smart Card'), ('qr', 'QR Code / Mobile App'), ('hybrid', 'Hybrid / Multi-modal')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('webhook_secret', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('offline', 'Offline'), ('disabled', 'Disabled'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('geofence_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geofence_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geofence_radius_m', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BiometricEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('check_in', 'Check In'), ('check_out', 'Check Out'), ('unknown_user', 'Unknown User'), ('enroll', 'Enrollment'), ('heartbeat', 'Heartbeat')], max_length=20)),
                ('device_user_id', models.CharField(blank=True, max_length=100)),
                ('occurred_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('process_status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched to Employee'), ('unmatched', 'No enrollment match'), ('duplicate', 'Duplicate — ignored'), ('error', 'Processing error')], default='pending', max_length=20)),
                ('processing_notes', models.CharField(blank=True, max_length=200)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hrm.biometricdevice')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_events', to='hrm.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['device', '-occurred_at'], name='hrm_biometr_device__289494_idx'), models.Index(fields=['employee', '-occurred_at'], name='hrm_biometr_employe_10d2c3_idx'), models.Index(fields=['process_status'], name='hrm_biometr_process_8f5869_idx'), models.Index(fields=['device_user_id', 'occurred_at'], name='hrm_biometr_device__543145_idx')],
            },
        ),
        migrations.CreateModel(
            name='BiometricEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_user_id', models.CharField(help_text='Internal ID the device reports for this person.', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='hrm.biometricdevice')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_enrollments', to='hrm.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['device_id', 'employee_id'],
                'indexes': [models.Index(fields=['employee', 'is_active'], name='hrm_biometr_employe_2d77b6_idx')],
                'unique_together': {('device', 'device_user_id')},
            },
        ),
        migrations.AddIndex(
            model_name='biometricdevice',
            index=models.Index(fields=['status'], name='hrm_biometr_status_4551d4_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricdevice',
            index=models.Index(fields=['device_type'], name='hrm_biometr_device__ef5dfd_idx'),
        ),
    ]
