# Generated by Django 5.2.14 on 2026-05-24 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_usermfa_secret_encrypted_alter_usermfa_secret'),
        ('hrm', '0015_biometricdevice_biometricevent_biometricenrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Tenant/MDA this employee belongs to. Source of truth for payroll-run scoping and tenant isolation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='core.organization'),
        ),
    ]
