# Generated by Django 5.2.14 on 2026-05-30 12:17
#
# Adds the dedicated ``hrm.search_employee_pii`` permission used to
# gate :meth:`hrm.models.Employee.find_by_pii_hash` (V5 hardening).
#
# A best-effort data step grants the new perm to Django Groups whose
# names match seeded HR / audit role codes. Tenants without those role
# suffixes get a silent no-op and can grant manually via the admin.

from django.db import migrations


# Role-code suffixes that should receive ``search_employee_pii`` by
# default. Mirrors the role codes seeded by
# ``tenants/management/commands/seed_default_roles.py``.
_PII_SEARCH_ROLE_SUFFIXES = [
    'hr_manager',          # senior HR role
    'internal_auditor',    # Auditor role (read-only PII reach for audit)
    'admin_manager',       # tenant System Admin
]


def forwards_grants(apps, schema_editor):
    """Best-effort grant of ``search_employee_pii`` to seeded HR/audit Groups."""
    Permission = apps.get_model('auth', 'Permission')
    Group = apps.get_model('auth', 'Group')

    try:
        perms = list(Permission.objects.filter(codename='search_employee_pii'))
    except Exception:
        perms = []
    # Custom perm rows are created by Django's post_migrate signal; if
    # not yet present we silently no-op. Operators can grant manually
    # later via the admin.
    if not perms:
        return

    for suffix in _PII_SEARCH_ROLE_SUFFIXES:
        try:
            matching = Group.objects.filter(name__iendswith=suffix)
        except Exception:
            continue
        for group in matching:
            for perm in perms:
                try:
                    group.permissions.add(perm)
                except Exception:
                    continue


def backwards_grants(apps, schema_editor):
    """Best-effort revoke of the grants applied in forwards step."""
    Permission = apps.get_model('auth', 'Permission')
    Group = apps.get_model('auth', 'Group')

    try:
        perms = list(Permission.objects.filter(codename='search_employee_pii'))
    except Exception:
        perms = []
    if not perms:
        return

    for suffix in _PII_SEARCH_ROLE_SUFFIXES:
        try:
            matching = Group.objects.filter(name__iendswith=suffix)
        except Exception:
            continue
        for group in matching:
            for perm in perms:
                try:
                    group.permissions.remove(perm)
                except Exception:
                    continue


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0020_re_encrypt_pii_v2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['employee_number'], 'permissions': (('search_employee_pii', 'Can search employees by PII hash'),)},
        ),
        migrations.RunPython(forwards_grants, backwards_grants),
    ]
