import type { ModuleConfig } from '../_base/types';

export const moduleConfig: ModuleConfig = {
  key: 'debt',
  label: 'Public Debt Management',
  icon: '🏦',
  description: 'Debt instruments, amortisation schedules, coupons, ledgers, service costs and aversion statements.',
  basePath: '/debt',
  entities: [
    {
      key: 'debtInstrument',
      plural: 'instruments',
      label: 'Debt Instruments',
      searchField: 'instrument_number',
      idField: 'id',
      statusField: 'status',
      columns: [
        {
          name: 'instrument_number',
          label: 'Instrument Number',
          type: 'text',
          required: true,
          placeholder: 'e.g. LOAN-2024-001',
        },
        {
          name: 'creditor',
          label: 'Creditor',
          type: 'text',
          required: true,
          placeholder: 'e.g. World Bank',
        },
        {
          name: 'instrument_type',
          label: 'Instrument Type',
          type: 'select',
          options: {
            loan: 'Loan',
            bond: 'Bond / Security',
            treasury_bill: 'Treasury Bill',
            guarantee: 'Guarantee',
            other: 'Other',
          },
        },
        { name: 'principal_amount', label: 'Principal', type: 'decimal', numeric: true },
        { name: 'status', label: 'Status', type: 'select', options: { draft: 'Draft', active: 'Active', closed: 'Closed' } },
      ],
      fields: [
        {
          name: 'instrument_number',
          label: 'Instrument Number',
          type: 'text',
          required: true,
          placeholder: 'e.g. LOAN-2024-001',
        },
        {
          name: 'instrument_type',
          label: 'Instrument Type',
          type: 'select',
          required: true,
          options: {
            loan: 'Loan',
            bond: 'Bond / Security',
            treasury_bill: 'Treasury Bill',
            guarantee: 'Guarantee',
            other: 'Other',
          },
        },
        { name: 'creditor', label: 'Creditor', type: 'text', required: true, placeholder: 'e.g. World Bank' },
        {
          name: 'currency',
          label: 'Currency',
          type: 'integer',
          reference: { module: 'accounting', entity: 'currency' },
        },
        { name: 'principal_amount', label: 'Principal Amount', type: 'decimal', numeric: true, required: true },
        { name: 'interest_rate', label: 'Interest Rate', type: 'decimal', numeric: true },
        { name: 'commitment_fee_rate', label: 'Commitment Fee Rate', type: 'decimal', numeric: true },
        { name: 'start_date', label: 'Start Date', type: 'date', required: true },
        { name: 'maturity_date', label: 'Maturity Date', type: 'date' },
        { name: 'grace_period', label: 'Grace Period (months)', type: 'integer', numeric: true },
        {
          name: 'status',
          label: 'Status',
          type: 'select',
          options: { draft: 'Draft', active: 'Active', closed: 'Closed' },
        },
        { name: 'is_concessional', label: 'Concessional', type: 'boolean' },
        { name: 'outstanding_principal', label: 'Outstanding Principal', type: 'decimal', numeric: true, hideInForm: true },
        { name: 'created_at', label: 'Created At', type: 'datetime', hideInForm: true, readOnly: true, secondary: true },
        { name: 'updated_at', label: 'Updated At', type: 'datetime', hideInForm: true, readOnly: true, secondary: true },
      ],
    },
    {
      key: 'amortisationSchedule',
      plural: 'schedules',
      label: 'Amortisation Schedules',
      searchField: 'coupon_date',
      idField: 'id',
      columns: [
        { name: 'instrument', label: 'Instrument', type: 'integer', reference: { module: 'debt', entity: 'debtInstrument' } },
        { name: 'coupon_date', label: 'Coupon Date', type: 'date' },
        { name: 'principal_amount', label: 'Principal', type: 'decimal', numeric: true },
        { name: 'interest_amount', label: 'Interest', type: 'decimal', numeric: true },
        { name: 'is_released', label: 'Released', type: 'boolean' },
      ],
      fields: [
        {
          name: 'instrument',
          label: 'Instrument',
          type: 'integer',
          required: true,
          reference: { module: 'debt', entity: 'debtInstrument' },
        },
        { name: 'coupon_date', label: 'Coupon Date', type: 'date', required: true },
        { name: 'principal_amount', label: 'Principal Amount', type: 'decimal', numeric: true },
        { name: 'interest_amount', label: 'Interest Amount', type: 'decimal', numeric: true },
        { name: 'commitment_fee', label: 'Commitment Fee', type: 'decimal', numeric: true },
        { name: 'total_amount', label: 'Total Amount', type: 'decimal', numeric: true, hideInForm: true },
        { name: 'is_released', label: 'Released', type: 'boolean' },
      ],
    },
    {
      key: 'amortisationCoupon',
      plural: 'coupons',
      label: 'Amortisation Coupons',
      searchField: 'status',
      idField: 'id',
      statusField: 'status',
      columns: [
        { name: 'schedule', label: 'Schedule', type: 'integer', reference: { module: 'debt', entity: 'amortisationSchedule' } },
        { name: 'principal_amount', label: 'Principal', type: 'decimal', numeric: true },
        { name: 'interest_amount', label: 'Interest', type: 'decimal', numeric: true },
        { name: 'status', label: 'Status', type: 'select', options: { scheduled: 'Scheduled', approved: 'Approved for Payment', paid: 'Paid', defaulted: 'Defaulted', closed: 'Closed' } },
        { name: 'paid_at', label: 'Paid At', type: 'datetime' },
      ],
      fields: [
        {
          name: 'schedule',
          label: 'Schedule',
          type: 'integer',
          required: true,
          reference: { module: 'debt', entity: 'amortisationSchedule' },
        },
        { name: 'principal_amount', label: 'Principal Amount', type: 'decimal', numeric: true },
        { name: 'interest_amount', label: 'Interest Amount', type: 'decimal', numeric: true },
        { name: 'commitment_fee', label: 'Commitment Fee', type: 'decimal', numeric: true },
        { name: 'total_amount', label: 'Total Amount', type: 'decimal', numeric: true, hideInForm: true },
        {
          name: 'status',
          label: 'Status',
          type: 'select',
          options: {
            scheduled: 'Scheduled',
            approved: 'Approved for Payment',
            paid: 'Paid',
            defaulted: 'Defaulted',
            closed: 'Closed',
          },
        },
        { name: 'warrant', label: 'Warrant', type: 'integer', reference: { module: 'budget', entity: 'warrant' } },
        { name: 'paid_at', label: 'Paid At', type: 'datetime', hideInForm: true, readOnly: true },
      ],
    },
    {
      key: 'amortisationLedger',
      plural: 'ledger',
      label: 'Amortisation Ledger',
      searchField: 'description',
      idField: 'id',
      columns: [
        { name: 'coupon', label: 'Coupon', type: 'integer', reference: { module: 'debt', entity: 'amortisationCoupon' } },
        {
          name: 'event',
          label: 'Event',
          type: 'select',
          options: { scheduled: 'Scheduled', approved: 'Approved', paid: 'Paid via Warrant', defaulted: 'Defaulted', closed: 'Closed' },
        },
        { name: 'amount', label: 'Amount', type: 'decimal', numeric: true },
        { name: 'description', label: 'Description', type: 'text' },
        { name: 'recorded_at', label: 'Recorded At', type: 'datetime' },
      ],
      fields: [
        {
          name: 'coupon',
          label: 'Coupon',
          type: 'integer',
          required: true,
          reference: { module: 'debt', entity: 'amortisationCoupon' },
        },
        {
          name: 'event',
          label: 'Event',
          type: 'select',
          required: true,
          options: { scheduled: 'Scheduled', approved: 'Approved', paid: 'Paid via Warrant', defaulted: 'Defaulted', closed: 'Closed' },
        },
        { name: 'amount', label: 'Amount', type: 'decimal', numeric: true },
        { name: 'warrant', label: 'Warrant', type: 'integer', reference: { module: 'budget', entity: 'warrant' } },
        { name: 'description', label: 'Description', type: 'text' },
        { name: 'recorded_by', label: 'Recorded By', type: 'integer', reference: { module: 'hrm', entity: 'employee' } },
        { name: 'recorded_at', label: 'Recorded At', type: 'datetime', hideInForm: true, readOnly: true },
      ],
    },
    {
      key: 'debtServiceCost',
      plural: 'service-costs',
      label: 'Debt Service Costs',
      searchField: 'fiscal_year',
      idField: 'id',
      columns: [
        { name: 'fiscal_year', label: 'Fiscal Year', type: 'integer', numeric: true },
        { name: 'month', label: 'Month', type: 'integer', numeric: true },
        { name: 'instrument', label: 'Instrument', type: 'integer', reference: { module: 'debt', entity: 'debtInstrument' } },
        { name: 'principal_paid', label: 'Principal Paid', type: 'decimal', numeric: true },
        { name: 'interest_paid', label: 'Interest Paid', type: 'decimal', numeric: true },
      ],
      fields: [
        { name: 'fiscal_year', label: 'Fiscal Year', type: 'integer', numeric: true, required: true },
        { name: 'month', label: 'Month', type: 'integer', numeric: true },
        {
          name: 'instrument',
          label: 'Instrument',
          type: 'integer',
          reference: { module: 'debt', entity: 'debtInstrument' },
        },
        { name: 'principal_paid', label: 'Principal Paid', type: 'decimal', numeric: true },
        { name: 'interest_paid', label: 'Interest Paid', type: 'decimal', numeric: true },
        { name: 'fees_paid', label: 'Fees Paid', type: 'decimal', numeric: true },
      ],
    },
    {
      key: 'debtAversionStatement',
      plural: 'statements',
      label: 'Debt Aversion Statements',
      searchField: 'fiscal_year',
      idField: 'id',
      columns: [
        { name: 'fiscal_year', label: 'Fiscal Year', type: 'integer', numeric: true },
        {
          name: 'pillar',
          label: 'Pillar',
          type: 'select',
          options: { domestic: 'Domestic Debt', external: 'External Debt', guarantees: 'Guarantees & Contingent' },
        },
        { name: 'outstanding_balance', label: 'Outstanding Balance', type: 'decimal', numeric: true },
        { name: 'debt_to_gdp', label: 'Debt to GDP', type: 'decimal', numeric: true },
        { name: 'assessment', label: 'Assessment', type: 'longtext' },
      ],
      fields: [
        { name: 'fiscal_year', label: 'Fiscal Year', type: 'integer', numeric: true, required: true },
        {
          name: 'pillar',
          label: 'Pillar',
          type: 'select',
          options: { domestic: 'Domestic Debt', external: 'External Debt', guarantees: 'Guarantees & Contingent' },
        },
        { name: 'outstanding_balance', label: 'Outstanding Balance', type: 'decimal', numeric: true },
        { name: 'gdp', label: 'GDP', type: 'decimal', numeric: true },
        { name: 'revenue', label: 'Revenue', type: 'decimal', numeric: true },
        { name: 'debt_to_gdp', label: 'Debt to GDP', type: 'decimal', numeric: true },
        { name: 'debt_service_to_revenue', label: 'Debt Service to Revenue', type: 'decimal', numeric: true },
        { name: 'assessment', label: 'Assessment', type: 'longtext' },
      ],
    },
  ],
};
