# Generated by Django 5.2.14 on 2026-09-02 22:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0112_journal_balance_guard_case_insensitive"),
        ("budget", "0017_alter_warrant_status"),
        ("hrm", "0021_perm_dedicated_v2_v3_v15_v5"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EstablishmentPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mda_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Free-text MDA when no NCoA segment is linked.",
                        max_length=200,
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("Entry", "Entry Level"),
                            ("Mid", "Mid Level"),
                            ("Senior", "Senior Level"),
                            ("Manager", "Manager"),
                            ("Director", "Director"),
                            ("Executive", "Executive"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "approved_quantity",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total approved posts for this MDA + grade.",
                    ),
                ),
                ("effective_date", models.DateField(default=django.utils.timezone.now)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("comments", models.TextField(blank=True, default="")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mda_admin",
                    models.ForeignKey(
                        blank=True,
                        help_text="NCoA administrative segment (MDA) this post belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.administrativesegment",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["mda_name", "grade"],
            },
        ),
        migrations.CreateModel(
            name="EstablishmentVariance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("filled_quantity", models.PositiveIntegerField(default=0)),
                ("approved_quantity", models.PositiveIntegerField(default=0)),
                (
                    "variance",
                    models.IntegerField(
                        default=0,
                        help_text="filled - approved. Negative = headroom; positive = breach.",
                    ),
                ),
                ("is_breach", models.BooleanField(default=False)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variances",
                        to="personnel_budget.establishmentpost",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["post"],
            },
        ),
        migrations.CreateModel(
            name="PayrollBudgetBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bound_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "remaining_at_binding",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "check_level",
                    models.CharField(
                        default="STRICT",
                        help_text="Copied from the governing BudgetCheckRule at binding time.",
                        max_length=10,
                    ),
                ),
                ("bound_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appropriation_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="budget.appropriation",
                    ),
                ),
                (
                    "bound_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payroll_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_binding",
                        to="hrm.payrollrun",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-bound_at"],
            },
        ),
        migrations.CreateModel(
            name="PersonnelCostForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fiscal_year", models.IntegerField(db_index=True)),
                ("mda_name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "month",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="1-12 for a monthly line; null for the annual total row.",
                        null=True,
                    ),
                ),
                (
                    "projected_payroll",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "approved_appropriation",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "projected_increment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Known increments (anniversary) expected in this period.",
                        max_digits=18,
                    ),
                ),
                (
                    "projected_promotion",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Known promotion-value changes in this period.",
                        max_digits=18,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "appropriation_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="personnel_forecasts",
                        to="budget.appropriation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["fiscal_year", "month"],
            },
        ),
        migrations.AddIndex(
            model_name="establishmentpost",
            index=models.Index(
                fields=["mda_name", "grade"], name="personnel_b_mda_nam_9e0119_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="establishmentpost",
            index=models.Index(fields=["status"], name="personnel_b_status_81300c_idx"),
        ),
        migrations.AddIndex(
            model_name="personnelcostforecast",
            index=models.Index(
                fields=["fiscal_year", "mda_name"],
                name="personnel_b_fiscal__22f89d_idx",
            ),
        ),
    ]
