# Generated by Django 6.0.2 on 2026-03-01 22:49

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=100)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SuperAdmin',
                'verbose_name_plural': 'SuperAdmins',
            },
        ),
        migrations.CreateModel(
            name='SuperAdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='QUOT ERP', max_length=200)),
                ('default_timezone', models.CharField(default='Africa/Lagos', max_length=50)),
                ('default_currency', models.CharField(default='NGN', max_length=10)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=60)),
                ('require_special_chars', models.BooleanField(default=True)),
                ('require_uppercase', models.BooleanField(default=True)),
                ('min_password_length', models.PositiveIntegerField(default=8)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('rate_limit_per_hour', models.PositiveIntegerField(default=1000)),
                ('token_expiry_days', models.PositiveIntegerField(default=1)),
                ('max_login_attempts', models.PositiveIntegerField(default=5)),
            ],
            options={
                'verbose_name': 'SuperAdmin Settings',
                'verbose_name_plural': 'SuperAdmin Settings',
            },
        ),
        migrations.CreateModel(
            name='SuperAdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superadmin', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='superadmin/avatars/')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='superadmin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
