# Generated by Django 4.2.28 on 2026-03-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_audit_fixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content_html',
            field=models.TextField(blank=True),
        ),
    ]
