# Generated by Django 6.0.2 on 2026-03-30 13:53
#
# Removes orphaned / duplicate models from the superadmin app:
#   - SuperAdmin (TenantMixin subclass — table may never have been created)
#   - SubscriptionPlan (duplicate — canonical copy lives in tenants app)
#   - Subscription (orphaned — replaced by tenants.TenantSubscription)
#
# Also migrates:
#   - Commission.subscription FK → tenants.TenantSubscription
#   - Announcement.target_plans M2M → tenants.SubscriptionPlan

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_alter_announcement_content_html'),
        ('tenants', '0007_client_soft_delete'),
    ]

    operations = [
        # Drop FK columns from Subscription before we can delete it
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='tenant',
        ),
        # Point Commission.subscription at the authoritative TenantSubscription
        migrations.AlterField(
            model_name='commission',
            name='subscription',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='commissions',
                to='tenants.tenantsubscription',
            ),
        ),
        # SuperAdmin(TenantMixin) — the table may never have been created by
        # django-tenants, so we use SeparateDatabaseAndState with a safe
        # DROP TABLE IF EXISTS rather than the default DELETE TABLE DDL.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name='SuperAdmin'),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='DROP TABLE IF EXISTS "superadmin_superadmin";',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        # Repoint the M2M pivot to the canonical tenants.SubscriptionPlan
        migrations.AlterField(
            model_name='announcement',
            name='target_plans',
            field=models.ManyToManyField(
                blank=True, related_name='announcements',
                to='tenants.subscriptionplan',
            ),
        ),
        # Duplicate SubscriptionPlan — drop model (table may not exist either)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name='SubscriptionPlan'),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='DROP TABLE IF EXISTS "superadmin_subscriptionplan";',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        # Orphaned Subscription model
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name='Subscription'),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='DROP TABLE IF EXISTS "superadmin_subscription";',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
