# Generated by Django 6.0.2 on 2026-03-30 14:18

import django.core.validators
import superadmin.encryption
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_remove_orphaned_models_fix_commission_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superadminsettings',
            name='smtp_password',
            field=superadmin.encryption.EncryptedCharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tenantsmtpconfig',
            name='smtp_password',
            field=superadmin.encryption.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='webhookconfig',
            name='retry_count',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='webhookconfig',
            name='secret_key',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
