# Generated by Django 5.2.14 on 2026-09-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0011_emailtemplate_hr_category_bigauto"),
    ]

    operations = [
        migrations.AddField(
            model_name="superadminsettings",
            name="transparency_portal_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Master switch for the public, unauthenticated fiscal transparency portal. When off, the public namespace returns 404.",
            ),
        ),
        migrations.CreateModel(
            name="PublishedSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_key", models.CharField(db_index=True, max_length=30)),
                ("title", models.CharField(max_length=255)),
                (
                    "aggregation",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("fiscal_year", models.IntegerField(db_index=True)),
                ("period", models.IntegerField(db_index=True, default=0)),
                (
                    "payload",
                    models.JSONField(help_text="Public snapshot payload (redacted)."),
                ),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "source_publication_id",
                    models.PositiveBigIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Opaque pk of the tenant schema Publication this materializes.",
                    ),
                ),
                ("published_at", models.DateTimeField(db_index=True)),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-published_at"],
                "indexes": [
                    models.Index(
                        fields=["dataset_key", "fiscal_year", "period"],
                        name="pub_snap_lookup_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dataset_key", "fiscal_year", "period", "content_hash"),
                        name="unique_published_snapshot_slot",
                    )
                ],
            },
        ),
    ]
