# Generated by Django 5.2.14 on 2026-09-13 23:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0011_emailtemplate_hr_category_bigauto"),
        ("tenants", "0015_client_slug_and_backfill"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("anthropic", "Anthropic (Claude)"),
                            ("openai", "OpenAI"),
                            ("gemini", "Google (Gemini)"),
                            ("openrouter", "OpenRouter"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=64)),
                (
                    "base_url",
                    models.URLField(
                        help_text="API base. Overridable for a proxy or a regional endpoint."
                    ),
                ),
                ("api_key_encrypted", models.TextField(blank=True, default="")),
                ("available_models", models.JSONField(blank=True, default=list)),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Platform-wide master switch. Off means no tenant may use it.",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "sends_document_images",
                    models.BooleanField(
                        default=True,
                        help_text="Scanned invoices and contracts are transmitted to this provider.",
                    ),
                ),
                (
                    "sends_ledger_amounts",
                    models.BooleanField(
                        default=True,
                        help_text="Transaction amounts and references are transmitted.",
                    ),
                ),
                (
                    "retains_data",
                    models.BooleanField(
                        default=False,
                        help_text="Provider retains submitted content beyond the request.",
                    ),
                ),
                (
                    "is_broker",
                    models.BooleanField(
                        default=False,
                        help_text="Routes to upstream providers rather than serving the model itself, so its data policy is the union of its upstreams. True for OpenRouter.",
                    ),
                ),
                ("data_policy_url", models.URLField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Provider",
                "ordering": ["sort_order", "display_name"],
            },
        ),
        migrations.CreateModel(
            name="AICall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "capability",
                    models.CharField(
                        choices=[
                            ("extraction", "Document extraction (scan to draft)"),
                            ("reconciliation", "Reconciliation matching"),
                            ("analysis", "Report analysis and narrative"),
                            ("classification", "Coding and classification"),
                            ("detection", "Anomaly and duplicate detection"),
                            ("drafting", "Document drafting"),
                        ],
                        max_length=32,
                    ),
                ),
                ("model_id", models.CharField(max_length=128)),
                ("request_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "redacted_field_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Identifiers tokenised before transmission.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("refused", "Refused before sending"),
                            ("capped", "Blocked by cost cap"),
                        ],
                        default="success",
                        max_length=16,
                    ),
                ),
                ("http_status", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("completion_tokens", models.PositiveIntegerField(default=0)),
                (
                    "cost_usd",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=10
                    ),
                ),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("subject", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_calls",
                        to="tenants.client",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calls",
                        to="superadmin.aiprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Call",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "capability", "-created_at"],
                        name="superadmin__tenant__5027ce_idx",
                    ),
                    models.Index(
                        fields=["tenant", "-created_at"],
                        name="superadmin__tenant__b6bf03_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TenantAISetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "capability",
                    models.CharField(
                        choices=[
                            ("extraction", "Document extraction (scan to draft)"),
                            ("reconciliation", "Reconciliation matching"),
                            ("analysis", "Report analysis and narrative"),
                            ("classification", "Coding and classification"),
                            ("detection", "Anomaly and duplicate detection"),
                            ("drafting", "Document drafting"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "model_id",
                    models.CharField(
                        help_text="Model identifier as the provider names it, e.g. claude-opus-5.",
                        max_length=128,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "monthly_cost_cap",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Monthly spend ceiling in USD. 0 disables the cap.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "require_redaction",
                    models.BooleanField(
                        default=True,
                        help_text="Strip bank accounts, BVN/TIN and contact details before transmission. Off should be a documented exception.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenant_settings",
                        to="superadmin.aiprovider",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_settings",
                        to="tenants.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant AI Setting",
                "ordering": ["tenant", "capability"],
                "unique_together": {("tenant", "capability")},
            },
        ),
    ]
