# Generated by Django 5.2.14 on 2026-09-14 00:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0012_aiprovider_aicall_tenantaisetting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aicall",
            name="cost_usd",
            field=models.DecimalField(
                decimal_places=8, default=Decimal("0E-8"), max_digits=12
            ),
        ),
    ]
