# Generated by Django 5.2.14 on 2026-09-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0014_seed_ai_providers"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiprovider",
            name="default_model_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Pre-selected when configuring a new capability. Existing capabilities keep the model they were saved with.",
                max_length=128,
            ),
        ),
    ]
