# Generated by Django 5.2.14 on 2026-09-26 00:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0015_aiprovider_default_model"),
        ("tenants", "0015_client_slug_and_backfill"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentGatewayProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[("remita", "Remita"), ("xpresspay", "Xpresspay")],
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=64)),
                (
                    "base_url",
                    models.URLField(
                        help_text="API base. Overridable for sandbox or a regional endpoint."
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[("sandbox", "Sandbox"), ("production", "Production")],
                        default="sandbox",
                        max_length=16,
                    ),
                ),
                ("api_key_encrypted", models.TextField(blank=True, default="")),
                ("secret_key_encrypted", models.TextField(blank=True, default="")),
                ("webhook_secret_encrypted", models.TextField(blank=True, default="")),
                (
                    "merchant_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                ("supports_disbursement", models.BooleanField(default=False)),
                ("supports_collection", models.BooleanField(default=False)),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Platform-wide master switch. Off means no tenant may use it.",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Payment Gateway Provider",
                "ordering": ["sort_order", "display_name"],
            },
        ),
        migrations.CreateModel(
            name="GatewayTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("disbursement", "Disbursement (payments out)"),
                            ("collection", "Revenue collection (money in)"),
                        ],
                        max_length=16,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=64, unique=True)),
                (
                    "gateway_reference",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                ("currency", models.CharField(default="NGN", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending (created, not yet sent)"),
                            ("sent", "Sent to gateway, awaiting settlement"),
                            ("success", "Settled successfully"),
                            ("failed", "Failed / rejected"),
                            ("refused", "Refused before sending"),
                            ("reversed", "Reversed after settlement"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "request_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("http_status", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("subject", models.JSONField(blank=True, default=dict)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gateway_transactions",
                        to="tenants.client",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="superadmin.paymentgatewayprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gateway Transaction",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "-created_at"],
                        name="superadmin__tenant__d450c2_idx",
                    ),
                    models.Index(
                        fields=["tenant", "direction", "-created_at"],
                        name="superadmin__tenant__fbe5c9_idx",
                    ),
                    models.Index(
                        fields=["status"], name="superadmin__status_1f80a7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TenantGatewaySetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "per_transaction_cap",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Per-transaction ceiling in NGN. 0 disables the cap.",
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenant_settings",
                        to="superadmin.paymentgatewayprovider",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gateway_settings",
                        to="tenants.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Gateway Setting",
                "ordering": ["tenant", "provider"],
                "unique_together": {("tenant", "provider")},
            },
        ),
    ]
