# Generated by Django 6.0.2 on 2026-03-01 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0002_employee_salary_structure_trainingprogram_department'),
        ('service', '0004_fix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='technician',
            old_name='employee_id',
            new_name='employee_code',
        ),
        migrations.AddField(
            model_name='technician',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_profile', to='hrm.employee'),
        ),
        migrations.AddIndex(
            model_name='citizenrequest',
            index=models.Index(fields=['status'], name='service_cit_status_f098a0_idx'),
        ),
        migrations.AddIndex(
            model_name='citizenrequest',
            index=models.Index(fields=['category'], name='service_cit_categor_6bdac3_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceschedule',
            index=models.Index(fields=['is_active'], name='service_mai_is_acti_809398_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceschedule',
            index=models.Index(fields=['frequency'], name='service_mai_frequen_096523_idx'),
        ),
        migrations.AddIndex(
            model_name='servicemetric',
            index=models.Index(fields=['period'], name='service_ser_period_7a004f_idx'),
        ),
        migrations.AddIndex(
            model_name='servicemetric',
            index=models.Index(fields=['period_start'], name='service_ser_period__a9458e_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['status'], name='service_ser_status_b6a52d_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['priority'], name='service_ser_priorit_5ebbe9_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['technician'], name='service_ser_technic_bf1890_idx'),
        ),
        migrations.AddIndex(
            model_name='technician',
            index=models.Index(fields=['is_active'], name='service_tec_is_acti_10fadf_idx'),
        ),
        migrations.AddIndex(
            model_name='technician',
            index=models.Index(fields=['is_available'], name='service_tec_is_avai_3ff25e_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status'], name='service_wor_status_de2bf8_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['priority'], name='service_wor_priorit_e1dc04_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['technician'], name='service_wor_technic_c0a497_idx'),
        ),
    ]
