# Generated by Django 6.0.2 on 2026-03-30 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_add_stock_reservation'),
        ('service', '0005_rename_employee_id_technician_employee_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceasset',
            name='inventory_serial',
            field=models.ForeignKey(blank=True, help_text='Linked inventory serial number', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.itemserialnumber'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='item',
            field=models.ForeignKey(blank=True, help_text='Linked inventory item for stock tracking', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.item'),
        ),
    ]
