# Generated by Django 6.0.2 on 2026-04-05 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0052_add_journal_source_soft_delete'),
        ('service', '0006_serviceasset_inventory_serial_workordermaterial_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='service_expense_account',
            field=models.ForeignKey(blank=True, help_text="Override Service Expense account. Falls back to DEFAULT_GL_ACCOUNTS['SERVICE_EXPENSE'].", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_tickets_as_expense', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='service_revenue_account',
            field=models.ForeignKey(blank=True, help_text="Override Service Revenue account. Falls back to DEFAULT_GL_ACCOUNTS['SERVICE_REVENUE'].", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_tickets_as_revenue', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='service_expense_account',
            field=models.ForeignKey(blank=True, help_text="Override Service Expense account. Falls back to DEFAULT_GL_ACCOUNTS['SERVICE_EXPENSE'].", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders_as_expense', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='service_revenue_account',
            field=models.ForeignKey(blank=True, help_text="Override Service Revenue account. Falls back to DEFAULT_GL_ACCOUNTS['SERVICE_REVENUE'].", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders_as_revenue', to='accounting.account'),
        ),
    ]
