# Generated by Django 6.0.2 on 2026-02-13 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='max_stock',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='item',
            name='min_stock',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='item',
            name='reorder_point',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Quantity at which reorder is triggered', max_digits=12),
        ),
        migrations.AddField(
            model_name='item',
            name='reorder_quantity',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Standard reorder quantity', max_digits=12),
        ),
        migrations.AddField(
            model_name='item',
            name='valuation_method',
            field=models.CharField(choices=[('WA', 'Weighted Average'), ('FIFO', 'First In First Out'), ('LIFO', 'Last In First Out')], default='WA', max_length=10),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='cost_method',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='to_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_central',
            field=models.BooleanField(default=False, help_text='Mark as central warehouse for transfers'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJ', 'Adjustment'), ('TRF', 'Transfer')], max_length=3),
        ),
        migrations.CreateModel(
            name='ItemBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50)),
                ('receipt_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('remaining_quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=19)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
            options={
                'unique_together': {('item', 'batch_number')},
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='For FIFO/LIFO tracking', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.itembatch'),
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.itemcategory')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.itemcategory'),
        ),
        migrations.CreateModel(
            name='ReorderAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.DecimalField(decimal_places=4, max_digits=15)),
                ('reorder_point', models.DecimalField(decimal_places=4, max_digits=15)),
                ('suggested_quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reconciliation_number', models.CharField(max_length=50, unique=True)),
                ('reconciliation_type', models.CharField(choices=[('Cycle Count', 'Cycle Count'), ('Full Audit', 'Full Audit'), ('Spot Check', 'Spot Check')], max_length=20)),
                ('reconciliation_date', models.DateField()),
                ('status', models.CharField(default='Draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockReconciliationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('physical_quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('variance_quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('variance_value', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('reason', models.TextField(blank=True)),
                ('is_adjusted', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item')),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockreconciliation')),
            ],
        ),
        migrations.CreateModel(
            name='ItemStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('reserved_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
            options={
                'unique_together': {('item', 'warehouse')},
            },
        ),
    ]
