# Generated by Django 6.0.2 on 2026-02-16 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_product_type_category'),
        ('inventory', '0002_fix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expense_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_items', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='item',
            name='inventory_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='accounting.account'),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.productcategory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.productcategory'),
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('stock', 'Stock'), ('non_stock', 'Non-Stock'), ('service', 'Service'), ('spares', 'Spares')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('asset_account', models.ForeignKey(blank=True, help_text='Asset account for spares/equipment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_type_asset_accounts', to='accounting.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('expense_account', models.ForeignKey(blank=True, help_text='Expense/cost account for goods sold', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_type_expense_accounts', to='accounting.account')),
                ('inventory_account', models.ForeignKey(blank=True, help_text='Inventory account for stock items', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_type_inventory_accounts', to='accounting.account')),
                ('revenue_account', models.ForeignKey(blank=True, help_text='Revenue account for sales', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_type_revenue_accounts', to='accounting.account')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='productcategory',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='inventory.producttype'),
        ),
        migrations.AddField(
            model_name='item',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.producttype'),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('name', 'product_type')},
        ),
    ]
