# Generated by Django 6.0.2 on 2026-02-17 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_fix_account_code_validation'),
        ('inventory', '0003_product_type_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='gl_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='accounting.journalheader'),
        ),
    ]
