# Generated by Django 6.0.2 on 2026-03-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_batchexpiryalert_itemserialnumber_alter_item_name_and_more'),
        ('sales', '0005_customer_positive_credit_limit'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='itembatch',
            index=models.Index(fields=['expiry_date'], name='inventory_i_expiry__fc6190_idx'),
        ),
        # migrations.AddIndex(
        #     model_name='itemserialnumber',
        #     index=models.Index(fields=['status'], name='inventory_i_status_9bd1e7_idx'),
        # ),
    ]
