# Generated by Django 6.0.2 on 2026-03-01 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_itembatch_inventory_i_expiry__fc6190_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'permissions': [('approve_stockmovement', 'Can approve stock movements')]},
        ),
    ]
