# Generated by Django 6.0.2 on 2026-03-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_stockmovement_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='selling_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
    ]
