# Generated by Django 4.2.28 on 2026-03-18 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0009_customer_credit_check_enabled_customer_credit_status_and_more'),
        ('inventory', '0009_batchexpiryalert_itemserialnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='valuation_method',
            field=models.CharField(choices=[('FIFO', 'FIFO'), ('WA', 'Weighted Average'), ('LIFO', 'LIFO')], default='WA', max_length=10),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('fulfilled_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Fulfilled', 'Fulfilled'), ('Partially_Fulfilled', 'Partially Fulfilled'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('reserved_date', models.DateField(auto_now_add=True)),
                ('expires_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.item')),
                ('sales_order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='sales.salesorderline')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-reserved_date'],
            },
        ),
    ]
