# Generated by Django 4.2.28 on 2026-03-24 20:12

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0038_baddebtwriteoff_financialratio_and_more'),
        ('inventory', '0012_phase0_fix_missing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchexpiryalert',
            name='alert_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='max_stock',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='item',
            name='min_stock',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='item',
            name='reorder_point',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='item',
            name='reorder_quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='item',
            name='total_quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='item',
            name='total_value',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='itembatch',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='itembatch',
            name='remaining_quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='itembatch',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='itemstock',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='itemstock',
            name='reserved_quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='clearing_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producttype_clearing_account_set', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='reorderalert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reorderalert',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='stockreconciliationline',
            name='is_adjusted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stockreconciliationline',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='stockreconciliationline',
            name='reconciliation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='inventory.stockreconciliation'),
        ),
        migrations.AddConstraint(
            model_name='reorderalert',
            constraint=models.UniqueConstraint(condition=models.Q(('is_sent', False)), fields=('item', 'warehouse'), name='unique_pending_reorder_alert'),
        ),
    ]
