# Generated by Django 4.2.28 on 2026-03-26 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_alter_billofmaterials_is_active_and_more'),
        ('inventory', '0013_alter_batchexpiryalert_alert_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='production_bom',
            field=models.ForeignKey(blank=True, help_text='Link to Bill of Materials for production', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_items', to='production.billofmaterials'),
        ),
    ]
