# Generated by Django 4.2.28 on 2026-03-26 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_add_production_bom_to_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('reference_type', models.CharField(max_length=50)),
                ('reference_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Reserved', 'Reserved'), ('Allocated', 'Allocated'), ('Released', 'Released'), ('Fulfilled', 'Fulfilled')], default='Reserved', max_length=20)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('item_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='inventory.itemstock')),
            ],
            options={
                'indexes': [models.Index(fields=['reference_type', 'reference_id'], name='inventory_s_referen_912c56_idx')],
            },
        ),
    ]
