# Generated by Django 6.0.2 on 2026-03-31 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_add_stock_reservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='itembatch',
            options={'verbose_name': 'Product Batch', 'verbose_name_plural': 'Product Batches'},
        ),
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='itemserialnumber',
            options={'verbose_name': 'Product Serial Number', 'verbose_name_plural': 'Product Serial Numbers'},
        ),
        migrations.AlterModelOptions(
            name='itemstock',
            options={'verbose_name': 'Product Stock', 'verbose_name_plural': 'Product Stock'},
        ),
        migrations.AlterUniqueTogether(
            name='itembatch',
            unique_together={('item', 'batch_number')},
        ),
    ]
