# Generated by Django 4.2.28 on 2026-04-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_item_options_alter_itembatch_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='shelf_life_days',
            field=models.PositiveIntegerField(blank=True, help_text='Expected shelf life in days. Used to auto-suggest expiry date on batch receipt.', null=True),
        ),
    ]
