# Generated by Django 4.2.28 on 2026-04-04 00:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_item_standard_price_cost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cost_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Current computed cost price. Updated after each GRN based on the valuation method.', max_digits=19),
        ),
        migrations.AlterField(
            model_name='item',
            name='standard_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='User-defined reference cost set at product creation. Used as cost price for Standard valuation and as an initial baseline for other methods.', max_digits=19),
        ),
    ]
