# Generated by Django 4.2.28 on 2026-04-04 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0051_add_tax_gl_and_wht_fields'),
        ('inventory', '0020_goods_in_transit_transfer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='goods_in_transit_account',
            field=models.ForeignKey(blank=True, help_text='Clearing GL account used as intermediary during inter-warehouse stock transfers. DR on dispatch, CR on receive. Balance = goods currently in transit.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producttype_git_account_set', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='transfer_status',
            field=models.CharField(blank=True, choices=[('In Transit', 'In Transit'), ('Received', 'Received')], default='', help_text='Lifecycle stage for TRF-type movements only. In Transit = dispatched (Warehouse A debited, GIT credited). Received = Warehouse B has posted GRN (Inventory B debited, GIT cleared).', max_length=20),
        ),
    ]
