# Generated by Django 6.0.2 on 2026-04-05 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_producttype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorysettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
