# Generated by Django 4.2.28 on 2026-04-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_add_unit_of_measure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='production_bom',
        ),
        migrations.RemoveField(
            model_name='itemserialnumber',
            name='sales_order_line',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='sales_order_line',
        ),
        migrations.AddField(
            model_name='itemserialnumber',
            name='issue_reference',
            field=models.CharField(blank=True, default='', help_text='Issue/distribution reference number', max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='requisition_reference',
            field=models.CharField(blank=True, default='', help_text='Purchase requisition or issue reference', max_length=100),
        ),
    ]
