"""
cash_planning — Cash Planning & Forecasting (G9 / FreeBalance GTCM completion).

FUTURE_MODULES §5.9: ``TreasuryForecast``, ``CashFlowForecast`` and
``CashFlowEntry`` exist but are populated manually. The real signal — open
commitments, contract year plans, payroll obligations, debt service — is
already in the database and unused.  This module turns those dormant models
into a working engine.

Scope:
  * CashPlan            — annual plan by month, by fund, by MDA.
  * Forecast engine (services.forecast_engine) — driven off live data:
    open ProcurementBudgetLink commitments, ContractYearPlan schedules,
    payroll runs, AmortisationSchedule (from ``debt``), historical revenue
    seasonality.
  * CashPosition        — daily projected TSA balance with a configurable
    warning floor.
  * WarrantRecommendation — proposed release schedule feeding the existing
    Warrant process rather than replacing it.
  * Variance            — planned vs actual inflow and outflow.
"""
from django.db import models
from django.utils import timezone

from core.models import AuditBaseModel


class CashPlan(AuditBaseModel):
    """Annual cash plan by month, by fund, by MDA."""

    PLAN_TYPE_CHOICES = [
        ('annual', 'Annual'),
        ('quarterly', 'Quarterly'),
        ('monthly', 'Monthly'),
    ]

    fiscal_year = models.IntegerField(db_index=True)
    month = models.PositiveIntegerField(null=True, blank=True)
    plan_type = models.CharField(max_length=20, choices=PLAN_TYPE_CHOICES, default='annual')

    fund = models.ForeignKey(
        'accounting.Fund', on_delete=models.PROTECT, null=True, blank=True,
        related_name='+',
    )
    mda_name = models.CharField(max_length=200, blank=True, default='')

    planned_inflow = models.DecimalField(max_digits=18, decimal_places=2, default=0)
    planned_outflow = models.DecimalField(max_digits=18, decimal_places=2, default=0)
    notes = models.TextField(blank=True, default='')

    class Meta:
        ordering = ['fiscal_year', 'month']

    @property
    def net_planned(self):
        return self.planned_inflow - self.planned_outflow


class CashForecastLine(AuditBaseModel):
    """A single forecast line generated by the engine (or entered manually)."""

    SOURCE_CHOICES = [
        ('commitment', 'Open Procurement Commitment'),
        ('contract', 'Contract Year Plan'),
        ('payroll', 'Payroll Obligation'),
        ('debt', 'Debt Service'),
        ('revenue', 'Revenue Seasonality'),
        ('manual', 'Manual Entry'),
    ]

    FLOW_CHOICES = [
        ('inflow', 'Inflow'),
        ('outflow', 'Outflow'),
    ]

    cash_plan = models.ForeignKey(
        CashPlan, on_delete=models.CASCADE, related_name='lines',
    )
    source = models.CharField(max_length=20, choices=SOURCE_CHOICES, default='manual')
    flow = models.CharField(max_length=10, choices=FLOW_CHOICES)
    amount = models.DecimalField(max_digits=18, decimal_places=2, default=0)
    due_date = models.DateField(default=timezone.now)
    description = models.TextField(blank=True, default='')
    source_ref = models.CharField(
        max_length=100, blank=True, default='',
        help_text='Reference to the originating record (PO / contract / run id).',
    )

    class Meta:
        ordering = ['due_date']


class CashPosition(AuditBaseModel):
    """Daily projected TSA balance with a configurable warning floor."""

    position_date = models.DateField(db_index=True)
    opening_balance = models.DecimalField(max_digits=18, decimal_places=2, default=0)
    projected_inflow = models.DecimalField(max_digits=18, decimal_places=2, default=0)
    projected_outflow = models.DecimalField(max_digits=18, decimal_places=2, default=0)
    closing_balance = models.DecimalField(max_digits=18, decimal_places=2, default=0)
    warning_floor = models.DecimalField(
        max_digits=18, decimal_places=2, default=0,
        help_text='Configurable floor below which the position flags a warning.',
    )
    is_below_floor = models.BooleanField(default=False)
    notes = models.TextField(blank=True, default='')

    class Meta:
        ordering = ['position_date']
        indexes = [models.Index(fields=['position_date'])]


class WarrantRecommendation(AuditBaseModel):
    """Proposed cash release schedule feeding the existing Warrant process."""

    STATUS_CHOICES = [
        ('proposed', 'Proposed'),
        ('accepted', 'Accepted'),
        ('converted', 'Converted to Warrant'),
        ('rejected', 'Rejected'),
    ]

    recommendation_date = models.DateField(default=timezone.now)
    mda_name = models.CharField(max_length=200, blank=True, default='')
    appropriation = models.ForeignKey(
        'budget.Appropriation', on_delete=models.PROTECT, null=True, blank=True,
        related_name='+',
    )
    fund = models.ForeignKey(
        'accounting.Fund', on_delete=models.PROTECT, null=True, blank=True,
        related_name='+',
    )
    proposed_amount = models.DecimalField(max_digits=18, decimal_places=2, default=0)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='proposed')
    rationale = models.TextField(blank=True, default='')
    warrant = models.ForeignKey(
        'budget.Warrant', on_delete=models.SET_NULL, null=True, blank=True,
        related_name='+',
        help_text='Set when the recommendation is converted to a Warrant.',
    )

    class Meta:
        ordering = ['recommendation_date']


class CashPlanVariance(AuditBaseModel):
    """Planned vs actual inflow and outflow for a period."""

    fiscal_year = models.IntegerField(db_index=True)
    month = models.PositiveIntegerField(null=True, blank=True)
    mda_name = models.CharField(max_length=200, blank=True, default='')
    planned_inflow = models.DecimalField(max_digits=18, decimal_places=2, default=0)
    actual_inflow = models.DecimalField(max_digits=18, decimal_places=2, default=0)
    planned_outflow = models.DecimalField(max_digits=18, decimal_places=2, default=0)
    actual_outflow = models.DecimalField(max_digits=18, decimal_places=2, default=0)

    class Meta:
        ordering = ['fiscal_year', 'month']
