import type { ModuleConfig } from '../_base/types';

export const moduleConfig: ModuleConfig = {
  key: 'personnel_budget',
  label: 'Establishment & Personnel Cost',
  icon: '👥',
  description:
    'Establishment posts, establishment variance, personnel cost forecast and payroll budget binding.',
  basePath: '/personnel-budget',
  entities: [
    {
      key: 'establishmentPost',
      plural: 'establishment-posts',
      label: 'Establishment Post',
      searchField: 'mda_name',
      statusField: 'status',
      columns: [
        { name: 'mda_name', label: 'MDA Name', type: 'text' },
        { name: 'grade', label: 'Grade', type: 'text' },
        { name: 'approved_quantity', label: 'Approved Qty', type: 'integer', numeric: true },
        { name: 'status', label: 'Status', type: 'select', options: { draft: 'Draft', submitted: 'Submitted', approved: 'Approved', rejected: 'Rejected' } },
        { name: 'effective_date', label: 'Effective Date', type: 'date' },
      ],
      fields: [
        { name: 'mda_admin', label: 'MDA (NCoA)', type: 'integer', required: false, reference: { module: 'accounting', entity: 'administrativeSegments' } },
        { name: 'mda_name', label: 'MDA Name', type: 'text', required: true },
        { name: 'mda_display', label: 'MDA Display', type: 'text', readOnly: true, hideInForm: true },
        { name: 'grade', label: 'Grade', type: 'select', required: true, options: { Entry: 'Entry Level', Mid: 'Mid Level', Senior: 'Senior Level', Manager: 'Manager', Director: 'Director', Executive: 'Executive' } },
        { name: 'approved_quantity', label: 'Approved Quantity', type: 'integer', required: true, numeric: true },
        { name: 'effective_date', label: 'Effective Date', type: 'date', required: true },
        { name: 'expiry_date', label: 'Expiry Date', type: 'date', required: false },
        { name: 'status', label: 'Status', type: 'select', required: true, options: { draft: 'Draft', submitted: 'Submitted', approved: 'Approved', rejected: 'Rejected' } },
        { name: 'approved_by', label: 'Approved By', type: 'integer', readOnly: true, hideInForm: true },
        { name: 'approved_at', label: 'Approved At', type: 'datetime', readOnly: true, hideInForm: true },
        { name: 'comments', label: 'Comments', type: 'longtext', required: false },
        { name: 'filled_quantity', label: 'Filled Quantity', type: 'integer', readOnly: true, hideInForm: true, numeric: true },
        { name: 'created_at', label: 'Created At', type: 'datetime', readOnly: true, hideInForm: true },
        { name: 'updated_at', label: 'Updated At', type: 'datetime', readOnly: true, hideInForm: true },
      ],
    },
    {
      key: 'establishmentVariance',
      plural: 'variances',
      label: 'Establishment Variance',
      searchField: 'post_mda',
      columns: [
        { name: 'post_grade', label: 'Grade', type: 'text' },
        { name: 'post_mda', label: 'MDA', type: 'text' },
        { name: 'filled_quantity', label: 'Filled', type: 'integer', numeric: true },
        { name: 'approved_quantity', label: 'Approved', type: 'integer', numeric: true },
        { name: 'variance', label: 'Variance', type: 'integer', numeric: true },
        { name: 'is_breach', label: 'Breach', type: 'boolean' },
      ],
      fields: [
        { name: 'post', label: 'Post', type: 'integer', required: true, reference: { module: 'personnel_budget', entity: 'establishmentPosts' } },
        { name: 'post_grade', label: 'Grade', type: 'text', readOnly: true, hideInForm: true },
        { name: 'post_mda', label: 'MDA', type: 'text', readOnly: true, hideInForm: true },
        { name: 'filled_quantity', label: 'Filled Quantity', type: 'integer', required: true, numeric: true },
        { name: 'approved_quantity', label: 'Approved Quantity', type: 'integer', required: true, numeric: true },
        { name: 'variance', label: 'Variance', type: 'integer', readOnly: true, numeric: true },
        { name: 'is_breach', label: 'Is Breach', type: 'boolean', readOnly: true, hideInForm: true },
        { name: 'utilisation_pct', label: 'Utilisation %', type: 'number', readOnly: true, hideInForm: true, numeric: true },
        { name: 'computed_at', label: 'Computed At', type: 'datetime', readOnly: true, hideInForm: true },
      ],
    },
    {
      key: 'personnelCostForecast',
      plural: 'forecasts',
      label: 'Personnel Cost Forecast',
      searchField: 'mda_name',
      columns: [
        { name: 'fiscal_year', label: 'Year', type: 'integer', numeric: true },
        { name: 'mda_name', label: 'MDA', type: 'text' },
        { name: 'projected_payroll', label: 'Projected Payroll', type: 'decimal', numeric: true },
        { name: 'approved_appropriation', label: 'Approved', type: 'decimal', numeric: true },
        { name: 'total_projected', label: 'Total Projected', type: 'decimal', numeric: true },
      ],
      fields: [
        { name: 'fiscal_year', label: 'Fiscal Year', type: 'integer', required: true, numeric: true },
        { name: 'mda_name', label: 'MDA Name', type: 'text', required: false },
        { name: 'appropriation_line', label: 'Appropriation Line', type: 'integer', required: false, reference: { module: 'budget', entity: 'appropriations' } },
        { name: 'month', label: 'Month (1-12)', type: 'integer', required: false, numeric: true },
        { name: 'projected_payroll', label: 'Projected Payroll', type: 'decimal', required: true, numeric: true },
        { name: 'approved_appropriation', label: 'Approved Appropriation', type: 'decimal', required: true, numeric: true },
        { name: 'projected_increment', label: 'Projected Increment', type: 'decimal', required: true, numeric: true },
        { name: 'projected_promotion', label: 'Projected Promotion', type: 'decimal', required: true, numeric: true },
        { name: 'total_projected', label: 'Total Projected', type: 'decimal', readOnly: true, hideInForm: true, numeric: true },
        { name: 'over_appropriation', label: 'Over Appropriation', type: 'boolean', readOnly: true, hideInForm: true },
        { name: 'notes', label: 'Notes', type: 'longtext', required: false },
        { name: 'created_at', label: 'Created At', type: 'datetime', readOnly: true, hideInForm: true },
        { name: 'updated_at', label: 'Updated At', type: 'datetime', readOnly: true, hideInForm: true },
      ],
    },
    {
      key: 'payrollBudgetBinding',
      plural: 'payroll-bindings',
      label: 'Payroll Budget Binding',
      searchField: 'payroll_run_ref',
      columns: [
        { name: 'payroll_run_ref', label: 'Payroll Run', type: 'text' },
        { name: 'appropriation_line', label: 'Appropriation Line', type: 'integer', numeric: true },
        { name: 'bound_amount', label: 'Bound Amount', type: 'decimal', numeric: true },
        { name: 'remaining_at_binding', label: 'Remaining', type: 'decimal', numeric: true },
        { name: 'check_level', label: 'Check Level', type: 'text' },
      ],
      fields: [
        { name: 'payroll_run', label: 'Payroll Run', type: 'integer', required: true, reference: { module: 'hrm', entity: 'payrollRuns' } },
        { name: 'payroll_run_ref', label: 'Payroll Run Ref', type: 'text', readOnly: true, hideInForm: true },
        { name: 'appropriation_line', label: 'Appropriation Line', type: 'integer', required: true, reference: { module: 'budget', entity: 'appropriations' } },
        { name: 'bound_amount', label: 'Bound Amount', type: 'decimal', required: true, numeric: true },
        { name: 'remaining_at_binding', label: 'Remaining at Binding', type: 'decimal', readOnly: true, hideInForm: true, numeric: true },
        { name: 'check_level', label: 'Check Level', type: 'text', readOnly: true, hideInForm: true },
        { name: 'bound_by', label: 'Bound By', type: 'integer', readOnly: true, hideInForm: true },
        { name: 'bound_at', label: 'Bound At', type: 'datetime', readOnly: true, hideInForm: true },
      ],
    },
  ],
};
