import type { ModuleConfig } from '../_base/types';

export const moduleConfig: ModuleConfig = {
  key: 'disclosure',
  label: 'Asset Declaration',
  icon: '📄',
  description: 'Declaration cycles, asset declarations, declaration items and disclosure access logs.',
  basePath: '/disclosure',
  entities: [
    {
      key: 'declarationCycle',
      plural: 'cycles',
      label: 'Declaration Cycle',
      searchField: 'name',
      idField: 'id',
      columns: [
        { name: 'name', label: 'Name', type: 'text' },
        { name: 'fiscal_year', label: 'Fiscal Year', type: 'integer', numeric: true },
        { name: 'opens_at', label: 'Opens At', type: 'datetime' },
        { name: 'closes_at', label: 'Closes At', type: 'datetime' },
        { name: 'is_open', label: 'Open', type: 'boolean' },
      ],
      fields: [
        { name: 'name', label: 'Name', type: 'text', required: true },
        { name: 'fiscal_year', label: 'Fiscal Year', type: 'integer', required: true, numeric: true },
        { name: 'opens_at', label: 'Opens At', type: 'datetime' },
        { name: 'closes_at', label: 'Closes At', type: 'datetime' },
        { name: 'is_open', label: 'Open', type: 'boolean' },
      ],
    },
    {
      key: 'assetDeclaration',
      plural: 'declarations',
      label: 'Asset Declaration',
      searchField: 'employee_name',
      idField: 'id',
      statusField: 'status',
      columns: [
        { name: 'employee_name', label: 'Employee', type: 'text' },
        { name: 'status', label: 'Status', type: 'text' },
        { name: 'cycle', label: 'Cycle', type: 'integer', reference: { module: 'disclosure', entity: 'declarationCycle' } },
        { name: 'submitted_at', label: 'Submitted At', type: 'datetime' },
        { name: 'acknowledged_at', label: 'Acknowledged At', type: 'datetime', secondary: true },
      ],
      fields: [
        { name: 'cycle', label: 'Cycle', type: 'integer', required: true, reference: { module: 'disclosure', entity: 'declarationCycle' } },
        { name: 'employee', label: 'Employee', type: 'integer', required: true, reference: { module: 'hrm', entity: 'employee' } },
        { name: 'employee_name', label: 'Employee', type: 'text', readOnly: true, hideInForm: true },
        { name: 'status', label: 'Status', type: 'select', required: true, options: { draft: 'Draft', submitted: 'Submitted', acknowledged: 'Acknowledged', queried: 'Queried', non_compliant: 'Non-Compliant' } },
        { name: 'submitted_at', label: 'Submitted At', type: 'datetime', readOnly: true, hideInForm: true },
        { name: 'acknowledged_at', label: 'Acknowledged At', type: 'datetime', readOnly: true, hideInForm: true },
        { name: 'acknowledged_by', label: 'Acknowledged By', type: 'object', readOnly: true, hideInForm: true },
        { name: 'items', label: 'Items', type: 'object', readOnly: true, hideInForm: true },
        { name: 'created_at', label: 'Created At', type: 'datetime', readOnly: true, hideInForm: true },
        { name: 'updated_at', label: 'Updated At', type: 'datetime', readOnly: true, hideInForm: true },
      ],
    },
    {
      key: 'declarationItem',
      plural: 'items',
      label: 'Declaration Item',
      searchField: 'description',
      idField: 'id',
      columns: [
        { name: 'asset_type', label: 'Asset Type', type: 'text' },
        { name: 'description', label: 'Description', type: 'text' },
        { name: 'declaration', label: 'Declaration', type: 'integer', reference: { module: 'disclosure', entity: 'assetDeclaration' } },
        { name: 'value_encrypted', label: 'Encrypted Value', type: 'text', readOnly: true, hideInForm: true, secondary: true },
        { name: 'value_ciphertext', label: 'Value Ciphertext', type: 'text', readOnly: true, hideInForm: true, secondary: true },
      ],
      fields: [
        { name: 'declaration', label: 'Declaration', type: 'integer', required: true, reference: { module: 'disclosure', entity: 'assetDeclaration' } },
        { name: 'asset_type', label: 'Asset Type', type: 'select', required: true, options: { cash: 'Cash & Bank Balances', real_estate: 'Real Estate', vehicle: 'Vehicles', investment: 'Investments', business: 'Business Interests', other: 'Other' } },
        { name: 'description', label: 'Description', type: 'longtext' },
        { name: 'value_encrypted', label: 'Encrypted Value', type: 'text', readOnly: true, hideInForm: true },
        { name: 'value_ciphertext', label: 'Value Ciphertext', type: 'text', readOnly: true, hideInForm: true },
      ],
    },
    {
      key: 'disclosureAccessLog',
      plural: 'access-log',
      label: 'Disclosure Access Log',
      searchField: 'action',
      idField: 'id',
      columns: [
        { name: 'accessed_by', label: 'Accessed By', type: 'text' },
        { name: 'action', label: 'Action', type: 'text' },
        { name: 'accessed_at', label: 'Accessed At', type: 'datetime' },
        { name: 'ip_address', label: 'IP Address', type: 'text', secondary: true },
        { name: 'declaration', label: 'Declaration', type: 'integer', reference: { module: 'disclosure', entity: 'assetDeclaration' }, secondary: true },
      ],
      fields: [
        { name: 'declaration', label: 'Declaration', type: 'integer', required: true, reference: { module: 'disclosure', entity: 'assetDeclaration' } },
        { name: 'accessed_by', label: 'Accessed By', type: 'object', readOnly: true, hideInForm: true },
        { name: 'accessed_at', label: 'Accessed At', type: 'datetime', readOnly: true, hideInForm: true },
        { name: 'action', label: 'Action', type: 'text' },
        { name: 'ip_address', label: 'IP Address', type: 'text' },
      ],
    },
  ],
};
