# Generated by Django 5.2.14 on 2026-09-02 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0112_journal_balance_guard_case_insensitive"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("dataset_key", models.CharField(max_length=30)),
                ("fiscal_year", models.IntegerField(blank=True, null=True)),
                ("period", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("published", "Published"),
                            ("retracted", "Retracted"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("published_url", models.URLField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source snapshot; never live tables.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.reportsnapshot",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="DataExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("dataset_key", models.CharField(max_length=30)),
                (
                    "format",
                    models.CharField(
                        choices=[("csv", "CSV"), ("json", "JSON")],
                        default="csv",
                        max_length=10,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="transparency/exports/%Y/"
                    ),
                ),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="transparency.publication",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PublicationPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dataset",
                    models.CharField(
                        choices=[
                            ("enacted_budget", "Enacted Budget"),
                            ("budget_execution", "Budget Execution"),
                            ("contract_awards", "Contract Awards"),
                            ("payments", "Payments Above Threshold"),
                            ("revenue_performance", "Revenue Performance"),
                            ("citizen_budget", "Citizen Budget Summary"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("aggregation", models.CharField(default="MDA level", max_length=100)),
                (
                    "lag_days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Publication lag in days after period close.",
                    ),
                ),
                (
                    "min_amount_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Only transactions at/above this amount are published.",
                        max_digits=18,
                    ),
                ),
                (
                    "requires_snapshot",
                    models.BooleanField(
                        default=True,
                        help_text="Never serve live tables; publish only from ReportSnapshot rows.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("superseded", "Superseded"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "approved_by",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["dataset"],
            },
        ),
        migrations.AddField(
            model_name="publication",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="publications",
                to="transparency.publicationpolicy",
            ),
        ),
        migrations.CreateModel(
            name="RedactionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "field_name",
                    models.CharField(
                        choices=[
                            ("employee_name", "Employee Name"),
                            ("employee_number", "Employee Number"),
                            ("vendor_name", "Vendor Name"),
                            ("vendor_bvn", "Vendor BVN"),
                            ("vendor_tin", "Vendor TIN"),
                            ("phone", "Phone Number"),
                            ("email", "Email Address"),
                            ("address", "Physical Address"),
                            ("bank_account", "Bank Account Number"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "pattern",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional regex identifying the sensitive value.",
                        max_length=200,
                    ),
                ),
                (
                    "replacement",
                    models.CharField(
                        default="***",
                        help_text="Replacement text applied at export.",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["field_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="publicationpolicy",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "approved")),
                fields=("dataset",),
                name="unique_approved_policy_per_dataset",
            ),
        ),
    ]
