# Generated by Django 6.0.2 on 2026-03-01 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_batchexpiryalert_itemserialnumber_alter_item_name_and_more'),
        ('procurement', '0012_goodsreceivednote_notes_goodsreceivednoteline_notes_and_more'),
        ('production', '0001_initial'),
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercomplaint',
            name='COMPLAINT_NUMBER',
        ),
        migrations.RemoveField(
            model_name='nonconformance',
            name='NCR_NUMBER',
        ),
        migrations.AddField(
            model_name='nonconformance',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of source document', null=True),
        ),
        migrations.AddField(
            model_name='nonconformance',
            name='source_type',
            field=models.CharField(blank=True, help_text='Procurement, Production, Sales, Inventory', max_length=50),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='goods_received_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_inspections', to='procurement.goodsreceivednote'),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_inspections', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_inspections', to='production.productionorder'),
        ),
    ]
