# Generated by Django 6.0.2 on 2026-03-01 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_remove_customercomplaint_complaint_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qualityinspection',
            options={'permissions': [('approve_qualityinspection', 'Can approve quality inspections')]},
        ),
    ]
