# Generated by Django 6.0.2 on 2026-03-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0003_alter_qualityinspection_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualityinspection',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Passed', 'Passed'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
