# Generated by Django 4.2.28 on 2026-03-18 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0010_alter_item_valuation_method_reservation'),
        ('quality', '0004_add_completed_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('trigger_event', models.CharField(choices=[('GRN_Created', 'On GRN Creation'), ('Production_Started', 'On Production Start'), ('Production_Completed', 'On Production Completion'), ('Sales_Dispatch', 'On Sales Dispatch'), ('Manual', 'Manual Trigger Only')], max_length=30)),
                ('inspection_type', models.CharField(choices=[('Incoming', 'Incoming Inspection'), ('In-Process', 'In-Process Inspection'), ('Final', 'Final Inspection'), ('Pre-Dispatch', 'Pre-Dispatch Inspection')], max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('auto_create', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('item_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.itemcategory')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.producttype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QA Configuration',
                'verbose_name_plural': 'QA Configurations',
            },
        ),
    ]
