# Generated by Django 4.2.28 on 2026-03-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0005_qaconfiguration'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='nonconformance',
            index=models.Index(fields=['status'], name='quality_non_status_a2bb7d_idx'),
        ),
        migrations.AddIndex(
            model_name='nonconformance',
            index=models.Index(fields=['severity'], name='quality_non_severit_2f6ff8_idx'),
        ),
        migrations.AddIndex(
            model_name='nonconformance',
            index=models.Index(fields=['assigned_to'], name='quality_non_assigne_098230_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityinspection',
            index=models.Index(fields=['status'], name='quality_qua_status_fc4c11_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityinspection',
            index=models.Index(fields=['inspection_type'], name='quality_qua_inspect_7ab377_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityinspection',
            index=models.Index(fields=['inspection_date'], name='quality_qua_inspect_e0da1e_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityinspection',
            index=models.Index(fields=['inspector'], name='quality_qua_inspect_aa7018_idx'),
        ),
    ]
