# Generated by Django 6.0.2 on 2026-03-30 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0006_nonconformance_quality_non_status_a2bb7d_idx_and_more'),
        ('sales', '0013_alter_deliverynoteline_delivery_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercomplaint',
            name='related_sales_order_ref',
            field=models.CharField(blank=True, help_text='Legacy: text reference kept for backward compat', max_length=50),
        ),
        migrations.AlterField(
            model_name='customercomplaint',
            name='related_sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='sales.salesorder'),
        ),
    ]
