# Generated by Django 6.0.2 on 2026-04-05 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0052_add_journal_source_soft_delete'),
        ('quality', '0007_customercomplaint_related_sales_order_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityinspection',
            name='qc_expense_account',
            field=models.ForeignKey(blank=True, help_text="Override QC Expense account. Falls back to DEFAULT_GL_ACCOUNTS['QC_EXPENSE'].", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_inspections_as_qc_expense', to='accounting.account'),
        ),
    ]
