# Generated by Django 5.2.14 on 2026-09-02 22:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "connector_type",
                    models.CharField(
                        choices=[
                            ("remita", "Remita"),
                            ("nibss", "NIBSS / Bank"),
                            ("gifmis", "GIFMIS"),
                            ("ippis", "IPPIS"),
                            ("bvn_tin", "BVN / TIN Verification"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[("sandbox", "Sandbox"), ("production", "Production")],
                        default="sandbox",
                        max_length=20,
                    ),
                ),
                ("base_url", models.URLField(blank=True, default="")),
                (
                    "credentials_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Key into superadmin/encryption.py encrypted store.",
                        max_length=200,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("timeout_seconds", models.PositiveIntegerField(default=30)),
                ("retry_limit", models.PositiveIntegerField(default=0)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["connector_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("messages_sent", models.PositiveIntegerField(default=0)),
                ("messages_received", models.PositiveIntegerField(default=0)),
                ("messages_failed", models.PositiveIntegerField(default=0)),
                (
                    "payload_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("trigger", models.CharField(blank=True, default="", max_length=100)),
                ("operator_note", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="integrations.integrationendpoint",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("out", "Outbound"), ("in", "Inbound")],
                        default="out",
                        max_length=10,
                    ),
                ),
                (
                    "message_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Idempotency key — a re-delivered message with the same key must never double-post.",
                        max_length=100,
                    ),
                ),
                (
                    "payload_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("received", "Received"),
                            ("replayed", "Replayed (idempotent)"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped (duplicate message_key)"),
                        ],
                        default="sent",
                        max_length=20,
                    ),
                ),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("failure_reason", models.TextField(blank=True, default="")),
                (
                    "source_model",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("source_id", models.PositiveIntegerField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="integrations.integrationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(
                        fields=["message_key"], name="integration_message_fbb9c7_idx"
                    ),
                    models.Index(
                        fields=["run", "status"], name="integration_run_id_9c296e_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("message_key__gt", "")),
                        fields=("run", "message_key"),
                        name="unique_message_key_per_run",
                    )
                ],
            },
        ),
    ]
