# Generated by Django 6.0.2 on 2026-03-28 01:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human label, e.g. "SAP Production"', max_length=120)),
                ('system_type', models.CharField(choices=[('sap_ecc', 'SAP ECC'), ('sap_s4hana', 'SAP S/4HANA (OData)'), ('sap_bc', 'SAP Business Central / B1'), ('dynamics_365_bc', 'Microsoft Dynamics 365 BC'), ('dynamics_365_fo', 'Microsoft Dynamics 365 F&O'), ('dynamics_ax', 'Microsoft Dynamics AX'), ('sage_intacct', 'Sage Intacct'), ('sage_200', 'Sage 200'), ('sage_50', 'Sage 50'), ('sage_x3', 'Sage X3'), ('quickbooks', 'QuickBooks Online'), ('xero', 'Xero'), ('netsuite', 'Oracle NetSuite'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('stripe', 'Stripe'), ('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('salesforce', 'Salesforce CRM'), ('hubspot', 'HubSpot CRM'), ('custom', 'Custom / Generic REST'), ('custom_soap', 'Custom SOAP/XML'), ('webhook_only', 'Webhook Only')], max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('base_url', models.URLField(blank=True, help_text='e.g. https://mycompany.s4hana.cloud/sap/opu/odata/')),
                ('auth_method', models.CharField(choices=[('none', 'No Auth'), ('api_key', 'API Key Header'), ('basic', 'HTTP Basic Auth'), ('bearer', 'Bearer Token'), ('oauth2_cc', 'OAuth 2.0 Client Credentials'), ('oauth2_auth', 'OAuth 2.0 Authorization Code'), ('sap_cookie', 'SAP CSRF Cookie'), ('hmac', 'HMAC Signature')], default='bearer', max_length=20)),
                ('credentials', models.JSONField(blank=True, default=dict, help_text='Auth credentials as JSON. Keys by auth_method: bearer={"token":""}, basic={"username":"","password":""}, api_key={"header_name":"X-Api-Key","key":""}, oauth2_cc={"client_id":"","client_secret":"","token_url":""}, sap_cookie={"username":"","password":"","csrf_url":""}')),
                ('token_cache', models.JSONField(blank=True, default=dict)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound (Remote -> DTSG)'), ('outbound', 'Outbound (DTSG -> Remote)'), ('bidirectional', 'Bidirectional')], default='bidirectional', max_length=20)),
                ('enabled_modules', models.JSONField(default=list, help_text='List of ModuleCode values. Empty = all.')),
                ('sync_interval_minutes', models.PositiveIntegerField(default=60, help_text='0 = manual only')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('next_sync_at', models.DateTimeField(blank=True, null=True)),
                ('webhook_secret', models.CharField(blank=True, max_length=128)),
                ('sap_client', models.CharField(blank=True, max_length=10)),
                ('sap_system_id', models.CharField(blank=True, max_length=10)),
                ('dynamics_tenant_id', models.CharField(blank=True, max_length=80)),
                ('dynamics_environment', models.CharField(blank=True, max_length=80)),
                ('sage_company_id', models.CharField(blank=True, max_length=80)),
                ('max_retries', models.PositiveSmallIntegerField(default=3)),
                ('retry_backoff_seconds', models.PositiveIntegerField(default=60)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Integration Config',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(choices=[('accounting', 'Accounting / GL'), ('ap', 'Accounts Payable'), ('ar', 'Accounts Receivable'), ('assets', 'Fixed Assets'), ('budget', 'Budget'), ('inventory', 'Inventory'), ('procurement', 'Procurement / P2P'), ('sales', 'Sales / O2C'), ('hrm', 'HRM / Payroll'), ('production', 'Production / MFG'), ('quality', 'Quality'), ('service', 'Service / Maintenance'), ('customers', 'Customers / CRM'), ('vendors', 'Vendors / Suppliers'), ('items', 'Items / Products'), ('all', 'All Modules')], max_length=30)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound (Remote -> DTSG)'), ('outbound', 'Outbound (DTSG -> Remote)'), ('bidirectional', 'Bidirectional')], max_length=20)),
                ('triggered_by', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual'), ('webhook', 'Webhook Trigger')], default='manual', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed'), ('skipped', 'Skipped (no change)'), ('retry', 'Queued for Retry')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('records_total', models.PositiveIntegerField(default=0)),
                ('records_created', models.PositiveIntegerField(default=0)),
                ('records_updated', models.PositiveIntegerField(default=0)),
                ('records_skipped', models.PositiveIntegerField(default=0)),
                ('records_failed', models.PositiveIntegerField(default=0)),
                ('error_summary', models.TextField(blank=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='integrations.integrationconfig')),
            ],
            options={
                'verbose_name': 'Sync Log',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncLogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(blank=True, max_length=80)),
                ('remote_id', models.CharField(blank=True, max_length=120)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('read', 'Read')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed'), ('skipped', 'Skipped (no change)'), ('retry', 'Queued for Retry')], max_length=20)),
                ('error_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('sync_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='integrations.synclog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('target_url', models.URLField()),
                ('events', models.JSONField(default=list, help_text='EventType list. Empty = all.')),
                ('modules', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('secret', models.CharField(blank=True, max_length=128)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('max_retries', models.PositiveSmallIntegerField(default=3)),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='integrations.integrationconfig')),
            ],
            options={
                'verbose_name': 'Webhook Endpoint',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80)),
                ('payload', models.JSONField()),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed'), ('skipped', 'Skipped (no change)'), ('retry', 'Queued for Retry')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='integrations.webhookendpoint')),
            ],
            options={
                'verbose_name': 'Webhook Delivery',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookInboundLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_system', models.CharField(blank=True, choices=[('sap_ecc', 'SAP ECC'), ('sap_s4hana', 'SAP S/4HANA (OData)'), ('sap_bc', 'SAP Business Central / B1'), ('dynamics_365_bc', 'Microsoft Dynamics 365 BC'), ('dynamics_365_fo', 'Microsoft Dynamics 365 F&O'), ('dynamics_ax', 'Microsoft Dynamics AX'), ('sage_intacct', 'Sage Intacct'), ('sage_200', 'Sage 200'), ('sage_50', 'Sage 50'), ('sage_x3', 'Sage X3'), ('quickbooks', 'QuickBooks Online'), ('xero', 'Xero'), ('netsuite', 'Oracle NetSuite'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('stripe', 'Stripe'), ('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('salesforce', 'Salesforce CRM'), ('hubspot', 'HubSpot CRM'), ('custom', 'Custom / Generic REST'), ('custom_soap', 'Custom SOAP/XML'), ('webhook_only', 'Webhook Only')], max_length=40)),
                ('event_type', models.CharField(blank=True, max_length=120)),
                ('headers', models.JSONField(default=dict)),
                ('raw_payload', models.TextField()),
                ('parsed_payload', models.JSONField(blank=True, null=True)),
                ('signature_valid', models.BooleanField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed'), ('skipped', 'Skipped (no change)'), ('retry', 'Queued for Retry')], default='pending', max_length=20)),
                ('processing_notes', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_logs', to='integrations.integrationconfig')),
            ],
            options={
                'verbose_name': 'Inbound Webhook Log',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('accounting', 'Accounting / GL'), ('ap', 'Accounts Payable'), ('ar', 'Accounts Receivable'), ('assets', 'Fixed Assets'), ('budget', 'Budget'), ('inventory', 'Inventory'), ('procurement', 'Procurement / P2P'), ('sales', 'Sales / O2C'), ('hrm', 'HRM / Payroll'), ('production', 'Production / MFG'), ('quality', 'Quality'), ('service', 'Service / Maintenance'), ('customers', 'Customers / CRM'), ('vendors', 'Vendors / Suppliers'), ('items', 'Items / Products'), ('all', 'All Modules')], max_length=30)),
                ('dtsg_field', models.CharField(help_text='Python dot-path in DTSG, e.g. "account.code"', max_length=120)),
                ('remote_field', models.CharField(max_length=120)),
                ('transform', models.CharField(choices=[('none', 'None'), ('upper', 'Uppercase'), ('lower', 'Lowercase'), ('zero_pad_10', 'Zero-pad to 10 chars (SAP GL account)'), ('date_iso', 'Date -> ISO-8601'), ('date_sap', 'Date -> SAP YYYYMMDD'), ('amount_abs', 'Amount -> absolute value'), ('debit_credit_sign', 'Negate for debit/credit sign convention'), ('boolean_x', 'Boolean -> X/empty (SAP)')], default='none', max_length=40)),
                ('default_value', models.CharField(blank=True, max_length=255)),
                ('is_required_remote', models.BooleanField(default=False)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound (Remote -> DTSG)'), ('outbound', 'Outbound (DTSG -> Remote)'), ('bidirectional', 'Bidirectional')], default='bidirectional', max_length=20)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_mappings', to='integrations.integrationconfig')),
            ],
            options={
                'ordering': ['module', 'dtsg_field'],
                'unique_together': {('config', 'module', 'dtsg_field', 'direction')},
            },
        ),
    ]
