import type { ModuleConfig } from '../_base/types';

export const moduleConfig: ModuleConfig = {
  key: 'revenue_admin',
  label: 'Revenue Administration (IGR)',
  icon: '🧾',
  description: 'Taxpayers, tax accounts, assessments, billing runs, demand notices, arrears and enforcement.',
  basePath: '/revenue-admin',
  entities: [
    {
      key: 'taxpayer',
      plural: 'taxpayers',
      label: 'Taxpayers',
      searchField: 'tin',
      idField: 'id',
      columns: [
        { name: 'tin', label: 'TIN', type: 'text', required: true, placeholder: 'e.g. 12345678-0001' },
        { name: 'case_type', label: 'Type', type: 'select', options: { individual: 'Individual', corporate: 'Corporate' } },
        { name: 'full_name', label: 'Full Name', type: 'text' },
        { name: 'business_name', label: 'Business Name', type: 'text' },
        { name: 'is_active', label: 'Active', type: 'boolean' },
      ],
      fields: [
        { name: 'tin', label: 'TIN', type: 'text', required: true, placeholder: 'e.g. 12345678-0001' },
        { name: 'case_type', label: 'Type', type: 'select', options: { individual: 'Individual', corporate: 'Corporate' } },
        { name: 'full_name', label: 'Full Name', type: 'text' },
        { name: 'business_name', label: 'Business Name', type: 'text' },
        { name: 'bvn', label: 'BVN', type: 'text', secondary: true },
        { name: 'email', label: 'Email', type: 'text', secondary: true },
        { name: 'phone', label: 'Phone', type: 'text', secondary: true },
        { name: 'address', label: 'Address', type: 'longtext', secondary: true },
        { name: 'is_active', label: 'Active', type: 'boolean' },
        { name: 'display_name', label: 'Display Name', type: 'text', readOnly: true, hideInForm: true },
      ],
    },
    {
      key: 'taxAccount',
      plural: 'tax-accounts',
      label: 'Tax Accounts',
      searchField: 'taxpayer',
      idField: 'id',
      columns: [
        { name: 'taxpayer', label: 'Taxpayer', type: 'integer', reference: { module: 'revenue_admin', entity: 'taxpayer' } },
        { name: 'revenue_head', label: 'Revenue Head', type: 'integer', reference: { module: 'accounting', entity: 'revenueHead' } },
        { name: 'running_balance', label: 'Running Balance', type: 'decimal', numeric: true },
      ],
      fields: [
        { name: 'taxpayer', label: 'Taxpayer', type: 'integer', required: true, reference: { module: 'revenue_admin', entity: 'taxpayer' } },
        { name: 'revenue_head', label: 'Revenue Head', type: 'integer', required: true, reference: { module: 'accounting', entity: 'revenueHead' } },
        { name: 'running_balance', label: 'Running Balance', type: 'decimal', numeric: true, readOnly: true, hideInForm: true },
      ],
    },
    {
      key: 'assessment',
      plural: 'assessments',
      label: 'Assessments',
      searchField: 'taxpayer',
      idField: 'id',
      statusField: 'status',
      columns: [
        { name: 'taxpayer', label: 'Taxpayer', type: 'integer', reference: { module: 'revenue_admin', entity: 'taxpayer' } },
        { name: 'fiscal_year', label: 'Fiscal Year', type: 'integer', numeric: true },
        { name: 'assessment_type', label: 'Type', type: 'select', options: { self: 'Self-Assessment', boj: 'Best of Judgement', amended: 'Amended' } },
        { name: 'status', label: 'Status', type: 'select', options: { draft: 'Draft', issued: 'Issued', objected: 'Objected', appealed: 'Appealed', settled: 'Settled' } },
        { name: 'assessed_amount', label: 'Amount', type: 'decimal', numeric: true },
      ],
      fields: [
        { name: 'taxpayer', label: 'Taxpayer', type: 'integer', required: true, reference: { module: 'revenue_admin', entity: 'taxpayer' } },
        { name: 'revenue_head', label: 'Revenue Head', type: 'integer', reference: { module: 'accounting', entity: 'revenueHead' } },
        { name: 'fiscal_year', label: 'Fiscal Year', type: 'integer', numeric: true, required: true },
        { name: 'assessment_type', label: 'Type', type: 'select', options: { self: 'Self-Assessment', boj: 'Best of Judgement', amended: 'Amended' } },
        { name: 'status', label: 'Status', type: 'select', options: { draft: 'Draft', issued: 'Issued', objected: 'Objected', appealed: 'Appealed', settled: 'Settled' } },
        { name: 'assessed_amount', label: 'Assessed Amount', type: 'decimal', numeric: true },
        { name: 'objection', label: 'Objection', type: 'longtext', secondary: true },
        { name: 'issued_at', label: 'Issued At', type: 'datetime', readOnly: true, hideInForm: true },
      ],
    },
    {
      key: 'billingRun',
      plural: 'billing-runs',
      label: 'Billing Runs',
      searchField: 'fiscal_year',
      idField: 'id',
      statusField: 'status',
      columns: [
        { name: 'revenue_head', label: 'Revenue Head', type: 'integer', reference: { module: 'accounting', entity: 'revenueHead' } },
        { name: 'fiscal_year', label: 'Fiscal Year', type: 'integer', numeric: true },
        { name: 'cycle', label: 'Cycle', type: 'text' },
        { name: 'status', label: 'Status', type: 'select', options: { draft: 'Draft', processed: 'Processed', completed: 'Completed' } },
        { name: 'total_amount', label: 'Total Amount', type: 'decimal', numeric: true },
      ],
      fields: [
        { name: 'revenue_head', label: 'Revenue Head', type: 'integer', required: true, reference: { module: 'accounting', entity: 'revenueHead' } },
        { name: 'fiscal_year', label: 'Fiscal Year', type: 'integer', numeric: true, required: true },
        { name: 'cycle', label: 'Cycle', type: 'text' },
        { name: 'status', label: 'Status', type: 'select', options: { draft: 'Draft', processed: 'Processed', completed: 'Completed' } },
        { name: 'notices_created', label: 'Notices Created', type: 'integer', numeric: true, readOnly: true, hideInForm: true },
        { name: 'total_amount', label: 'Total Amount', type: 'decimal', numeric: true, readOnly: true, hideInForm: true },
        { name: 'processed_at', label: 'Processed At', type: 'datetime', readOnly: true, hideInForm: true },
      ],
    },
    {
      key: 'demandNotice',
      plural: 'demand-notices',
      label: 'Demand Notices',
      searchField: 'notice_number',
      idField: 'id',
      statusField: 'status',
      columns: [
        { name: 'notice_number', label: 'Notice Number', type: 'text', required: true },
        { name: 'taxpayer', label: 'Taxpayer', type: 'integer', reference: { module: 'revenue_admin', entity: 'taxpayer' } },
        { name: 'amount_due', label: 'Amount Due', type: 'decimal', numeric: true },
        { name: 'amount_paid', label: 'Amount Paid', type: 'decimal', numeric: true },
        { name: 'status', label: 'Status', type: 'select', options: { issued: 'Issued', paid: 'Paid', partial: 'Partially Paid', disputed: 'Disputed', overdue: 'Overdue' } },
      ],
      fields: [
        { name: 'notice_number', label: 'Notice Number', type: 'text', required: true },
        { name: 'taxpayer', label: 'Taxpayer', type: 'integer', required: true, reference: { module: 'revenue_admin', entity: 'taxpayer' } },
        { name: 'billing_run', label: 'Billing Run', type: 'integer', reference: { module: 'revenue_admin', entity: 'billingRun' } },
        { name: 'assessment', label: 'Assessment', type: 'integer', reference: { module: 'revenue_admin', entity: 'assessment' } },
        { name: 'amount_due', label: 'Amount Due', type: 'decimal', numeric: true },
        { name: 'amount_paid', label: 'Amount Paid', type: 'decimal', numeric: true },
        { name: 'due_date', label: 'Due Date', type: 'date', required: true },
        { name: 'status', label: 'Status', type: 'select', options: { issued: 'Issued', paid: 'Paid', partial: 'Partially Paid', disputed: 'Disputed', overdue: 'Overdue' } },
        { name: 'issued_at', label: 'Issued At', type: 'datetime', readOnly: true, hideInForm: true },
      ],
    },
    {
      key: 'arrearsLedger',
      plural: 'arrears',
      label: 'Arrears Ledger',
      searchField: 'taxpayer',
      idField: 'id',
      columns: [
        { name: 'taxpayer', label: 'Taxpayer', type: 'integer', reference: { module: 'revenue_admin', entity: 'taxpayer' } },
        { name: 'fiscal_year', label: 'Fiscal Year', type: 'integer', numeric: true },
        { name: 'revenue_head', label: 'Revenue Head', type: 'integer', reference: { module: 'accounting', entity: 'revenueHead' } },
        { name: 'amount', label: 'Amount', type: 'decimal', numeric: true },
        { name: 'is_settled', label: 'Settled', type: 'boolean' },
      ],
      fields: [
        { name: 'taxpayer', label: 'Taxpayer', type: 'integer', required: true, reference: { module: 'revenue_admin', entity: 'taxpayer' } },
        { name: 'fiscal_year', label: 'Fiscal Year', type: 'integer', numeric: true, required: true },
        { name: 'revenue_head', label: 'Revenue Head', type: 'integer', reference: { module: 'accounting', entity: 'revenueHead' } },
        { name: 'amount', label: 'Amount', type: 'decimal', numeric: true },
        { name: 'arrears_date', label: 'Arrears Date', type: 'date' },
        { name: 'ageing_days', label: 'Ageing Days', type: 'integer', numeric: true, readOnly: true, hideInForm: true },
        { name: 'is_settled', label: 'Settled', type: 'boolean' },
      ],
    },
    {
      key: 'enforcementCase',
      plural: 'enforcement-cases',
      label: 'Enforcement Cases',
      searchField: 'taxpayer',
      idField: 'id',
      statusField: 'status',
      columns: [
        { name: 'taxpayer', label: 'Taxpayer', type: 'integer', reference: { module: 'revenue_admin', entity: 'taxpayer' } },
        { name: 'status', label: 'Status', type: 'select', options: { open: 'Open', distraint: 'Distraint Ordered', resolved: 'Resolved', closed: 'Closed' } },
        { name: 'amount_in_dispute', label: 'Amount in Dispute', type: 'decimal', numeric: true },
        { name: 'distraint_order', label: 'Distraint Order', type: 'text', secondary: true },
        { name: 'opened_at', label: 'Opened At', type: 'datetime' },
      ],
      fields: [
        { name: 'taxpayer', label: 'Taxpayer', type: 'integer', required: true, reference: { module: 'revenue_admin', entity: 'taxpayer' } },
        { name: 'arrears', label: 'Arrears Ledger', type: 'integer', reference: { module: 'revenue_admin', entity: 'arrearsLedger' } },
        { name: 'amount_in_dispute', label: 'Amount in Dispute', type: 'decimal', numeric: true },
        { name: 'status', label: 'Status', type: 'select', options: { open: 'Open', distraint: 'Distraint Ordered', resolved: 'Resolved', closed: 'Closed' } },
        { name: 'distraint_order', label: 'Distraint Order', type: 'text' },
        { name: 'resolved_at', label: 'Resolved At', type: 'datetime' },
        { name: 'opened_at', label: 'Opened At', type: 'datetime', readOnly: true, hideInForm: true },
      ],
    },
    {
      key: 'taxClearanceCertificate',
      plural: 'clearance-certificates',
      label: 'Tax Clearance Certificates',
      searchField: 'certificate_number',
      idField: 'id',
      statusField: 'status',
      columns: [
        { name: 'certificate_number', label: 'Certificate Number', type: 'text', required: true },
        { name: 'taxpayer', label: 'Taxpayer', type: 'integer', reference: { module: 'revenue_admin', entity: 'taxpayer' } },
        { name: 'status', label: 'Status', type: 'select', options: { issued: 'Issued', verified: 'Verified', expired: 'Expired' } },
        { name: 'fiscal_year', label: 'Fiscal Year', type: 'integer', numeric: true },
        { name: 'expiry_date', label: 'Expiry Date', type: 'date' },
      ],
      fields: [
        { name: 'certificate_number', label: 'Certificate Number', type: 'text', required: true },
        { name: 'taxpayer', label: 'Taxpayer', type: 'integer', required: true, reference: { module: 'revenue_admin', entity: 'taxpayer' } },
        { name: 'status', label: 'Status', type: 'select', options: { issued: 'Issued', verified: 'Verified', expired: 'Expired' } },
        { name: 'fiscal_year', label: 'Fiscal Year', type: 'integer', numeric: true, required: true },
        { name: 'issue_date', label: 'Issue Date', type: 'date' },
        { name: 'expiry_date', label: 'Expiry Date', type: 'date' },
        { name: 'verified_at', label: 'Verified At', type: 'datetime', readOnly: true, hideInForm: true },
      ],
    },
  ],
};
