import type { ModuleConfig } from '../_base/types';

export const moduleConfig: ModuleConfig = {
  key: 'internal_audit',
  label: 'Internal Audit Management',
  icon: '🕵️',
  description: 'Audit universe, plans, engagements, working papers, findings and follow-ups.',
  basePath: '/internal-audit',
  entities: [
    {
      key: 'auditUniverse',
      plural: 'universe',
      label: 'Audit Universe',
      searchField: 'entity_name',
      idField: 'id',
      columns: [
        { name: 'entity_name', label: 'Entity Name', type: 'text' },
        { name: 'entity_ref', label: 'Entity Ref', type: 'text' },
        { name: 'risk_score', label: 'Risk Score', type: 'integer', numeric: true },
        { name: 'is_active', label: 'Active', type: 'boolean' },
      ],
      fields: [
        { name: 'entity_name', label: 'Entity Name', type: 'text', required: true },
        { name: 'entity_ref', label: 'Entity Ref', type: 'text', secondary: true },
        { name: 'risk_score', label: 'Risk Score', type: 'integer', numeric: true },
        { name: 'is_active', label: 'Active', type: 'boolean', secondary: true },
      ],
    },
    {
      key: 'auditPlan',
      plural: 'plans',
      label: 'Audit Plans',
      searchField: 'title',
      idField: 'id',
      statusField: 'status',
      columns: [
        { name: 'fiscal_year', label: 'Fiscal Year', type: 'integer', numeric: true },
        { name: 'title', label: 'Title', type: 'text' },
        {
          name: 'status',
          label: 'Status',
          type: 'select',
          options: { draft: 'Draft', approved: 'Approved', completed: 'Completed', cancelled: 'Cancelled' },
        },
        { name: 'total_engagements', label: 'Total Engagements', type: 'integer', numeric: true },
      ],
      fields: [
        { name: 'fiscal_year', label: 'Fiscal Year', type: 'integer', numeric: true, required: true },
        { name: 'title', label: 'Title', type: 'text', required: true },
        {
          name: 'status',
          label: 'Status',
          type: 'select',
          options: { draft: 'Draft', approved: 'Approved', completed: 'Completed', cancelled: 'Cancelled' },
        },
        { name: 'total_engagements', label: 'Total Engagements', type: 'integer', numeric: true, secondary: true },
        { name: 'approved_by', label: 'Approved By', type: 'integer', hideInForm: true, readOnly: true, secondary: true },
        { name: 'approved_at', label: 'Approved At', type: 'datetime', hideInForm: true, readOnly: true, secondary: true },
      ],
    },
    {
      key: 'auditEngagement',
      plural: 'engagements',
      label: 'Audit Engagements',
      searchField: 'title',
      idField: 'id',
      statusField: 'status',
      columns: [
        { name: 'title', label: 'Title', type: 'text' },
        {
          name: 'status',
          label: 'Status',
          type: 'select',
          options: { planned: 'Planned', fieldwork: 'Fieldwork', drafting: 'Drafting', reviewed: 'Reviewed', issued: 'Issued', cancelled: 'Cancelled' },
        },
        { name: 'plan', label: 'Plan', type: 'integer', reference: { module: 'internal_audit', entity: 'auditPlan' } },
        { name: 'universe', label: 'Universe', type: 'integer', reference: { module: 'internal_audit', entity: 'auditUniverse' } },
      ],
      fields: [
        { name: 'plan', label: 'Plan', type: 'integer', required: true, reference: { module: 'internal_audit', entity: 'auditPlan' } },
        { name: 'universe', label: 'Universe', type: 'integer', reference: { module: 'internal_audit', entity: 'auditUniverse' } },
        { name: 'title', label: 'Title', type: 'text', required: true },
        { name: 'scope', label: 'Scope', type: 'longtext', secondary: true },
        {
          name: 'status',
          label: 'Status',
          type: 'select',
          options: { planned: 'Planned', fieldwork: 'Fieldwork', drafting: 'Drafting', reviewed: 'Reviewed', issued: 'Issued', cancelled: 'Cancelled' },
        },
        { name: 'team', label: 'Team', type: 'object', hideInForm: true, readOnly: true, secondary: true },
        { name: 'planned_start', label: 'Planned Start', type: 'date', secondary: true },
        { name: 'planned_end', label: 'Planned End', type: 'date', secondary: true },
      ],
    },
    {
      key: 'workingPaper',
      plural: 'working-papers',
      label: 'Working Papers',
      searchField: 'title',
      idField: 'id',
      columns: [
        { name: 'title', label: 'Title', type: 'text' },
        { name: 'engagement', label: 'Engagement', type: 'integer', reference: { module: 'internal_audit', entity: 'auditEngagement' } },
        { name: 'reference', label: 'Reference', type: 'text' },
        { name: 'attachment_hash', label: 'Attachment Hash', type: 'text' },
      ],
      fields: [
        { name: 'engagement', label: 'Engagement', type: 'integer', required: true, reference: { module: 'internal_audit', entity: 'auditEngagement' } },
        { name: 'title', label: 'Title', type: 'text', required: true },
        { name: 'reference', label: 'Reference', type: 'text', secondary: true },
        { name: 'description', label: 'Description', type: 'longtext', secondary: true },
        { name: 'attachment', label: 'Attachment', type: 'text', secondary: true },
        { name: 'attachment_hash', label: 'Attachment Hash', type: 'text', secondary: true },
        { name: 'created_by', label: 'Created By', type: 'integer', hideInForm: true, readOnly: true, secondary: true },
      ],
    },
    {
      key: 'auditFinding',
      plural: 'findings',
      label: 'Audit Findings',
      searchField: 'title',
      idField: 'id',
      statusField: 'status',
      columns: [
        { name: 'title', label: 'Title', type: 'text' },
        {
          name: 'rating',
          label: 'Rating',
          type: 'select',
          options: { low: 'Low', medium: 'Medium', high: 'High', critical: 'Critical' },
        },
        {
          name: 'status',
          label: 'Status',
          type: 'select',
          options: { open: 'Open', agreed: 'Agreed', implemented: 'Implemented', closed: 'Closed', accepted_risk: 'Accepted Risk' },
        },
        { name: 'engagement', label: 'Engagement', type: 'integer', reference: { module: 'internal_audit', entity: 'auditEngagement' } },
        { name: 'due_date', label: 'Due Date', type: 'date' },
      ],
      fields: [
        { name: 'engagement', label: 'Engagement', type: 'integer', required: true, reference: { module: 'internal_audit', entity: 'auditEngagement' } },
        { name: 'title', label: 'Title', type: 'text', required: true },
        {
          name: 'rating',
          label: 'Rating',
          type: 'select',
          options: { low: 'Low', medium: 'Medium', high: 'High', critical: 'Critical' },
        },
        {
          name: 'status',
          label: 'Status',
          type: 'select',
          options: { open: 'Open', agreed: 'Agreed', implemented: 'Implemented', closed: 'Closed', accepted_risk: 'Accepted Risk' },
        },
        { name: 'recommendation', label: 'Recommendation', type: 'longtext', secondary: true },
        { name: 'management_response', label: 'Management Response', type: 'longtext', secondary: true },
        { name: 'agreed_action', label: 'Agreed Action', type: 'longtext', secondary: true },
        { name: 'due_date', label: 'Due Date', type: 'date', secondary: true },
      ],
    },
    {
      key: 'followUp',
      plural: 'follow-ups',
      label: 'Follow-Ups',
      searchField: 'note',
      idField: 'id',
      columns: [
        { name: 'finding', label: 'Finding', type: 'integer', reference: { module: 'internal_audit', entity: 'auditFinding' } },
        { name: 'follow_up_date', label: 'Follow-Up Date', type: 'date' },
        { name: 'is_overdue', label: 'Overdue', type: 'boolean' },
        { name: 'note', label: 'Note', type: 'longtext' },
      ],
      fields: [
        { name: 'finding', label: 'Finding', type: 'integer', required: true, reference: { module: 'internal_audit', entity: 'auditFinding' } },
        { name: 'follow_up_date', label: 'Follow-Up Date', type: 'date', required: true },
        { name: 'note', label: 'Note', type: 'longtext', secondary: true },
        { name: 'is_overdue', label: 'Overdue', type: 'boolean', secondary: true },
        { name: 'escalated_by', label: 'Escalated By', type: 'integer', hideInForm: true, readOnly: true, secondary: true },
      ],
    },
    {
      key: 'continuousAuditRule',
      plural: 'continuous-rules',
      label: 'Continuous Audit Rules',
      searchField: 'name',
      idField: 'id',
      columns: [
        { name: 'name', label: 'Name', type: 'text' },
        { name: 'sql_hint', label: 'SQL Hint', type: 'longtext' },
        { name: 'schedule', label: 'Schedule', type: 'text' },
        { name: 'is_active', label: 'Active', type: 'boolean' },
      ],
      fields: [
        { name: 'name', label: 'Name', type: 'text', required: true },
        { name: 'sql_hint', label: 'SQL Hint', type: 'longtext', secondary: true },
        { name: 'schedule', label: 'Schedule', type: 'text', secondary: true },
        { name: 'is_active', label: 'Active', type: 'boolean', secondary: true },
      ],
    },
  ],
};
