# Generated by Django 5.2.14 on 2026-09-02 22:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0112_journal_balance_guard_case_insensitive"),
        ("budget", "0017_alter_warrant_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AmortisationCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "principal_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "interest_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "commitment_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("approved", "Approved for Payment"),
                            ("paid", "Paid"),
                            ("defaulted", "Defaulted"),
                            ("closed", "Closed"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warrant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="budget.warrant",
                    ),
                ),
            ],
            options={
                "ordering": ["schedule"],
            },
        ),
        migrations.CreateModel(
            name="AmortisationLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("approved", "Approved"),
                            ("paid", "Paid via Warrant"),
                            ("defaulted", "Defaulted"),
                            ("closed", "Closed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_events",
                        to="debt.amortisationcoupon",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warrant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="budget.warrant",
                    ),
                ),
            ],
            options={
                "ordering": ["recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="AmortisationSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("coupon_date", models.DateField()),
                (
                    "principal_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "interest_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "commitment_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("is_released", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["instrument", "coupon_date"],
            },
        ),
        migrations.AddField(
            model_name="amortisationcoupon",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coupons",
                to="debt.amortisationschedule",
            ),
        ),
        migrations.CreateModel(
            name="DebtAversionStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fiscal_year", models.IntegerField(db_index=True)),
                (
                    "pillar",
                    models.CharField(
                        choices=[
                            ("domestic", "Domestic Debt"),
                            ("external", "External Debt"),
                            ("guarantees", "Guarantees & Contingent"),
                        ],
                        default="domestic",
                        max_length=20,
                    ),
                ),
                (
                    "outstanding_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "gdp",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "debt_to_gdp",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "debt_service_to_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("assessment", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["fiscal_year", "pillar"],
            },
        ),
        migrations.CreateModel(
            name="DebtInstrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instrument_number",
                    models.CharField(db_index=True, max_length=60, unique=True),
                ),
                (
                    "instrument_type",
                    models.CharField(
                        choices=[
                            ("loan", "Loan"),
                            ("bond", "Bond / Security"),
                            ("treasury_bill", "Treasury Bill"),
                            ("guarantee", "Guarantee"),
                            ("other", "Other"),
                        ],
                        default="loan",
                        max_length=20,
                    ),
                ),
                ("creditor", models.CharField(db_index=True, max_length=255)),
                (
                    "principal_amount",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "interest_rate",
                    models.DecimalField(decimal_places=3, default=0, max_digits=6),
                ),
                (
                    "commitment_fee_rate",
                    models.DecimalField(decimal_places=3, default=0, max_digits=6),
                ),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("maturity_date", models.DateField(blank=True, null=True)),
                (
                    "grace_period",
                    models.PositiveIntegerField(
                        default=0, help_text="Grace period in months."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_concessional", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.currency",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["instrument_number"],
            },
        ),
        migrations.AddField(
            model_name="amortisationschedule",
            name="instrument",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="debt.debtinstrument",
            ),
        ),
        migrations.CreateModel(
            name="DebtServiceCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fiscal_year", models.IntegerField(db_index=True)),
                ("month", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "principal_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "interest_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "fees_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="debt.debtinstrument",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["fiscal_year", "month"],
            },
        ),
    ]
