# Generated by Django 4.2.28 on 2026-03-18 12:08

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0002_approval_approvalgroup_approvalstep_approvallog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalApprovalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(choices=[('SalesOrder', 'Sales Orders'), ('PurchaseOrder', 'Purchase Orders'), ('ProductionOrder', 'Production Orders'), ('QualityInspection', 'Quality Inspections'), ('Budget', 'Budgets'), ('JournalEntry', 'Journal Entries'), ('Maintenance', 'Maintenance')], max_length=30, unique=True)),
                ('approval_mode', models.CharField(choices=[('Disabled', 'Approvals Disabled - Auto-approve'), ('Optional', 'Optional - Can approve manually'), ('Required', 'Required - Must go through approval'), ('Strict', 'Strict - All require approval')], default='Required', max_length=20)),
                ('use_amount_threshold', models.BooleanField(default=False)),
                ('low_amount_threshold', models.DecimalField(decimal_places=2, default=Decimal('10000'), max_digits=15)),
                ('high_amount_threshold', models.DecimalField(decimal_places=2, default=Decimal('100000'), max_digits=15)),
                ('auto_approve_below_threshold', models.BooleanField(default=True)),
                ('send_notifications', models.BooleanField(default=True)),
                ('notify_requester', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approval Settings',
                'verbose_name_plural': 'Approval Settings',
            },
        ),
    ]
