# Generated by Django 4.2.28 on 2026-03-26 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_approvaldelegation'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalstep',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='sla_hours',
            field=models.PositiveIntegerField(default=24, help_text='SLA in hours for this step'),
        ),
        migrations.CreateModel(
            name='ApprovalSLAViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_completion', models.DateTimeField()),
                ('actual_completion', models.DateTimeField(blank=True, null=True)),
                ('delay_hours', models.PositiveIntegerField(default=0)),
                ('severity', models.CharField(choices=[('Low', 'Low - < 24 hours'), ('Medium', 'Medium - 24-48 hours'), ('High', 'High - 48-72 hours'), ('Critical', 'Critical - > 72 hours')], max_length=20)),
                ('notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approval_step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sla_violation', to='workflow.approvalstep')),
            ],
        ),
    ]
