# Generated by Django 4.2.28 on 2026-04-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_add_sla_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalapprovalsettings',
            name='module',
            field=models.CharField(choices=[('PurchaseRequest', 'Purchase Requests'), ('PurchaseOrder', 'Purchase Orders'), ('GoodsReceivedNote', 'Goods Received Notes'), ('InvoiceVerification', 'Invoice Verification (3-Way Match)'), ('PurchaseReturn', 'Purchase Returns'), ('SalesOrder', 'Sales Orders'), ('ProductionOrder', 'Production Orders'), ('QualityInspection', 'Quality Inspections'), ('Budget', 'Budgets'), ('JournalEntry', 'Journal Entries'), ('Maintenance', 'Maintenance')], max_length=30, unique=True),
        ),
    ]
