# Generated by Django 4.2.28 on 2026-04-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_add_leaverequest_module_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalapprovalsettings',
            name='module',
            field=models.CharField(choices=[('PurchaseRequest', 'Purchase Requests'), ('PurchaseOrder', 'Purchase Orders'), ('GoodsReceivedNote', 'Goods Received Notes'), ('InvoiceVerification', 'Invoice Verification (3-Way Match)'), ('PurchaseReturn', 'Purchase Returns'), ('PaymentVoucher', 'Payment Vouchers'), ('Appropriation', 'Budget Appropriations'), ('Warrant', 'Cash Release Warrants'), ('RevenueWriteOff', 'Revenue Write-Offs'), ('AssetDisposal', 'Asset Disposals'), ('Budget', 'Budgets'), ('JournalEntry', 'Journal Entries'), ('LeaveRequest', 'Leave Requests'), ('PayrollRun', 'Payroll Runs')], max_length=30, unique=True),
        ),
    ]
