# Generated by Django 4.2.28 on 2026-04-10 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_organization_userorganization'),
        ('workflow', '0008_alter_globalapprovalsettings_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalgroup',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='MDA-scoped group; null = global group', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_groups', to='core.organization'),
        ),
        migrations.AddField(
            model_name='approvaltemplate',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='MDA-scoped template; null = global template', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_templates', to='core.organization'),
        ),
    ]
