# Generated by Django 4.2.28 on 2026-05-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_approvalgroup_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], db_index=True, default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['content_type', 'object_id'], name='approval_genericfk_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvalgroup',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='uniq_approvalgroup_name_per_org'),
        ),
    ]
