# Generated by Django 5.2.14 on 2026-05-24 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_usermfa_secret_encrypted_alter_usermfa_secret'),
        ('workflow', '0010_alter_approval_status_alter_approvalstep_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='MDA owning this approval; used by MDA-isolation queries.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='core.organization'),
        ),
    ]
