# Generated by Django 5.2.14 on 2026-06-06 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_re_encrypt_mfa_secrets_v2'),
        ('workflow', '0012_backfill_approval_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalgroup',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text="Indirect membership via curated roles. Users with an active RoleAssignment to any of these roles can act on this group's approval steps.", related_name='approval_groups', to='core.role'),
        ),
        migrations.AlterField(
            model_name='approvalgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='approval_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='globalapprovalsettings',
            name='module',
            field=models.CharField(choices=[('PurchaseRequest', 'Purchase Requests'), ('PurchaseOrder', 'Purchase Orders'), ('GoodsReceivedNote', 'Goods Received Notes'), ('InvoiceVerification', 'Invoice Verification (3-Way Match)'), ('PurchaseReturn', 'Purchase Returns'), ('PaymentVoucher', 'Payment Vouchers'), ('Appropriation', 'Budget Appropriations'), ('Warrant', 'Cash Release Warrants'), ('RevenueWriteOff', 'Revenue Write-Offs'), ('AssetDisposal', 'Asset Disposals'), ('Budget', 'Budgets'), ('Contract', 'Contracts (IPCs · Variations · Mobilisation · Retention)'), ('VendorInvoice', 'Vendor Invoices (AP)'), ('RevenueCollection', 'Revenue Collections (IGR)'), ('BankReconciliation', 'TSA Bank Reconciliations'), ('JournalEntry', 'Journal Entries'), ('LeaveRequest', 'Leave Requests'), ('PayrollRun', 'Payroll Runs')], max_length=30, unique=True),
        ),
    ]
