# Generated by Django 5.2.14 on 2026-09-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0013_approvalgroup_roles_alter_approvalgroup_members_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalapprovalsettings",
            name="module",
            field=models.CharField(
                choices=[
                    ("PurchaseRequest", "Purchase Requests"),
                    ("PurchaseOrder", "Purchase Orders"),
                    ("GoodsReceivedNote", "Goods Received Notes"),
                    ("InvoiceVerification", "Invoice Verification (3-Way Match)"),
                    ("PurchaseReturn", "Purchase Returns"),
                    ("PaymentVoucher", "Payment Vouchers"),
                    ("Appropriation", "Budget Appropriations"),
                    ("Warrant", "Cash Release Warrants"),
                    ("RevenueWriteOff", "Revenue Write-Offs"),
                    ("AssetDisposal", "Asset Disposals"),
                    ("Budget", "Budgets"),
                    (
                        "Contract",
                        "Contracts (IPCs · Variations · Mobilisation · Retention)",
                    ),
                    ("VendorInvoice", "Vendor Invoices (AP)"),
                    ("RevenueCollection", "Revenue Collections (IGR)"),
                    ("BankReconciliation", "TSA Bank Reconciliations"),
                    ("JournalEntry", "Journal Entries"),
                    ("LeaveRequest", "Leave Requests"),
                    ("PayrollRun", "Payroll Runs"),
                    ("PaymentDocument", "Payment Documents"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
    ]
