import type { ModuleConfig } from '../_base/types';

export const moduleConfig: ModuleConfig = {
  key: 'egp',
  label: 'e-Procurement & Tendering',
  icon: '🏷️',
  description: 'Tender notices, bidder registration, bids, evaluation and awards.',
  basePath: '/egp',
  entities: [
    {
      key: 'tenderNotice',
      plural: 'tenders',
      label: 'Tender Notices',
      searchField: 'title',
      idField: 'id',
      statusField: 'status',
      columns: [
        { name: 'reference', label: 'Reference', type: 'text' },
        { name: 'title', label: 'Title', type: 'text' },
        { name: 'category', label: 'Category', type: 'text', secondary: true },
        { name: 'method', label: 'Method', type: 'select', options: {
          open: 'Open Competitive Bidding',
          selective: 'Selective Bidding',
          restricted: 'Restricted Bidding',
          direct: 'Direct Procurement',
          two_stage: 'Two-Stage Bidding',
        }, secondary: true },
        { name: 'closing_date', label: 'Closing Date', type: 'date', secondary: true },
        { name: 'status', label: 'Status', type: 'select', options: {
          draft: 'Draft',
          published: 'Published',
          closed: 'Closed',
          cancelled: 'Cancelled',
        } },
      ],
      fields: [
        { name: 'reference', label: 'Reference', type: 'text', required: true },
        { name: 'title', label: 'Title', type: 'text', required: true },
        { name: 'description', label: 'Description', type: 'longtext' },
        { name: 'category', label: 'Category', type: 'text' },
        { name: 'method', label: 'Method', type: 'select', options: {
          open: 'Open Competitive Bidding',
          selective: 'Selective Bidding',
          restricted: 'Restricted Bidding',
          direct: 'Direct Procurement',
          two_stage: 'Two-Stage Bidding',
        }, required: true },
        { name: 'published_date', label: 'Published Date', type: 'date', required: true },
        { name: 'closing_date', label: 'Closing Date', type: 'date' },
        { name: 'status', label: 'Status', type: 'select', options: {
          draft: 'Draft',
          published: 'Published',
          closed: 'Closed',
          cancelled: 'Cancelled',
        }, required: true },
        { name: 'documents', label: 'Documents', type: 'text' },
        { name: 'created_at', label: 'Created At', type: 'datetime', readOnly: true, hideInForm: true },
        { name: 'updated_at', label: 'Updated At', type: 'datetime', readOnly: true, hideInForm: true },
      ],
    },
    {
      key: 'bidderRegistration',
      plural: 'bidder-registrations',
      label: 'Bidder Registrations',
      searchField: 'vendor',
      idField: 'id',
      statusField: 'status',
      columns: [
        { name: 'vendor', label: 'Vendor', type: 'integer', numeric: true },
        { name: 'status', label: 'Status', type: 'select', options: {
          pending: 'Pending',
          registered: 'Registered',
          suspended: 'Suspended',
          blacklisted: 'Blacklisted',
        } },
        { name: 'certificate_expiry', label: 'Certificate Expiry', type: 'date', secondary: true },
        { name: 'tax_clearance_expiry', label: 'Tax Clearance Expiry', type: 'date', secondary: true },
        { name: 'registered_at', label: 'Registered At', type: 'datetime', secondary: true },
      ],
      fields: [
        { name: 'vendor', label: 'Vendor', type: 'integer', numeric: true, required: true },
        { name: 'status', label: 'Status', type: 'select', options: {
          pending: 'Pending',
          registered: 'Registered',
          suspended: 'Suspended',
          blacklisted: 'Blacklisted',
        }, required: true },
        { name: 'certificate_expiry', label: 'Certificate Expiry', type: 'date' },
        { name: 'tax_clearance_expiry', label: 'Tax Clearance Expiry', type: 'date' },
        { name: 'pencom_evidence', label: 'PenCom Evidence', type: 'boolean' },
        { name: 'itf_compliance', label: 'ITF Compliance', type: 'boolean' },
        { name: 'categories', label: 'Categories', type: 'object' },
        { name: 'registered_at', label: 'Registered At', type: 'datetime', readOnly: true, hideInForm: true },
      ],
    },
    {
      key: 'bid',
      plural: 'bids',
      label: 'Bids',
      searchField: 'bidder',
      idField: 'id',
      statusField: 'status',
      columns: [
        { name: 'tender', label: 'Tender', type: 'integer', numeric: true },
        { name: 'bidder', label: 'Bidder', type: 'integer', numeric: true },
        { name: 'status', label: 'Status', type: 'select', options: {
          submitted: 'Submitted (Sealed)',
          opened: 'Opened',
          responsive: 'Responsive',
          non_responsive: 'Non-Responsive',
          disqualified: 'Disqualified',
          withdrawn: 'Withdrawn',
        } },
        { name: 'submitted_at', label: 'Submitted At', type: 'datetime', secondary: true },
        { name: 'opened_at', label: 'Opened At', type: 'datetime', secondary: true },
      ],
      fields: [
        { name: 'tender', label: 'Tender', type: 'integer', numeric: true, required: true },
        { name: 'bidder', label: 'Bidder', type: 'integer', numeric: true, required: true },
        { name: 'status', label: 'Status', type: 'select', options: {
          submitted: 'Submitted (Sealed)',
          opened: 'Opened',
          responsive: 'Responsive',
          non_responsive: 'Non-Responsive',
          disqualified: 'Disqualified',
          withdrawn: 'Withdrawn',
        }, required: true },
        { name: 'submitted_at', label: 'Submitted At', type: 'datetime', required: true },
        { name: 'encrypted_payload', label: 'Encrypted Payload', type: 'text' },
        { name: 'payload_hash', label: 'Payload Hash', type: 'text', readOnly: true, hideInForm: true },
        { name: 'opened_at', label: 'Opened At', type: 'datetime', readOnly: true, hideInForm: true },
        { name: 'opened_by', label: 'Opened By', type: 'integer', numeric: true, readOnly: true, hideInForm: true },
        { name: 'created_at', label: 'Created At', type: 'datetime', readOnly: true, hideInForm: true },
        { name: 'updated_at', label: 'Updated At', type: 'datetime', readOnly: true, hideInForm: true },
      ],
    },
    {
      key: 'bidDocument',
      plural: 'bid-documents',
      label: 'Bid Documents',
      searchField: 'name',
      idField: 'id',
      columns: [
        { name: 'bid', label: 'Bid', type: 'integer', numeric: true },
        { name: 'name', label: 'Name', type: 'text' },
        { name: 'file', label: 'File', type: 'text' },
      ],
      fields: [
        { name: 'bid', label: 'Bid', type: 'integer', numeric: true, required: true },
        { name: 'name', label: 'Name', type: 'text', required: true },
        { name: 'file', label: 'File', type: 'text', required: true },
      ],
    },
    {
      key: 'bidOpening',
      plural: 'bid-openings',
      label: 'Bid Openings',
      searchField: 'tender',
      idField: 'id',
      columns: [
        { name: 'tender', label: 'Tender', type: 'integer', numeric: true },
        { name: 'opened_at', label: 'Opened At', type: 'datetime' },
        { name: 'opened_by', label: 'Opened By', type: 'integer', numeric: true, secondary: true },
        { name: 'minutes', label: 'Minutes', type: 'longtext', secondary: true },
      ],
      fields: [
        { name: 'tender', label: 'Tender', type: 'integer', numeric: true, required: true },
        { name: 'opened_at', label: 'Opened At', type: 'datetime', required: true },
        { name: 'attendance', label: 'Attendance', type: 'object' },
        { name: 'opened_by', label: 'Opened By', type: 'integer', numeric: true, readOnly: true, hideInForm: true },
        { name: 'minutes', label: 'Minutes', type: 'longtext' },
      ],
    },
    {
      key: 'evaluationCommittee',
      plural: 'evaluation-committees',
      label: 'Evaluation Committees',
      searchField: 'name',
      idField: 'id',
      columns: [
        { name: 'tender', label: 'Tender', type: 'integer', numeric: true },
        { name: 'name', label: 'Name', type: 'text' },
        { name: 'members', label: 'Members', type: 'object', secondary: true },
        { name: 'is_active', label: 'Active', type: 'boolean' },
      ],
      fields: [
        { name: 'tender', label: 'Tender', type: 'integer', numeric: true, required: true },
        { name: 'name', label: 'Name', type: 'text', required: true },
        { name: 'members', label: 'Members', type: 'object' },
        { name: 'is_active', label: 'Active', type: 'boolean', required: true },
      ],
    },
    {
      key: 'evaluationCriterion',
      plural: 'evaluation-criteria',
      label: 'Evaluation Criteria',
      searchField: 'name',
      idField: 'id',
      columns: [
        { name: 'committee', label: 'Committee', type: 'integer', numeric: true },
        { name: 'name', label: 'Name', type: 'text' },
        { name: 'weight', label: 'Weight', type: 'decimal', numeric: true },
      ],
      fields: [
        { name: 'committee', label: 'Committee', type: 'integer', numeric: true, required: true },
        { name: 'name', label: 'Name', type: 'text', required: true },
        { name: 'weight', label: 'Weight', type: 'decimal', numeric: true, required: true },
      ],
    },
    {
      key: 'bidScore',
      plural: 'bid-scores',
      label: 'Bid Scores',
      searchField: 'bid',
      idField: 'id',
      columns: [
        { name: 'bid', label: 'Bid', type: 'integer', numeric: true },
        { name: 'criterion', label: 'Criterion', type: 'integer', numeric: true },
        { name: 'score', label: 'Score', type: 'decimal', numeric: true },
        { name: 'weighted_score', label: 'Weighted Score', type: 'decimal', numeric: true, readOnly: true, secondary: true },
        { name: 'comment', label: 'Comment', type: 'longtext', secondary: true },
      ],
      fields: [
        { name: 'bid', label: 'Bid', type: 'integer', numeric: true, required: true },
        { name: 'criterion', label: 'Criterion', type: 'integer', numeric: true, required: true },
        { name: 'score', label: 'Score', type: 'decimal', numeric: true, required: true },
        { name: 'weighted_score', label: 'Weighted Score', type: 'decimal', numeric: true, readOnly: true, hideInForm: true },
        { name: 'comment', label: 'Comment', type: 'longtext' },
        { name: 'scored_by', label: 'Scored By', type: 'integer', numeric: true, readOnly: true, hideInForm: true },
      ],
    },
    {
      key: 'tenderAward',
      plural: 'awards',
      label: 'Tender Awards',
      searchField: 'tender',
      idField: 'id',
      statusField: 'status',
      columns: [
        { name: 'tender', label: 'Tender', type: 'integer', numeric: true },
        { name: 'winning_bid', label: 'Winning Bid', type: 'integer', numeric: true },
        { name: 'award_amount', label: 'Award Amount', type: 'decimal', numeric: true },
        { name: 'status', label: 'Status', type: 'select', options: {
          draft: 'Draft',
          approved: 'Approved',
          contract_created: 'Contract Created',
          cancelled: 'Cancelled',
        } },
        { name: 'awarded_at', label: 'Awarded At', type: 'datetime', secondary: true },
      ],
      fields: [
        { name: 'tender', label: 'Tender', type: 'integer', numeric: true, required: true },
        { name: 'winning_bid', label: 'Winning Bid', type: 'integer', numeric: true, required: true },
        { name: 'status', label: 'Status', type: 'select', options: {
          draft: 'Draft',
          approved: 'Approved',
          contract_created: 'Contract Created',
          cancelled: 'Cancelled',
        }, required: true },
        { name: 'award_amount', label: 'Award Amount', type: 'decimal', numeric: true, required: true },
        { name: 'contract', label: 'Contract', type: 'integer', numeric: true },
        { name: 'purchase_order', label: 'Purchase Order', type: 'integer', numeric: true },
        { name: 'awarded_at', label: 'Awarded At', type: 'datetime', readOnly: true, hideInForm: true },
        { name: 'awarded_by', label: 'Awarded By', type: 'integer', numeric: true, readOnly: true, hideInForm: true },
        { name: 'created_at', label: 'Created At', type: 'datetime', readOnly: true, hideInForm: true },
        { name: 'updated_at', label: 'Updated At', type: 'datetime', readOnly: true, hideInForm: true },
      ],
    },
  ],
};
