# Generated by Django 6.0.2 on 2026-02-13 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='quantity_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='vendor',
            name='on_time_deliveries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='quality_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='vendor',
            name='total_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='total_purchase_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Posted', 'Posted'), ('Rejected', 'Rejected'), ('Closed', 'Closed')], default='Draft', max_length=20),
        ),
        migrations.CreateModel(
            name='InvoiceMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_reference', models.CharField(max_length=50)),
                ('invoice_date', models.DateField()),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('po_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('grn_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Matched', 'Matched'), ('Variance', 'Variance'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('variance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('variance_reason', models.TextField(blank=True)),
                ('matched_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('goods_received_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_matchings', to='procurement.goodsreceivednote')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_matchings', to='procurement.purchaseorder')),
            ],
        ),
    ]
