# Generated by Django 6.0.2 on 2026-02-14 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_fix'),
        ('procurement', '0004_fix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderline',
            old_name='order',
            new_name='po',
        ),
        migrations.RemoveField(
            model_name='goodsreceivednote',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='goodsreceivednoteline',
            name='item_description',
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='received_by',
            field=models.CharField(default='SYSTEM', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicematching',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicematching',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicematching',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='invoicematching',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='mda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.mda'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='mda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.mda'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procurement.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoicematching',
            name='goods_received_note',
            field=models.ForeignKey(default=1, null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, to='procurement.goodsreceivednote'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoicematching',
            name='grn_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoicematching',
            name='matched_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoicematching',
            name='po_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoicematching',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procurement.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='invoicematching',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Matched', 'Matched'), ('Variance', 'Variance'), ('Approved', 'Approved')], default='Draft', max_length=20),
        ),
    ]
