# Generated by Django 6.0.2 on 2026-02-14 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicematching',
            name='goods_received_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procurement.goodsreceivednote'),
        ),
    ]
