# Generated by Django 6.0.2 on 2026-02-14 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicematching',
            name='goods_received_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='procurement.goodsreceivednote'),
        ),
        migrations.AlterField(
            model_name='invoicematching',
            name='grn_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='invoicematching',
            name='po_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='invoicematching',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='procurement.purchaseorder'),
        ),
    ]
