# Generated by Django 6.0.2 on 2026-02-14 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_fix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='status',
        ),
    ]
