# Generated by Django 6.0.2 on 2026-02-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_remove_purchaserequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Draft', max_length=20),
        ),
    ]
