# Generated by Django 6.0.2 on 2026-02-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0010_enhance_procurement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasetype',
            options={'verbose_name_plural': 'Purchase Types (Legacy)'},
        ),
        migrations.AddField(
            model_name='purchasetype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Received', 'Received'), ('Posted', 'Posted'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20),
        ),
    ]
