# Generated by Django 6.0.2 on 2026-03-01 19:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_alter_budgettransfer_approved_by'),
        ('procurement', '0012_goodsreceivednote_notes_goodsreceivednoteline_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='goodsreceivednote',
            index=models.Index(fields=['status'], name='procurement_status_0dade5_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceivednote',
            index=models.Index(fields=['purchase_order'], name='procurement_purchas_b11f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicematching',
            index=models.Index(fields=['status'], name='procurement_status_f83f00_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='procurement_status_6b6895_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['vendor'], name='procurement_vendor__395a70_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['status'], name='procurement_status_4e1362_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['status'], name='procurement_status_94223b_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['vendor'], name='procurement_vendor__8370bd_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['is_active'], name='procurement_is_acti_e35e27_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorcreditnote',
            index=models.Index(fields=['status'], name='procurement_status_47f128_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorcreditnote',
            index=models.Index(fields=['vendor'], name='procurement_vendor__9733f9_idx'),
        ),
        migrations.AddIndex(
            model_name='vendordebitnote',
            index=models.Index(fields=['status'], name='procurement_status_af8b42_idx'),
        ),
        migrations.AddIndex(
            model_name='vendordebitnote',
            index=models.Index(fields=['vendor'], name='procurement_vendor__4eeb71_idx'),
        ),
    ]
