# Generated by Django 6.0.2 on 2026-03-01 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0013_goodsreceivednote_procurement_status_0dade5_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'permissions': [('approve_purchaseorder', 'Can approve purchase orders')]},
        ),
        migrations.AlterModelOptions(
            name='purchaserequest',
            options={'permissions': [('approve_purchaserequest', 'Can approve purchase requests')]},
        ),
    ]
