# Generated by Django 6.0.2 on 2026-03-05 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_stockmovement_options'),
        ('procurement', '0014_alter_purchaseorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceivednote',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Receiving warehouse for this GRN', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse'),
        ),
    ]
