# Generated by Django 6.0.2 on 2026-03-07 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_add_asset_to_purchaseorderline'),
        ('procurement', '0015_add_warehouse_to_grn'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_lines', to='accounting.fixedasset'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='accounting.costcenter'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_request_lines', to='accounting.fixedasset'),
        ),
    ]
