# Generated by Django 6.0.2 on 2026-03-07 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_stockmovement_options'),
        ('procurement', '0016_add_asset_to_purchaseorderline'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequestline',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_request_lines', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_request_lines', to='inventory.productcategory'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_request_lines', to='inventory.producttype'),
        ),
    ]
