# Generated by Django 4.2.28 on 2026-03-18 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procurement', '0018_purchase_return_po_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceMatchingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_variance_percent', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('price_variance_percent', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('allow_partial_match', models.BooleanField(default=True)),
                ('auto_escalate_unmatched', models.BooleanField(default=True)),
                ('escalation_threshold_days', models.IntegerField(default=3)),
                ('require_grn_for_payment', models.BooleanField(default=True)),
                ('auto_approve_matched', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Invoice Matching Settings',
                'verbose_name_plural': 'Invoice Matching Settings',
            },
        ),
        migrations.CreateModel(
            name='VendorContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('contract_value', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('auto_renew', models.BooleanField(default=False)),
                ('renewal_terms_days', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Expired', 'Expired'), ('Terminated', 'Terminated')], default='Draft', max_length=20)),
                ('document', models.FileField(blank=True, null=True, upload_to='vendor_contracts/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='procurement.vendor')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='VendorClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('New', 'New'), ('Qualified', 'Qualified'), ('Approved', 'Approved'), ('Preferred', 'Preferred'), ('Blocked', 'Blocked')], default='New', max_length=20)),
                ('qualification_date', models.DateField(blank=True, null=True)),
                ('qualification_expiry', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_approvals', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='procurement.vendor')),
            ],
            options={
                'ordering': ['-is_current', '-qualification_date'],
            },
        ),
    ]
