# Generated by Django 4.2.28 on 2026-03-24 20:12

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0019_invoicematchingsettings_vendorcontract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicematching',
            name='payment_hold',
            field=models.BooleanField(default=False, help_text='Automatically set when invoice variance exceeds threshold. Must be cleared before payment.'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednoteline',
            name='quantity_received',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='quantity_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='estimated_unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='purchasereturnline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='purchasereturnline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='vendorcontract',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='vendor_contracts/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'xlsx', 'jpg', 'png'])]),
        ),
    ]
