# Generated by Django 4.2.28 on 2026-03-26 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0038_baddebtwriteoff_financialratio_and_more'),
        ('procurement', '0020_invoicematching_payment_hold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicematching',
            name='vendor_invoice',
            field=models.ForeignKey(blank=True, help_text='Link to the accounting VendorInvoice for payment processing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_matchings', to='accounting.vendorinvoice'),
        ),
    ]
