# Generated by Django 4.2.28 on 2026-03-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0021_add_vendor_invoice_to_invoice_matching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Received', 'Received'), ('On Hold', 'On Hold'), ('Posted', 'Posted'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20),
        ),
    ]
