# Generated by Django 6.0.2 on 2026-03-31 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0050_accountingsettings_sales_downpayment'),
        ('procurement', '0029_purchasereturnline_po_line_item_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Vendor Categories',
                'ordering': ['name'],
            },
        ),
        migrations.RenameIndex(
            model_name='purchasereturn',
            new_name='procurement_purchas_98aebf_idx',
            old_name='procurement_purchas_da7e1c_idx',
        ),
        migrations.AddField(
            model_name='vendorcategory',
            name='reconciliation_account',
            field=models.ForeignKey(help_text='AP reconciliation account from Chart of Accounts', limit_choices_to={'reconciliation_type': 'accounts_payable'}, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_categories', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendors', to='procurement.vendorcategory'),
        ),
    ]
