# Generated by Django 6.0.2 on 2026-04-03 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0051_add_tax_gl_and_wht_fields'),
        ('procurement', '0031_vendor_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='accounting.taxcode'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='wht_exempt',
            field=models.BooleanField(default=False, help_text='Exempt this transaction from withholding tax'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='wht_exempt',
            field=models.BooleanField(default=False, help_text='Exempt this vendor from withholding tax'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='withholding_tax_code',
            field=models.ForeignKey(blank=True, help_text='Default WHT code applied to this vendor on transactions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='accounting.withholdingtax'),
        ),
    ]
