# Generated by Django 4.2.28 on 2026-04-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0032_add_tax_gl_and_wht_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceivednoteline',
            name='batch_number',
            field=models.CharField(blank=True, default='', help_text='Batch or lot number from the supplier label.', max_length=100),
        ),
        migrations.AddField(
            model_name='goodsreceivednoteline',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Expiry / best-before date from the supplier label.', null=True),
        ),
    ]
