# Generated by Django 4.2.28 on 2026-04-09 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0056_ncoa_segments'),
        ('budget', '0006_ncoa_segments'),
        ('procurement', '0035_pr_line_account_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('GOODS_SERVICES', 'Goods & Services'), ('WORKS', 'Works / Construction'), ('CONSULTANCY', 'Consultancy Services')], max_length=20)),
                ('authority_level', models.CharField(choices=[('ACCOUNTING_OFFICER', 'Accounting Officer'), ('PTB', 'Parastatal Tenders Board (PTB)'), ('MTB', 'Ministerial Tenders Board (MTB)'), ('EXCO', 'State Executive Council'), ('BPP', 'Bureau of Public Procurement')], max_length=25)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Null = unlimited (highest tier)', max_digits=20, null=True)),
                ('requires_bpp_no', models.BooleanField(default=False, help_text='Requires No Objection Certificate from BPP')),
                ('is_active', models.BooleanField(default=True)),
                ('fiscal_year', models.ForeignKey(blank=True, help_text='Null = applies to all fiscal years', null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.fiscalyear')),
            ],
            options={
                'verbose_name': 'BPP Procurement Threshold',
                'verbose_name_plural': 'BPP Procurement Thresholds',
                'ordering': ['category', 'min_amount'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementBudgetLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committed_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('committed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Commitment'), ('INVOICED', 'Partially/Fully Invoiced'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('appropriation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commitments', to='budget.appropriation')),
                ('ncoa_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_commitments', to='accounting.ncoacode')),
                ('purchase_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='budget_link', to='procurement.purchaseorder')),
            ],
            options={
                'verbose_name': 'Procurement Budget Link',
                'verbose_name_plural': 'Procurement Budget Links',
            },
        ),
        migrations.CreateModel(
            name='CertificateOfNoObjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('issued_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('authority_level', models.CharField(max_length=25)),
                ('issuing_officer', models.CharField(max_length=200)),
                ('is_valid', models.BooleanField(default=True)),
                ('amount_covered', models.DecimalField(decimal_places=2, max_digits=20)),
                ('scope_description', models.TextField()),
                ('conditions', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='no_objection', to='procurement.purchaseorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificate of No Objection',
                'verbose_name_plural': 'Certificates of No Objection',
            },
        ),
    ]
