# Generated by Django 4.2.28 on 2026-04-12 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0058_administrativesegment_legacy_mda_and_more'),
        ('procurement', '0036_procurementthreshold_procurementbudgetlink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_sort_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='vendor',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Registration expiry date (typically end of fiscal year)', null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='registration_date',
            field=models.DateField(blank=True, help_text='Date vendor was registered/renewed', null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='registration_fiscal_year',
            field=models.ForeignKey(blank=True, help_text='Fiscal year this registration is valid for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_vendors', to='accounting.fiscalyear'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='registration_number',
            field=models.CharField(blank=True, default='', help_text='BPP/State registration certificate number', max_length=50),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['expiry_date'], name='procurement_expiry__0cc6c7_idx'),
        ),
    ]
