# Generated by Django 4.2.28 on 2026-04-12 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0058_administrativesegment_legacy_mda_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procurement', '0037_vendor_bank_account_number_vendor_bank_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorRenewalInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('GENERATED', 'Invoice Generated'), ('SENT', 'Sent to Vendor'), ('PAID', 'Payment Confirmed'), ('CANCELLED', 'Cancelled')], default='GENERATED', max_length=15)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, default='', help_text='Vendor payment receipt/teller number', max_length=50)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(help_text='Fiscal year the vendor is renewing for', on_delete=django.db.models.deletion.PROTECT, related_name='renewal_invoices', to='accounting.fiscalyear')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_invoices', to='accounting.journalheader')),
                ('tsa_account', models.ForeignKey(help_text='TSA bank account where vendor should pay', on_delete=django.db.models.deletion.PROTECT, related_name='renewal_invoices', to='accounting.treasuryaccount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renewal_invoices', to='procurement.vendor')),
            ],
            options={
                'ordering': ['-invoice_date'],
                'indexes': [models.Index(fields=['vendor', 'status'], name='procurement_vendor__9710a3_idx'), models.Index(fields=['fiscal_year', 'status'], name='procurement_fiscal__ea5c08_idx')],
            },
        ),
    ]
