# Generated by Django 4.2.28 on 2026-04-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0038_vendorrenewalinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorrenewalinvoice',
            name='invoice_type',
            field=models.CharField(choices=[('REGISTRATION', 'Initial Registration'), ('RENEWAL', 'Annual Renewal')], default='RENEWAL', max_length=15),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Activated only after registration payment is confirmed'),
        ),
    ]
