# Generated by Django 4.2.28 on 2026-04-16 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_remove_item_production_bom_and_more'),
        ('procurement', '0040_grn_mda_and_warehouse_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Receiving warehouse for this GRN. Auto-resolved from the MDA via inventory.services.get_default_warehouse_for_mda() — not exposed in the UI.', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse'),
        ),
    ]
