# Generated by Django 4.2.28 on 2026-04-19 00:39

from django.db import migrations, models


# Priority order for keeping the "winner" PO when de-duplicating against a
# single PR. More progressed workflow states outrank earlier ones so we
# never demote a posted/closed PO to Rejected.
_STATUS_PRIORITY = {
    'Closed':   60,
    'Posted':   50,
    'Approved': 40,
    'Pending':  30,
    'Draft':    20,
    'Rejected': 10,
}


def demote_duplicate_pos(apps, schema_editor):
    """Before we can add the unique constraint, collapse any existing
    (PR → many active POs) violations.

    Strategy: pick the PO with the highest workflow priority for each PR
    (ties broken by pk asc — oldest wins) as the canonical row. Mark every
    other PO on that PR as ``status='Rejected'`` and note the reason in
    the ``notes`` field so auditors can see why the demotion happened.

    No rows are deleted — the audit trail stays intact.
    """
    PurchaseOrder = apps.get_model('procurement', 'PurchaseOrder')
    from django.db.models import Count

    dupe_keys = (
        PurchaseOrder.objects
        .exclude(status='Rejected')
        .exclude(purchase_request__isnull=True)
        .values('purchase_request')
        .annotate(n=Count('id'))
        .filter(n__gt=1)
    )
    for key in dupe_keys:
        pos = list(
            PurchaseOrder.objects.filter(
                purchase_request_id=key['purchase_request'],
            ).exclude(status='Rejected').order_by('pk')
        )
        # Rank by status priority, ties resolved by oldest pk
        pos.sort(
            key=lambda p: (-_STATUS_PRIORITY.get(p.status, 0), p.pk),
        )
        keeper = pos[0]
        for extra in pos[1:]:
            reason = (
                f'Auto-demoted on migration: duplicate conversion of '
                f'PR #{key["purchase_request"]} — kept {keeper.po_number} '
                f'({keeper.status}) as canonical.'
            )
            existing_notes = (extra.notes or '').strip()
            extra.notes = (
                f'{existing_notes}\n\n[MIGRATION] {reason}'
                if existing_notes else f'[MIGRATION] {reason}'
            )
            extra.status = 'Rejected'
            extra.save(update_fields=['status', 'notes'])


def noop_reverse(apps, schema_editor):
    """Reverse is a no-op — we cannot reconstruct prior statuses."""
    pass


class Migration(migrations.Migration):

    # Non-atomic: PostgreSQL refuses to add a partial-index constraint
    # in the same transaction that just updated the underlying rows
    # (pending FK trigger events). Split the RunPython and the
    # AddConstraint so the data changes commit first.
    atomic = False

    dependencies = [
        ('procurement', '0042_perf_indexes'),
    ]

    operations = [
        migrations.RunPython(demote_duplicate_pos, noop_reverse),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(
                condition=models.Q(('purchase_request__isnull', False), models.Q(('status', 'Rejected'), _negated=True)),
                fields=('purchase_request',),
                name='uniq_active_po_per_purchase_request',
            ),
        ),
    ]
