# Generated by Django 4.2.28 on 2026-04-19 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0084_depreciation_run_schedule'),
        ('procurement', '0043_purchaseorder_uniq_active_po_per_purchase_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicematching',
            name='tax_code',
            field=models.ForeignKey(blank=True, help_text='VAT / input-tax code to apply to invoice subtotal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_matchings', to='accounting.taxcode'),
        ),
        migrations.AddField(
            model_name='invoicematching',
            name='wht_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Computed WHT amount = subtotal × withholding_tax.rate.', max_digits=15),
        ),
        migrations.AddField(
            model_name='invoicematching',
            name='withholding_tax',
            field=models.ForeignKey(blank=True, help_text='Withholding tax code to apply to invoice subtotal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_matchings', to='accounting.withholdingtax'),
        ),
    ]
