# Generated by Django 4.2.28 on 2026-04-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0044_invoicematching_tax_code_invoicematching_wht_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicematching',
            name='wht_exempt',
            field=models.BooleanField(default=False, help_text='Exempt this transaction from withholding tax, overriding the vendor default.'),
        ),
        migrations.AddField(
            model_name='invoicematching',
            name='wht_exempt_reason',
            field=models.CharField(blank=True, default='', help_text='Audit reason for the transaction-level WHT exemption.', max_length=255),
        ),
    ]
