# Generated by Django 4.2.28 on 2026-05-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0047_invoicematching_verification_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicematching',
            name='gl_post_error',
            field=models.TextField(blank=True, default='', help_text='Last GL auto-post error from the workflow signal — cleared on successful retry.'),
        ),
        migrations.AddIndex(
            model_name='invoicematching',
            index=models.Index(fields=['verification_number'], name='procurement_verific_a7172b_idx'),
        ),
    ]
