# Generated by Django 5.2.14 on 2026-08-12 00:59

import procurement.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0048_add_invoicematching_gl_post_error"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="bank_account_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="10-digit NUBAN. Optional here; required before the payment can join a bank payment batch.",
                max_length=20,
                validators=[procurement.validators.validate_nuban],
            ),
        ),
    ]
