# Generated by Django 5.2.14 on 2026-09-20 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0128_remove_payment_uniq_live_payment_per_pv_and_more"),
        ("procurement", "0049_alter_vendor_bank_account_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="downpaymentrequest",
            name="payment_voucher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="down_payment_requests",
                to="accounting.paymentvouchergov",
            ),
        ),
    ]
