import type { ModuleConfig } from '../_base/types';

export const moduleConfig: ModuleConfig = {
  key: 'transparency',
  label: 'Fiscal Transparency Portal',
  icon: '🔎',
  description:
    'Publication policies, fiscal publications, redaction rules and data exports.',
  basePath: '/transparency',
  entities: [
    {
      key: 'publicationPolicy',
      plural: 'policies',
      label: 'Publication Policy',
      searchField: 'dataset',
      statusField: 'status',
      idField: 'id',
      columns: [
        { name: 'dataset', label: 'Dataset', type: 'select', options: { enacted_budget: 'Enacted Budget', budget_execution: 'Budget Execution', contract_awards: 'Contract Awards', payments: 'Payments Above Threshold', revenue_performance: 'Revenue Performance', citizen_budget: 'Citizen Budget Summary' } },
        { name: 'aggregation', label: 'Aggregation Level', type: 'text' },
        { name: 'lag_days', label: 'Lag Days', type: 'integer', numeric: true },
        { name: 'min_amount_threshold', label: 'Min Amount', type: 'decimal', numeric: true },
        { name: 'status', label: 'Status', type: 'select', options: { draft: 'Draft', approved: 'Approved', superseded: 'Superseded' } },
      ],
      fields: [
        { name: 'dataset', label: 'Dataset', type: 'select', required: true, options: { enacted_budget: 'Enacted Budget', budget_execution: 'Budget Execution', contract_awards: 'Contract Awards', payments: 'Payments Above Threshold', revenue_performance: 'Revenue Performance', citizen_budget: 'Citizen Budget Summary' } },
        { name: 'aggregation', label: 'Aggregation Level', type: 'text', required: true },
        { name: 'lag_days', label: 'Lag Days', type: 'integer', required: true, numeric: true },
        { name: 'min_amount_threshold', label: 'Min Amount Threshold', type: 'decimal', required: true, numeric: true },
        { name: 'requires_snapshot', label: 'Requires Snapshot', type: 'boolean' },
        { name: 'status', label: 'Status', type: 'select', required: true, options: { draft: 'Draft', approved: 'Approved', superseded: 'Superseded' } },
        { name: 'approved_by', label: 'Approved By', type: 'text', readOnly: true, hideInForm: true },
        { name: 'approved_at', label: 'Approved At', type: 'datetime', readOnly: true, hideInForm: true },
        { name: 'created_at', label: 'Created At', type: 'datetime', readOnly: true, hideInForm: true },
        { name: 'updated_at', label: 'Updated At', type: 'datetime', readOnly: true, hideInForm: true },
      ],
    },
    {
      key: 'publication',
      plural: 'publications',
      label: 'Publication',
      searchField: 'title',
      statusField: 'status',
      idField: 'id',
      columns: [
        { name: 'title', label: 'Title', type: 'text' },
        { name: 'dataset_key', label: 'Dataset Key', type: 'text' },
        { name: 'fiscal_year', label: 'Fiscal Year', type: 'integer', numeric: true, secondary: true },
        { name: 'status', label: 'Status', type: 'select', options: { queued: 'Queued', published: 'Published', retracted: 'Retracted' } },
        { name: 'published_at', label: 'Published At', type: 'datetime', secondary: true },
      ],
      fields: [
        { name: 'policy', label: 'Policy', type: 'integer', required: true, reference: { module: 'transparency', entity: 'publicationPolicy' } },
        { name: 'snapshot', label: 'Report Snapshot', type: 'integer', reference: { module: 'accounting', entity: 'reportSnapshot' } },
        { name: 'title', label: 'Title', type: 'text', required: true },
        { name: 'dataset_key', label: 'Dataset Key', type: 'text', required: true },
        { name: 'fiscal_year', label: 'Fiscal Year', type: 'integer', numeric: true },
        { name: 'period', label: 'Period', type: 'integer', numeric: true },
        { name: 'status', label: 'Status', type: 'select', required: true, options: { queued: 'Queued', published: 'Published', retracted: 'Retracted' } },
        { name: 'published_at', label: 'Published At', type: 'datetime', readOnly: true, hideInForm: true },
        { name: 'published_url', label: 'Published URL', type: 'text' },
        { name: 'published_by', label: 'Published By', type: 'integer', readOnly: true, hideInForm: true },
        { name: 'created_at', label: 'Created At', type: 'datetime', readOnly: true, hideInForm: true },
        { name: 'updated_at', label: 'Updated At', type: 'datetime', readOnly: true, hideInForm: true },
      ],
    },
    {
      key: 'redactionRule',
      plural: 'redaction-rules',
      label: 'Redaction Rule',
      searchField: 'field_name',
      idField: 'id',
      columns: [
        { name: 'field_name', label: 'Field Name', type: 'select', options: { employee_name: 'Employee Name', employee_number: 'Employee Number', vendor_name: 'Vendor Name', vendor_bvn: 'Vendor BVN', vendor_tin: 'Vendor TIN', phone: 'Phone Number', email: 'Email Address', address: 'Physical Address', bank_account: 'Bank Account Number' } },
        { name: 'pattern', label: 'Pattern', type: 'text', secondary: true },
        { name: 'replacement', label: 'Replacement', type: 'text' },
        { name: 'is_active', label: 'Active', type: 'boolean' },
      ],
      fields: [
        { name: 'field_name', label: 'Field Name', type: 'select', required: true, options: { employee_name: 'Employee Name', employee_number: 'Employee Number', vendor_name: 'Vendor Name', vendor_bvn: 'Vendor BVN', vendor_tin: 'Vendor TIN', phone: 'Phone Number', email: 'Email Address', address: 'Physical Address', bank_account: 'Bank Account Number' } },
        { name: 'pattern', label: 'Pattern', type: 'text', placeholder: 'Optional regex for the sensitive value' },
        { name: 'replacement', label: 'Replacement', type: 'text', required: true },
        { name: 'is_active', label: 'Active', type: 'boolean' },
      ],
    },
    {
      key: 'dataExport',
      plural: 'exports',
      label: 'Data Export',
      searchField: 'dataset_key',
      idField: 'id',
      columns: [
        { name: 'dataset_key', label: 'Dataset Key', type: 'text' },
        { name: 'format', label: 'Format', type: 'select', options: { csv: 'CSV', json: 'JSON' } },
        { name: 'publication', label: 'Publication', type: 'integer', numeric: true },
        { name: 'row_count', label: 'Row Count', type: 'integer', numeric: true },
        { name: 'created_at', label: 'Created At', type: 'datetime', secondary: true },
      ],
      fields: [
        { name: 'dataset_key', label: 'Dataset Key', type: 'text', required: true },
        { name: 'format', label: 'Format', type: 'select', required: true, options: { csv: 'CSV', json: 'JSON' } },
        { name: 'publication', label: 'Publication', type: 'integer', required: true, reference: { module: 'transparency', entity: 'publication' } },
        { name: 'file', label: 'File', type: 'text', readOnly: true, hideInForm: true },
        { name: 'row_count', label: 'Row Count', type: 'integer', numeric: true },
        { name: 'created_at', label: 'Created At', type: 'datetime', readOnly: true, hideInForm: true },
      ],
    },
  ],
};
