# Generated by Django 6.0.2 on 2026-02-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalheader',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Posted', 'Posted'), ('Rejected', 'Rejected')], default='Draft', max_length=20),
        ),
    ]
