# Generated by Django 6.0.2 on 2026-02-14 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_fix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('revised_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('control_level', models.CharField(choices=[('NONE', 'No Control'), ('WARNING', 'Warning Only'), ('HARD_STOP', 'Hard Stop')], default='HARD_STOP', max_length=10)),
                ('enable_encumbrance', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.account')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets_created', to=settings.AUTH_USER_MODEL)),
                ('function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.function')),
                ('fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.fund')),
                ('geo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.geo')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.program')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amendment_type', models.CharField(choices=[('INCREASE', 'Increase'), ('DECREASE', 'Decrease'), ('TRANSFER', 'Transfer')], max_length=10)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('new_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('requested_date', models.DateField(auto_now_add=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments_approved', to=settings.AUTH_USER_MODEL)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='accounting.budget')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_date'],
            },
        ),
        migrations.CreateModel(
            name='BudgetAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=20)),
                ('transaction_id', models.IntegerField()),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('anomaly_score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('anomaly_type', models.CharField(choices=[('UNUSUAL_AMOUNT', 'Unusual Amount'), ('UNUSUAL_TIMING', 'Unusual Timing'), ('UNUSUAL_PATTERN', 'Unusual Pattern')], max_length=20)),
                ('description', models.TextField()),
                ('reviewed', models.BooleanField(default=False)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='accounting.budget')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=20)),
                ('transaction_id', models.IntegerField()),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('available_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('check_result', models.CharField(choices=[('PASSED', 'Passed'), ('WARNING', 'Warning'), ('BLOCKED', 'Blocked')], max_length=10)),
                ('override_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_logs', to='accounting.budget')),
                ('override_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetEncumbrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_type', models.CharField(choices=[('PR', 'Purchase Requisition'), ('PO', 'Purchase Order'), ('CONTRACT', 'Contract')], max_length=20)),
                ('reference_id', models.IntegerField()),
                ('encumbrance_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('liquidated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PARTIALLY_LIQUIDATED', 'Partially Liquidated'), ('FULLY_LIQUIDATED', 'Fully Liquidated'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=25)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encumbrances', to='accounting.budget')),
            ],
            options={
                'ordering': ['-encumbrance_date'],
            },
        ),
        migrations.CreateModel(
            name='BudgetForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('predicted_utilization_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('predicted_exhaustion_date', models.DateField(blank=True, null=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('model_version', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='accounting.budget')),
            ],
            options={
                'ordering': ['-forecast_date'],
            },
        ),
        migrations.CreateModel(
            name='BudgetPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField()),
                ('period_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUAL', 'Annual')], max_length=10)),
                ('period_number', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fiscal_year', '-period_number'],
                'unique_together': {('fiscal_year', 'period_type', 'period_number')},
            },
        ),
        migrations.AddField(
            model_name='budget',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='accounting.budgetperiod'),
        ),
        migrations.CreateModel(
            name='BudgetTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('transfer_date', models.DateField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_approved', to=settings.AUTH_USER_MODEL)),
                ('from_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='accounting.budget')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_requested', to=settings.AUTH_USER_MODEL)),
                ('to_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='accounting.budget')),
            ],
            options={
                'ordering': ['-transfer_date'],
            },
        ),
        migrations.CreateModel(
            name='MDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=50)),
                ('mda_type', models.CharField(choices=[('MINISTRY', 'Ministry'), ('DEPARTMENT', 'Department'), ('AGENCY', 'Agency'), ('PARASTATAL', 'Parastatal')], max_length=20)),
                ('head_of_entity', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_mda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_entities', to='accounting.mda')),
            ],
            options={
                'verbose_name': 'MDA',
                'verbose_name_plural': 'MDAs',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='budget',
            name='mda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='accounting.mda'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['budget_code'], name='accounting__budget__d5e1fb_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['mda', 'period'], name='accounting__mda_id_2f29f7_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['period', 'account'], name='accounting__period__51e8b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('period', 'mda', 'account', 'fund', 'function', 'program', 'geo')},
        ),
    ]
