# Generated by Django 6.0.2 on 2026-02-14 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinvoice',
            name='mda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.mda'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='mda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.mda'),
        ),
        migrations.AddField(
            model_name='journalheader',
            name='mda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.mda'),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='mda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.mda'),
        ),
    ]
