# Generated by Django 6.0.2 on 2026-02-14 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorinvoice',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.account'),
        ),
    ]
