# Generated by Django 6.0.2 on 2026-02-16 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_product_type_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consolidationgroup',
            name='companies',
            field=models.ManyToManyField(related_name='member_consolidation_groups', to='accounting.intercompany'),
        ),
        migrations.AlterField(
            model_name='consolidationgroup',
            name='parent_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_consolidation_groups', to='accounting.intercompany'),
        ),
        migrations.AlterField(
            model_name='costallocationrule',
            name='allocation_method',
            field=models.CharField(choices=[('Percentage', 'Percentage'), ('Equal', 'Equal'), ('Based on Revenue', 'Based on Revenue'), ('Based on Headcount', 'Based on Headcount'), ('Based on Square Footage', 'Based on Square Footage'), ('Custom', 'Custom')], max_length=25),
        ),
    ]
