# Generated by Django 6.0.2 on 2026-03-01 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_alter_budgettransfer_approved_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['budget_code'], 'permissions': [('approve_budget', 'Can approve budgets')]},
        ),
        migrations.AlterModelOptions(
            name='budgettransfer',
            options={'ordering': ['-transfer_date'], 'permissions': [('approve_budgettransfer', 'Can approve budget transfers')]},
        ),
        migrations.AlterModelOptions(
            name='journalheader',
            options={'ordering': ['-posting_date', '-id'], 'permissions': [('post_journalheader', 'Can post journal entries to GL'), ('approve_journalheader', 'Can approve journal entries')]},
        ),
    ]
