# Generated by Django 6.0.2 on 2026-03-07 18:23

import django.db.models.deletion
from django.db import migrations, models


def add_is_operational_if_missing(apps, schema_editor):
    """Add is_operational column only if it doesn't already exist."""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_name = 'accounting_costcenter' AND column_name = 'is_operational'"
        )
        if not cursor.fetchone():
            cursor.execute(
                'ALTER TABLE "accounting_costcenter" ADD COLUMN "is_operational" boolean DEFAULT true NOT NULL'
            )


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_alter_budget_options_alter_budgettransfer_options_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_is_operational_if_missing, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='costcenter',
                    name='is_operational',
                    field=models.BooleanField(default=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='glbalance',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.account'),
        ),
    ]
