# Generated by Django 6.0.2 on 2026-03-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_customerinvoiceline_vendorinvoiceline'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorinvoice',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='vendor_invoices/attachments/'),
        ),
    ]
