# Generated by Django 4.2.28 on 2026-03-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_add_asset_to_purchaseorderline'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalline',
            name='document_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
