# Generated by Django 4.2.28 on 2026-03-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_journalline_document_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('prefix', models.CharField(blank=True, max_length=10)),
                ('next_value', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='document_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='journalheader',
            name='document_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='document_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='document_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='document_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
