# Generated by Django 4.2.28 on 2026-03-17 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0026_transactionsequence_customerinvoice_document_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetperiod',
            name='allow_adjustments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='budgetperiod',
            name='allow_postings',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='budgetperiod',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_periods_closed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetperiod',
            name='closed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetperiod',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_periods_locked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetperiod',
            name='locked_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetperiod',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='budgetperiod',
            name='fiscal_year',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='budgetperiod',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open for Posting'), ('ADJUSTMENT', 'Adjustment Period'), ('CLOSED', 'Closed'), ('LOCKED', 'Locked (Final)')], db_index=True, default='DRAFT', max_length=10),
        ),
        migrations.AddIndex(
            model_name='budgetperiod',
            index=models.Index(fields=['fiscal_year', 'period_type', 'status'], name='accounting__fiscal__e69b0e_idx'),
        ),
        migrations.AddIndex(
            model_name='glbalance',
            index=models.Index(fields=['fiscal_year', 'period'], name='accounting__fiscal__2db8fc_idx'),
        ),
        migrations.AddIndex(
            model_name='glbalance',
            index=models.Index(fields=['account', 'fiscal_year'], name='accounting__account_347734_idx'),
        ),
        migrations.AddIndex(
            model_name='glbalance',
            index=models.Index(fields=['fund', 'fiscal_year', 'period'], name='accounting__fund_id_b3f399_idx'),
        ),
        migrations.AddIndex(
            model_name='journalheader',
            index=models.Index(fields=['posting_date', 'status', 'fund'], name='accounting__posting_372c0e_idx'),
        ),
        migrations.AddIndex(
            model_name='journalheader',
            index=models.Index(fields=['status', 'mda'], name='accounting__status_d5d0cc_idx'),
        ),
        migrations.AddIndex(
            model_name='journalheader',
            index=models.Index(fields=['document_number'], name='accounting__documen_425840_idx'),
        ),
        migrations.AddIndex(
            model_name='journalheader',
            index=models.Index(fields=['reference_number'], name='accounting__referen_8bcf80_idx'),
        ),
    ]
