# Generated by Django 4.2.28 on 2026-03-18 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0019_invoicematchingsettings_vendorcontract_and_more'),
        ('sales', '0009_customer_credit_check_enabled_customer_credit_status_and_more'),
        ('accounting', '0027_budgetperiod_allow_adjustments_and_more'),
    ]

    operations = [
    ]
