# Generated by Django 4.2.28 on 2026-03-18 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_customer_credit_check_enabled_customer_credit_status_and_more'),
        ('procurement', '0019_invoicematchingsettings_vendorcontract_and_more'),
        ('accounting', '0029_rename_assetmaintenance_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmaintenance',
            name='external_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_entries', to='accounting.journalheader'),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='parts_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='MaintenanceBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField()),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('spent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_budgets', to='accounting.costcenter')),
                ('mda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_budgets', to='accounting.mda')),
            ],
            options={
                'unique_together': {('fiscal_year', 'mda', 'cost_center')},
            },
        ),
        migrations.CreateModel(
            name='CustomerAging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_date', models.DateField()),
                ('current', models.DecimalField(decimal_places=2, default=0, help_text='Current (0-30 days)', max_digits=15)),
                ('days_30', models.DecimalField(decimal_places=2, default=0, help_text='31-60 days', max_digits=15)),
                ('days_60', models.DecimalField(decimal_places=2, default=0, help_text='61-90 days', max_digits=15)),
                ('days_90', models.DecimalField(decimal_places=2, default=0, help_text='91-120 days', max_digits=15)),
                ('days_120', models.DecimalField(decimal_places=2, default=0, help_text='Over 120 days', max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aging_records', to='sales.customer')),
            ],
            options={
                'ordering': ['-as_of_date', 'customer__name'],
                'unique_together': {('customer', 'as_of_date')},
            },
        ),
    ]
