# Generated manually for new accounting models

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0019_invoicematchingsettings_vendorcontract_and_more'),
        ('sales', '0009_customer_credit_check_enabled_customer_credit_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0034_accounting_services_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('rate_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], default='PERCENTAGE', max_length=20)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tax_authority', models.CharField(blank=True, default='', max_length=100)),
                ('tax_type', models.CharField(choices=[('VAT', 'VAT'), ('WHT', 'Withholding Tax'), ('STAMP', 'Stamp Duty'), ('EXCISE', 'Excise Duty')], default='VAT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        # NOTE: TaxCode already created in 0018_taxcode_withholdingtax_enhance.
        # Instead of CreateModel, we transform the existing TaxCode to the 0035 state:
        # Remove fields not in 0035's model (direction, rate, tax_account were in 0018/0019)
        migrations.RemoveField(
            model_name='taxcode',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='taxcode',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='taxcode',
            name='tax_account',
        ),
        # Add fields that 0035's TaxCode model introduces
        migrations.AddField(
            model_name='taxcode',
            name='tax_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.taxrate'),
        ),
        migrations.AddField(
            model_name='taxcode',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taxcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VATReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('return_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], default='MONTHLY', max_length=20)),
                ('total_output_vat', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_input_vat', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_vat_payable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_vat_refundable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('zero_rated_sales', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('exempt_sales', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('ASSESSED', 'Assessed'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='DRAFT', max_length=20)),
                ('filing_reference', models.CharField(blank=True, default='', max_length=50)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vat_returns', to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-period_end'],
                'unique_together': {('period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='VATReturnDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='accounting.vatreturn')),
                ('document_type', models.CharField(choices=[('VI', 'Vendor Invoice'), ('CI', 'Customer Invoice'), ('JE', 'Journal Entry')], max_length=5)),
                ('document_id', models.IntegerField(default=0)),
                ('document_number', models.CharField(max_length=50)),
                ('document_date', models.DateField()),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_output', models.CharField(choices=[('OUTPUT', 'Output VAT'), ('INPUT', 'Input VAT')], max_length=10)),
                ('tax_code', models.CharField(blank=True, default='', max_length=20)),
                ('counterparty_name', models.CharField(blank=True, default='', max_length=200)),
                ('counterparty_tax_id', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'ordering': ['document_date'],
            },
        ),
        migrations.CreateModel(
            name='WHTCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('certificate_date', models.DateField()),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wht_certificates', to='procurement.vendor')),
                ('vendor_name', models.CharField(max_length=200)),
                ('vendor_address', models.TextField(blank=True, default='')),
                ('vendor_tin', models.CharField(max_length=20)),
                ('wht_type', models.CharField(choices=[('DIVIDEND', 'Dividend'), ('INTEREST', 'Interest'), ('RENT', 'Rent'), ('ROYALTY', 'Royalty'), ('SERVICE_FEE', 'Service Fee'), ('TECHNICAL_FEE', 'Technical Fee')], max_length=20)),
                ('wht_rate', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('wht_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('nature_of_payment', models.CharField(max_length=200)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=50)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('SUBMITTED', 'Submitted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wht_certificates', to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-certificate_date'],
            },
        ),
        migrations.CreateModel(
            name='PettyCashFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_name', models.CharField(max_length=100)),
                ('fund_code', models.CharField(max_length=20, unique=True)),
                ('custodian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_funds', to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_funds', to='accounting.account')),
                ('float_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('minimum_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency_code', models.CharField(default='NGN', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['fund_code'],
            },
        ),
        migrations.CreateModel(
            name='PettyCashVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=50, unique=True)),
                ('petty_cash_fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='accounting.pettycashfund')),
                ('voucher_date', models.DateField()),
                ('payee_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('category', models.CharField(choices=[('OFFICE_SUPPLIES', 'Office Supplies'), ('TRAVEL', 'Travel'), ('MEALS', 'Meals & Entertainment'), ('POSTAGE', 'Postage & Courier'), ('FUEL', 'Fuel'), ('REPAIRS', 'Repairs & Maintenance'), ('OTHER', 'Other')], max_length=30)),
                ('receipt_attached', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_approved', to=settings.AUTH_USER_MODEL)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_vouchers', to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-voucher_date'],
            },
        ),
        migrations.CreateModel(
            name='PettyCashReplenishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replenishment_number', models.CharField(max_length=50, unique=True)),
                ('petty_cash_fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replenishments', to='accounting.pettycashfund')),
                ('replenishment_date', models.DateField()),
                ('total_vouchers', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.bankaccount')),
                ('journal_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('POSTED', 'Posted')], default='DRAFT', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_replenishments', to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-replenishment_date'],
            },
        ),
        migrations.CreateModel(
            name='ChequeRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_number', models.CharField(max_length=50)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cheques', to='accounting.bankaccount')),
                ('issue_date', models.DateField()),
                ('payee_name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency_code', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('CASHED', 'Cashed'), ('STOPPED', 'Stopped'), ('LOST', 'Lost'), ('EXPIRED', 'Expired')], default='ISSUED', max_length=20)),
                ('cheque_type', models.CharField(choices=[('PAYMENT', 'Payment'), ('CASH', 'Cash')], default='PAYMENT', max_length=20)),
                ('narration', models.TextField(blank=True, default='')),
                ('cleared_date', models.DateField(blank=True, null=True)),
                ('stop_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques_issued', to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-issue_date'],
                'unique_together': {('bank_account', 'cheque_number')},
            },
        ),
        migrations.CreateModel(
            name='PaymentVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=50, unique=True)),
                ('voucher_date', models.DateField()),
                ('payee_type', models.CharField(choices=[('VENDOR', 'Vendor'), ('CUSTOMER', 'Customer'), ('EMPLOYEE', 'Employee'), ('OTHER', 'Other')], max_length=20)),
                ('payee_name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('TRANSFER', 'Bank Transfer'), ('CARD', 'Card')], max_length=20)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.bankaccount')),
                ('cheque_number', models.CharField(blank=True, default='', max_length=50)),
                ('narration', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('approval_level', models.IntegerField(default=0)),
                ('journal_id', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_vouchers', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_vouchers_approved', to=settings.AUTH_USER_MODEL)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fiscal_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.fiscalperiod')),
            ],
            options={
                'ordering': ['-voucher_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetRevaluationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revaluation_date', models.DateField()),
                ('revaluation_number', models.CharField(max_length=50, unique=True)),
                ('revaluation_method', models.CharField(choices=[('FAIR_VALUE', 'Fair Value'), ('INDEXED_COST', 'Indexed Cost'), ('EXTERNAL_VALUATION', 'External Valuation')], max_length=20)),
                ('valuator_name', models.CharField(blank=True, default='', max_length=200)),
                ('valuator_qualification', models.CharField(blank=True, default='', max_length=200)),
                ('valuation_report_reference', models.CharField(blank=True, default='', max_length=100)),
                ('total_cost_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_accum_depr_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_revaluation_surplus', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_revaluation_loss', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('REVERSED', 'Reversed')], default='DRAFT', max_length=20)),
                ('revaluation_gain_account', models.CharField(default='3101', max_length=20)),
                ('revaluation_loss_account', models.CharField(default='8101', max_length=20)),
                ('revaluation_surplus_account', models.CharField(default='3100', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_id', models.IntegerField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revaluations_approved', to=settings.AUTH_USER_MODEL)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_revaluations', to=settings.AUTH_USER_MODEL)),
                ('fiscal_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.fiscalperiod')),
            ],
            options={
                'ordering': ['-revaluation_date'],
            },
        ),
        migrations.AddIndex(
            model_name='assetrevaluationrun',
            index=models.Index(fields=['revaluation_date'], name='asset_reval_reval_d_xxx_idx'),
        ),
        migrations.AddIndex(
            model_name='assetrevaluationrun',
            index=models.Index(fields=['status'], name='asset_reval_status_xxx_idx'),
        ),
        migrations.CreateModel(
            name='AssetRevaluationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(blank=True, default='', max_length=50)),
                ('asset_name', models.CharField(blank=True, default='', max_length=200)),
                ('cost_before', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('accum_depr_before', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('nbv_before', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cost_after', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('accum_depr_after', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('nbv_after', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cost_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('accum_depr_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('revaluation_surplus', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('revaluation_loss', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revaluations', to='accounting.fixedasset')),
                ('revaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='accounting.assetrevaluationrun')),
            ],
            options={
                'ordering': ['asset_code'],
            },
        ),
        # NOTE: AssetDisposal already created in 0008_product_type_category.
        # 0019 then stripped it down. Now we transform from 0019 state to 0035 target state.
        # 0019 state fields: id, disposal_date, disposal_method, asset, documented_by, gain_loss, proceeds
        # Remove fields added by 0019 that are not in 0035's model:
        migrations.RemoveField(model_name='assetdisposal', name='documented_by'),
        migrations.RemoveField(model_name='assetdisposal', name='gain_loss'),
        migrations.RemoveField(model_name='assetdisposal', name='proceeds'),
        # Add fields that 0035's AssetDisposal model introduces:
        migrations.AddField(
            model_name='assetdisposal',
            name='disposal_number',
            field=models.CharField(max_length=50, unique=True, default='DISP-TEMP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='disposal_reason',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='buyer_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='buyer_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='sale_proceeds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='disposal_costs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='net_proceeds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='acquisition_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='accum_depreciation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='net_book_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='gain_on_disposal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='loss_on_disposal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('POSTED', 'Posted')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='gain_account',
            field=models.CharField(default='7200', max_length=20),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='loss_account',
            field=models.CharField(default='8200', max_length=20),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='journal_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposals_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_disposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='fiscal_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.fiscalperiod'),
        ),
        migrations.AlterModelOptions(
            name='assetdisposal',
            options={'ordering': ['-disposal_date']},
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_note_number', models.CharField(max_length=50, unique=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='sales.customer')),
                ('customer_name', models.CharField(blank=True, default='', max_length=200)),
                ('credit_note_date', models.DateField()),
                ('original_invoice_number', models.CharField(blank=True, default='', max_length=50)),
                ('reason', models.TextField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency_code', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('APPLIED', 'Applied'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('journal_id', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes_approved', to=settings.AUTH_USER_MODEL)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-credit_note_date'],
            },
        ),
        migrations.CreateModel(
            name='DebitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_note_number', models.CharField(max_length=50, unique=True)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debit_notes', to='procurement.vendor')),
                ('vendor_name', models.CharField(blank=True, default='', max_length=200)),
                ('debit_note_date', models.DateField()),
                ('original_invoice_number', models.CharField(blank=True, default='', max_length=50)),
                ('reason', models.TextField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency_code', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('APPLIED', 'Applied'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('journal_id', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_notes', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_notes_approved', to=settings.AUTH_USER_MODEL)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-debit_note_date'],
            },
        ),
        migrations.CreateModel(
            name='BadDebtProvision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provision_number', models.CharField(max_length=50, unique=True)),
                ('provision_date', models.DateField()),
                ('fiscal_year', models.IntegerField()),
                ('total_receivables', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('provision_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('provision_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('prior_provision', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('provision_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('POSTED', 'Posted')], default='DRAFT', max_length=20)),
                ('journal_id', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bad_debt_provisions', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bad_debt_provisions_approved', to=settings.AUTH_USER_MODEL)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fiscal_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.fiscalperiod')),
            ],
            options={
                'ordering': ['-provision_date'],
            },
        ),
        migrations.CreateModel(
            name='CashFlowEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('document_type', models.CharField(choices=[('RECEIPT', 'Receipt'), ('PAYMENT', 'Payment'), ('TRANSFER', 'Transfer'), ('FEE', 'Fee'), ('OTHER', 'Other')], max_length=20)),
                ('document_number', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cash_flow_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='accounting.cashflowcategory')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.bankaccount')),
                ('journal_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalline')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='PeriodClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], max_length=20)),
                ('closing_date', models.DateField()),
                ('total_debits', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_credits', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_closings', to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fiscal_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closings', to='accounting.fiscalperiod')),
            ],
            options={
                'ordering': ['-closing_date'],
                'unique_together': {('fiscal_period', 'closing_type')},
            },
        ),
        migrations.CreateModel(
            name='SuspenseClearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clearing_date', models.DateField()),
                ('clearing_reference', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=10)),
                ('clearing_type', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic'), ('JOURNAL', 'Journal Entry')], max_length=20)),
                ('description', models.TextField()),
                ('journal_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLEARED', 'Cleared'), ('REVERSED', 'Reversed')], default='PENDING', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspense_clearing', to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suspense_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clearing_entries', to='accounting.journalline')),
            ],
            options={
                'ordering': ['-clearing_date'],
            },
        ),
        # NOTE: YearEndClosing already created in 0019. Transform from 0019 state to 0035 target state.
        # 0019 state fields: id, created_at, updated_at, fiscal_year, closing_date, status,
        #   income_summary_debit, income_summary_credit, net_income, retained_earnings_debit,
        #   retained_earnings_credit, closed_date, notes, closed_by, closing_journal, created_by,
        #   opening_journal, updated_by
        # Remove fields in 0019 state not in 0035 target:
        migrations.RemoveField(model_name='yearendclosing', name='updated_at'),
        migrations.RemoveField(model_name='yearendclosing', name='income_summary_debit'),
        migrations.RemoveField(model_name='yearendclosing', name='income_summary_credit'),
        migrations.RemoveField(model_name='yearendclosing', name='retained_earnings_debit'),
        migrations.RemoveField(model_name='yearendclosing', name='retained_earnings_credit'),
        migrations.RemoveField(model_name='yearendclosing', name='closed_date'),
        migrations.RemoveField(model_name='yearendclosing', name='closed_by'),
        migrations.RemoveField(model_name='yearendclosing', name='closing_journal'),
        migrations.RemoveField(model_name='yearendclosing', name='opening_journal'),
        migrations.RemoveField(model_name='yearendclosing', name='updated_by'),
        # Add fields in 0035 target not in 0019 state:
        migrations.AddField(
            model_name='yearendclosing',
            name='closing_journal_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yearendclosing',
            name='net_income_journal_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yearendclosing',
            name='revenue_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='yearendclosing',
            name='expense_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='yearendclosing',
            name='retained_earnings_before',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='yearendclosing',
            name='retained_earnings_after',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='yearendclosing',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yearendclosing',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='year_closings_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='yearendclosing',
            name='next_fiscal_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        # AlterField to update status choices and alter created_by related_name:
        migrations.AlterField(
            model_name='yearendclosing',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('REVERSED', 'Reversed')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='yearendclosing',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='year_closings', to=settings.AUTH_USER_MODEL),
        ),
    ]
