# Generated by Django 4.2.28 on 2026-03-24 20:12

import accounting.models
import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_customer_credit_check_enabled_customer_credit_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procurement', '0020_invoicematching_payment_hold_and_more'),
        ('accounting', '0037_audit_fixes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadDebtWriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('write_off_number', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(default='', max_length=200)),
                ('original_invoice_number', models.CharField(blank=True, default='', max_length=50)),
                ('write_off_date', models.DateField()),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_written_off', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('reason', models.TextField()),
                ('age_at_write_off', models.IntegerField(default=0)),
                ('days_overdue', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('RECOVERED', 'Recovered')], default='PENDING', max_length=20)),
                ('provision_reference', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('journal_id', models.IntegerField(blank=True, null=True)),
                ('recovered_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('recovered_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-write_off_date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField()),
                ('period', models.IntegerField()),
                ('calculation_date', models.DateField()),
                ('ratio_category', models.CharField(max_length=50)),
                ('ratio_name', models.CharField(max_length=100)),
                ('ratio_value', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('ratio_unit', models.CharField(default='ratio', max_length=20)),
                ('benchmark_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('industry_average', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('is_favorable', models.BooleanField(default=True)),
                ('is_within_threshold', models.BooleanField(default=True)),
                ('calculation_details', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-calculation_date'],
            },
        ),
        migrations.RemoveField(
            model_name='assetrevaluation',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='assetrevaluation',
            name='documented_by',
        ),
        migrations.AlterModelOptions(
            name='assetmaintenance',
            options={'ordering': ['-scheduled_date'], 'permissions': [('approve_assetmaintenance', 'Can approve maintenance')]},
        ),
        migrations.AlterModelOptions(
            name='pettycashfund',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='taxrate',
            options={'ordering': ['tax_type', '-effective_date']},
        ),
        migrations.RenameIndex(
            model_name='assetrevaluationrun',
            new_name='accounting__revalua_62abed_idx',
            old_name='asset_reval_reval_d_xxx_idx',
        ),
        migrations.RenameIndex(
            model_name='assetrevaluationrun',
            new_name='accounting__status_7b48d5_idx',
            old_name='asset_reval_status_xxx_idx',
        ),
        migrations.RemoveField(
            model_name='cashflowentry',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='cashflowentry',
            name='cash_flow_category',
        ),
        migrations.RemoveField(
            model_name='cashflowentry',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cashflowentry',
            name='document_number',
        ),
        migrations.RemoveField(
            model_name='cashflowentry',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='cashflowentry',
            name='journal_line',
        ),
        migrations.RemoveField(
            model_name='chequeregister',
            name='cleared_date',
        ),
        migrations.RemoveField(
            model_name='chequeregister',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='chequeregister',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='chequeregister',
            name='currency_code',
        ),
        migrations.RemoveField(
            model_name='chequeregister',
            name='narration',
        ),
        migrations.RemoveField(
            model_name='chequeregister',
            name='payee_name',
        ),
        migrations.RemoveField(
            model_name='chequeregister',
            name='stop_date',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='debitnote',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='debitnote',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='debitnote',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='approval_level',
        ),
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='fiscal_period',
        ),
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='narration',
        ),
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='status',
        ),
        migrations.RemoveField(
            model_name='periodclosing',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='periodclosing',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='pettycashfund',
            name='account',
        ),
        migrations.RemoveField(
            model_name='pettycashfund',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pettycashfund',
            name='currency_code',
        ),
        migrations.RemoveField(
            model_name='pettycashfund',
            name='fund_code',
        ),
        migrations.RemoveField(
            model_name='pettycashfund',
            name='fund_name',
        ),
        migrations.RemoveField(
            model_name='pettycashreplenishment',
            name='total_vouchers',
        ),
        migrations.RemoveField(
            model_name='pettycashvoucher',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pettycashvoucher',
            name='payee_name',
        ),
        migrations.RemoveField(
            model_name='pettycashvoucher',
            name='status',
        ),
        migrations.RemoveField(
            model_name='suspenseclearing',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='suspenseclearing',
            name='amount_type',
        ),
        migrations.RemoveField(
            model_name='suspenseclearing',
            name='clearing_reference',
        ),
        migrations.RemoveField(
            model_name='suspenseclearing',
            name='clearing_type',
        ),
        migrations.RemoveField(
            model_name='suspenseclearing',
            name='journal_id',
        ),
        migrations.RemoveField(
            model_name='suspenseclearing',
            name='suspense_transaction',
        ),
        migrations.RemoveField(
            model_name='taxcode',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='taxcode',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='taxcode',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='taxrate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='taxrate',
            name='effective_from',
        ),
        migrations.RemoveField(
            model_name='taxrate',
            name='effective_to',
        ),
        migrations.RemoveField(
            model_name='taxrate',
            name='rate_type',
        ),
        migrations.RemoveField(
            model_name='taxrate',
            name='tax_authority',
        ),
        migrations.RemoveField(
            model_name='taxrate',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='whtcertificate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='whtcertificate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='whtcertificate',
            name='invoice_date',
        ),
        migrations.RemoveField(
            model_name='whtcertificate',
            name='vendor_tin',
        ),
        migrations.RemoveField(
            model_name='whtcertificate',
            name='wht_amount',
        ),
        migrations.RemoveField(
            model_name='whtcertificate',
            name='wht_rate',
        ),
        migrations.RemoveField(
            model_name='whtcertificate',
            name='wht_type',
        ),
        migrations.AddField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances', to='procurement.vendor'),
        ),
        migrations.AddField(
            model_name='assetrevaluationdetail',
            name='journal_line_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetrevaluationdetail',
            name='justification',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='assetrevaluationdetail',
            name='valuation_source',
            field=models.CharField(choices=[('INTERNAL', 'Internal Valuation'), ('EXTERNAL', 'External Valuer'), ('MARKET', 'Market Comparison'), ('INDEX', 'Cost Index')], default='INTERNAL', max_length=20),
        ),
        migrations.AddField(
            model_name='baddebtprovision',
            name='closing_provision',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='baddebtprovision',
            name='new_provisions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='baddebtprovision',
            name='opening_provision',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='baddebtprovision',
            name='period',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='baddebtprovision',
            name='provision_type',
            field=models.CharField(default='SPECIFIC', max_length=20),
        ),
        migrations.AddField(
            model_name='baddebtprovision',
            name='provisioning_method',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='baddebtprovision',
            name='recoveries',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='baddebtprovision',
            name='write_offs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='cashflowentry',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_flow_entries', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='cashflowentry',
            name='account_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cashflowentry',
            name='account_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cashflowentry',
            name='cash_flow_type',
            field=models.CharField(choices=[('OPERATING', 'Operating Activities'), ('INVESTING', 'Investing Activities'), ('FINANCING', 'Financing Activities')], default='OPERATING', max_length=20),
        ),
        migrations.AddField(
            model_name='cashflowentry',
            name='fiscal_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.fiscalperiod'),
        ),
        migrations.AddField(
            model_name='cashflowentry',
            name='fiscal_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cashflowentry',
            name='journal_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashflowentry',
            name='period',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chequeregister',
            name='bounce_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chequeregister',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chequeregister',
            name='issued_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques_issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chequeregister',
            name='journal_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chequeregister',
            name='payee',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='chequeregister',
            name='presentation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chequeregister',
            name='presented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chequeregister',
            name='presented_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques_presented', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chequeregister',
            name='reference_document',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='chequeregister',
            name='stop_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='applied_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='applied_invoices',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='original_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='accounting.customerinvoice'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='reason_type',
            field=models.CharField(choices=[('RETURN', 'Goods Return'), ('DISCOUNT', 'Discount'), ('CORRECTION', 'Price Correction'), ('DAMAGE', 'Damaged Goods'), ('SHORTAGE', 'Short Delivery'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='applied_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='applied_invoices',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='original_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_notes', to='accounting.vendorinvoice'),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='reason_type',
            field=models.CharField(choices=[('RETURN', 'Goods Return'), ('PRICE_INCREASE', 'Price Increase'), ('ADDITIONAL_CHARGE', 'Additional Charge'), ('DAMAGE', 'Damaged Goods'), ('SHORTAGE', 'Short Delivery'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_vouchers', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='approval_history',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='approvers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='attachments',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.costcenter'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='currency_code',
            field=models.CharField(default='NGN', max_length=3),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='is_reconciled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='payee_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pv_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='reconciliation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='reference_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='periodclosing',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='periodclosing',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closings_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='periodclosing',
            name='closing_entries',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='periodclosing',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='periodclosing',
            name='trial_balance_check',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pettycashfund',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_accounts', to='accounting.bankaccount'),
        ),
        migrations.AddField(
            model_name='pettycashfund',
            name='code',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='pettycashfund',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pettycashreplenishment',
            name='reimbursement_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='pettycashreplenishment',
            name='vouchers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='pettycashreplenishment',
            name='vouchers_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='pettycashvoucher',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_vouchers', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='pettycashvoucher',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='pettycashvoucher',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.costcenter'),
        ),
        migrations.AddField(
            model_name='pettycashvoucher',
            name='payee',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='suspenseclearing',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='suspenseclearing',
            name='cleared_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='suspenseclearing',
            name='clearing_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clearing_entries', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='suspenseclearing',
            name='clearing_number',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='suspenseclearing',
            name='journal_header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suspense_clearings', to='accounting.journalheader'),
        ),
        migrations.AddField(
            model_name='suspenseclearing',
            name='suspense_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suspense_clearings', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='suspenseclearing',
            name='suspense_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='taxcode',
            name='direction',
            field=models.CharField(choices=[('purchase', 'Purchase (Input)'), ('sales', 'Sales (Output)'), ('both', 'Both')], db_index=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='taxcode',
            name='rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='taxcode',
            name='tax_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_codes', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='account_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='applies_to_domestic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='applies_to_imports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='code',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='effective_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whtcertificate',
            name='certificate_type',
            field=models.CharField(choices=[('ROYALTY', 'Royalty'), ('SERVICE', 'Service Fee'), ('RENT', 'Rent'), ('DIVIDEND', 'Dividend'), ('INTEREST', 'Interest'), ('CONTRACT', 'Contract Payment')], default='SERVICE', max_length=20),
        ),
        migrations.AddField(
            model_name='whtcertificate',
            name='contract_reference',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='whtcertificate',
            name='fiscal_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='whtcertificate',
            name='invoice_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='whtcertificate',
            name='issued_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='whtcertificate',
            name='issued_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wht_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='whtcertificate',
            name='payment_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='whtcertificate',
            name='period',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='whtcertificate',
            name='vendor_tax_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='whtcertificate',
            name='withholding_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='whtcertificate',
            name='withholding_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='accountingdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=accounting.models.tenant_upload_path),
        ),
        migrations.AlterField(
            model_name='assetmaintenance',
            name='maintenance_type',
            field=models.CharField(choices=[('Preventive', 'Preventive - Scheduled maintenance'), ('Corrective', 'Corrective - Break/fix'), ('Predictive', 'Predictive - Condition-based'), ('Emergency', 'Emergency - Urgent repair'), ('Inspection', 'Inspection - Safety/compliance'), ('Overhaul', 'Overhaul - Major restoration')], default='Preventive', max_length=20),
        ),
        migrations.AlterField(
            model_name='baddebtprovision',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisions_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='baddebtprovision',
            name='fiscal_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='baddebtprovision',
            name='provision_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='budgetencumbrance',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='cashflowentry',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cashflowentry',
            name='entry_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='chequeregister',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheques', to='accounting.bankaccount'),
        ),
        migrations.AlterField(
            model_name='chequeregister',
            name='cheque_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='chequeregister',
            name='cheque_type',
            field=models.CharField(choices=[('CASH', 'Cash Cheque'), ('PAYMENT', 'Payment Cheque'), ('POSTDATED', 'Post-Dated')], default='PAYMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='chequeregister',
            name='issue_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='chequeregister',
            name='status',
            field=models.CharField(choices=[('ISSUED', 'Issued'), ('PRESENTED', 'Presented'), ('PAID', 'Paid'), ('BOUNCED', 'Bounced'), ('CANCELLED', 'Cancelled'), ('STOPPED', 'Stopped'), ('EXPIRED', 'Expired')], default='ISSUED', max_length=20),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.customer'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='customer_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('APPLIED', 'Applied'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_notes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('APPLIED', 'Applied'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='procurement.vendor'),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='vendor_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pv_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.bankaccount'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pv_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='payee_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='payee_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('TRANSFER', 'Bank Transfer'), ('EFT', 'Electronic Fund Transfer')], default='TRANSFER', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='voucher_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='periodclosing',
            name='closing_type',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Year-End')], max_length=20),
        ),
        migrations.AlterField(
            model_name='periodclosing',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('VERIFIED', 'Verified'), ('POSTED', 'Posted'), ('REVERSED', 'Reversed')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='pettycashfund',
            name='custodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_custodian', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pettycashreplenishment',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='petty_replenishments', to='accounting.bankaccount'),
        ),
        migrations.AlterField(
            model_name='pettycashreplenishment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pettycashreplenishment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pettycashvoucher',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pettycashvoucher',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pettycashvoucher',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pettycashvoucher',
            name='petty_cash_fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='accounting.pettycashfund'),
        ),
        migrations.AlterField(
            model_name='pettycashvoucher',
            name='voucher_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='pettycashvoucher',
            name='voucher_number',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='suspenseclearing',
            name='clearing_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='suspenseclearing',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='suspenseclearing',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspense_clearings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='suspenseclearing',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='suspenseclearing',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partially Cleared'), ('CLEARED', 'Cleared')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='taxcode',
            name='code',
            field=models.CharField(db_index=True, default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='taxcode',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='taxcode',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='taxcode',
            name='tax_type',
            field=models.CharField(choices=[('vat', 'VAT'), ('sales_tax', 'Sales Tax'), ('service_tax', 'Service Tax'), ('excise_duty', 'Excise Duty'), ('customs_duty', 'Customs Duty')], db_index=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='tax_type',
            field=models.CharField(choices=[('VAT', 'Value Added Tax'), ('WHT', 'Withholding Tax'), ('ST', 'Sales Tax'), ('EXC', 'Excise Duty'), ('CET', 'Customs & Excise')], default='VAT', max_length=10),
        ),
        migrations.AlterField(
            model_name='vatreturn',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vatreturn',
            name='period_end',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='vatreturn',
            name='period_start',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='vatreturndetail',
            name='document_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='vatreturndetail',
            name='document_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vatreturndetail',
            name='document_type',
            field=models.CharField(choices=[('VI', 'Vendor Invoice'), ('CI', 'Customer Invoice'), ('JE', 'Journal Entry')], default='JE', max_length=5),
        ),
        migrations.AlterField(
            model_name='vatreturndetail',
            name='is_output',
            field=models.CharField(choices=[('OUTPUT', 'Output VAT'), ('INPUT', 'Input VAT')], default='OUTPUT', max_length=10),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=accounting.models.tenant_upload_path),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='whtcertificate',
            name='certificate_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='whtcertificate',
            name='certificate_number',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='whtcertificate',
            name='nature_of_payment',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='whtcertificate',
            name='status',
            field=models.CharField(choices=[('ISSUED', 'Issued'), ('DELIVERED', 'Delivered'), ('UTILIZED', 'Utilized'), ('CANCELLED', 'Cancelled')], default='ISSUED', max_length=20),
        ),
        migrations.AlterField(
            model_name='whtcertificate',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='procurement.vendor'),
        ),
        migrations.AlterField(
            model_name='whtcertificate',
            name='vendor_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='xbrlreport',
            name='fiscal_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='xbrlreport',
            name='period_end',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='xbrlreport',
            name='period_start',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='xbrlreport',
            name='report_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='xbrlreport',
            name='report_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='baddebtprovision',
            unique_together={('fiscal_year', 'period')},
        ),
        migrations.AddIndex(
            model_name='cashflowentry',
            index=models.Index(fields=['fiscal_year', 'period', 'cash_flow_type'], name='accounting__fiscal__bca03a_idx'),
        ),
        migrations.AddIndex(
            model_name='chequeregister',
            index=models.Index(fields=['payee', 'status'], name='accounting__payee_470957_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentvoucher',
            index=models.Index(fields=['payee_name', 'voucher_date'], name='accounting__payee_n_f88cf8_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentvoucher',
            index=models.Index(fields=['approval_status'], name='accounting__approva_151f5c_idx'),
        ),
        migrations.AddIndex(
            model_name='pettycashvoucher',
            index=models.Index(fields=['petty_cash_fund', 'voucher_date'], name='accounting__petty_c_75e2d2_idx'),
        ),
        migrations.AddIndex(
            model_name='whtcertificate',
            index=models.Index(fields=['vendor', 'fiscal_year'], name='accounting__vendor__5d7534_idx'),
        ),
        migrations.AddIndex(
            model_name='whtcertificate',
            index=models.Index(fields=['certificate_date'], name='accounting__certifi_5f60e9_idx'),
        ),
        migrations.DeleteModel(
            name='AssetRevaluation',
        ),
        migrations.AddField(
            model_name='financialratio',
            name='fiscal_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.fiscalperiod'),
        ),
        migrations.AddField(
            model_name='baddebtwriteoff',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='write_offs_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='baddebtwriteoff',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='write_offs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='baddebtwriteoff',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.customer'),
        ),
        migrations.AddField(
            model_name='baddebtwriteoff',
            name='original_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.customerinvoice'),
        ),
        migrations.RemoveField(
            model_name='baddebtprovision',
            name='prior_provision',
        ),
        migrations.RemoveField(
            model_name='baddebtprovision',
            name='provision_adjustment',
        ),
        migrations.RemoveField(
            model_name='baddebtprovision',
            name='provision_amount',
        ),
        migrations.RemoveField(
            model_name='baddebtprovision',
            name='provision_number',
        ),
        migrations.RemoveField(
            model_name='baddebtprovision',
            name='provision_percentage',
        ),
        migrations.RemoveField(
            model_name='baddebtprovision',
            name='total_receivables',
        ),
        migrations.AddIndex(
            model_name='financialratio',
            index=models.Index(fields=['fiscal_year', 'period', 'ratio_category'], name='accounting__fiscal__fc9b81_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='financialratio',
            unique_together={('fiscal_year', 'period', 'ratio_name')},
        ),
    ]
