# Generated by Django 6.0.2 on 2026-04-03 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0050_accountingsettings_sales_downpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxcode',
            name='input_tax_account',
            field=models.ForeignKey(blank=True, help_text='GL account for input/purchase tax (e.g. Input VAT Receivable)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='input_tax_codes', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='taxcode',
            name='output_tax_account',
            field=models.ForeignKey(blank=True, help_text='GL account for output/sales tax (e.g. Output VAT Payable)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output_tax_codes', to='accounting.account'),
        ),
    ]
