# Generated by Django 6.0.2 on 2026-04-05 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0051_add_tax_gl_and_wht_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinvoice',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='journalheader',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalheader',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalheader',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='journalheader',
            name='is_reversed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='journalheader',
            name='posted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the journal was posted to the GL.', null=True),
        ),
        migrations.AddField(
            model_name='journalheader',
            name='posted_by',
            field=models.ForeignKey(blank=True, help_text='User who triggered the GL posting action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journals_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalheader',
            name='source_document_id',
            field=models.PositiveIntegerField(blank=True, help_text='PK of the source record (SalesOrder.pk, PayrollRun.pk, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='journalheader',
            name='source_module',
            field=models.CharField(blank=True, help_text="Originating module: 'sales', 'procurement', 'hrm', 'inventory', etc.", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='journalline',
            name='cost_center',
            field=models.ForeignKey(blank=True, help_text='MDA / Department cost centre this line is allocated to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to='accounting.mda'),
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_reconciliation',
            field=models.ForeignKey(blank=True, help_text='The bank reconciliation that cleared this payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_payments', to='accounting.bankreconciliation'),
        ),
        migrations.AddField(
            model_name='payment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_reconciled',
            field=models.BooleanField(db_index=True, default=False, help_text='Set to True when this payment has been matched in a completed bank reconciliation.'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='bank_reconciliation',
            field=models.ForeignKey(blank=True, help_text='The bank reconciliation that cleared this receipt.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_receipts', to='accounting.bankreconciliation'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipt',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='receipt',
            name='is_reconciled',
            field=models.BooleanField(db_index=True, default=False, help_text='Set to True when this receipt has been matched in a completed bank reconciliation.'),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='accountingdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='tenants/documents/'),
        ),
        migrations.AddIndex(
            model_name='journalheader',
            index=models.Index(fields=['source_module', 'source_document_id'], name='accounting__source__aa74d6_idx'),
        ),
    ]
