# Generated by Django 4.2.28 on 2026-04-07 19:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0053_accountingsettings_default_currency_5'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeratehistory',
            name='rate_valid_from',
            field=models.DateField(default=datetime.date.today, help_text='Start date for this exchange rate'),
        ),
        migrations.AddField(
            model_name='exchangeratehistory',
            name='rate_valid_to',
            field=models.DateField(blank=True, help_text='End date for this exchange rate (blank = ongoing)', null=True),
        ),
        migrations.AlterField(
            model_name='assetdisposal',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposals', to='accounting.fixedasset'),
        ),
        migrations.AlterField(
            model_name='assetdisposal',
            name='disposal_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='assetdisposal',
            name='disposal_method',
            field=models.CharField(choices=[('SALE', 'Sale'), ('SCRAP', 'Scrapped'), ('DONATION', 'Donated'), ('THEFT', 'Stolen'), ('LOSS', 'Lost'), ('TRADE_IN', 'Trade-in')], max_length=20),
        ),
        migrations.AlterField(
            model_name='withholdingtax',
            name='withholding_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withholding_tax_codes', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='yearendclosing',
            name='closing_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='yearendclosing',
            name='fiscal_year',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='yearendclosing',
            unique_together={('fiscal_year',)},
        ),
    ]
