# Generated by Django 4.2.28 on 2026-04-09 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0054_add_exchange_rate_date_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, default='', max_length=50)),
                ('level', models.CharField(choices=[('SECTOR', 'Sector'), ('ORGANIZATION', 'Organization'), ('SUB_ORG', 'Sub-Organization'), ('SUB_SUB_ORG', 'Sub-Sub-Organization'), ('UNIT', 'Unit')], max_length=15)),
                ('sector_code', models.CharField(choices=[('01', 'Administrative Sector'), ('02', 'Economic Sector'), ('03', 'Law and Justice Sector'), ('04', 'Regional Sector'), ('05', 'Social Sector')], max_length=2)),
                ('organization_code', models.CharField(blank=True, default='', max_length=2)),
                ('sub_org_code', models.CharField(blank=True, default='', max_length=3)),
                ('sub_sub_org_code', models.CharField(blank=True, default='', max_length=3)),
                ('unit_code', models.CharField(blank=True, default='', max_length=2)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_mda', models.BooleanField(default=False)),
                ('mda_type', models.CharField(blank=True, choices=[('MINISTRY', 'Ministry'), ('DEPARTMENT', 'Department'), ('AGENCY', 'Agency / Parastatal'), ('UNIT', 'Unit / Division')], default='', max_length=15)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Administrative Segment (MDA)',
                'verbose_name_plural': 'Administrative Segments (MDA)',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EconomicSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=8, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('account_type_code', models.CharField(choices=[('1', 'Revenue'), ('2', 'Expenditure'), ('3', 'Assets'), ('4', 'Liabilities and Net Assets')], db_index=True, max_length=1)),
                ('sub_type_code', models.CharField(default='0', max_length=1)),
                ('account_class_code', models.CharField(default='00', max_length=2)),
                ('sub_class_code', models.CharField(default='00', max_length=2)),
                ('line_item_code', models.CharField(default='00', max_length=2)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_posting_level', models.BooleanField(db_index=True, default=False)),
                ('is_control_account', models.BooleanField(default=False)),
                ('normal_balance', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], default='DEBIT', max_length=6)),
                ('legacy_account_type', models.CharField(blank=True, choices=[('Asset', 'Asset'), ('Liability', 'Liability'), ('Equity', 'Equity / Net Assets'), ('Income', 'Income / Revenue'), ('Expense', 'Expense / Expenditure')], default='', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Economic Segment (Account)',
                'verbose_name_plural': 'Economic Segments (Accounts)',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FunctionalSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=5, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('division_code', models.CharField(choices=[('701', 'General Public Services'), ('702', 'Defence'), ('703', 'Public Order and Safety'), ('704', 'Economic Affairs'), ('705', 'Environmental Protection'), ('706', 'Housing and Community Amenities'), ('707', 'Health'), ('708', 'Recreation, Culture and Religion'), ('709', 'Education'), ('710', 'Social Protection')], db_index=True, max_length=3)),
                ('group_code', models.CharField(blank=True, default='0', max_length=1)),
                ('class_code', models.CharField(blank=True, default='0', max_length=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Functional Segment (COFOG)',
                'verbose_name_plural': 'Functional Segments (COFOG)',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FundSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=5, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('main_fund_code', models.CharField(choices=[('01', 'Federation Account (FAAC — Statutory)'), ('02', 'Capital Development Fund'), ('03', 'Contingency Fund'), ('04', 'Education Tax / UBEC Fund'), ('05', 'Donor / Grant Funds'), ('06', 'Domestic Loans'), ('07', 'Foreign Loans'), ('08', 'Internally Generated Revenue (IGR)'), ('09', 'Other Government Receipts')], db_index=True, max_length=2)),
                ('sub_fund_code', models.CharField(blank=True, default='0', max_length=1)),
                ('fund_source_code', models.CharField(blank=True, default='00', max_length=2)),
                ('donor_name', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_restricted', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Fund Segment',
                'verbose_name_plural': 'Fund Segments',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='GeographicSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=8, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('zone_code', models.CharField(choices=[('1', 'North-Central'), ('2', 'North-East'), ('3', 'North-West'), ('4', 'South-East'), ('5', 'South-South'), ('6', 'South-West')], db_index=True, max_length=1)),
                ('state_code', models.CharField(db_index=True, default='00', max_length=2)),
                ('senatorial_code', models.CharField(blank=True, default='0', max_length=1)),
                ('lga_code', models.CharField(blank=True, default='00', max_length=2)),
                ('ward_code', models.CharField(blank=True, default='00', max_length=2)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Geographic Segment',
                'verbose_name_plural': 'Geographic Segments',
                'ordering': ['zone_code', 'state_code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='NCoACode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'verbose_name': 'NCoA Code',
                'verbose_name_plural': 'NCoA Codes',
            },
        ),
        migrations.CreateModel(
            name='PaymentInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary_name', models.CharField(max_length=200)),
                ('beneficiary_account', models.CharField(max_length=20)),
                ('beneficiary_bank', models.CharField(max_length=100)),
                ('beneficiary_sort', models.CharField(blank=True, default='', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('narration', models.CharField(max_length=200)),
                ('batch_reference', models.CharField(blank=True, default='', max_length=50)),
                ('bank_reference', models.CharField(blank=True, default='', help_text='Bank settlement reference (populated after processing)', max_length=100)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Submission'), ('SUBMITTED', 'Submitted to CBN/Bank'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed / Paid'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='PENDING', max_length=15)),
                ('failure_reason', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Payment Instruction',
                'verbose_name_plural': 'Payment Instructions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentVoucherGov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voucher_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('payment_type', models.CharField(choices=[('VENDOR', 'Vendor / Contractor Payment'), ('SALARY', 'Salary Payment'), ('ALLOWANCE', 'Allowance / Honorarium'), ('PENSION', 'Pension Remittance'), ('STATUTORY', 'Statutory Deduction Remittance'), ('REFUND', 'Revenue Refund'), ('TRANSFER', 'Inter-Account Transfer'), ('PETTY_CASH', 'Petty Cash Replenishment'), ('SUBVENTION', 'Subvention / Transfer'), ('DEBT', 'Debt Service Payment')], max_length=20)),
                ('payee_name', models.CharField(max_length=200)),
                ('payee_account', models.CharField(max_length=20)),
                ('payee_bank', models.CharField(max_length=100)),
                ('payee_sort_code', models.CharField(blank=True, default='', max_length=10)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('wht_amount', models.DecimalField(decimal_places=2, default=0, help_text='Withholding Tax deduction', max_digits=20)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('narration', models.CharField(max_length=500)),
                ('source_document', models.CharField(blank=True, default='', help_text='PO/Contract reference number', max_length=100)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=50)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CHECKED', 'Checked'), ('AUDITED', 'Internal Audit Verified'), ('APPROVED', 'Approved by Accounting Officer'), ('SCHEDULED', 'Scheduled for Payment'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('REVERSED', 'Reversed')], default='DRAFT', max_length=15)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Payment Voucher',
                'verbose_name_plural': 'Payment Vouchers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=14, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('policy_code', models.CharField(max_length=2)),
                ('programme_code', models.CharField(max_length=2)),
                ('project_code', models.CharField(blank=True, default='', max_length=6)),
                ('objective_code', models.CharField(blank=True, default='', max_length=2)),
                ('activity_code', models.CharField(blank=True, default='', max_length=2)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_capital', models.BooleanField(db_index=True, default=False)),
                ('project_start', models.DateField(blank=True, null=True)),
                ('project_end', models.DateField(blank=True, null=True)),
                ('total_project_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.programmesegment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Programme Segment',
                'verbose_name_plural': 'Programme Segments',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RevenueCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('payer_name', models.CharField(max_length=200)),
                ('payer_tin', models.CharField(blank=True, default='', help_text='Taxpayer Identification Number', max_length=20)),
                ('payer_phone', models.CharField(blank=True, default='', max_length=20)),
                ('payer_address', models.CharField(blank=True, default='', max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payment_reference', models.CharField(max_length=50, unique=True)),
                ('rrr', models.CharField(blank=True, default='', help_text='Remita Retrieval Reference', max_length=20)),
                ('collection_date', models.DateField()),
                ('value_date', models.DateField(blank=True, help_text='Date funds actually credited to TSA', null=True)),
                ('collection_channel', models.CharField(choices=[('BANK', 'Bank Branch'), ('ONLINE', 'Online Payment'), ('USSD', 'USSD / Mobile'), ('AGENT', 'Agent Banking'), ('COUNTER', 'Government Counter'), ('POS', 'Point of Sale')], default='BANK', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed'), ('POSTED', 'Posted to GL'), ('REVERSED', 'Reversed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
                ('period_month', models.IntegerField(blank=True, help_text='Assessment period month (for PAYE)', null=True)),
                ('period_year', models.IntegerField(blank=True, help_text='Assessment period year (for PAYE)', null=True)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('collecting_mda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revenue_collections', to='accounting.administrativesegment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_collections', to='accounting.journalheader')),
                ('ncoa_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_collections', to='accounting.ncoacode')),
            ],
            options={
                'verbose_name': 'Revenue Collection',
                'verbose_name_plural': 'Revenue Collections',
                'ordering': ['-collection_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RevenueHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('revenue_type', models.CharField(choices=[('PAYE', 'Pay As You Earn (PAYE)'), ('DIRECT_ASSESSMENT', 'Direct Assessment'), ('ROAD_TAX', 'Road Tax / Vehicle License'), ('STAMP_DUTY', 'Stamp Duty'), ('CGT', 'Capital Gains Tax'), ('WHT', 'Withholding Tax'), ('FEES_FINES', 'Fees and Fines'), ('LICENSE', 'Licenses and Permits'), ('RENT', 'Rent on Government Property'), ('DIVIDEND', 'Dividends from Government Companies'), ('INVESTMENT', 'Investment Income'), ('GRANT', 'Grants and Transfers'), ('FAAC', 'Federation Account Allocation'), ('OTHER', 'Other IGR')], max_length=30)),
                ('remittance_rate', models.DecimalField(decimal_places=2, default=100, help_text='Percentage of collection remitted to TSA (default 100%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('collection_mda', models.ForeignKey(blank=True, help_text='MDA responsible for collecting this revenue', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revenue_heads', to='accounting.administrativesegment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('economic_segment', models.ForeignKey(help_text='NCoA economic code for this revenue type', on_delete=django.db.models.deletion.PROTECT, related_name='revenue_heads', to='accounting.economicsegment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Revenue Head',
                'verbose_name_plural': 'Revenue Heads',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TreasuryAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('account_name', models.CharField(max_length=200)),
                ('bank', models.CharField(help_text='CBN or designated bank', max_length=100)),
                ('sort_code', models.CharField(blank=True, default='', max_length=10)),
                ('account_type', models.CharField(choices=[('MAIN_TSA', 'Main TSA (CBN)'), ('CONSOLIDATED', 'Consolidated Revenue Fund'), ('SUB_ACCOUNT', 'MDA Sub-Account'), ('ZERO_BALANCE', 'Zero Balance Account (MDA)'), ('HOLDING', 'Holding Account'), ('REVENUE', 'Revenue Collection Account')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, help_text='Current balance (updated by payment/receipt postings)', max_digits=22)),
                ('last_reconciled', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('fund_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.fundsegment')),
                ('mda', models.ForeignKey(blank=True, help_text='MDA that owns this sub-account', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tsa_accounts', to='accounting.administrativesegment')),
                ('parent_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_accounts', to='accounting.treasuryaccount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TSA Account',
                'verbose_name_plural': 'TSA Accounts',
                'ordering': ['account_type', 'account_number'],
            },
        ),
        migrations.RemoveField(
            model_name='consolidation',
            name='group',
        ),
        migrations.RemoveField(
            model_name='consolidation',
            name='period',
        ),
        migrations.RemoveField(
            model_name='consolidationgroup',
            name='companies',
        ),
        migrations.RemoveField(
            model_name='consolidationgroup',
            name='reporting_currency',
        ),
        migrations.RemoveField(
            model_name='consolidationrun',
            name='group',
        ),
        migrations.RemoveField(
            model_name='consolidationrun',
            name='period',
        ),
        migrations.RemoveField(
            model_name='consolidationrun',
            name='run_by',
        ),
        migrations.RemoveField(
            model_name='intercompany',
            name='default_currency',
        ),
        migrations.AlterUniqueTogether(
            name='intercompanyaccountmapping',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='intercompanyaccountmapping',
            name='inter_company',
        ),
        migrations.RemoveField(
            model_name='intercompanyaccountmapping',
            name='local_account',
        ),
        migrations.RemoveField(
            model_name='intercompanyallocation',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='intercompanyallocation',
            name='source_company',
        ),
        migrations.RemoveField(
            model_name='intercompanycashtransfer',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='intercompanycashtransfer',
            name='from_company',
        ),
        migrations.RemoveField(
            model_name='intercompanycashtransfer',
            name='to_company',
        ),
        migrations.AlterUniqueTogether(
            name='intercompanyconfig',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='intercompanyconfig',
            name='ap_account',
        ),
        migrations.RemoveField(
            model_name='intercompanyconfig',
            name='ar_account',
        ),
        migrations.RemoveField(
            model_name='intercompanyconfig',
            name='company',
        ),
        migrations.RemoveField(
            model_name='intercompanyconfig',
            name='expense_account',
        ),
        migrations.RemoveField(
            model_name='intercompanyconfig',
            name='partner_company',
        ),
        migrations.RemoveField(
            model_name='intercompanyconfig',
            name='revenue_account',
        ),
        migrations.RemoveField(
            model_name='intercompanyelimination',
            name='period',
        ),
        migrations.RemoveField(
            model_name='intercompanyinvoice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='intercompanyinvoice',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='intercompanyinvoice',
            name='from_company',
        ),
        migrations.RemoveField(
            model_name='intercompanyinvoice',
            name='linked_journal',
        ),
        migrations.RemoveField(
            model_name='intercompanyinvoice',
            name='to_company',
        ),
        migrations.RemoveField(
            model_name='intercompanytransaction',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='intercompanytransaction',
            name='inter_company',
        ),
        migrations.RemoveField(
            model_name='intercompanytransfer',
            name='from_company',
        ),
        migrations.RemoveField(
            model_name='intercompanytransfer',
            name='to_company',
        ),
        migrations.AlterModelOptions(
            name='customeraging',
            options={'ordering': ['-as_of_date', 'customer_name']},
        ),
        migrations.AlterUniqueTogether(
            name='customeraging',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='baddebtwriteoff',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerinvoice',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerinvoice',
            name='sales_order',
        ),
        migrations.RemoveField(
            model_name='deferredrevenue',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='taxexemption',
            name='customer',
        ),
        migrations.AddField(
            model_name='customeraging',
            name='customer_id_ref',
            field=models.IntegerField(blank=True, help_text='Legacy customer ID reference', null=True),
        ),
        migrations.AddField(
            model_name='customeraging',
            name='customer_name',
            field=models.CharField(default='', help_text='Debtor/payer name (replaces FK to deleted sales.Customer)', max_length=200),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='customer_name',
            field=models.CharField(blank=True, default='', help_text='Payer/debtor name (replaces FK to deleted sales.Customer)', max_length=200),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='customer_tin',
            field=models.CharField(blank=True, default='', help_text='Tax Identification Number', max_length=20),
        ),
        migrations.AddField(
            model_name='deferredrevenue',
            name='payer_name',
            field=models.CharField(blank=True, default='', help_text='Revenue payer name (replaces FK to deleted sales.Customer)', max_length=200),
        ),
        migrations.AddField(
            model_name='receipt',
            name='customer_name',
            field=models.CharField(blank=True, default='', help_text='Payer name (replaces FK to deleted sales.Customer)', max_length=200),
        ),
        migrations.AddField(
            model_name='taxexemption',
            name='entity_name',
            field=models.CharField(blank=True, default='', help_text='Exempt entity name (replaces FK to deleted sales.Customer)', max_length=200),
        ),
        migrations.AlterField(
            model_name='baddebtwriteoff',
            name='customer_name',
            field=models.CharField(default='', help_text='Debtor name (replaces FK to deleted sales.Customer)', max_length=200),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='customer_name',
            field=models.CharField(default='', help_text='Debtor name (replaces FK to deleted sales.Customer)', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='customeraging',
            unique_together={('customer_name', 'as_of_date')},
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Consolidation',
        ),
        migrations.DeleteModel(
            name='ConsolidationGroup',
        ),
        migrations.DeleteModel(
            name='ConsolidationRun',
        ),
        migrations.DeleteModel(
            name='InterCompany',
        ),
        migrations.DeleteModel(
            name='InterCompanyAccountMapping',
        ),
        migrations.DeleteModel(
            name='InterCompanyAllocation',
        ),
        migrations.DeleteModel(
            name='InterCompanyCashTransfer',
        ),
        migrations.DeleteModel(
            name='InterCompanyConfig',
        ),
        migrations.DeleteModel(
            name='InterCompanyElimination',
        ),
        migrations.DeleteModel(
            name='InterCompanyInvoice',
        ),
        migrations.DeleteModel(
            name='InterCompanyTransaction',
        ),
        migrations.DeleteModel(
            name='InterCompanyTransfer',
        ),
        migrations.AddField(
            model_name='revenuecollection',
            name='revenue_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='accounting.revenuehead'),
        ),
        migrations.AddField(
            model_name='revenuecollection',
            name='tsa_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_collections', to='accounting.treasuryaccount'),
        ),
        migrations.AddField(
            model_name='revenuecollection',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
