# Generated by Django 4.2.28 on 2026-04-09 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_ncoa_segments'),
        ('accounting', '0055_ncoa_segments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvouchergov',
            name='appropriation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_vouchers', to='budget.appropriation'),
        ),
        migrations.AddField(
            model_name='paymentvouchergov',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentvouchergov',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_vouchers', to='accounting.journalheader'),
        ),
        migrations.AddField(
            model_name='paymentvouchergov',
            name='ncoa_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_vouchers', to='accounting.ncoacode'),
        ),
        migrations.AddField(
            model_name='paymentvouchergov',
            name='tsa_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_vouchers', to='accounting.treasuryaccount'),
        ),
        migrations.AddField(
            model_name='paymentvouchergov',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentvouchergov',
            name='warrant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_vouchers', to='budget.warrant'),
        ),
        migrations.AddField(
            model_name='paymentinstruction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentinstruction',
            name='payment_voucher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment_instruction', to='accounting.paymentvouchergov'),
        ),
        migrations.AddField(
            model_name='paymentinstruction',
            name='tsa_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_instructions', to='accounting.treasuryaccount'),
        ),
        migrations.AddField(
            model_name='paymentinstruction',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ncoacode',
            name='administrative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.administrativesegment'),
        ),
        migrations.AddField(
            model_name='ncoacode',
            name='economic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.economicsegment'),
        ),
        migrations.AddField(
            model_name='ncoacode',
            name='functional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.functionalsegment'),
        ),
        migrations.AddField(
            model_name='ncoacode',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.fundsegment'),
        ),
        migrations.AddField(
            model_name='ncoacode',
            name='geographic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.geographicsegment'),
        ),
        migrations.AddField(
            model_name='ncoacode',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.programmesegment'),
        ),
        migrations.AddField(
            model_name='geographicsegment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='geographicsegment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.geographicsegment'),
        ),
        migrations.AddField(
            model_name='geographicsegment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fundsegment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fundsegment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.fundsegment'),
        ),
        migrations.AddField(
            model_name='fundsegment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='functionalsegment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='functionalsegment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.functionalsegment'),
        ),
        migrations.AddField(
            model_name='functionalsegment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='economicsegment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='economicsegment',
            name='legacy_account',
            field=models.OneToOneField(blank=True, help_text='Maps this NCoA segment to legacy Account for GL compatibility', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='economic_segment', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='economicsegment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.economicsegment'),
        ),
        migrations.AddField(
            model_name='economicsegment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='administrativesegment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='administrativesegment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.administrativesegment'),
        ),
        migrations.AddField(
            model_name='administrativesegment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='customeraging',
            name='customer',
        ),
        migrations.AddField(
            model_name='journalline',
            name='economic_segment',
            field=models.ForeignKey(blank=True, help_text='NCoA Economic segment (the account)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.economicsegment'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='ncoa_code',
            field=models.ForeignKey(blank=True, help_text='Full 52-digit NCoA composite code', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.ncoacode'),
        ),
        migrations.AddIndex(
            model_name='revenuecollection',
            index=models.Index(fields=['revenue_head', 'collection_date'], name='accounting__revenue_1922f0_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuecollection',
            index=models.Index(fields=['status', 'collection_date'], name='accounting__status_e06413_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuecollection',
            index=models.Index(fields=['payer_tin'], name='accounting__payer_t_9c4036_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentvouchergov',
            index=models.Index(fields=['status', 'payment_type'], name='accounting__status_332060_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentvouchergov',
            index=models.Index(fields=['voucher_number'], name='accounting__voucher_d0a254_idx'),
        ),
        migrations.AddIndex(
            model_name='ncoacode',
            index=models.Index(fields=['economic', 'administrative'], name='accounting__economi_3e159c_idx'),
        ),
        migrations.AddIndex(
            model_name='ncoacode',
            index=models.Index(fields=['fund', 'programme'], name='accounting__fund_id_9f4b4e_idx'),
        ),
        migrations.AddIndex(
            model_name='ncoacode',
            index=models.Index(fields=['economic', 'functional'], name='accounting__economi_73a081_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ncoacode',
            unique_together={('administrative', 'economic', 'functional', 'programme', 'fund', 'geographic')},
        ),
        migrations.AddIndex(
            model_name='geographicsegment',
            index=models.Index(fields=['zone_code', 'state_code', 'is_active'], name='accounting__zone_co_c66c53_idx'),
        ),
        migrations.AddIndex(
            model_name='economicsegment',
            index=models.Index(fields=['account_type_code', 'is_posting_level', 'is_active'], name='accounting__account_d1089a_idx'),
        ),
        migrations.AddIndex(
            model_name='administrativesegment',
            index=models.Index(fields=['sector_code', 'is_active'], name='accounting__sector__c53517_idx'),
        ),
        migrations.AddIndex(
            model_name='administrativesegment',
            index=models.Index(fields=['level', 'is_active'], name='accounting__level_34edc1_idx'),
        ),
    ]
