# Generated by Django 4.2.28 on 2026-04-10 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0057_remove_journalline_economic_segment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativesegment',
            name='legacy_mda',
            field=models.OneToOneField(blank=True, help_text='Maps this NCoA segment to legacy MDA for GL compatibility', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncoa_segment', to='accounting.mda'),
        ),
        migrations.AddField(
            model_name='functionalsegment',
            name='legacy_function',
            field=models.OneToOneField(blank=True, help_text='Maps to legacy Function for GL compatibility', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncoa_segment', to='accounting.function'),
        ),
        migrations.AddField(
            model_name='fundsegment',
            name='legacy_fund',
            field=models.OneToOneField(blank=True, help_text='Maps to legacy Fund for GL compatibility', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncoa_segment', to='accounting.fund'),
        ),
        migrations.AddField(
            model_name='geographicsegment',
            name='legacy_geo',
            field=models.OneToOneField(blank=True, help_text='Maps to legacy Geo for GL compatibility', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncoa_segment', to='accounting.geo'),
        ),
        migrations.AddField(
            model_name='programmesegment',
            name='legacy_program',
            field=models.OneToOneField(blank=True, help_text='Maps to legacy Program for GL compatibility', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncoa_segment', to='accounting.program'),
        ),
    ]
