# Generated by Django 4.2.28 on 2026-04-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0058_administrativesegment_legacy_mda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='require_vendor_registration_invoice',
            field=models.BooleanField(default=True, help_text='When enabled, new vendors start inactive and require a registration invoice + payment confirmation before activation. When disabled, vendors are created active immediately (no invoice gate).'),
        ),
    ]
