# Generated by Django 4.2.28 on 2026-04-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0059_add_vendor_invoice_gate_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorinvoice',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Approved', 'Approved'), ('Posted', 'Posted'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid'), ('Void', 'Void')], default='Draft', max_length=20),
        ),
    ]
