# Generated by Django 4.2.28 on 2026-04-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0060_add_posted_to_vendor_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='require_pv_before_payment',
            field=models.BooleanField(default=False, help_text='When True, outgoing Payments must reference an approved Payment Voucher (PV). When False, direct payments from vendor invoices are allowed.'),
        ),
    ]
