# Generated by Django 4.2.28 on 2026-04-16 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0061_add_require_pv_before_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_voucher',
            field=models.ForeignKey(blank=True, help_text='PV that authorises this payment. Required when require_pv_before_payment setting is True.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_payments', to='accounting.paymentvouchergov'),
        ),
    ]
