# Generated by Django 4.2.28 on 2026-04-16 22:19

import accounting.models.gl
import accounting.models.receivables
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0062_add_payment_voucher_fk_on_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TSABankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statement_file', models.FileField(upload_to=accounting.models.gl.tenant_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('statement_from', models.DateField(help_text='First transaction date covered by the statement')),
                ('statement_to', models.DateField(help_text='Last transaction date covered by the statement')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_debits', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_credits', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('line_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PARSED', 'Parsed'), ('MATCHED', 'Auto-matched'), ('COMPLETED', 'Completed'), ('FAILED', 'Parse Failed')], default='PARSED', max_length=12)),
                ('parse_errors', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tsa_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statement_imports', to='accounting.treasuryaccount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Statement Import',
                'verbose_name_plural': 'Bank Statement Imports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=accounting.models.receivables.tenant_upload_path),
        ),
        migrations.CreateModel(
            name='TSABankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(help_text='1-based row order from the file')),
                ('transaction_date', models.DateField()),
                ('value_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('match_status', models.CharField(choices=[('UNMATCHED', 'Unmatched'), ('AUTO', 'Auto-matched'), ('MANUAL', 'Manually matched'), ('IGNORED', 'Ignored')], default='UNMATCHED', max_length=10)),
                ('match_confidence', models.DecimalField(decimal_places=2, default=0, help_text='0-100: how confident the auto-matcher was', max_digits=5)),
                ('matched_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement_lines', to='accounting.paymentinstruction')),
                ('matched_revenue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement_lines', to='accounting.revenuecollection')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.tsabankstatement')),
            ],
            options={
                'ordering': ['statement_id', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='TSAReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('book_balance', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('statement_balance', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('adjusted_balance', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('unmatched_debits', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('unmatched_credits', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEWED', 'Reviewed'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tsa_reconciliations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('statement_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='accounting.tsabankstatement')),
                ('tsa_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='accounting.treasuryaccount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TSA Reconciliation',
                'verbose_name_plural': 'TSA Reconciliations',
                'ordering': ['-period_end'],
                'indexes': [models.Index(fields=['tsa_account', '-period_end'], name='accounting__tsa_acc_49f95c_idx'), models.Index(fields=['status'], name='accounting__status_f09432_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='tsareconciliation',
            constraint=models.UniqueConstraint(fields=('tsa_account', 'period_start', 'period_end'), name='uniq_tsa_recon_period'),
        ),
        migrations.AddIndex(
            model_name='tsabankstatementline',
            index=models.Index(fields=['statement', 'match_status'], name='accounting__stateme_58c52e_idx'),
        ),
        migrations.AddIndex(
            model_name='tsabankstatementline',
            index=models.Index(fields=['reference'], name='accounting__referen_1ca226_idx'),
        ),
        migrations.AddIndex(
            model_name='tsabankstatement',
            index=models.Index(fields=['tsa_account', '-statement_to'], name='accounting__tsa_acc_410050_idx'),
        ),
    ]
