# Generated by Django 4.2.28 on 2026-04-16 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0063_tsabankstatement_alter_vendorinvoice_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinstruction',
            name='is_reconciled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='paymentinstruction',
            name='reconciliation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_payments', to='accounting.tsareconciliation'),
        ),
        migrations.AddField(
            model_name='revenuecollection',
            name='is_reconciled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='revenuecollection',
            name='reconciliation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_revenues', to='accounting.tsareconciliation'),
        ),
        migrations.AddField(
            model_name='tsabankstatement',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='tsabankstatementline',
            name='matched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tsabankstatementline',
            name='matched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_statement_lines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tsabankstatementline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
