# Generated by Django 4.2.28 on 2026-04-16 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0066_dedupe_journal_source_docs'),
    ]

    operations = [
        # Idempotency guard: a previous attempt to apply this migration on
        # some tenants failed AFTER creating the first unique index. Drop
        # any pre-existing constraints/indexes by those names so the
        # AddConstraint operations below can succeed cleanly.
        migrations.RunSQL(
            sql=(
                'ALTER TABLE accounting_journalheader '
                '  DROP CONSTRAINT IF EXISTS uniq_journalheader_reference_number;\n'
                'DROP INDEX IF EXISTS uniq_journalheader_reference_number;\n'
                'ALTER TABLE accounting_journalheader '
                '  DROP CONSTRAINT IF EXISTS uniq_journalheader_source_doc_posted;\n'
                'DROP INDEX IF EXISTS uniq_journalheader_source_doc_posted;\n'
                'ALTER TABLE accounting_journalline '
                '  DROP CONSTRAINT IF EXISTS jrn_line_debit_nonneg;\n'
                'ALTER TABLE accounting_journalline '
                '  DROP CONSTRAINT IF EXISTS jrn_line_credit_nonneg;\n'
                'ALTER TABLE accounting_journalline '
                '  DROP CONSTRAINT IF EXISTS jrn_line_not_both_sides;\n'
                'ALTER TABLE accounting_journalline '
                '  DROP CONSTRAINT IF EXISTS jrn_line_at_least_one_side;\n'
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='journalreversal',
            name='original_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='accounting.journalheader'),
        ),
        migrations.AddConstraint(
            model_name='journalheader',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_number__gt', '')), fields=('reference_number',), name='uniq_journalheader_reference_number'),
        ),
        migrations.AddConstraint(
            model_name='journalheader',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Posted'), ('source_module__isnull', False), ('source_document_id__isnull', False)), fields=('source_module', 'source_document_id'), name='uniq_journalheader_source_doc_posted'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(check=models.Q(('debit__gte', 0)), name='jrn_line_debit_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(check=models.Q(('credit__gte', 0)), name='jrn_line_credit_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(check=models.Q(('debit__gt', 0), ('credit__gt', 0), _negated=True), name='jrn_line_not_both_sides'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(check=models.Q(('debit__gt', 0), ('credit__gt', 0), _connector='OR'), name='jrn_line_at_least_one_side'),
        ),
    ]
