# Generated by Django 4.2.28 on 2026-04-16 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0067_alter_journalreversal_original_journal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiscalperiod',
            options={'ordering': ['fiscal_year', 'period_number'], 'permissions': [('reopen_fiscal_period', 'Can reopen a closed fiscal period')]},
        ),
    ]
