# Generated by Django 4.2.28 on 2026-04-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0068_alter_fiscalperiod_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionauditlog',
            name='sequence_number',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='transactionauditlog',
            index=models.Index(fields=['sequence_number'], name='accounting__sequenc_f690a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='transactionauditlog',
            constraint=models.UniqueConstraint(condition=models.Q(('sequence_number__isnull', False)), fields=('tenant_id', 'sequence_number'), name='uniq_txn_audit_tenant_seq'),
        ),
    ]
