# Generated by Django 4.2.28 on 2026-04-17 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0069_transactionauditlog_sequence_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='glbalance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='glbalance',
            name='mda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gl_balances', to='accounting.mda'),
        ),
        migrations.AlterUniqueTogether(
            name='glbalance',
            unique_together={('account', 'fund', 'function', 'program', 'geo', 'mda', 'fiscal_year', 'period')},
        ),
        migrations.AddIndex(
            model_name='glbalance',
            index=models.Index(fields=['mda', 'fiscal_year', 'period'], name='accounting__mda_id_d2ce36_idx'),
        ),
        migrations.AddIndex(
            model_name='glbalance',
            index=models.Index(fields=['mda', 'account', 'fiscal_year'], name='accounting__mda_id_a51c70_idx'),
        ),
    ]
