# Generated by Django 4.2.28 on 2026-04-17 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0070_alter_glbalance_unique_together_glbalance_mda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='accumulated_fund_account_code',
            field=models.CharField(blank=True, default='43100000', help_text='Chart-of-Accounts code used as the Accumulated Surplus/Deficit target for year-end close. Defaults to NCoA 43100000 (General Reserve Fund).', max_length=20),
        ),
    ]
