# Generated by Django 4.2.28 on 2026-04-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0071_accountingsettings_accumulated_fund_account_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glbalance',
            options={'ordering': ['fiscal_year', 'period', 'account__code'], 'permissions': [('view_financial_statements', 'Can view IPSAS financial statements (SoFP, SoFPerformance, Cash Flow, Changes in Net Assets, Notes, Budget-vs-Actual)')]},
        ),
    ]
