# Generated by Django 4.2.28 on 2026-04-17 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0072_alter_glbalance_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(db_index=True, help_text='Canonical key: "ipsas.sofp", "ipsas.sofperformance", "ipsas.cashflow", "ipsas.changes_in_net_assets", "ipsas.notes", "ipsas.budget_vs_actual", "statutory.firs_wht", "statutory.paye", "statutory.pencom", "statutory.nsitf", "statutory.nhia", "statutory.itf", "statutory.oagf_mfr", "statutory.firs_vat".', max_length=64)),
                ('fiscal_year', models.IntegerField(db_index=True)),
                ('period', models.IntegerField(db_index=True, default=0)),
                ('payload', models.JSONField()),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['report_type', 'fiscal_year', 'period'], name='accounting__report__a65eaa_idx'), models.Index(fields=['report_type', '-generated_at'], name='accounting__report__88e0ee_idx'), models.Index(fields=['content_hash'], name='accounting__content_9206de_idx')],
            },
        ),
    ]
