# Generated by Django 4.2.28 on 2026-04-17 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0073_reportsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, help_text='Unique reference for the provision, e.g. PROV-2026-001.', max_length=32, unique=True)),
                ('category', models.CharField(choices=[('LITIGATION', 'Litigation / Legal Damages'), ('PENSION', 'Pension Arrears'), ('RESTRUCTURING', 'Restructuring / Reorganisation'), ('ONEROUS', 'Onerous Contract'), ('ENVIRONMENTAL', 'Environmental Remediation'), ('WARRANTY', 'Warranty / Guarantee'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Nature of the obligation and its basis. Appears in Note 6 of the IPSAS Notes.')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('undiscounted_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Undiscounted expected outflow, if different from amount.', max_digits=20, null=True)),
                ('discount_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Discount rate applied, e.g. 0.1250 for 12.5%.', max_digits=6, null=True)),
                ('recognition_date', models.DateField(help_text='Date the provision was first recognised.')),
                ('expected_settlement_date', models.DateField(blank=True, help_text='Best estimate of when settlement will occur.', null=True)),
                ('likelihood', models.CharField(choices=[('REMOTE', 'Remote (< 10%)'), ('POSSIBLE', 'Possible (10-50%)'), ('PROBABLE', 'Probable (> 50%)'), ('CERTAIN', 'Virtually certain')], default='PROBABLE', help_text='IPSAS 19 recognition requires "Probable" or above.', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RECOGNISED', 'Recognised'), ('SETTLED', 'Settled'), ('REVERSED', 'Reversed (no longer probable)'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=12)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, help_text='Journal that posted the provision to the GL.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisions', to='accounting.journalheader')),
                ('mda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provisions', to='accounting.mda')),
                ('settled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisions_settled', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recognition_date', 'reference'],
                'permissions': [('recognise_provision', 'Can recognise (post) a provision'), ('reverse_provision', 'Can reverse a provision when no longer probable')],
                'indexes': [models.Index(fields=['status', '-recognition_date'], name='accounting__status_3e7474_idx'), models.Index(fields=['category', 'status'], name='accounting__categor_5d1c59_idx'), models.Index(fields=['mda', 'status'], name='accounting__mda_id_7263ec_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContingentLiability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=32, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('estimated_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Best estimate of the possible obligation; may be None when no reliable estimate is possible.', max_digits=20, null=True)),
                ('likelihood', models.CharField(choices=[('REMOTE', 'Remote (< 10%)'), ('POSSIBLE', 'Possible (10-50%)'), ('PROBABLE', 'Probable (> 50%)'), ('CERTAIN', 'Virtually certain')], default='POSSIBLE', max_length=10)),
                ('arising_date', models.DateField()),
                ('expected_resolution_date', models.DateField(blank=True, null=True)),
                ('is_disclosed', models.BooleanField(default=True, help_text='Include in Note 6 of the financial statements.')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('mda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contingent_liabilities', to='accounting.mda')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Contingent liabilities',
                'ordering': ['-arising_date', 'reference'],
                'indexes': [models.Index(fields=['is_disclosed', '-arising_date'], name='accounting__is_disc_79c260_idx'), models.Index(fields=['mda', 'likelihood'], name='accounting__mda_id_63f386_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContingentAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=32, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('estimated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('likelihood', models.CharField(choices=[('REMOTE', 'Remote (< 10%)'), ('POSSIBLE', 'Possible (10-50%)'), ('PROBABLE', 'Probable (> 50%)'), ('CERTAIN', 'Virtually certain')], default='POSSIBLE', max_length=10)),
                ('arising_date', models.DateField()),
                ('expected_realisation_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('mda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contingent_assets', to='accounting.mda')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Contingent assets',
                'ordering': ['-arising_date', 'reference'],
                'indexes': [models.Index(fields=['likelihood', '-arising_date'], name='accounting__likelih_ad1b0e_idx')],
            },
        ),
    ]
