# Generated by Django 4.2.28 on 2026-04-17 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0074_provision_contingentliability_contingentasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningBalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transition_date', models.DateField(help_text='Date of transition to accrual-basis IPSAS. Opening balances are stated as at the END of the day before this date.', unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Narrative context for the transition (e.g. "State of Delta: transition from cash IPSAS to accrual IPSAS effective 1 January 2026").')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft — being assembled'), ('REVIEWED', 'Reviewed — items frozen pending finalisation'), ('FINALISED', 'Finalised — posted to GL; immutable')], db_index=True, default='DRAFT', max_length=12)),
                ('total_assets', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('total_liabilities', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('total_net_assets', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('finalised_at', models.DateTimeField(blank=True, null=True)),
                ('transition_notes', models.TextField(blank=True, default='', help_text='IPSAS 33 ¶142 transition reconciliation — how the prior cash-basis closing position reconciles to this accrual opening position.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('finalisation_journal', models.ForeignKey(blank=True, help_text='The single JournalHeader that posted the opening balances to the GL.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance_sheet', to='accounting.journalheader')),
                ('finalised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opening_balance_sheets_finalised', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opening Balance Sheet (IPSAS 33)',
                'verbose_name_plural': 'Opening Balance Sheets (IPSAS 33)',
                'ordering': ['-transition_date'],
                'permissions': [('finalise_opening_balance_sheet', 'Can finalise (post) an opening balance sheet')],
            },
        ),
        migrations.CreateModel(
            name='OpeningBalanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('deemed_cost_basis', models.CharField(blank=True, choices=[('HISTORICAL', 'Historical cost (traced)'), ('FAIR_VALUE', 'Fair value at transition date (¶64)'), ('PREVIOUS_GAAP', 'Previous GAAP carrying amount (¶66)'), ('INDEXED_COST', 'Indexed historical cost (¶68)'), ('REVALUATION', 'Prior revaluation (¶70)')], default='HISTORICAL', max_length=16)),
                ('deemed_cost_rationale', models.TextField(blank=True, default='', help_text='When deemed_cost_basis != HISTORICAL, IPSAS 33 ¶142 requires disclosure of the rationale + valuation approach.')),
                ('supporting_document_ref', models.CharField(blank=True, default='', help_text='Reference to the external valuation report, photo index, or other supporting evidence.', max_length=200)),
                ('memo', models.CharField(blank=True, default='', max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance_items', to='accounting.account')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.openingbalancesheet')),
            ],
            options={
                'ordering': ['account__code'],
            },
        ),
        migrations.CreateModel(
            name='MDAImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(db_index=True, help_text='journal_summary | revenue_collection | payroll_summary | provisions', max_length=64)),
                ('idempotency_key', models.CharField(db_index=True, help_text='SHA-256 key — commits with the same payload collide here.', max_length=64, unique=True)),
                ('row_count', models.IntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mda_import_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntangibleAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_number', models.CharField(db_index=True, help_text='e.g. INTAN-2026-001', max_length=32, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('SOFTWARE_LICENCE', 'Software Licence'), ('SOFTWARE_DEVELOPED', 'Internally-Developed Software'), ('PATENT', 'Patent'), ('COPYRIGHT', 'Copyright'), ('TRADEMARK', 'Trademark'), ('DEVELOPMENT', 'Development Expenditure'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('acquisition_date', models.DateField()),
                ('useful_life_months', models.IntegerField(blank=True, help_text='None = indefinite useful life (not amortised per ¶88).', null=True)),
                ('amortisation_method', models.CharField(choices=[('STRAIGHT_LINE', 'Straight-line'), ('REDUCING', 'Reducing balance'), ('UNITS_OF_USE', 'Units of use'), ('NOT_AMORTISED', 'Not amortised (indefinite useful life)')], default='STRAIGHT_LINE', max_length=16)),
                ('accumulated_amortisation', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('residual_value', models.DecimalField(decimal_places=2, default=0, help_text='IPSAS 31 ¶100: usually zero for intangibles unless there is an active market or third-party commitment.', max_digits=20)),
                ('impairment_loss', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('last_impairment_review', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('IMPAIRED', 'Impaired'), ('DISPOSED', 'Disposed'), ('RETIRED', 'Retired')], db_index=True, default='ACTIVE', max_length=12)),
                ('disposed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intangible_assets_disposed', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intangible_assets', to='accounting.journalheader')),
                ('mda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intangible_assets', to='accounting.mda')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-acquisition_date', 'asset_number'],
                'permissions': [('amortise_intangible_asset', 'Can post amortisation for an intangible asset'), ('impair_intangible_asset', 'Can record an impairment')],
            },
        ),
        migrations.AddConstraint(
            model_name='openingbalanceitem',
            constraint=models.UniqueConstraint(fields=('sheet', 'account'), name='uniq_obs_sheet_account'),
        ),
        migrations.AddConstraint(
            model_name='openingbalanceitem',
            constraint=models.CheckConstraint(check=models.Q(('debit__gte', 0)), name='obs_item_debit_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='openingbalanceitem',
            constraint=models.CheckConstraint(check=models.Q(('credit__gte', 0)), name='obs_item_credit_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='openingbalanceitem',
            constraint=models.CheckConstraint(check=models.Q(('debit__gt', 0), ('credit__gt', 0), _negated=True), name='obs_item_not_both_sides'),
        ),
        migrations.AddIndex(
            model_name='mdaimportlog',
            index=models.Index(fields=['data_type', '-created_at'], name='accounting__data_ty_b458a1_idx'),
        ),
        migrations.AddIndex(
            model_name='intangibleasset',
            index=models.Index(fields=['status', '-acquisition_date'], name='accounting__status_8cb95b_idx'),
        ),
        migrations.AddIndex(
            model_name='intangibleasset',
            index=models.Index(fields=['category', 'status'], name='accounting__categor_7d40d5_idx'),
        ),
        migrations.AddIndex(
            model_name='intangibleasset',
            index=models.Index(fields=['mda', 'status'], name='accounting__mda_id_fcaeac_idx'),
        ),
    ]
