# Generated by Django 4.2.28 on 2026-04-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0075_openingbalancesheet_openingbalanceitem_mdaimportlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='intangible_accumulated_amortisation_code',
            field=models.CharField(blank=True, default='32201000', help_text='CoA code credited for accumulated amortisation on intangible assets. Contra-asset balance on the intangibles line of the Statement of Financial Position. Defaults to NCoA 32201000.', max_length=20),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='intangible_amortisation_expense_code',
            field=models.CharField(blank=True, default='22301000', help_text='CoA code debited when monthly intangible-asset amortisation is posted (IPSAS 31 ¶97). Defaults to NCoA 22301000 (Amortisation — Intangible Assets).', max_length=20),
        ),
    ]
