# Generated by Django 4.2.28 on 2026-04-17 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0076_accountingsettings_intangible_accumulated_amortisation_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialBenefitScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, help_text='e.g. DELTA-CCT-2026, LAGOS-CARE-ELDERLY.', max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('CCT', 'Conditional Cash Transfer'), ('UNEMPLOYMENT', 'Unemployment Benefit'), ('DISABILITY', 'Disability Support'), ('OLD_AGE', 'Old-Age Grant (non-contributory)'), ('HEALTH_SUBSIDY', 'Healthcare Subsidy'), ('FOOD_SECURITY', 'Food / Nutrition Support'), ('EDUCATION', 'Education Grant / Bursary'), ('HOUSING', 'Housing Support'), ('OTHER', 'Other Social Benefit')], db_index=True, max_length=20)),
                ('eligibility_criteria', models.TextField(help_text='Plain-English description of who qualifies (age, income, geography, etc.).')),
                ('standard_benefit_amount', models.DecimalField(decimal_places=2, default=0, help_text='Default amount per payment period. Per-claim overrides allowed at SocialBenefitClaim.amount.', max_digits=20)),
                ('payment_frequency', models.CharField(blank=True, default='MONTHLY', help_text='MONTHLY / QUARTERLY / ANNUAL / ONE_OFF.', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, help_text='Annual or programme-total budget allocation.', max_digits=22)),
                ('funding_source', models.CharField(blank=True, default='', help_text='e.g. "State Consolidated Revenue Fund", "Federal World-Bank CCT grant".', max_length=200)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SocialBenefitClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim_reference', models.CharField(db_index=True, help_text='Unique claim reference, e.g. DELTA-CCT-2026-000123.', max_length=40, unique=True)),
                ('beneficiary_name', models.CharField(max_length=200)),
                ('beneficiary_identifier', models.CharField(blank=True, default='', help_text='NIN / BVN / scheme-specific ID. Denormalised — no FK to a citizen master.', max_length=64)),
                ('beneficiary_phone', models.CharField(blank=True, default='', max_length=30)),
                ('beneficiary_address', models.TextField(blank=True, default='')),
                ('period_year', models.IntegerField(db_index=True)),
                ('period_month', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount for this period. Overrides the scheme default when present.', max_digits=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending eligibility check'), ('ELIGIBLE', 'Eligible — awaiting approval'), ('APPROVED', 'Approved — awaiting payment'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=10)),
                ('eligible_date', models.DateField(blank=True, help_text='Date the beneficiary first met eligibility per scheme rules. IPSAS 42 ¶31: liability recognised at this date for the next single payment.', null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, default='', help_text='Bank / mobile-money / voucher reference.', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_benefit_claims_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_benefit_claims', to='accounting.journalheader')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='accounting.socialbenefitscheme')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_year', '-period_month', 'claim_reference'],
            },
        ),
        migrations.CreateModel(
            name='PensionScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, help_text='e.g. DELTA-CPS, DELTA-LEGACY-DB.', max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('scheme_type', models.CharField(choices=[('DEFINED_CONTRIBUTION', 'Defined Contribution (DC)'), ('DEFINED_BENEFIT', 'Defined Benefit (DB)')], db_index=True, max_length=22)),
                ('coverage_note', models.TextField(blank=True, default='', help_text='Which employee groups this scheme covers (e.g. "All civil servants hired after 1 July 2004").')),
                ('employee_contribution_rate', models.DecimalField(decimal_places=2, default=0, help_text='Employee contribution as % of pensionable pay. DC only (typically 8%).', max_digits=5)),
                ('employer_contribution_rate', models.DecimalField(decimal_places=2, default=0, help_text='Employer contribution as % of pensionable pay. DC only (typically 10%).', max_digits=5)),
                ('established_date', models.DateField(blank=True, help_text='When the scheme was established.', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed to new members'), ('TERMINATED', 'Terminated')], db_index=True, default='ACTIVE', max_length=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PensionContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_year', models.IntegerField(db_index=True)),
                ('period_month', models.IntegerField()),
                ('headcount', models.IntegerField(default=0)),
                ('employee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('employer_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pension_contributions', to='accounting.journalheader')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='accounting.pensionscheme')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_year', '-period_month'],
            },
        ),
        migrations.CreateModel(
            name='ActuarialValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valuation_date', models.DateField(db_index=True)),
                ('dbo', models.DecimalField(decimal_places=2, help_text='Present value of the defined benefit obligation. IPSAS 39 ¶63(a).', max_digits=22)),
                ('plan_assets', models.DecimalField(decimal_places=2, default=0, help_text='Fair value of plan assets. IPSAS 39 ¶63(b).', max_digits=22)),
                ('service_cost', models.DecimalField(decimal_places=2, default=0, help_text='Current service cost for the period. Goes to the Statement of Financial Performance.', max_digits=20)),
                ('interest_cost', models.DecimalField(decimal_places=2, default=0, help_text='Net interest on net defined benefit liability.', max_digits=20)),
                ('past_service_cost', models.DecimalField(decimal_places=2, default=0, help_text='Past service cost from plan amendments.', max_digits=20)),
                ('gain_on_settlement', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('actuarial_gains_losses', models.DecimalField(decimal_places=2, default=0, help_text='Remeasurements of the net defined benefit liability. Positive = gain reducing the liability. Negative = loss increasing it. Posted to net assets (IPSAS 39 ¶68).', max_digits=20)),
                ('return_on_plan_assets', models.DecimalField(decimal_places=2, default=0, help_text='Actual return on plan assets (if funded). Excluded interest component covered separately.', max_digits=20)),
                ('valuation_method', models.CharField(choices=[('PROJECTED_UNIT_CREDIT', 'Projected Unit Credit (PUC) — IPSAS 39 ¶69'), ('ATTAINED_AGE', 'Attained Age method'), ('ENTRY_AGE_NORMAL', 'Entry Age Normal'), ('OTHER', 'Other (document in methodology)')], default='PROJECTED_UNIT_CREDIT', max_length=24)),
                ('discount_rate', models.DecimalField(blank=True, decimal_places=4, help_text='e.g. 0.1500 for 15%. Used for present-value calculations of future benefit payments.', max_digits=6, null=True)),
                ('salary_growth_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('pension_growth_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('mortality_table', models.CharField(blank=True, default='', help_text='Mortality table used, e.g. "A49/52 Ultimate".', max_length=100)),
                ('assumptions_narrative', models.TextField(blank=True, default='', help_text='Free-text summary of assumptions for Note 8 disclosure.')),
                ('valuer_firm', models.CharField(blank=True, default='', max_length=200)),
                ('valuer_fellow', models.CharField(blank=True, default='', help_text='Name of the qualified actuary signing the report.', max_length=200)),
                ('report_reference', models.CharField(blank=True, default='', help_text='Reference to the valuation report PDF / document.', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actuarial_valuations', to='accounting.pensionscheme')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-valuation_date'],
            },
        ),
        migrations.AddIndex(
            model_name='socialbenefitscheme',
            index=models.Index(fields=['category', 'status'], name='accounting__categor_f2fb65_idx'),
        ),
        migrations.AddIndex(
            model_name='socialbenefitclaim',
            index=models.Index(fields=['scheme', 'status'], name='accounting__scheme__8fdea0_idx'),
        ),
        migrations.AddIndex(
            model_name='socialbenefitclaim',
            index=models.Index(fields=['scheme', '-period_year', '-period_month'], name='accounting__scheme__e4c0c9_idx'),
        ),
        migrations.AddIndex(
            model_name='socialbenefitclaim',
            index=models.Index(fields=['beneficiary_identifier'], name='accounting__benefic_ddd9f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialbenefitclaim',
            constraint=models.UniqueConstraint(condition=models.Q(('beneficiary_identifier__gt', '')), fields=('scheme', 'beneficiary_identifier', 'period_year', 'period_month'), name='uniq_social_claim_benef_period'),
        ),
        migrations.AddIndex(
            model_name='pensionscheme',
            index=models.Index(fields=['scheme_type', 'status'], name='accounting__scheme__58822c_idx'),
        ),
        migrations.AddIndex(
            model_name='pensioncontribution',
            index=models.Index(fields=['scheme', '-period_year', '-period_month'], name='accounting__scheme__413040_idx'),
        ),
        migrations.AddConstraint(
            model_name='pensioncontribution',
            constraint=models.UniqueConstraint(fields=('scheme', 'period_year', 'period_month'), name='uniq_pension_contribution_scheme_period'),
        ),
        migrations.AddIndex(
            model_name='actuarialvaluation',
            index=models.Index(fields=['scheme', '-valuation_date'], name='accounting__scheme__18364e_idx'),
        ),
        migrations.AddConstraint(
            model_name='actuarialvaluation',
            constraint=models.UniqueConstraint(fields=('scheme', 'valuation_date'), name='uniq_actuarial_valuation_scheme_date'),
        ),
    ]
