# Generated by Django 4.2.28 on 2026-04-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0077_socialbenefitscheme_socialbenefitclaim_pensionscheme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='defined_benefit_obligation_code',
            field=models.CharField(blank=True, default='42201000', help_text='CoA code credited by pension accrual / debited by pension payments. Present Value of the Defined Benefit Obligation on the Statement of Financial Position. Defaults to NCoA 42201000 (Non-current pension liability).', max_length=20),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='pension_interest_expense_code',
            field=models.CharField(blank=True, default='24100000', help_text='CoA code debited for monthly pension interest expense (IPSAS 39 ¶64 net interest on NDB liability). Defaults to NCoA 24100000 (Debt-service / Interest).', max_length=20),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='pension_service_cost_code',
            field=models.CharField(blank=True, default='21400000', help_text='CoA code debited for monthly pension current-service cost (IPSAS 39 ¶64). Defaults to NCoA 21400000 (Personnel costs — pension).', max_length=20),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='social_benefit_expense_code',
            field=models.CharField(blank=True, default='25100000', help_text='CoA code debited when social-benefit batch payments post. Defaults to NCoA 25100000 (Transfers & Subventions — Social Benefits).', max_length=20),
        ),
    ]
