# Generated by Django 4.2.28 on 2026-04-18 19:45

from django.db import migrations, models


DEFAULT_RULES = [
    # Revenue (1xxxxxxx) — never gated. Revenue is statistical; actuals
    # legitimately exceed or miss the RevenueBudget targets without blocking.
    {
        'gl_from': '10000000', 'gl_to': '19999999',
        'check_level': 'NONE',
        'description': 'Revenue — no budget gating (statistical vs. RevenueBudget targets)',
        'priority': 10,
    },
    # Personnel Costs (21xxxxxx) — STRICT by default. Salary spend is the
    # single biggest government line item; "no appropriation, no cash" is
    # the correct discipline here out of the box.
    #
    # NOTE: Migration 0092 supersedes this rule on every existing
    # tenant — it removes this narrow STRICT rule and replaces it with
    # a wide WARNING rule on 20000000–29999999. Fresh tenants run 0080
    # then immediately 0092, ending up at the same wide-WARNING end
    # state. This narrow rule is preserved here as historical record
    # only; do not modify it.
    {
        'gl_from': '21000000', 'gl_to': '21999999',
        'check_level': 'STRICT',
        'description': 'Personnel Costs — salaries, allowances, pension contributions',
        'priority': 100,
    },
    # Assets (3xxxxxxx) — WARNING by default. Asset acquisitions are
    # usually budget-backed but direct journal entries (revaluation,
    # depreciation, transfers) shouldn't be blocked. Admin may escalate
    # this to STRICT for tighter capex discipline.
    {
        'gl_from': '30000000', 'gl_to': '39999999',
        'check_level': 'WARNING',
        'description': 'Assets — warning-only; admin may raise to strict',
        'priority': 20,
    },
    # Liabilities (4xxxxxxx) — WARNING. Liabilities are rarely gated
    # directly; they're usually the credit side of an expense journal
    # that's gated at the expense leg.
    {
        'gl_from': '40000000', 'gl_to': '49999999',
        'check_level': 'WARNING',
        'description': 'Liabilities — warning-only',
        'priority': 20,
    },
]


def seed_default_rules(apps, schema_editor):
    """Ship sensible starter rules for every tenant.

    Four ranges cover the full NCoA economic classification:
      · Revenue (1x)    → NONE
      · Personnel (21x) → STRICT  (expense family where discipline matters most)
      · Assets (3x)     → WARNING
      · Liabilities (4x)→ WARNING

    Tenant admin can edit, disable or add rules through the Settings UI.
    """
    BudgetCheckRule = apps.get_model('accounting', 'BudgetCheckRule')
    for rule in DEFAULT_RULES:
        BudgetCheckRule.objects.get_or_create(
            gl_from=rule['gl_from'], gl_to=rule['gl_to'],
            defaults={
                'check_level': rule['check_level'],
                'description': rule['description'],
                'priority': rule['priority'],
            },
        )


def remove_default_rules(apps, schema_editor):
    BudgetCheckRule = apps.get_model('accounting', 'BudgetCheckRule')
    for rule in DEFAULT_RULES:
        BudgetCheckRule.objects.filter(
            gl_from=rule['gl_from'], gl_to=rule['gl_to'],
        ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0079_perf_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCheckRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gl_from', models.CharField(db_index=True, help_text='Lowest GL account code included in this rule (inclusive).', max_length=20)),
                ('gl_to', models.CharField(db_index=True, help_text='Highest GL account code included in this rule (inclusive).', max_length=20)),
                ('check_level', models.CharField(choices=[('NONE', 'No check — posts without any appropriation check'), ('WARNING', 'Warning — flags when appropriation is over threshold'), ('STRICT', 'Strict — blocks posting without an active appropriation')], default='WARNING', max_length=10)),
                ('warning_threshold_pct', models.DecimalField(decimal_places=2, default=80.0, help_text='Utilisation % at which a WARNING-level rule starts flagging (ignored for NONE and STRICT). Default 80%.', max_digits=5)),
                ('description', models.CharField(blank=True, default='', help_text='What this range represents (e.g. "Personnel Costs", "Capital Expenditure"). Surfaced in the Settings UI and in the warning message on the UI.', max_length=200)),
                ('priority', models.IntegerField(default=0, help_text='Tiebreaker when two rules have the same range width. Higher priority wins.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Budget Check Rule',
                'verbose_name_plural': 'Budget Check Rules',
                'ordering': ['gl_from', '-priority'],
                'indexes': [models.Index(fields=['is_active', 'gl_from', 'gl_to'], name='accounting__is_acti_2a7e0f_idx')],
            },
        ),
        migrations.RunPython(seed_default_rules, remove_default_rules),
    ]
