# Generated by Django 4.2.28 on 2026-04-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0081_topup_default_budget_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedasset',
            name='asset_category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
