# Generated by Django 4.2.28 on 2026-04-19 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0082_fixedasset_category_freeform'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalline',
            name='asset',
            field=models.ForeignKey(blank=True, help_text='Fixed asset this line relates to (optional; used by depreciation, disposal and cost-accumulation entries).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.fixedasset'),
        ),
    ]
