# Generated by Django 4.2.28 on 2026-04-19 11:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0083_journalline_asset_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepreciationRunSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Uncheck to pause the auto-run without deleting the schedule.')),
                ('day_of_month', models.PositiveSmallIntegerField(default=1, help_text='Day (1–28) when the monthly run fires. Values >28 are clamped to the last day of each month by the command.')),
                ('last_run_at', models.DateTimeField(blank=True, help_text='Wall-clock time of the most recent fire.', null=True)),
                ('last_run_period_date', models.DateField(blank=True, help_text='The period_date (month-end) depreciated in the last run.', null=True)),
                ('last_run_assets_posted', models.PositiveIntegerField(default=0)),
                ('last_run_total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('last_run_skipped', models.PositiveIntegerField(default=0)),
                ('last_run_error', models.TextField(blank=True, default='')),
                ('next_run_date', models.DateField(blank=True, db_index=True, help_text='Command fires when today >= this date.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Depreciation Run Schedule',
                'verbose_name_plural': 'Depreciation Run Schedules',
                'ordering': ['-is_active', '-next_run_date'],
            },
        ),
    ]
