# Generated by Django 4.2.28 on 2026-04-19 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0084_depreciation_run_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentVoucherDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deduction_type', models.CharField(choices=[('WHT', 'Withholding Tax'), ('STAMP_DUTY', 'Stamp Duty'), ('VAT_WITHHELD', 'VAT Withheld at Source'), ('HANDLING', 'Bank / Handling Charges'), ('INSURANCE', 'Insurance Premium'), ('RETENTION', 'Contract Retention'), ('OTHER', 'Other Deduction')], max_length=15)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('rate', models.DecimalField(decimal_places=2, default=0, help_text='Rate used to compute amount (informational).', max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('gl_account', models.ForeignKey(help_text='GL liability/revenue account credited at payment time.', on_delete=django.db.models.deletion.PROTECT, related_name='pv_deductions', to='accounting.account')),
                ('payment_voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='accounting.paymentvouchergov')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('withholding_tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pv_deductions', to='accounting.withholdingtax')),
            ],
            options={
                'ordering': ['payment_voucher', 'id'],
                'indexes': [models.Index(fields=['deduction_type'], name='accounting__deducti_8e653e_idx')],
            },
        ),
    ]
