# Generated by Django 4.2.28 on 2026-04-24 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0085_paymentvoucherdeduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasuryaccount',
            name='gl_cash_account',
            field=models.ForeignKey(blank=True, help_text='GL control account for this TSA. Every cash-side posting against this treasury account should hit this GL account. Required for IPSAS-compliant cash flow reporting.', limit_choices_to={'account_type': 'Asset', 'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tsa_accounts', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='treasuryaccount',
            name='ncoa_cash_code',
            field=models.ForeignKey(blank=True, help_text="Optional NCoA economic classification for this TSA's cash position (e.g. '1101.001 — Cash & Bank at CBN').", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tsa_accounts', to='accounting.ncoacode'),
        ),
    ]
