# Generated by Django 4.2.28 on 2026-04-27 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0086_treasuryaccount_gl_cash_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='asset_category',
            field=models.ForeignKey(blank=True, help_text='Asset Category whose cost_account receives the rerouted debit and whose depreciation rules apply to the new asset. Required when auto_create_asset is True.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auto_create_accounts', to='accounting.assetcategory'),
        ),
        migrations.AddField(
            model_name='account',
            name='auto_create_asset',
            field=models.BooleanField(default=False, help_text="When ON, debits to this account auto-create a FixedAsset in the linked Asset Category and reroute the debit to that category's cost_account at posting time."),
        ),
    ]
