# Generated by Django 4.2.28 on 2026-04-27 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0087_account_auto_create_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='created_from_journal_line',
            field=models.ForeignKey(blank=True, help_text='Journal line that triggered auto-capitalisation, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_created_assets', to='accounting.journalline'),
        ),
    ]
