# Generated by Django 4.2.28 on 2026-04-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0088_fixedasset_created_from_journal_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economicsegment',
            name='code',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
