# Generated by Django 4.2.28 on 2026-04-28 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0089_widen_economicsegment_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasuryaccount',
            name='ncoa_cash_code',
            field=models.ForeignKey(blank=True, help_text="NCoA Economic Segment classification for this TSA's cash position (e.g. '31030205 — Cash Transfer / JAAC Direct Allocation'). Used by IPSAS Cash Flow Statement to group treasury accounts by economic classification.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tsa_accounts', to='accounting.economicsegment'),
        ),
    ]
