# Generated by Django 4.2.28 on 2026-04-28 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0090_alter_treasuryaccount_ncoa_cash_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='vendor_registration_revenue_account',
            field=models.ForeignKey(blank=True, help_text='Income account credited when a vendor pays their registration invoice. Tenants on Nigerian NCoA typically point this to 12100200 (Vendor Registration Fees) or another 12xxxxxx revenue code; tenants on a different chart pick whichever Income code represents their registration revenue stream.', limit_choices_to={'account_type': 'Income', 'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settings_vendor_reg_revenue', to='accounting.account'),
        ),
    ]
