# Generated by Django 4.2.28 on 2026-05-05 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0098_warrant_before_payment_toggle'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vendoradvanceclearance',
            new_name='accounting__advance_451788_idx',
            old_name='acct_vadv_clearance_idx',
        ),
        migrations.AlterField(
            model_name='account',
            name='reconciliation_type',
            field=models.CharField(blank=True, choices=[('accounts_payable', 'Account Payable'), ('accounts_receivable', 'Account Receivable'), ('inventory', 'Inventory'), ('asset_accounting', 'Asset Accounting'), ('bank_accounting', 'Bank Accounting'), ('vendor_advance', 'Vendor Advance (Special GL)')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='vendoradvance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendoradvance',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendoradvanceclearance',
            name='clearing_journal',
            field=models.ForeignKey(blank=True, help_text='The DR-AP / CR-Vendor-Advance contra journal.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_advance_clearances', to='accounting.journalheader'),
        ),
        migrations.AlterField(
            model_name='vendoradvanceclearance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendoradvanceclearance',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
