# Generated by Django 4.2.28 on 2026-05-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0099_add_retention_release_accrual_journal'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='treasuryaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('account_type', 'MAIN_TSA'), ('is_active', True)), fields=('account_type', 'mda'), name='uniq_main_tsa_per_mda_active'),
        ),
    ]
