# Generated by Django 5.2.14 on 2026-05-23 23:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0101_account_is_postable_header_flag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tsabankstatementline',
            constraint=models.UniqueConstraint(condition=models.Q(('matched_payment__isnull', False)), fields=('matched_payment',), name='uniq_tsastmtline_matched_payment'),
        ),
        migrations.AddConstraint(
            model_name='tsabankstatementline',
            constraint=models.UniqueConstraint(condition=models.Q(('matched_revenue__isnull', False)), fields=('matched_revenue',), name='uniq_tsastmtline_matched_revenue'),
        ),
    ]
