# Generated by Django 5.2.14 on 2026-05-25
#
# WS5-A — Replace GLBalance.unique_together with a UniqueConstraint that
# uses NULLS NOT DISTINCT, so any combination of NULL dimensions still
# collides for get_or_create(). Requires Postgres 15+ (this project runs 18).
#
# Before adding the new constraint we MUST collapse any pre-existing
# logically-duplicate rows that the old NULLS DISTINCT semantics permitted,
# otherwise CREATE UNIQUE INDEX will fail. GLBalance is derived state
# (rebuilt from journal lines via gl_posting service), so the safest dedup
# strategy is: keep the row with the smallest pk per dimension tuple and
# sum the duplicate debit/credit amounts into it, then delete the rest.

from django.db import migrations, models


DEDUPE_SQL = r"""
WITH ranked AS (
    SELECT id,
           account_id, fund_id, function_id, program_id, geo_id, mda_id,
           fiscal_year, period,
           debit_balance, credit_balance,
           MIN(id) OVER (
               PARTITION BY account_id, fund_id, function_id, program_id,
                            geo_id, mda_id, fiscal_year, period
           ) AS keeper_id,
           COUNT(*) OVER (
               PARTITION BY account_id, fund_id, function_id, program_id,
                            geo_id, mda_id, fiscal_year, period
           ) AS dup_count
    FROM accounting_glbalance
),
sums AS (
    SELECT keeper_id,
           SUM(debit_balance)  AS total_debit,
           SUM(credit_balance) AS total_credit
    FROM ranked
    WHERE dup_count > 1
    GROUP BY keeper_id
)
UPDATE accounting_glbalance g
SET debit_balance  = sums.total_debit,
    credit_balance = sums.total_credit
FROM sums
WHERE g.id = sums.keeper_id;

DELETE FROM accounting_glbalance
WHERE id IN (
    SELECT id FROM (
        SELECT id,
               MIN(id) OVER (
                   PARTITION BY account_id, fund_id, function_id, program_id,
                                geo_id, mda_id, fiscal_year, period
               ) AS keeper_id
        FROM accounting_glbalance
    ) t
    WHERE t.id <> t.keeper_id
);
"""


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0102_tsabankstatementline_uniq_tsastmtline_matched_payment_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='glbalance',
            unique_together=set(),
        ),
        migrations.RunSQL(
            sql=DEDUPE_SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddConstraint(
            model_name='glbalance',
            constraint=models.UniqueConstraint(
                fields=('account', 'fund', 'function', 'program', 'geo', 'mda', 'fiscal_year', 'period'),
                name='uniq_glbalance_dims_nulls_not_distinct',
                nulls_distinct=False,
            ),
        ),
    ]
