# Generated by Django 5.2.14 on 2026-05-30 07:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0103_glbalance_unique_nulls_not_distinct'),
        ('contracts', '0011_contract_retention_cap_percent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCascadeFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_class', models.CharField(blank=True, default='', help_text='Exception class name, for triage filtering.', max_length=120)),
                ('error_message', models.TextField(help_text='Full exception message at the time of failure.')),
                ('error_context', models.JSONField(blank=True, default=dict, help_text='Extra structured context (caller user, source action, request id, etc).')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='', help_text='What was done to resolve. Auditable.')),
                ('ipc', models.ForeignKey(blank=True, help_text='The IPC whose mark_paid step failed. Null for non-IPC cascade failures (e.g. AR receipt allocation).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cascade_failures', to='contracts.interimpaymentcertificate')),
                ('payment', models.ForeignKey(help_text='The payment whose cascade failed.', on_delete=django.db.models.deletion.PROTECT, related_name='cascade_failures', to='accounting.payment')),
                ('resolved_by', models.ForeignKey(blank=True, help_text='User who marked the failure resolved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment cascade failure',
                'verbose_name_plural': 'Payment cascade failures',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ipc', 'resolved'], name='pcf_ipc_resolved_idx')],
            },
        ),
    ]
