# Generated by Django 5.2.14 on 2026-05-30 12:17
#
# Adds dedicated permissions surfaced by the WS comprehensive-review
# remediation:
#
#   * V2  — ``accounting.force_close_periods``  (FiscalPeriod)
#   * V3  — ``accounting.resolve_paymentcascadefailure``  (PaymentCascadeFailure)
#   * V15 — ``accounting.view_gl_reconciliation_diff``  (Account)
#
# A best-effort data step grants the new perms to existing Django Groups
# whose names match the seeded accounting / audit role codes
# (``<tenant_schema>_<role_code>``). Tenants that haven't seeded those
# groups simply see no-ops — they can grant manually later via the
# admin. Superusers always bypass the perm check regardless.

from django.db import migrations


# Role codes (suffixes) that should receive the new perms by default.
# These mirror the seed in tenants/management/commands/seed_default_roles.py.
# Mapping: perm codename → list of role-code suffixes whose Groups receive it.
_DEFAULT_GRANTS = {
    'force_close_periods': [
        'accountant',           # senior accounting role (Accountant General-style)
        'treasury_manager',     # senior treasury approver
        'admin_manager',        # tenant System Admin
    ],
    'resolve_paymentcascadefailure': [
        'accountant',
        'accounts_officer',     # Finance Officer-equivalent
        'treasury_manager',
        'admin_manager',
    ],
    'view_gl_reconciliation_diff': [
        'accountant',
        'internal_auditor',     # Auditor role
        'admin_manager',
    ],
}


def _grant_perm_to_groups(apps, perm_codename, role_suffixes):
    """Grant ``perm_codename`` to every Group whose name ends with one of
    the supplied role-code suffixes (``<tenant_schema>_<role_code>``).

    Best-effort: silently skips missing Permission rows (model not yet
    registered against the perm), missing Groups, or any group with no
    match. Always swallows lookup failures so a half-seeded tenant does
    not break the schema migration.
    """
    Permission = apps.get_model('auth', 'Permission')
    Group = apps.get_model('auth', 'Group')

    # The perm row for a custom permission added via ``Meta.permissions``
    # is created by Django's ``post_migrate`` signal AFTER all schema
    # migrations finish. At this point in the migration the row may not
    # exist yet — that's expected. We try to grant it now; if absent the
    # grant is harmlessly skipped and operators can re-grant via the
    # admin once the perm row materialises.
    try:
        perms = list(Permission.objects.filter(codename=perm_codename))
    except Exception:
        perms = []
    if not perms:
        return

    for suffix in role_suffixes:
        try:
            # Match both bare role-code groups and tenant-prefixed
            # ``<schema>_<role_code>`` groups.
            matching = Group.objects.filter(name__iendswith=suffix)
        except Exception:
            continue
        for group in matching:
            for perm in perms:
                try:
                    group.permissions.add(perm)
                except Exception:
                    # Tolerant: any single failure (e.g. cross-tenant
                    # FK quirk) must not abort the whole migration.
                    continue


def forwards_grants(apps, schema_editor):
    for codename, suffixes in _DEFAULT_GRANTS.items():
        _grant_perm_to_groups(apps, codename, suffixes)


def backwards_grants(apps, schema_editor):
    """Best-effort revoke of the grants applied in forwards step."""
    Permission = apps.get_model('auth', 'Permission')
    Group = apps.get_model('auth', 'Group')
    for codename, suffixes in _DEFAULT_GRANTS.items():
        try:
            perms = list(Permission.objects.filter(codename=codename))
        except Exception:
            perms = []
        if not perms:
            continue
        for suffix in suffixes:
            try:
                matching = Group.objects.filter(name__iendswith=suffix)
            except Exception:
                continue
            for group in matching:
                for perm in perms:
                    try:
                        group.permissions.remove(perm)
                    except Exception:
                        continue


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0104_paymentcascadefailure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['code'], 'permissions': (('view_gl_reconciliation_diff', 'Can view GL reconciliation diff and warnings on aging reports'),)},
        ),
        migrations.AlterModelOptions(
            name='fiscalperiod',
            options={'ordering': ['fiscal_year', 'period_number'], 'permissions': [('reopen_fiscal_period', 'Can reopen a closed fiscal period'), ('force_close_periods', 'Can force-close fiscal periods with pending journals')]},
        ),
        migrations.AlterModelOptions(
            name='paymentcascadefailure',
            options={'ordering': ['-created_at'], 'permissions': (('resolve_paymentcascadefailure', 'Can resolve payment cascade failures'),), 'verbose_name': 'Payment cascade failure', 'verbose_name_plural': 'Payment cascade failures'},
        ),
        migrations.RunPython(forwards_grants, backwards_grants),
    ]
