# Generated by Django 5.2.14 on 2026-05-30 12:36
#
# V7 — Fiscal period reopen two-actor approval workflow.
#
# Schema:
#   * New permission ``accounting.reopen_fiscal_period_single_actor`` —
#     escape hatch that restores the legacy single-user reopen path.
#   * New model ``FiscalPeriodReopenApproval`` — records the
#     request/approve workflow with PENDING / APPROVED / EXECUTED /
#     REJECTED / EXPIRED status.
#
# Data step (forwards_grant_single_actor_to_superusers):
#   * Grants the NEW ``reopen_fiscal_period_single_actor`` permission
#     ONLY to users whose ``is_superuser`` flag is True. Existing
#     holders of ``accounting.reopen_fiscal_period`` are NOT auto-granted
#     the escape hatch — they get the safer two-step flow by default.
#     Tenants that need the legacy single-actor path for emergency
#     situations can grant it manually via the admin to specific users.
#
# Transition note (reverse_op):
#   * Operators currently scripting against POST
#     /api/accounting/fiscal-periods/<pk>/reopen/ will receive
#     405 Method Not Allowed responses with a migration message
#     pointing to the new endpoints:
#       POST /api/accounting/fiscal-periods/<pk>/reopen-request/   (Stage 1)
#       POST /api/accounting/reopen-approvals/<id>/approve/        (Stage 2)
#       POST /api/accounting/reopen-approvals/<id>/reject/         (cancel)
#   * E2E suites that previously exercised the single-actor flow must
#     either (a) be updated to use the two-step flow, or (b) the
#     calling test user must be granted both
#     ``accounting.reopen_fiscal_period`` AND
#     ``accounting.reopen_fiscal_period_single_actor`` to keep the
#     legacy path working. Option (a) is preferred; option (b) is the
#     emergency / break-glass route.
#   * The reverse_op revokes the new perm from superusers and drops
#     the model — but the new ``reopen_request`` / ``reopen_approve``
#     endpoints will then 500 because the model is gone. Reverse only
#     for a clean rollback, not in production.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards_grant_single_actor_to_superusers(apps, schema_editor):
    """Grant ``accounting.reopen_fiscal_period_single_actor`` to all
    superusers as the emergency escape-hatch population.

    Existing non-superuser holders of ``accounting.reopen_fiscal_period``
    intentionally do NOT receive this perm — the default behaviour
    switches to the safe two-step flow. Tenants that need the legacy
    single-actor path can grant the new perm explicitly via the admin.

    Best-effort: silently skips if the Permission row is not yet
    created (it materialises via ``post_migrate``); operators can
    re-run the migration or grant manually.
    """
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    Permission = apps.get_model('auth', 'Permission')
    try:
        perm = Permission.objects.filter(
            codename='reopen_fiscal_period_single_actor',
        ).first()
    except Exception:
        perm = None
    if perm is None:
        # Permission row isn't created until post_migrate fires for the
        # AlterModelOptions step. The grant runs again on every
        # subsequent migrate or can be performed manually via the
        # admin — there's no security risk in deferring it.
        return
    try:
        supers = User.objects.filter(is_superuser=True)
    except Exception:
        return
    for user in supers:
        try:
            user.user_permissions.add(perm)
        except Exception:
            # Tolerant: any single failure must not abort the migration.
            continue


def backwards_revoke_single_actor(apps, schema_editor):
    """Best-effort revoke of the single-actor grant applied forwards.

    Reverse note: the rollback drops the model + perm, so the new
    ``reopen_request`` and ``reopen_approve`` endpoints will start
    returning 500 once this migration is unapplied. Only reverse for a
    full rollback, never partway.
    """
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    Permission = apps.get_model('auth', 'Permission')
    try:
        perm = Permission.objects.filter(
            codename='reopen_fiscal_period_single_actor',
        ).first()
    except Exception:
        perm = None
    if perm is None:
        return
    try:
        supers = User.objects.filter(is_superuser=True)
    except Exception:
        return
    for user in supers:
        try:
            user.user_permissions.remove(perm)
        except Exception:
            continue


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0105_perm_dedicated_v2_v3_v15_v5'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiscalperiod',
            options={
                'ordering': ['fiscal_year', 'period_number'],
                'permissions': [
                    ('reopen_fiscal_period', 'Can reopen a closed fiscal period'),
                    ('force_close_periods', 'Can force-close fiscal periods with pending journals'),
                    (
                        'reopen_fiscal_period_single_actor',
                        'Can reopen a closed fiscal period without a second-actor approval (emergency escape hatch)',
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name='FiscalPeriodReopenApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reason', models.TextField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('EXECUTED', 'Executed'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=12)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reopen_approvals_given', to=settings.AUTH_USER_MODEL)),
                ('fiscal_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reopen_approvals', to='accounting.fiscalperiod')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reopen_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['fiscal_period', 'status'], name='accounting__fiscal__1734db_idx')],
            },
        ),
        migrations.RunPython(
            forwards_grant_single_actor_to_superusers,
            backwards_revoke_single_actor,
        ),
    ]
