# Generated by Django 5.2.14 on 2026-06-11 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0106_fiscal_period_reopen_approval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=16)),
                ('label', models.CharField(help_text='Human-readable name, e.g. "Statement of Financial Position FY2026".', max_length=255)),
                ('fmt', models.CharField(help_text='Render format: xlsx | pdf | html.', max_length=8)),
                ('report_payload', models.JSONField(help_text='Pre-computed report dict to render. Stored via DjangoJSONEncoder — Decimals round-trip as strings.')),
                ('file', models.FileField(blank=True, null=True, upload_to='async_exports/%Y/%m/')),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=128)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='async_export_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
