# Generated by Django 5.2.14 on 2026-08-12 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0107_asyncexportjob"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankLetterSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ministry_name",
                    models.CharField(default="Ministry of Finance", max_length=200),
                ),
                (
                    "office_name",
                    models.CharField(
                        default="Office of the Accountant General", max_length=200
                    ),
                ),
                (
                    "office_address",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "letterhead_logo",
                    models.ImageField(
                        blank=True,
                        help_text="State coat of arms (PNG/JPG, ~200px tall).",
                        null=True,
                        upload_to="bank_letters/logos/",
                    ),
                ),
                (
                    "accountant_general_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "accountant_general_title",
                    models.CharField(
                        default="Permanent Secretary/Accountant General", max_length=200
                    ),
                ),
                (
                    "accountant_general_signature",
                    models.ImageField(
                        blank=True, null=True, upload_to="bank_letters/signatures/"
                    ),
                ),
                (
                    "director_treasury_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "director_treasury_title",
                    models.CharField(default="Director Treasurer", max_length=200),
                ),
                (
                    "director_treasury_signature",
                    models.ImageField(
                        blank=True, null=True, upload_to="bank_letters/signatures/"
                    ),
                ),
                (
                    "director_mgmt_acct_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "director_mgmt_acct_title",
                    models.CharField(
                        default="Director Management Acct", max_length=200
                    ),
                ),
                (
                    "director_mgmt_acct_signature",
                    models.ImageField(
                        blank=True, null=True, upload_to="bank_letters/signatures/"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bank Letter Settings",
                "verbose_name_plural": "Bank Letter Settings",
            },
        ),
    ]
