# Generated by Django 5.2.14 on 2026-08-12 00:58

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0108_banklettersettings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch_number",
                    models.CharField(db_index=True, max_length=30, unique=True),
                ),
                ("batch_date", models.DateField(default=datetime.date.today)),
                ("addressee_bank_name", models.CharField(max_length=100)),
                ("addressee_account_no", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Dispatched", "Dispatched"),
                            ("Confirmed", "Confirmed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Draft",
                        max_length=15,
                    ),
                ),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_reason", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_payment_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dispatched_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispatched_payment_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_bank_account",
                    models.ForeignKey(
                        help_text="The government account the bank is instructed to debit.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_batches",
                        to="accounting.bankaccount",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Batch",
                "verbose_name_plural": "Payment Batches",
                "ordering": ["-batch_date", "-batch_number"],
            },
        ),
        migrations.CreateModel(
            name="PaymentBatchLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField(help_text="The S/N column.")),
                ("payee_name", models.CharField(max_length=200)),
                ("payee_bank", models.CharField(max_length=100)),
                ("payee_account", models.CharField(max_length=20)),
                ("purpose", models.CharField(blank=True, default="", max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "is_active_membership",
                    models.BooleanField(db_index=True, default=True),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="accounting.paymentbatch",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batch_lines",
                        to="accounting.payment",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence"],
            },
        ),
        migrations.AddIndex(
            model_name="paymentbatch",
            index=models.Index(
                fields=["status", "batch_date"], name="accounting__status_f224f0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentbatchline",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active_membership", True)),
                fields=("payment",),
                name="uniq_active_payment_batch_membership",
            ),
        ),
    ]
