# Generated by Django 5.2.14 on 2026-09-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0112_journal_balance_guard_case_insensitive"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankstatementline",
            name="match_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="bankstatementline",
            name="matched_transaction_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
