# Generated by Django 5.2.14 on 2026-09-15 00:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0113_bank_statement_line_multi_match"),
        ("budget", "0017_alter_warrant_status"),
        ("procurement", "0049_alter_vendor_bank_account_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendorinvoice",
            name="invoice_number",
            field=models.CharField(db_index=True, default="", max_length=50),
        ),
        migrations.AddConstraint(
            model_name="paymentvouchergov",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("source_document", ""), _negated=True),
                    models.Q(("status__in", ["CANCELLED", "REVERSED"]), _negated=True),
                ),
                fields=("source_document",),
                name="uniq_live_pv_source_document",
            ),
        ),
        migrations.AddConstraint(
            model_name="vendorinvoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_deleted", False),
                    models.Q(("invoice_number", ""), _negated=True),
                ),
                fields=("vendor", "invoice_number"),
                name="uniq_vendor_invoice_number",
            ),
        ),
    ]
