# Generated by Django 5.2.14 on 2026-09-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0113_payment_batch_line_audit"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentbatch",
            name="bank_reference",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The bank's advice / transaction reference confirming the instruction was executed.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="paymentbatch",
            name="confirmation_document",
            field=models.FileField(
                blank=True,
                help_text="Optional scan of the bank advice or stamped letter.",
                null=True,
                upload_to="bank_letters/confirmations/%Y/",
            ),
        ),
    ]
