# Generated by Django 5.2.14 on 2026-09-17 12:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0122_group_roots_with_postings_are_headers"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentDeductionCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, default="", max_length=20, unique=True
                    ),
                ),
                ("name", models.CharField(default="", max_length=150)),
                (
                    "deduction_type",
                    models.CharField(
                        choices=[
                            ("WHT", "Withholding Tax"),
                            ("STAMP_DUTY", "Stamp Duty"),
                            ("VAT_WITHHELD", "VAT Withheld at Source"),
                            ("HANDLING", "Bank / Handling Charges"),
                            ("INSURANCE", "Insurance Premium"),
                            ("RETENTION", "Contract Retention"),
                            ("OTHER", "Other Deduction"),
                        ],
                        db_index=True,
                        default="OTHER",
                        max_length=15,
                    ),
                ),
                (
                    "calculation_method",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage of gross"),
                            ("fixed", "Fixed amount"),
                        ],
                        default="percentage",
                        max_length=10,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text='Percentage rate applied to gross when method is "percentage".',
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "fixed_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text='Flat amount deducted when method is "fixed".',
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "gl_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="GL liability/revenue account credited when this deduction is taken.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_deduction_codes",
                        to="accounting.account",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
    ]
