# Generated by Django 5.2.14 on 2026-09-17 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0123_paymentdeductioncode"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentvoucherdeduction",
            name="deduction_code",
            field=models.ForeignKey(
                blank=True,
                help_text="Payment Deduction setting this line was created from (carries its GL account and percentage/fixed basis).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pv_deductions",
                to="accounting.paymentdeductioncode",
            ),
        ),
    ]
