# Generated by Django 5.2.14 on 2026-09-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0124_paymentvoucherdeduction_deduction_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentvouchergov",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("VENDOR", "Vendor / Contractor Payment"),
                    ("ADVANCE", "Advance Request"),
                    ("SALARY", "Salary Payment"),
                    ("ALLOWANCE", "Allowance / Honorarium"),
                    ("PENSION", "Pension Remittance"),
                    ("STATUTORY", "Statutory Deduction Remittance"),
                    ("REFUND", "Revenue Refund"),
                    ("TRANSFER", "Inter-Account Transfer"),
                    ("PETTY_CASH", "Petty Cash Replenishment"),
                    ("SUBVENTION", "Subvention / Transfer"),
                    ("DEBT", "Debt Service Payment"),
                ],
                max_length=20,
            ),
        ),
    ]
