# Generated by Django 5.2.14 on 2026-09-17 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0125_alter_paymentvouchergov_payment_type"),
        ("procurement", "0049_alter_vendor_bank_account_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentvouchergov",
            name="special_gl_indicator",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SAP special G/L indicator. 'A' = vendor down payment / advance; blank for ordinary payments.",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="paymentvouchergov",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_vouchers",
                to="procurement.vendor",
            ),
        ),
    ]
