# Generated by Django 5.2.14 on 2026-09-18 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0126_paymentvouchergov_special_gl_indicator_and_more"),
        ("procurement", "0049_alter_vendor_bank_account_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("payment_voucher__isnull", False),
                    models.Q(("status", "Void"), _negated=True),
                ),
                fields=("payment_voucher",),
                name="uniq_live_payment_per_pv",
            ),
        ),
    ]
