# Generated by Django 5.2.14 on 2026-09-20 22:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0127_payment_uniq_live_payment_per_pv"),
        ("procurement", "0049_alter_vendor_bank_account_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="payment",
            name="uniq_live_payment_per_pv",
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("payment_voucher__isnull", False),
                    models.Q(("status", "Void"), _negated=True),
                    ("is_deleted", False),
                ),
                fields=("payment_voucher",),
                name="uniq_live_payment_per_pv",
            ),
        ),
    ]
