# Generated by Django 5.2.14 on 2026-09-20 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0128_remove_payment_uniq_live_payment_per_pv_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="cheque",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="accounting.check",
            ),
        ),
    ]
