# Generated by Django 5.2.14 on 2026-09-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0129_payment_cheque"),
    ]

    operations = [
        migrations.AddField(
            model_name="check",
            name="date_collected",
            field=models.DateField(blank=True, null=True),
        ),
    ]
