# Generated by Django 5.2.14 on 2026-09-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0130_check_date_collected"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorinvoice",
            name="retention_withheld",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
