# Generated by Django 5.2.14 on 2026-09-27 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0131_paymentdocument_paymentdocumentline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentdocumentline",
            name="memo",
        ),
    ]
