# Generated by Django 5.2.14 on 2026-09-27 19:55

import accounting.models.gl
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0132_remove_paymentdocumentline_memo"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentdocument",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to=accounting.models.gl.tenant_upload_path
            ),
        ),
    ]
