# Generated by Django 5.2.14 on 2026-09-27 20:15

import accounting.models.payment_document
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0133_paymentdocument_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentdocument",
            name="attachment_original_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="paymentdocument",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=accounting.models.payment_document.payment_document_attachment_path,
            ),
        ),
    ]
