# Generated by Django 5.2.14 on 2026-09-27 20:48

import accounting.models.payment_document
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0134_paymentdocument_attachment_original_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentdocument",
            name="attachment",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=accounting.models.payment_document.payment_document_attachment_path,
            ),
        ),
    ]
