# Generated by Django 5.2.14 on 2026-09-27 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0135_alter_paymentdocument_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentdocumentline",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_document_lines",
                to="accounting.account",
            ),
        ),
    ]
