# Generated by Django 5.2.14 on 2026-09-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0136_alter_paymentdocumentline_account"),
        ("procurement", "0050_downpaymentrequest_payment_voucher"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="paymentdocumentline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("account__isnull", False),
                    ("vendor__isnull", False),
                    _connector="OR",
                ),
                name="paymentdocumentline_account_or_vendor",
            ),
        ),
    ]
