# Generated by Django 5.2.14 on 2026-09-28 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounting",
            "0137_paymentdocumentline_paymentdocumentline_account_or_vendor",
        ),
        ("procurement", "0050_downpaymentrequest_payment_voucher"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_document",
            field=models.ForeignKey(
                blank=True,
                help_text="Source Payment Document when this payment settles a PD (mutually exclusive with payment_voucher).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cash_payments",
                to="accounting.paymentdocument",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("payment_voucher__isnull", False),
                    ("payment_document__isnull", False),
                    _negated=True,
                ),
                name="payment_not_both_pv_and_document",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("payment_document__isnull", False),
                    models.Q(("status", "Void"), _negated=True),
                    ("is_deleted", False),
                ),
                fields=("payment_document",),
                name="uniq_live_payment_per_document",
            ),
        ),
    ]
