# Generated by Django 5.2.14 on 2026-09-28 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0138_payment_payment_document_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentdocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Pending Approval", "Pending Approval"),
                    ("Approved", "Approved"),
                    ("Paid", "Paid"),
                    ("Void", "Void"),
                ],
                db_index=True,
                default="Draft",
                max_length=20,
            ),
        ),
    ]
