# Generated by Django 5.2.14 on 2026-09-28 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0141_alter_paymentdocument_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentvouchergov",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Payment Proposal",
                "verbose_name_plural": "Payment Proposals",
            },
        ),
    ]
