# Generated by Django 5.2.14 on 2026-09-28 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0131_vendorinvoice_retention_withheld"),
        ("accounting", "0143_backfill_gateway_settlement_clearing"),
    ]

    operations = []
