# Generated by Django 6.0.2 on 2026-02-16 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_fix_model_errors'),
        ('inventory', '0003_product_type_category'),
        ('sales', '0003_fix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='accounts_receivable_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'Asset'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_ar_accounts', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='revenue_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'Income'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_revenue_accounts', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='mda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.mda'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='delivery_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='delivery_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='mda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.mda'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='payment_terms',
            field=models.CharField(choices=[('Immediate', 'Immediate'), ('Net_15', 'Net 15'), ('Net_30', 'Net 30'), ('Net_45', 'Net 45'), ('Net_60', 'Net 60'), ('Due_on_Receipt', 'Due on Receipt')], default='Net_30', max_length=20),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='terms_and_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_order_lines', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_order_lines', to='inventory.productcategory'),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_order_lines', to='inventory.producttype'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='revenue_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'Income'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Posted', 'Posted'), ('Rejected', 'Rejected'), ('Closed', 'Closed')], default='Draft', max_length=20),
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_number', models.CharField(max_length=50, unique=True)),
                ('delivery_date', models.DateField()),
                ('delivered_by', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Delivered', 'Delivered'), ('Posted', 'Posted'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('vehicle_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.salesorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryNoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_delivered', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.deliverynote')),
                ('so_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.salesorderline')),
            ],
        ),
    ]
