# Generated by Django 6.0.2 on 2026-03-01 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_customer_sales_custo_is_acti_1b1d19_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotation',
            options={'permissions': [('approve_quotation', 'Can approve quotations')]},
        ),
        migrations.AlterModelOptions(
            name='salesorder',
            options={'permissions': [('approve_salesorder', 'Can approve sales orders')]},
        ),
    ]
