# Generated by Django 4.2.28 on 2026-03-12 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_journalline_document_number'),
        ('inventory', '0009_batchexpiryalert_itemserialnumber_and_more'),
        ('sales', '0007_alter_quotation_options_alter_salesorder_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='salesorder',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='sales_custo_is_acti_1b1d19_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='sales_custo_custome_890109_idx',
        ),
        migrations.RemoveIndex(
            model_name='deliverynote',
            name='sales_deliv_status_83eb35_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='sales_lead_status_54f721_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='sales_lead_source_4744a0_idx',
        ),
        migrations.RemoveIndex(
            model_name='opportunity',
            name='sales_oppor_stage_23a402_idx',
        ),
        migrations.RemoveIndex(
            model_name='quotation',
            name='sales_quota_status_de197d_idx',
        ),
        migrations.RemoveIndex(
            model_name='salesorder',
            name='sales_sales_status_480214_idx',
        ),
        migrations.AlterField(
            model_name='customer',
            name='accounts_receivable_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_email',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_person',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='industry',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='revenue_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_revenue_account_set', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='vat_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='website',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='driver_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='notes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='vehicle_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='deliverynoteline',
            name='delivery_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.deliverynote'),
        ),
        migrations.AlterField(
            model_name='deliverynoteline',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='company',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='lead',
            name='converted_to_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.customer'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='lead',
            name='estimated_value',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='lead',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='notes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.customer'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='expected_value',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.lead'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='notes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='probability',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='notes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='terms',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quotationline',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='quotationline',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quotationline',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.quotation'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='delivery_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='delivery_contact',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='notes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='payment_terms',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.quotation'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='revenue_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='terms_and_conditions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.salesorder'),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.productcategory'),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.producttype'),
        ),
    ]
