# Generated by Django 4.2.28 on 2026-03-18 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0019_invoicematchingsettings_vendorcontract_and_more'),
        ('sales', '0008_alter_quotation_options_alter_salesorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_check_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_status',
            field=models.CharField(choices=[('Good', 'Good Standing'), ('Warning', 'Credit Warning'), ('Exceeded', 'Credit Exceeded'), ('Blocked', 'Credit Blocked')], default='Good', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_warning_threshold',
            field=models.DecimalField(decimal_places=2, default=80.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='last_stage_change',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='stage_duration_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='drop_ship_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drop_ship_orders', to='procurement.vendor'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='is_drop_ship',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='linked_purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linked_sales_orders', to='procurement.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('Prospecting', 'Prospecting'), ('Qualification', 'Qualification'), ('Proposal', 'Proposal'), ('Negotiation', 'Negotiation'), ('Closed_Won', 'Closed Won'), ('Closed_Lost', 'Closed Lost')], default='Prospecting', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
