# Generated by Django 4.2.28 on 2026-04-09 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_customer_credit_check_enabled_customer_credit_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_note_number', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'sales_creditnote',
            },
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_number', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'sales_deliverynote',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'sales_lead',
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'sales_opportunity',
            },
        ),
        migrations.CreateModel(
            name='POSRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'sales_posregister',
            },
        ),
        migrations.CreateModel(
            name='POSSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.posregister')),
            ],
            options={
                'db_table': 'sales_possession',
            },
        ),
        migrations.CreateModel(
            name='POSTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.possession')),
            ],
            options={
                'db_table': 'sales_postransaction',
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'sales_pricelist',
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'sales_quotation',
            },
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'sales_salesreturn',
            },
        ),
        migrations.CreateModel(
            name='SalesReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_return', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.salesreturn')),
            ],
            options={
                'db_table': 'sales_salesreturnline',
            },
        ),
        migrations.CreateModel(
            name='QuotationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.quotation')),
            ],
            options={
                'db_table': 'sales_quotationline',
            },
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.pricelist')),
            ],
            options={
                'db_table': 'sales_pricelistitem',
            },
        ),
        migrations.CreateModel(
            name='POSTransactionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.postransaction')),
            ],
            options={
                'db_table': 'sales_postransactionline',
            },
        ),
        migrations.CreateModel(
            name='DeliveryNoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.deliverynote')),
            ],
            options={
                'db_table': 'sales_deliverynoteline',
            },
        ),
    ]
