# Generated by Django 4.2.28 on 2026-03-26 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_creditnote_pricelist_pricelistitem_salesreturn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='sales.pricelist'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='discount_reason',
            field=models.TextField(blank=True, help_text='O2C-M1: Reason for discount'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('Percentage', 'Percentage'), ('Fixed', 'Fixed Amount')], help_text='O2C-M1: Order-level discount type', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='O2C-M1: Discount value (percentage or fixed amount)', max_digits=10),
        ),
    ]
