# Generated by Django 4.2.28 on 2026-03-26 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_add_stock_reservation'),
        ('sales', '0011_add_price_list_to_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationline',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_lines', to='inventory.item'),
        ),
    ]
