# Generated by Django 6.0.2 on 2026-03-30 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_add_item_to_quotationline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynoteline',
            name='delivery_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='sales.deliverynote'),
        ),
        migrations.AlterField(
            model_name='quotationline',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='sales.quotation'),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='sales.salesorder'),
        ),
    ]
