# Generated by Django 6.0.2 on 2026-03-31 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0050_accountingsettings_sales_downpayment'),
        ('sales', '0017_remove_customertype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='accounts_receivable_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_ar_accounts', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='customercategory',
            name='accounts_receivable_account',
            field=models.ForeignKey(help_text='AR GL account debited when invoicing customers in this category', on_delete=django.db.models.deletion.PROTECT, related_name='customer_category_ar_accounts', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='customercategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customercategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customercategory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
