# Generated by Django 6.0.2 on 2026-04-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_make_customer_fields_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='payment_terms',
            field=models.CharField(blank=True, choices=[('immediate', 'Due on Receipt (0 days)'), ('net_7', 'Net 7 (7 days)'), ('net_15', 'Net 15 (15 days)'), ('net_30', 'Net 30 (30 days)'), ('net_45', 'Net 45 (45 days)'), ('net_60', 'Net 60 (60 days)'), ('net_90', 'Net 90 (90 days)')], default='net_30', max_length=20),
        ),
    ]
