# Generated by Django 6.0.2 on 2026-04-03 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0051_add_tax_gl_and_wht_fields'),
        ('sales', '0021_add_payment_terms_to_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='wht_exempt',
            field=models.BooleanField(default=False, help_text='Exempt this customer from withholding tax'),
        ),
        migrations.AddField(
            model_name='customer',
            name='withholding_tax_code',
            field=models.ForeignKey(blank=True, help_text='Default WHT code applied to this customer on transactions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='accounting.withholdingtax'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='accounting.taxcode'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='wht_exempt',
            field=models.BooleanField(default=False, help_text='Exempt this transaction from withholding tax'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='accounting.taxcode'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='wht_exempt',
            field=models.BooleanField(default=False, help_text='Exempt this transaction from withholding tax'),
        ),
    ]
