# Generated by Django 4.2.28 on 2026-04-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_add_tax_gl_and_wht_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
